### ISSUE TITLE
Themes configuration is not applied to user settings tab theme field

### ISSUE THREAD

**Issue by SimonMulquin** [element-hq/element-web#10486]
**Is your suggestion related to a problem? Please describe.**
I added a new theme to my configs (riot: webpack-config, react-sdk: themeController), the theme itself isn't selectable since the select field hardcode themes options. (reeact-sdk: src/components/views/settings/tabs/user/GeneralUserSettingsTab.js line155)

I also had to hardcode some pieces of theme configuration (riot: webpack-config, react-sdk: themeController).

**Describe the solution you'd like**
Options should contain all existing themes.

Themes should be configurable without modifying the source code

**Describe alternatives you've considered**
Fork and hardcode...

**Additional context**
We would like to use Riot with our matrix servers in a mutli-institutions context where it will be important for institutions to implement they own theme so the user can distinguish them when using they implementation of Riot. (also it would be appreciated to have the possibility to fetch themes on a files server rather than in node_modules)

see issue 10397

**Comment by t3chguy** [comment]
Fixed by custom themes work
