### ISSUE TITLE
It's possible to end up in a state where you can't interact with Riot

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#11099]
No matter where I click I can't dismiss either of these:
![image](https://user-images.githubusercontent.com/1190097/66477161-4cba2000-ea8f-11e9-964b-1cbf0cbaaac2.png)

No buttons on either div work.

**Comment by t3chguy** [comment]
Is this just if the request comes in while you had the top left menu open or something more exotic?

**Comment by turt2live** [comment]
just that the request came in while I had my MXID highlighted in the top left menu.

**Comment by t3chguy** [comment]
Closing this as presumed fixed in the many years due to lack of further reported cases
