### ISSUE TITLE
There is no error when server hangs up, but when it is also still somewhat connectable.

### ISSUE THREAD

**Issue by tx1683** [element-hq/element-web#11785]
### Description

There is no error when server hangs up, but when it is also still somewhat connectable. For example when joining large room, or some random crash make server unresponsive in certain ways, but server is still running (so there is working connection to it, and thus no connection error).

It is problem because you can send messages, they are showing as delivered, but they really are not. Sometime to recover from that state you must restart server, and often that messages are lost forever. In some other cases, they are still delivered, but all at once or in strange order.

### Steps to reproduce

- Wait for server to hang up
- Send message
- Message is shown as delivered, but it isn't

Expected: Error as if connection was broken, and option to resent undelivered message when server returns to normal state.

Logs being sent: no

### Version information

- **Platform**: web and desktop

For the web app:

- **Browser**: Firefox 71 and earlier verions
- **OS**: Arch Linux, Debian 10
- **URL**: riot.junta.pl

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.5.6

**Comment by t3chguy** [comment]
Closing this as presumed fixed in the many years due to lack of further reported cases
