### ISSUE TITLE
Display HS and IS URLs on welcome page

### ISSUE THREAD

**Issue by jryans** [element-hq/element-web#12021]
Display HS (homeserver) and IS (identity server) URLs on welcome page.

Certain deployment types, such as SSO auth, hide the HS URL more so than others. This makes it hard to know how to connect with a custom client. We should clearly display the HS and IS URLs on the welcome page (or nearby place if there's something better) so everyone knows what to do.

**Comment by jryans** [comment]
I am guessing @nadonomy will have some feedback on this.

**Comment by aaronraimist** [comment]
Alternatively, don't. Steer everyone towards using their full username and use well-known rather than teaching them the homeserver URL.

**Comment by gaelledel** [comment]
Agree with Aaron
