### ISSUE TITLE
starting a VC with 2 people + a invitee can result in very strange race conditions

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#1202]
Starting a voice/video conference (VC) with 2 people + a invitee can result in very strange race conditions.

## Reproduction instructions

1. have a room with 2 people (A,B) + invitee (C)
2. user A hits video call button - starts 1:1 with B
3. C joins the room
4. user C starts a voice/video conference
5. all hell breaks loose, with Voip Conference users appearing in the memberlist and all sorts.

**Comment by SimonBrandner** [comment]
The simple solution here would probably be to just start a conference if we have invitees

**Comment by kittykat** [comment]
The correct approach would be to check if the room is not a DM and if it is not, then start a conference call instead of a 1:1 call

**Comment by SimonBrandner** [comment]
> The correct approach would be to check if the room is not a DM and if it is not, then start a conference call instead of a 1:1 call

I would argue that we should just check the member + invite count. Making this dependent on whether the room is a DM or not seems a little unideal. Both because people have DMs with more than 2 members and because this can break at times

**Comment by kittykat** [comment]
> > The correct approach would be to check if the room is not a DM and if it is not, then start a conference call instead of a 1:1 call
> 
> I would argue that we should just check the member + invite count. Making this dependent on whether the room is a DM or not seems a little unideal. Both because people have DMs with more than 2 members and because this can break at times

That would work unless a call is already in progress. Good point about DMs having more than two members. Can we do a check on "if room is not a DM and if it has 3+ members"? I defer to @dbkr to check the logic.

**Comment by SimonBrandner** [comment]
> That would work unless a call is already in progress

If a call is already in progress, I don't think this can work?

I think the best could actually be "If a room is not a DM or room has 3 >= members/invitees"

**Comment by dbkr** [comment]
Yeah, we could do that check. I guess it depends on what expectations are of DM rooms, Generally the intention would be to talk to a specific person, so a 1:1 call would make sense: especially if the other user was a bot, but there are probably other cases.

Also worth noting that this bug sounds like it was originally about the old, old MCU based conferencing (since it talks about voip conference users) although obviously the behaviour is still a little odd.

**Comment by SimonBrandner** [comment]
Removed `good first issue` and `Help Wanted` as solving this causes other bugs

**Comment by SimonBrandner** [comment]
Will be fixed by Element Call

**Comment by t3chguy** [comment]
Fixed by Jitsi/EC
