### ISSUE TITLE
Riot/Web didn't show ~7 events in a room, which were visible on Riot/iOS

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#12216]
https://github.com/matrix-org/riot-web-rageshakes/issues/2183 has details

**Comment by IF-Adin** [comment]
> [matrix-org/riot-web-rageshakes#2183](https://github.com/matrix-org/riot-web-rageshakes/issues/2183) has details

That's a 404.

**Comment by uhoreg** [comment]
> That's a 404.

It's a private repository for storing the rageshake data, so won't be visible to the general public.  That page does actually exist. ;)

**Comment by IF-Adin** [comment]
> > That's a 404.
> 
> It's a private repository for storing the rageshake data, so won't be visible to the general public. That page does actually exist. ;)

I'm so sorry, i didn't know.

**Comment by t3chguy** [comment]
Closing this as presumed fixed in the past 4.5 years due to lack of further reported cases
