### ISSUE TITLE
New login/registration flows assume you have a back button, which Riot/Desktop doesn't

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#12323]
e.g. how do I get out of this on Riot/Desktop?

<img width="1035" alt="Screenshot 2020-02-11 at 20 26 26" src="https://user-images.githubusercontent.com/1294269/74276095-fabf2a80-4d0c-11ea-8618-4f45372fe3ee.png">

**Comment by nekojanai** [comment]
I don't think that's an issue anymore?

**Comment by t3chguy** [comment]
Agreed

**Comment by t3chguy** [comment]
Agreed
