### ISSUE TITLE
Regression: Room Addresses in the room settings no longer displays a list of aliases

### ISSUE THREAD

**Issue by hellcp** [element-hq/element-web#12389]
### Description

In all of my joined rooms, the Room Addresses part of the room settings is missing the list of local addresses, stating "This room has no local addresses", despite the fact they have canonical aliases as well as some other aliases.

### Steps to reproduce

- Go to any room in your room list
- Click on the settings
- See the list of aliases missing

![Screenshot from 2020-02-16 16-40-48](https://user-images.githubusercontent.com/30577011/74607706-2d856c00-50db-11ea-89ce-87860408ecfd.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 72.0.2
- **OS**: openSUSE Tumbleweed 20200211
- **URL**: *riot.im/develop/* and *riot.im/app/*

**Comment by tulir** [comment]
It's a feature in synapse 1.10 as a temporary solution for the alias spam that has happened in #matrix:matrix.org and some other rooms recently

**Comment by hellcp** [comment]
That's annoying, what is the plan for fixing it?

**Comment by ara4n** [comment]
https://github.com/matrix-org/matrix-doc/blob/rav/proposal/alt_canonical_aliases/proposals/2432-revised-alias-publishing.md

**Comment by hellcp** [comment]
Huh, that's actually a great proposal, thank you for all the work you put into this :D

**Comment by richvdh** [comment]
related: https://github.com/vector-im/riot-web/issues/12337

**Comment by t3chguy** [comment]
We support the alt aliases API now
