### ISSUE TITLE
Userlist only shows a small subset of users, even across client restarts

### ISSUE THREAD

**Issue by TapGhoul** [element-hq/element-web#12439]
### Description

When loading into a specific room, the userlist only loads a few users (in this case 6), however on mobile I can see all almost 200 users. Restarting Riot does not seem to fix it.

### Steps to reproduce

Honestly no clue.

Log: Sent   

Desktop (borked)
![image](https://user-images.githubusercontent.com/3120639/74948927-146d1a00-5451-11ea-8f34-524e87847387.png)
Mobile (working)
![Screenshot_20200221-022314](https://user-images.githubusercontent.com/3120639/74948969-2a7ada80-5451-11ea-8173-00923fa4f690.png)

### Version information

- **Platform**: Desktop

- **OS**: Arch Linux
- **Version**: 1.5.9

**Comment by t3chguy** [comment]
Closing this as presumed fixed in the past 4.5 years due to lack of further reported cases
