### ISSUE TITLE
After completing security Riot says it's unable to connect to the homeserver

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#12694]
![image](https://user-images.githubusercontent.com/1190097/76459267-7ca08300-63a1-11ea-88e4-cfaf4b5ac670.png)

This is 100% because it's impossible for it to sync fast enough, based on the network requests I see. Just a bit awkward because it clearly can talk to the homeserver, it's just unable to sync.

**Comment by jryans** [comment]
Hmm, so the `initialSync` request is still hasn't responded?

Could you screenshot the network view from DevTools perhaps and / or send a rageshake?

**Comment by turt2live** [comment]
it is 100% the initial sync timing out and taking more than 3 attempts. The devtools window is gone now, and a rageshake from that client has definitely overrun the maximum length due to some testing (sorry).

**Comment by SiinaCutie** [comment]
I am also having this issue in Firefox as well as the glossy desktop app.

Someone was able to register and use it fine, so I warned them to not log out until this is fixed.

The only error showing up is this, and it repeates every n seconds:
```
Waiting for saved sync before retrying push rules... vendors~init.js:2:950859
MatrixClient sync state => ERROR
vendors~init.js:2:950859
Getting push rules... vendors~init.js:2:950859
Getting push rules failed Error: "Server returned 404 error"
    i https://riot.im/app/bundles/9f769ac7a648e2ec9507/vendors~init.js:2
    p https://riot.im/app/bundles/9f769ac7a648e2ec9507/vendors~init.js:2
    f https://riot.im/app/bundles/9f769ac7a648e2ec9507/vendors~init.js:2
    onreadystatechange https://riot.im/app/bundles/9f769ac7a648e2ec9507/vendors~init.js:2
    onreadystatechange https://riot.im/app/bundles/9f769ac7a648e2ec9507/vendors~init.js:2```

**Comment by hosnianas** [comment]
Verifier le fichier sites-aviable de nginx

**Comment by t3chguy** [comment]
Closing due to no reproduction since 2020
