### ISSUE TITLE
Wrong, incomplete or outdated canonical and local aliases shown in room settings

### ISSUE THREAD

**Issue by bwindels** [element-hq/element-web#12891]
Nad:
>  only had #nad-bruno-test:matrix.org as all of local, published & main
which I removed, by deleting it from the local alias section
leaving me with zero aliases
then tried to add #riot-design-internal:matrix.org and was told it was taken, so added #riot-design-internal2:matrix.org

**Comment by bwindels** [comment]
See https://matrix.to/#/!maVEfftuKxhnPMcckU:matrix.org/$15852230571512UdeFP:matrix.org?via=matrix.org&via=vector.modular.im&via=riot.ovh

**Comment by ara4n** [comment]
I think I also saw this at some point, alongside the mess of https://github.com/vector-im/riot-web/issues/12765
