### ISSUE TITLE
Mentions don't highlight the message

### ISSUE THREAD

**Issue by z3ntu** [element-hq/element-web#12923]
### Description

Mentions in Riot don't highlight the message where one was mentioned (anymore?)

![image](https://user-images.githubusercontent.com/3768500/77853519-c0d6b480-71e4-11ea-9131-c44716c35db2.png)

### Steps to reproduce

- Receive a message where one was mentioned
- The message is not highlighted

Describe how what happens differs from what you expected.

The message should be highlighted.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.5.12

**Comment by dbkr** [comment]
Did you change the notification settings for the room in question?

**Comment by z3ntu** [comment]
The room is set to "Mentions only" 
![image](https://user-images.githubusercontent.com/3768500/77910267-297a6b80-728f-11ea-92c2-b7e5b84ecb72.png)

 and my global notification settings are the following:
![image](https://user-images.githubusercontent.com/3768500/77910236-1bc4e600-728f-11ea-8f1d-9fa24c4fa67b.png)

**Comment by Gggarth** [comment]
I experienced this bug, it happened when I had the notifications on "on" instead of "noisy".
When I changed them back to "noisy" and disabled audio notifications, it worked again.

**Comment by t3chguy** [comment]
Closing this as presumed fixed in the past 4.5 years due to lack of further reported cases
