### ISSUE TITLE
Stabilise cross-signing and secret storage APIs

### ISSUE THREAD

**Issue by jryans** [element-hq/element-web#13651]
At the moment, all cross-signing and secret storage APIs in the JS SDK are marked as unstable and may change without notice.

Now that we have released, we should do any API clean up that comes to mind and then stabilise these by removing this text and treating future breaking changes after that point as major version bump as per usual SemVer rules.

**Comment by t3chguy** [comment]
@richvdh is this fixed by your shiny "new" crypto-api?

**Comment by richvdh** [comment]
Yeah I think so! The unstable apis are still there, but will be removed as part of https://github.com/element-hq/element-web/issues/26922, so I think we can close this.
