### ISSUE TITLE
Sessions don't agree whether they're verified/trusted

### ISSUE THREAD

**Issue by gcp** [element-hq/element-web#13744]
### Description

After the upgrade to encryption, I verified all my devices (which involved setting (a) passwords (b) recovery keys (c) signing on to SSO (d) doing emoji pairing). As I finished verifying the last machine, all machines were suddenly not authenticated again. All but one refused the recovery key, so I started the process again from that machine. (I'm not sure if this part is relevant to the bug I'm filing here, but if everything breaks it's hard to know what is relevant or not)

After I finished verifying the sessions, I was stuck with 1 machine that was showing as unverified on the other clients - this was right after I had already verified it. The machine itself doesn't show the "verify this session" doorhanger thing any more. However, I can see the machine in the list of sessions, and it shows as untrusted, even on its own list, and even offers to start the verification against...itself I guess? That seemed to hang though.

### Steps to reproduce

- See above.

Describe how what happens differs from what you expected.

After verifying a machine, it should show as verified on others.

### Version information

**Platform**: web (in-browser)

For the web app:

**Browser**: Firefox Nightly
**OS**: Ubuntu 18.04
**URL**: chat.mozilla.org

**Comment by richvdh** [comment]
Sadly this seems to have bitrotted. Feel free to open new issues if this happens again. Don't forget to submit debug logs from within the client.
