### ISSUE TITLE
Update ThirdPartyMemberInfo as it uses old styling

### ISSUE THREAD

**Issue by t3chguy** [element-hq/element-web#13817]
and so we can remove _MemberInfo.scss it depends on

**Comment by turt2live** [comment]
@luixxiul this may be a good one to take a look at - we're trying to remove the `MemberInfo` classes that `ThirdPartyMemberInfo` uses.

**Comment by luixxiul** [comment]
@turt2live I see, I am going to take a look :-)

**Comment by t3chguy** [comment]
This happened
