### ISSUE TITLE
Terms of Service popup on every key stroke on invitation screen

### ISSUE THREAD

**Issue by mcnesium** [element-hq/element-web#14028]
![Screenshot from 2020-06-14 12-06-25](https://user-images.githubusercontent.com/476060/84590558-06943800-ae38-11ea-809f-1a5885bc3278.png)

In the room invitation screen, when you are not copypasting but actually typing an email address into the field, the terms of service thing pops up as soon as what you typed is recognized as an email address.

The popup returns **on every key stroke** then, even though you may not have completed typing the address. That situation might occur e.g. when you typed `test@domain.com` while you actually wanted to type `test@domain.com.au`, or you want to change anything within the address, correct a typo or change the alias part of your catch-all email account.

Either the delay for the popup should be increased a lot, or the tos notice could be integrated into the invitation screen, with the invite-button disabled until you have checked that checkmark, e.g. like this:

![Screenshot from 2020-06-14 12-22-11](https://user-images.githubusercontent.com/476060/84590900-7efbf880-ae3a-11ea-9018-7d39efae79eb.png)

**Comment by t3chguy** [comment]
Closing due to no further reports in 3 years, presumed fixed
