### ISSUE TITLE
Unable to decrypt messages in chat

### ISSUE THREAD

**Issue by Insaf01** [element-hq/element-web#14074]
I am having trouble reading some messages in chat rooms via pm cause I keep getting this message

** Unable to decrypt: The sender's device has not sent us the keys for this message. **

I am using riot on the web via chrome.

Please help me fix this problem

**Comment by Ezwen** [comment]
Same problem here, I cannot read from Element Web my own messages sent from Element Android. Both devices are verified.

**Comment by nu111** [comment]
Same problem for me and for a colleague of mine. This is the source of decrypted event
```json
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.bad.encrypted",
    "body": "** Unable to decrypt: DecryptionError: The sender's device has not sent us the keys for this message. **"
  }
}
```

**Comment by nakshi-kalolia5** [comment]
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.bad.encrypted",
    "body": "** Unable to decrypt: DecryptionError: The sender's device has not sent us the keys for this message. **"
  }
}

Going through the same.
Has anyone find the solution yet>

**Comment by EricPoggel** [comment]
I signed out and signed back in to Element on Windows 10.  Now I see this same error on all old messages.  My homeserver is matrix.org.

**Comment by omgomgomgomg** [comment]
same here with a bunch of ~50 people, all kinds of clients

**Comment by traceback-ops** [comment]
Same error when sign back into Element

**Comment by Bubanio85** [comment]
Same problem here

**Comment by t3chguy** [comment]
Duplicate of https://github.com/element-hq/element-meta/issues/245
