### ISSUE TITLE
Warn on logout if there are message keys pending backup

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#14830]
Or probably a spinner with an option to skip & discard the keys. Probably a bit of an edge case as they'd generally be uploaded promptly, unless you're offline in which case you're not receiving message keys at all.

**Comment by dbkr** [comment]
It looks like soft logout tries to do something like this but see https://github.com/vector-im/riot-web/issues/14829

**Comment by richvdh** [comment]
duplicate of #27267
