### ISSUE TITLE
Target Node 12 as minimum supported version, package as ES modules for NPM

### ISSUE THREAD

**Issue by jryans** [element-hq/element-web#16274]
These days it's generally safe to target Node 12 and package ES modules natively for NPM. See also https://github.com/sindresorhus/meta/discussions/15 for related discussions.

**Comment by jryans** [comment]
Note this is different from e.g. what version of Node we suggest for development. This is about effectively what JavaScript features do we target as the baseline when publishing packages (JS SDK, React SDK) to NPM.

**Comment by t3chguy** [comment]
We target node 18 now and package all npm packages as ESM
