### ISSUE TITLE
react-sdk jest tests can be way off

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#16840]
The error:
![image](https://user-images.githubusercontent.com/1190097/113248960-28519500-927b-11eb-8de7-384d05676437.png)

The line it is complaining about:
![image](https://user-images.githubusercontent.com/1190097/113249003-399aa180-927b-11eb-8410-2460eb9fb0dc.png)

The error preview is completely wrong, and the line number is way off as well.

**Comment by Palid** [comment]
Seems we need to change babel/typescript config for Jest only. See https://github.com/facebook/jest/issues/336 for reference.

**Comment by t3chguy** [comment]
Haven't seen this in a very long time
