### ISSUE TITLE
[UI] The shield in the room sidebar detail shouldn't cover up the room avatar

### ISSUE THREAD

**Issue by ShadowJonathan** [element-hq/element-web#16950]
![image](https://user-images.githubusercontent.com/22740616/114696274-c5e9a180-9d1c-11eb-99c2-64ed3f09c7db.png)

Currently the shield "covers" the actual room avatar, and it's placement suggests it is another room avatar.

#### Suggestion

Move the shield to the beginning/end of the name of the room in the detail view (just like the titlebar)
![image](https://user-images.githubusercontent.com/22740616/114696428-ed406e80-9d1c-11eb-8bf7-20320fb74ee3.png)

Or; make it smaller in comparison to the room avatar.

Or; make the "shield avatar" not cover the room avatar in this detail view.

**Comment by SimonBrandner** [comment]
![Screenshot_20210414_131556](https://user-images.githubusercontent.com/25768714/114701790-8e322800-9d23-11eb-95ab-a1dd15c92c5f.png)


What about something more like this?

**Comment by ShadowJonathan** [comment]
> What about something more like this?

In the case of non-encrypted rooms I'd maybe also ask for the "circle" to be removed, so it's basically only small badge of a grey shield with a cross through it, without covering a significant part of the avatar.

**Comment by t3chguy** [comment]
This changed in the right panel redesign
