### ISSUE TITLE
Session verification at login is overwhelming to some users

### ISSUE THREAD

**Issue by jryans** [element-hq/element-web#17015]
At the moment, we always show "verify this session" prompts during the login flow when adding any session after the first one, even if you do not have encrypted rooms yet. I believe the Product thinking at the time was that this would be good to recommend for all sessions when you login so they are already cross-signed and ready to go once you eventually do join an encrypted room.

Some people have no intention of using encryption though, and for those users, this verification ceremony is unwieldy and overwhelming.

**Comment by kittykat** [comment]
Also, the verification process doesn't make sense when there is only one session which the user is able to access (e.g. all previous sessions were in private browsing windows).

**Comment by richvdh** [comment]
I think we're committed to this (indeed we're planning to enforce it, cf https://github.com/element-hq/matrix-react-sdk/pull/29).
