### ISSUE TITLE
Desktop Startup "Unable to restore session"

### ISSUE THREAD

**Issue by mirdaki** [element-hq/element-web#17210]
### Description

The last several times I've logged in to my Fedora desktop, Element has failed to restore it's session, and I need to fully re-login. In each case, Element was closed by me restarting the machine before me starting it again and seeing the message.

### Steps to reproduce

- Start Element

It should load up and restore my previous session.

Logs being sent: yes

![image](https://user-images.githubusercontent.com/8786151/117556709-a5152300-b020-11eb-9265-b0c303ad2d50.png)

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Fedora 34
- **Version**: 1.7.25

Thank you for developing Element!

**Comment by mirdaki** [comment]
It may not be related, but each time I've tried to do encryption verification from my phone via scanning the QR code, it fails and I have to do it again or it just takes several minutes to propagate.

**Comment by aaronraimist** [comment]
It is quite likely this is an issue with the community maintained Fedora package. The only Linux package that Element maintains is for Debian/Ubuntu. You should probably open an issue with the Fedora package that you are using.

**Comment by mirdaki** [comment]
Sure thing!

**Comment by omalaspinas** [comment]
I have the same problem on manjaro linux on one of my computers that appeared last week. I'm running:

Element version: 1.10.6
Olm version: 3.2.8

**Comment by richvdh** [comment]
Unsurprisingly, after 3 years, we no longer have the logs for this, so can't really tell what happened.
