### ISSUE TITLE
New image viewing lightbox is too zoomed in

### ISSUE THREAD

**Issue by nadonomy** [element-hq/element-web#17235]
I'm always too zoomed in on large images in the new image viewer. They exceed my screen size and I end up needing to use CMD+/- to view the full image.

I think in an ideal world I'd like:

1. By default, show images at 100%. Shrink to fit if exceeding the size of the viewport.
2. Single click to toggle between:
    1. If an image is shrunk to fit: Toggle between shrink to fit & 100%
    2. If an image isn't shrunk to fit: Toggle between 100% & 200%
3. To be able to click and hold to pan/drag.
4. To have some kind of zoom in/zoom out buttons on canvas, with the zoom level shown contextually (e.g. on hover) and a button to reset to default if I've strayed from it.

**Comment by SimonBrandner** [comment]
@nadonomy, this looks very much like [#17184](https://github.com/vector-im/element-web/issues/17184) which was a bug - should be fixed now

**Comment by SimonBrandner** [comment]
> I think in an ideal world I'd like:
> 
>     1. By default, show images at 100%. Shrink to fit if exceeding the size of the viewport.
> 
>     2. Single click to toggle between:
>        
>        1. If an image is shrunk to fit: Toggle between shrink to fit & 100%
>        2. If an image isn't shrunk to fit: Toggle between 100% & 200%
> 
>     3. To be able to click and hold to pan/drag.
> 
>     4. To have some kind of zoom in/zoom out buttons on canvas, with the zoom level shown contextually (e.g. on hover) and a button to reset to default if I've strayed from it.

Mostly, this is how it works now
