### ISSUE TITLE
Message deletion reason isn't displayed

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-web#17241]
### Description

Deleting (redacting) a message offers to input the reason for the deletion. That reason seems to never be displayed (except viewing the hidden redaction event in debug mode).

### Steps to reproduce

- redact msg

Describe how what happens differs from what you expected.
What is this for if not display? It would also spare people from derailing the conversation by having to explain.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021051101-1

**Comment by SimonBrandner** [comment]
It would require an amount of design work to figure out how to do this. There was [#5604](https://github.com/matrix-org/matrix-react-sdk/pull/5604)

**Comment by HarHarLinks** [comment]
I didn't realize, I'm assuming the argument is that redaction events (i.e. redaction reason) can't be redacted?
In that case, the feature should be removed completely until redesigned in a proper way that prohibits abuse. Further, Element shouldn't offer the reason text input since that is only confusing.
