### ISSUE TITLE
`forget` calls a `membershipChange` of 'forget'

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#17510]
This isn't a membership and is cheating at calling the `/forget` api

**Comment by andybalaam** [comment]
@turt2live is this done? If not, please could you expand the description? I don't understand what this issue means at the moment.

**Comment by Johennes** [comment]
Link to code in question: https://github.com/matrix-org/matrix-js-sdk/blob/6deb2bc7a977ee62be0e923bf7d881d0fccf28e6/src/client.ts#L3945
