### ISSUE TITLE
Element is really confused about Dark Mode vs Light Mode

### ISSUE THREAD

**Issue by xobs** [element-hq/element-web#17592]
![image](https://user-images.githubusercontent.com/238325/121155186-28bd6c00-c87a-11eb-8e16-7f32888a5431.png)

![image](https://user-images.githubusercontent.com/238325/121155224-3246d400-c87a-11eb-8b83-beb480cd9790.png)
![image](https://user-images.githubusercontent.com/238325/121154810-d7ad7800-c879-11eb-87b7-f5dc569b0d3e.png)

### Description

I restarted Element today because it said it had an update. Prior to the update, I was in Dark Mode. After the update, the program restarted in Light Mode.

Clicking the icon in the user drop-down menu doesn't affect the setting. Additionally, in the `Appearance` setting window, the theme always defaults to `Dark` even when it's actually `Light`. In order to force it into `Dark` mode, the setting must be toggled from `Dark` to `Light` and then back to `Dark`.

### Version information

- **Platform**: web (in-browser) or desktop?

For the desktop app:

- **OS**: Windows 10, 20H2, 19042.985
- **Version**: 1.7.30

**Comment by HarHarLinks** [comment]
#17590 perhaps?

**Comment by xobs** [comment]
Yep. Nothing showed up when I searched for "dark mode", hence the new issue. Closing in favor of #17590.
