### ISSUE TITLE
Element Desktop i18n invalid use of Counterpart setLocale

### ISSUE THREAD

**Issue by t3chguy** [element-hq/element-web#17779]
passes an array of strings where a string is expected
https://github.com/vector-im/element-desktop/blob/develop/src/language-helper.js#L108

**Comment by Palid** [comment]
This file doesn't exist anymore, closing.

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-desktop/blob/develop/src/language-helper.ts#L120

**Comment by dbkr** [comment]
Going to say this is a t-task given it doesn't appear to have any user-facing impact

**Comment by t3chguy** [comment]
This got fixed at some point
