### ISSUE TITLE
Progress indicator for key backup restore in background

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#17830]
When we restore the key backup automatically on login, or when you restore explicitly and close the dialog, there's no indicator of progress.

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/element-web/issues/17157 https://github.com/vector-im/element-web/issues/20694

**Comment by richvdh** [comment]
seems to be the same as #20694, but that has more info, so let's close this one.

**Comment by richvdh** [comment]
Duplicate of #20694
