### ISSUE TITLE
Spurious 'upgrade encryption' toast

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#17886]
<del>Seems like it's possible it get 'Upgrade encryption' toasts when everything set up fine: possibly a race where the tests for whether encryption is set up can be run before everything's ready?</del>

Edit: It happens every time the user starts the app, so must be that something is in a weird state where the checks don't think everything's set up but then the bootstrap doesn't do anything.

Rageshake linked.

**Comment by dbkr** [comment]
Also not sure the room upgrades tag is relevant here: room upgrade !== encryption upgrade

**Comment by SimonBrandner** [comment]
I could have sworn there was _room upgrade_ in the title 🤣

**Comment by schildbach** [comment]
Just for reference, here is a screenshot of the toast.
![Screenshot from 2021-07-07 10-29-30](https://user-images.githubusercontent.com/743306/124734913-d96c6900-df15-11eb-9edf-444ad3ad4e47.png)

**Comment by Palid** [comment]
This also happens on the MacOS Desktop version. I can attach some additional logs if necessary.

**Comment by dbkr** [comment]
Looks like we probably fixed a check in the typescript conversion and now this is checking that the key backup key is in SSSS, which is isn't for some people (probably account old enough to have key backup before <del>it was cool</del>.  Hitting the upgrade button should prompt for the SSSS passphrase and save the key backup key to SSSS.

Other possibility is that these are accounts with a transitional 'identity' entry in SSSS (ie. declaring that the key backup secret is the same as the SSSS master key) and element isn't recognising this.

**Comment by dbkr** [comment]
Anyone who's getting this: could you check whether you have your key backup key stored, as follows:

 1. Open devtools by typing `/devtools` and pressing enter in the composer in any room
 2. Click 'Explore Account Data'
 3. Look for `m.megolm_backup.v1`
 4. If it's there, click it

I'm interested in a) whether `m.megolm_backup.v1` is there at all and if it is, whether it's a structure with `iv` /  `ciphertext` / `mac` in it or just `passthrough`, or something else (don't post actual screenshots: it's all encrypted but still, no reason to let the world try cracking your key backup key).

eg. my account has:

![Screenshot 2021-07-07 at 17 50 02](https://user-images.githubusercontent.com/986903/124799511-88c43280-df4c-11eb-960a-f5c85a98de86.png)

**Comment by schildbach** [comment]
For me, `m.megolm_backup.v1` is not present. However I'm using encryption since day 1 (3 years) ago, and I have all sorts of key backups. Is there reason to worry?

**Comment by evoL** [comment]
Same for me, `m.megolm_backup.v1` is not present at all. The account is from 2018.

**Comment by valkum** [comment]
`m.megolm_backup.v1` is missing for me as well. Account is on a private homeserver and from around 2017.

**Comment by dbkr** [comment]
Thanks all - seems like your backup key has just not made it into secret storage at all then.

**Comment by schildbach** [comment]
May I ask how can we fix this?

**Comment by dbkr** [comment]
The 'upgrade' process should probably be fixing this state, so we'll make it so it does.

**Comment by valkum** [comment]
I wan't to adress that in the current state, if I click on the Upgrade button the screen flashes but nothing happens.

**Comment by schildbach** [comment]
Does this fix mean I do nothing and just wait for the update of element-web, which will hopefully fix it by itself?

**Comment by t3chguy** [comment]
You might have to perform the upgrade once to migrate into SSSS

**Comment by schildbach** [comment]
> You might have to perform the upgrade once to migrate into SSSS

After the update of element-web, I assume?

**Comment by t3chguy** [comment]
Yes. On a version with the fix.

**Comment by schildbach** [comment]
I just installed 1.7.33, clicked on "upgrade now" and entered my "Riot Key Backup/recovery passphrase".

However the `m.megolm_backup.v1` key is still not present.

**Comment by evoL** [comment]
For me it works. I refreshed `app.element.io` to launch the new version, entered the security key in both dialogs and now the `m.megolm_backup.v1` key is present.

**Comment by schildbach** [comment]
Can someone re-open this?

**Comment by schildbach** [comment]
For me, there was only _one_ dialog. And no success or failure message.

**Comment by saukko** [comment]
I have this same issue

**Comment by aaronraimist** [comment]
@uhoreg I'm assuming this was an accidental closure?

**Comment by t3chguy** [comment]
Doubt it, upgrade encryption relates to 4S keys, that js-sdk PR touches 4S keys.

**Comment by foxx** [comment]
We're still having this issue even on the latest versions of Matrix, Elements Web and Elements Desktop for Windows.

**Elements Web:** element-v1.10.15
**Synapse:** matrix-synapse-py3 (1.61.1+bullseye1)
**Elements Desktop for Windows:** 1.10.15

To be clear, it happens on every login and will not disappear after entering a valid Security Key or Passphrase. It also does not go away after performing a "Restore from Key Backup" after doing a logout/login.

This seems to have been a problem for at least a year now but it's not immediately clear why it happens.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/651797/176433340-23450805-5bd5-402e-860c-f7ece47302f8.png">

<img width="682" alt="image" src="https://user-images.githubusercontent.com/651797/176433526-ed54221c-5a2e-4d25-9a60-ecedcb922b00.png">

**Comment by pReya** [comment]
Same here, this toast still appears on every login in the browser with latest Element version.

**Comment by derzahla** [comment]
just started happening to me on two of my laptops after upgrading my non-federated homeserver.  I dont get it on my mobile. I have no idea what "security key" i am supposed to enter, account and homeserver were create 5+ years ago IIRC.  I tried restoring from backup, resetting and finally 'rm -rf  ~/.config/Element' on one system.  After logging in and reverifying from my mobile I am not able to see any encrypted history.  What am I supposed to do to fix this?

**Comment by richvdh** [comment]
I'm going to close this, because the original cause is likely long gone.

Anyone continuing to see related problems: Please open a new issue, and send a bug report from within the app.

**Comment by telmich** [comment]
Good day @richvdh - I have just verified that the problem still persists in the following versions:

- elementweb 1.11.59
- elementweb 1.11.65

The error is exactly as describe above, however from devtools the iv / cipheretxt / mac payload in m.megolm_backup.v1 is actually filled in.

It repeats on every login and entering the secure backup key does not work at all.

The setup in this case is using SSO with keycloak as a backend.

**Comment by richvdh** [comment]
>  Please open a new issue, and send a bug report from within the app.
