### ISSUE TITLE
Can't receive friend's messages

### ISSUE THREAD

**Issue by Extarys** [element-hq/element-web#18009]
#### Description

My friend reinstalled Element and still had his recover passphrase. But it says on my side that he is unverified. I can launch the verification process and he accepts, but nothing happens and it times out I guess or I can cancel. If he starts it I don't receive the request. Are we doing something wrong?
He can see the messages I send, but I don't see what he sends. On his ends it looks like the message was indeed received by the server.

The UI provides no feedback or solution for what is happening. I'm glad his computer is next to mine so I can try stuff but I'm glad it's not happening to a remote friend or family member 😂

My side:
![image](https://user-images.githubusercontent.com/11581433/125846974-d3c08492-5cf1-4603-91e0-fd090dea5e26.png)

His side:
![image](https://user-images.githubusercontent.com/11581433/125847146-38906b5f-1c6e-4b9a-9174-7b2cca5d0e77.png)

![image](https://user-images.githubusercontent.com/11581433/125848044-10a664c3-a0c0-4f5e-b5e4-5f32c08b258c.png)

**When I ask for verification:**
![image](https://user-images.githubusercontent.com/11581433/125846282-2e8d4c51-f6cd-4d1c-9e88-c14af5a64496.png)

On his side he gets a popup and accept and then get a loading animation. Then it doesn't do anything until one of us back with the upper left arrow.

I then decide to click don "Verify" under his list of clients I think and it ask for manual or with emoji and that worked. But the overall problem persist.

#### Steps to reproduce

*Not tested*
- Create an account
- Format your computer
- Reconnect with your backup passphrase
- Try PM'ing someone I would assume

I guess it also depends on each users personal configuration.

Describe how what happens differs from what you expected.

I would expect to receive my friends texts, or receive more feedback from the UI on what is going on and how to fix this.
I believe UI feedback is important to help general users/non tech people to use Matrix/element easier.

**Logs being sent:** Yes, one report from each computer.

#### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Linxu openSuse Flatpak
- **Version**:  1.7.32

**Comment by richvdh** [comment]
this seems to have bitrotted. Suggest opening a new issue if it still persists
