### ISSUE TITLE
Unable to "upgrade encryption"

### ISSUE THREAD

**Issue by piggz** [element-hq/element-web#18253]
#### Description

Using element.io, i am regularly prompted that an "Encryption Upgrade" is available. If I click "Upgrade" I am prompted for a "Security Phrase".  When I signed up for matrix, I am sure all I recorded was a Password and a "Recovery Key".  Neither of these works as a "Security Phrase" with the message " Unable to access secret storage. Please verify that you entered the correct Security Phrase."  There is an option to use a "Security Key" again, I dont recall a security key when I set up the account, but I did record my "Recovery Key".  Entering my 48char Recovery Key here, with or without spaces gives the message "Wrong Security Key"

What am I doing wrong, and why is the terminology different?

#### Steps to reproduce

See above

Describe how what happens differs from what you expected.

I expect either my password or recovery key to work, but neither does.

Logs being sent: yes/no

#### Version information

- **Platform**:
Firefox 90.0, Linux, app.element.io

**Comment by richvdh** [comment]
Sadly this didn't get investigated. Anyone continuing to see it: please open a new issue, and send a bug report from inside the app.
