### ISSUE TITLE
M11.8 Iterate on onboarding via URL

### ISSUE THREAD

**Issue by nadonomy** [element-hq/element-web#18290]
* Tight loop iteration, reducing friction from matrix.to -> client
* Revisit opportunities to use restricted room events to better personalise matrix.to content & client preview content
* Could be advantageous to document matrix.to issues in its own repo, but for now will use this issue as a way for us to capture an end-to-end experience into the client

**Comment by t3chguy** [comment]
This lacks sufficient context to continue, will need to be picked up by some future project
