### ISSUE TITLE
Session verification problems

### ISSUE THREAD

**Issue by breadcentric** [element-hq/element-web#18386]
#### Description

I have returned to Element after a 3.5 years break (we can say that I left Riot in favour of Element). I had big problems getting started which started with not being able to verify my sessions. (Side comment: "verify login" sounds like an account verification during registration and "Use another login" as an option to cross-verify sessions sounds like I should be using a different account, not perform an operation between two sessions).

# Steps to reproduce

## First login on phone, then in the web client, emoji verification

 1. Request the verification:
 1. I can see the same emojis on both ends and accept that they match:
 1. Result

1 | 2 | 3 (result)
--- | --- | ---
![](https://user-images.githubusercontent.com/31169082/128221060-5597dbcb-f001-4019-90f0-0471faabfe3f.png) <img src="https://user-images.githubusercontent.com/558581/179873545-5ec5ea77-b837-4ee9-9591-f211e7b94ac3.png" width="540"> | ![](https://user-images.githubusercontent.com/31169082/128221259-31ef08a2-6e87-4534-8d6b-58816cfacec8.png) <img src="https://user-images.githubusercontent.com/31169082/128221553-3e58a34a-0468-4bb5-bffe-2f4b0eb343b6.jpg" width="540"> | <img src="https://user-images.githubusercontent.com/31169082/128221584-fc64bf2f-70a8-4c1c-9f28-4c399f2bc3a9.jpg" width="540"> ![](https://user-images.githubusercontent.com/31169082/128221223-2eb68726-dee1-4a88-a17a-7507e5f1124b.png)

## First login in the web client, then on phone, emoji verification

 1. Request the verification:
 1. again, emojis match:
 1. I accept them and result

1 | 2 | 3 (result)
--- | --- | ---
![](https://user-images.githubusercontent.com/31169082/128221928-ae2e1894-d388-4930-acce-d4d12cc2575a.png) ![](https://user-images.githubusercontent.com/31169082/128222006-2144dc1d-9878-4360-8b10-d03d01c96a84.png) | ![](https://user-images.githubusercontent.com/31169082/128222126-5e44e647-32da-4c69-b9e9-9d9b33a344b0.png) ![](https://user-images.githubusercontent.com/31169082/128222081-f2ebcf7a-bc97-4139-87bf-a7e3760d7326.png) | ![](https://user-images.githubusercontent.com/31169082/128222263-2e41b976-50c7-4587-83b8-86b544991d2b.png) <img src="https://user-images.githubusercontent.com/31169082/128222915-34c3c83d-3fbb-4674-b220-9f00a239f260.png" width="540">

## First login in the web client, then on phone, qr code verification

I was able to scan the code and the phone showed this:
. | .
--- | ---
![](https://user-images.githubusercontent.com/31169082/128222517-4c3691ef-088f-4777-ac34-f324857030d7.png) | ![](https://user-images.githubusercontent.com/31169082/128222545-fe2ee636-e220-47a6-88b2-2f1f5be8bd28.png)

I confirmed and received this on phone and the app:

. | .
--- | ---
![](https://user-images.githubusercontent.com/31169082/128222626-85002bba-d324-4fe8-840c-de596d24ed9e.png) | ![](https://user-images.githubusercontent.com/31169082/128222666-4e61e28c-7f9c-4eff-8e28-b7dfcacc2aeb.png)

I ended up (if I remember correctly I dare not trying to repeat it) going on the phone into settings, security, sessions management and was able to select verification by text which was one-sided and just worked.

If it helps, I have also had problems sending messages in a newly created conversation. I created it on the phone and couldn't send messages, then in the browser I could (and could see them on the phone), but when I logged out and back in in the browser all messages were encrypted. I could only send messages from the phone after I completed the verification.

### Describe how what happens differs from what you expected.

I was expecting verification to work at first try.

Logs being sent: yes

#### Version information

- **Platform**: web (in-browser) or desktop?
In browser (and phone)

For the web app:

- **Browser**: Firefox 90.0
- **OS**: Ubuntu
- **URL**: app.element.io

For the phone app:
1.1.15[40101152] (G-b2969) on Android 10 (Huawei BLA-L29)

**Comment by yuuyins** [comment]
emoji and security key verification are broken between desktop and web for me too since a few versions now

```
Element version: 1.10.8
Olm version: 3.2.8
```

**Comment by richvdh** [comment]
Sadly, this didn't get any investigation 3 years ago, and is no longer relevant
