### ISSUE TITLE
When forgeting a chan in "historical" section, application needs to be restarted to have it disappear

### ISSUE THREAD

**Issue by Porkepix** [element-hq/element-web#18473]
### Steps to reproduce

1. Leave a chan
2. Ask Element to forget that chan after it moved in the historical section
3. The chan is still visible until the software is restarted

### What happened?

The chan is still visible after clicking to forget it

### What did you expect?

It should disappear right away, for that a redraw of the left bar would be needed

### Operating system

Arch Linux

### Application version

1.7.34

### How did you install the app?

Package manager

**Comment by gsouquet** [comment]
Thank you for reporting this issue,

I have tried this in the version 1.7.34 and was not able to reproduce it. The room list is driven by your homeserver.
Either there is a client-side issue that prevents the room from being deleted locally, or your homeserver is not updating the room list quickly enough.

Would you be able to reproduce the issue on your setup once more, and then rageshake (submit logs) before you restart the application?

**Comment by Porkepix** [comment]
I can't "ragecheck" as we're not talking about a mobile application here but about the desktop one. Plus, I always want to check what logs sends before sending anything.

The homeserver is matrix.org, and I already experiences the issue several times.

**Comment by t3chguy** [comment]
Settings > Help & About > Send debug logs

**Comment by t3chguy** [comment]
The historical section is no more
