### ISSUE TITLE
CSS hot reload switches you between light and dark theme upon refresh

### ISSUE THREAD

**Issue by germain-gg** [element-hq/element-web#18484]
### Steps to reproduce

1. Set `MATRIX_THEMES='light,dark'` in `.env`
2. Run `yarn start` in `element-web`
3. Refresh the page, admire which theme is used
4. Refresh the page again

### What happened?

Sometimes the theme will switch from light to dark or from dark to light

### What did you expect?

The theme to remain the same

### Operating system

macOS

### Browser information

Chrome

### URL for webapp

localhost

**Comment by t3chguy** [comment]
CSS hot reload died
