### ISSUE TITLE
Cannot establish VOIP connection between two different matrix servers

### ISSUE THREAD

**Issue by Palid** [element-hq/element-web#18650]
This could probably be split into couple of smaller issues, but I'd prefer someone more involved in VOIP to first have a look at this.
It seems that there's a few different problems here.

First one is that for some reason I couldn't establish VOIP connection neither within matrix.hackerspace.pl <->matrix.hackerspace.pl server, nor matrix.org <-> matrix.hackerspace.pl

The second one is that in case of not being able to establish a connection due to this error (missing config on synapse? turn server? no idea so far) we're not showing any indication of that to in the client, which may make the end-user think that the feature's just broken for no particular reason. Showing that it can't establish connection because it's not supported or something similar would be a much better experience.

**Comment by SimonBrandner** [comment]
@Palid, could you please send your logs, I think we can't do much without them

**Comment by Palid** [comment]
> @Palid, could you please send your logs, I think we can't do much without them

rageshake was sent, just trying to add another two ones.

**Comment by jeena** [comment]
I have something similar but with a twist. I have two users on the same server. As long as they are in the same WiFi then it works just fine, but as soon as we are in different networks I get the same behavior.

**Comment by t3chguy** [comment]
@jeena sounds like your TURN server isn't working.

**Comment by t3chguy** [comment]
Closing as presumed TURN server misconfiguration, no response to dig deeper
