### ISSUE TITLE
Improve ping/highlight colour notification

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-web#18802]
#### What would you like to do?
Change ping/highlight colour.
![Screenshot from 2021-08-26 21-31-19](https://user-images.githubusercontent.com/51663/131034053-5683416f-168c-4f92-931e-dbf1a1682606.png)

#### Why would you like to do it?
- Red is a jarring colour
- Red is a poor choice for red/* colourblind users

#### How would you like to achieve it?
- Change default ping colour - #441
- Invert colour (from theme?) - #1655
- Add a user setting to chose ping colour - #6520

## Pre-development checks
 - [x] Tagged as T-Enhancement and with correct A-* label
 - [ ] Product team confirmed that this feature:
   - [ ] …is on the roadmap or
   - [ ] …could be added to the roadmap or developed by a community member
 - [ ] Final design has been approved by the Element design team and attached to this issue: <link to design>
 - [ ] Acceptance criteria:
   - [ ] Default colour of pings is changed to be not as jarring
   - [ ] Default colour can be changed by users

**Comment by janogarcia** [comment]
@rufuskahler Will be addressed by the new color system in the works as for https://github.com/vector-im/element-web/issues/23302#issuecomment-1381423400 👍
