### ISSUE TITLE
Improve the E2EE device verification and keys requesting flow

### ISSUE THREAD

**Issue by Palid** [element-hq/element-web#18881]
Currently the flow to request keys to unencrypt old messages on a new device is extremely confusing for a lot of users. We don't provide enough data to the users that they will be able to unecrypt only messages from cross-verified sessions, and not from all the verified sessions. 

There's also the case where users click "request keys" link under a message, but that doesn't do anything because this session is not cross-verified with a session that has those keys.

The general idea about this issue is to:

- Improve copy for those actions to properly notify user that they may not be able to unencrypt messages if they aren't cross-verified with proper session
- Add some big, error modal window that your sessions are not properly verified, as of above, and that the keys request has failed

Probably adding a way to see which sessions are cross-verified in the sessions list would be quite useful too, but if I remember correctly we don't exactly have a way of knowing this?

Related: https://github.com/vector-im/element-web/issues/18652

**Comment by americanrefugee** [comment]
Hello! This seems related to [Issue #9544](https://github.com/matrix-org/matrix-react-sdk/pull/9544), in which case perhaps that will fix things. If not, then we can pick this back up whenever it makes sense. Either way I'm happy to support on this issue.

**Comment by t3chguy** [comment]
Closing as most of this has changed and more change is continuing via the Crypto team
