### ISSUE TITLE
Unable to verify other session

### ISSUE THREAD

**Issue by stephen304** [element-hq/element-web#18934]
### Steps to reproduce

1. Have an unverified session
2. Try to verify
3. Enter security phrase to confirm
4. Nothing changes after pressing continue

### What did you expect?
The session to be verified

### What happened?
Nothing - other session is still unverified and restarting the app shows another warning about the unverified session

This might be related to some state on my account - my backups settings section has a weird error:
![image](https://user-images.githubusercontent.com/981915/132268530-9d25d504-5ac0-4b67-9a22-72add81fb517.png)
![image](https://user-images.githubusercontent.com/981915/132268588-62354668-052a-4923-a387-a6d2fbbc5eb0.png)

Also here's the log from the dev console when it completes verification:
![image](https://user-images.githubusercontent.com/981915/132269470-b1b77bb1-bddc-478c-918a-9466ae40e43b.png)

It looks like these 2 issues may be related:
https://github.com/vector-im/element-web/issues/13153
https://github.com/vector-im/element-web/issues/13507

### Operating system

Arch Linux

### Application version

Element version: 1.7.34 olm version: 3.2.3

### How did you install the app?

package manager: https://archlinux.org/packages/community/x86_64/element-desktop/

### Homeserver

matrix.org

### Have you submitted a rageshake?

Yes

**Comment by dbkr** [comment]
Yeah, that error is saying that when it obtained the key it wanted use to sign your device, it didn't get the one it was expecting, so this seems related. Have you reset cross signing at any point?

**Comment by dbkr** [comment]
OK, mostly this was just to figure out how your account could have got into this state, but to work around I'd suggest first try logging out & back in again on the device where you can't verify. If that doesn't work, reset cross signing on one device then log out & log back in again on the others.

**Comment by stephen304** [comment]
@dbkr Unfortunately logging out and back in on my main laptop (where I was trying to verify my work laptop) seems to have made things a bit worse - now my main laptop as well as my work laptop show up as unverified. I can confirm that I saw the same error in the dev console when logging back in (when it asks you to verify, I went with entering my security password instead of following the prompts on my phone).

Curiously, on my phone it shows all my devices as verified. it looks like I may have to reset cross signing :(

**Comment by stephen304** [comment]
@dbkr So I reset cross signing and was prompted to restore from key backup, which took a while for 20,000 keys. I relogged all of my other devices, that seems to have resolved any weirdness and now all devices show as verified on all other devices. I still have some unknown signatures on the backup so I hope that won't cause any issues:
![image](https://user-images.githubusercontent.com/981915/132583365-b9985ff1-2766-4269-ba1b-e6b525ff1c77.png)

**Comment by richvdh** [comment]
looks like this fell off the radar. I assume the OP is no longer struggling with this, three years later.

**Comment by stephen304** [comment]
@richvdh Hi I am actually still experiencing issues that I believe are related to this. I was hoping for a response with guidance on whether the unknown signatures are an issue. Ever since I reset cross signing and restored from backup I have noticed an assortment of weird behaviors related to verification.

This is what my settings > security tab looks like currently:
![Screenshot_20240904_091244](https://github.com/user-attachments/assets/1bb8f95f-8091-4473-b0bb-982cf8f3d9eb)

* There is an unknown error under message search
* There is a promp to "upgrade encryption", but after entering my security phrase, the notification remains (I have confirmed my security phrase like 5 times and it doesn't seem to do anything)
![Screenshot_20240904_091349](https://github.com/user-attachments/assets/a01a7263-97c7-4382-a29a-c02a395d1fa8)
* I am unable to set up backup on my pixel 5 in element (non-x)
  * If I verify with another device, the android says "request sent" and after clicking verify with emoji on my laptop, it gets stuck loading until it times out - my android continues to say "a verification request has been sent"
  * If I try to use my recovery phrase, I immediately get an error "cannot find secrets in storage" - but both my element on android and element desktop are already verified with a green shield so I'm not sure how I am getting this error
![Screenshot_20240904-091826_Element](https://github.com/user-attachments/assets/44589665-c38b-45a7-aa4d-d14662535e8d)
![Screenshot_20240904-092002_Element](https://github.com/user-attachments/assets/f1a39a93-e2e7-449b-8432-78e44c29a7ae)

**Comment by richvdh** [comment]
Ok, a couple of things:

 * signatures on your backup from unknown sessions are not a problem. Likely they are devices that you have since logged out.
 * The "upgrade your encryption" thing is annoying and broken. It is slated for removal, at https://github.com/element-hq/element-web/issues/27455.
 * It seems like there is some important information missing from your server-side key storage; this is probably the reason you are seeing the "upgrade your encryption" thing, and the reason you can't restore with your recovery key on android. https://github.com/element-hq/element-web/issues/27253 is a potential cause here; best workaround is to try a reset:
   1. In Element-Web: make sure that your settings say "**Backup key cached:** cached locally, well formed" and "**Master private key:** cached locally"
   2. Press the "Reset" button under "Secure Backup". It will prompt you to enter a new Security phrase: feel free to use the old one.
   3. It may appear to block the application for a long time: make sure to let it do its thing (https://github.com/element-hq/element-web/issues/26892)
 * The "unknown error" under Message search may well be a separate problem, but let's park that for now.

**Comment by stephen304** [comment]
@richvdh Thanks that was super helpful - resetting resolved the persistent notification and once it finished I was finally able to enable secure backup on element android, as well as sync the backup to element-x which also wasn't accepting my backup passphrase before. So I think we can consider this resolved :tada:

**Comment by richvdh** [comment]
Great, thanks for feeding back, and sorry this got stuck for so long.
