### ISSUE TITLE
Change beta-dot design

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#19083]
Bug to track changing the animation design of the blue pulsating dot that appears on the '+' of spaces when you log in. The dot itself is fine, but the pulsating turns out to be impossible without sending chrome into a mode where subpixel font rendering doesn't work on windows.

This should allow us to resolve https://github.com/vector-im/element-web/issues/18564

**Comment by Palid** [comment]
@dbkr This doesn't seem to be a problem anymore since the DOM refactor. It only breaks rendering for the left-left panel, which didn't have subpixel rendered fonts anyways due to different reasons.
I think we can safely close it?

**Comment by Palid** [comment]
@dbkr closable? 😆
