### ISSUE TITLE
Downloading logs crashes the display manager

### ISSUE THREAD

**Issue by mpldr** [element-hq/element-web#19321]
### Steps to reproduce

1. All Settings
2. Help & About
3. Submit Debug Logs
4. Download Logs

#### What did you expect?

to get my logs

#### What happened instead?

SDDM crashed

### Operating system

Linux

### Application version

1.8.5

### How did you install the app?

pacman (Arch Community Repo)

### Homeserver

moritz.sh

### Will you send logs?

Yes (or at least try it)

**Comment by novocaine** [comment]
Can you record a core dump and send us a stack trace?

Similarly to https://github.com/vector-im/element-web/issues/19169#issuecomment-927973547
