### ISSUE TITLE
Feature Request: Ability to adjust volume of each user.

### ISSUE THREAD

**Issue by dillfrescott** [element-hq/element-web#19369]
#### What would you like to do?

I'd love the ability to adjust the volume of individual users in the call.

#### Why would you like to do it?

Because sometimes some people are way too loud or quiet, especially on some setups. I feel like user volumes is something that should have been added a long time ago. My brother won't even use element because in his words "This is a necessary feature, you would think element would have this by now."

#### How would you like to achieve it?

Just a simple volume slider when a user is clicked on.

### Have you considered any alternatives?

Discord has this, along with many other chat programs that feature audio calling.

### Additional context

n/a

**Comment by SimonBrandner** [comment]
@DillFrescott, are you talking about group calls (Jitsi with more than 2 users)? IIRC, that should already be a thing

**Comment by SimonBrandner** [comment]
> @SimonBrandner My bad, I was under the impression that more than two people could join the integrated calling system.

It's not possible atm, though it should be possible in near future :)
