### ISSUE TITLE
Sending a thread message resets scroll position in main timeline

### ISSUE THREAD

**Issue by germain-gg** [element-hq/element-web#19412]
### Steps to reproduce

1. Scroll up in a room
2. Open the thread panel
3. Send a message in a thread

#### What did you expect?

For the room scroll position to remain untouched

#### What happened instead?

It scrolls to the live position

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I would guess that we dispatch something and it gets caught by both timelines
