### ISSUE TITLE
Download button not working sometimes on encrypted files

### ISSUE THREAD

**Issue by chagai95** [element-hq/element-web#19427]
### Steps to reproduce

No idea

### Outcome

Here is What happened:

https://user-images.githubusercontent.com/31655082/137714917-9d09b759-35f1-4552-b5b0-2e994b4287e7.mp4

### Operating system

Windows

### Browser information

Version 93.0.4577.63 (Official Build) (64-bit)

### URL for webapp

private server

### Homeserver

private server

### Will you send logs?

No

**Comment by gsouquet** [comment]
If you still experience the issue, yes

**Comment by chagai95** [comment]
No I don't - as seen at the end of the video 😉, the issue is about it happening in the first place

**Comment by SimonBrandner** [comment]
So I think this might be happening if the app loads to that room and you don't switch out of it. Will test

**Comment by SimonBrandner** [comment]
> So I think this might be happening if the app loads to that room and you don't switch out of it. Will test

Hmm, that doesn't seem to be the case but the user that is experiencing this seems to be able to resolve this by switching in and out of the room. That room is also the room on which Element did load :thinking:

**Comment by SimonBrandner** [comment]
Have rageshaked from that device though I have doubts about the logs being useful :(

**Comment by chopin2712** [comment]
I have the same issue, I installed it on Linux using the tarball and nginx (the homeserver is matrix.org). I am browsing the website using Firefox, I've tried to hard refresh but the issue is not solved. 

My nginx config file follows this template:

```
server {
	listen 80;
	listen [::]:80;

	server_name domain.tld;

	return 301 https://domain.tld$request_uri;
}

server {
    listen       443 ssl http2;
    listen  [::]:443 ssl http2;
    server_name  domain.tld;

    ssl_certificate /etc/letsencrypt/live/domain.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domain.tld/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/domain.tld/fullchain.pem;

    root   /var/www/element;
    index  index.html;

    location = /index.html {
        add_header Cache-Control "no-cache";
    }

    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Content-Security-Policy "frame-ancestors 'none'";

    error_page   500 502 503 504  /50x.html;
}
```

**Comment by SimonBrandner** [comment]
![Screenshot_20211121_103844](https://user-images.githubusercontent.com/25768714/142756961-0e20c106-0bca-435a-858b-280a9ea2b65d.png)

This just happened to me on a file that first was UISI but that then went away, switching to a different room and back fixed the issue. Have rageshaked

**Comment by NHAS** [comment]
We are having this same issue, users are unable to download encrypted files. I dont have any good information about what may be causing this. 
I am also using nginx with a similar configuration to what has already been posted here, albeit minus the `frame-ancestors` direct (but with X-Frame-Options)

I can tell you that the web application does not even generate a request to our matrix server. So quite certain this is on the web app side. 

For us it has been quite stubborn, I've tried all the fixes mentioned here and none of them work for two of our users. 

We are on the most recent version of element-web 1.9.5.

Also this issue does not occur on element-desktop.

**Comment by NHAS** [comment]
After talking to our affected users I've got some more information about the fault. 

When clicking on the download button, the application successfully issue a network request. 

![image (4)](https://user-images.githubusercontent.com/6820641/143320152-b25f7a42-b14e-4b7e-abe3-2eb2066906a8.png)

However, it doesnt download the file correctly. In the console this error is shown (with domain omitted) 

![image (3)](https://user-images.githubusercontent.com/6820641/143320119-4af5d0e8-cb75-43e5-972b-a9eb5f69fdff.png)

**Comment by emikulic** [comment]
I see this in the JS console when download fails:

```
FileDownloader.ts:50 Error while parsing the 'sandbox' attribute: 'allow-downloads-without-user-activation' is an invalid sandbox flag.
get iframe @ FileDownloader.ts:50
download @ FileDownloader.ts:93
doDownload @ DownloadActionButton.tsx:75
(anonymous) @ DownloadActionButton.tsx:71
[...]
Refused to frame '[url elided]' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

**Comment by SimonBrandner** [comment]
I think I've got the exact repro steps:

1. Have users A and B who have a DM
2. Both users switch to that DM
4. User B turns off their Element
5. User A runs `/discardsession`
6. User A sends a file/picture
7. User B turns on their Element
8. User B clicks the download button
9. Nothing happens

**Comment by SimonBrandner** [comment]
`S-Minor` as the workaround is to switch to another room and then back

**Comment by haydenmc** [comment]
This workaround doesn't work for me - I have the same console output as @emikulic, pasted below.

Should I file a new bug? Currently downloads do not work _at all_, even in unencrypted channels, and I have not found a workaround.

Running Edge Version 101.0.1210.39 (Official build) (64-bit) on Windows 11.

Element version: 1.10.10
Olm version: 3.2.8

```
FileDownloader.ts:50 
        
       Error while parsing the 'sandbox' attribute: 'allow-downloads-without-user-activation' is an invalid sandbox flag.
get iframe @ FileDownloader.ts:50
download @ FileDownloader.ts:93
doDownload @ DownloadActionButton.tsx:76
(anonymous) @ DownloadActionButton.tsx:72
await in (anonymous) (async)
ze @ react-dom.production.min.js:52
Ye @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
wr @ react-dom.production.min.js:100
xr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Me @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Dr @ react-dom.production.min.js:105
Zt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Ae @ react-dom.production.min.js:292
$t @ react-dom.production.min.js:73

Refused to frame '[url elided]' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

**Comment by t3chguy** [comment]
Given the shape of the fix, this is a regression from the media event helper stuff
