### ISSUE TITLE
Code block markup css broke

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-web#19445]
### Steps to reproduce

post a multiline code block using triple backticks

#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/137892324-579719f9-ee4c-4c54-8052-2c9a82970cae.png)

### Operating system

arch

### Application version

Element Nightly version: 2021101901 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by gsouquet** [comment]
Probably related to matrix-org/matrix-react-sdk#6973
