### ISSUE TITLE
Cannot upgrade room due to `Cannot read properties of undefined (reading 'length')`

### ISSUE THREAD

**Issue by Mikaela** [element-hq/element-web#19509]
### Steps to reproduce

1. Open a room
2. Enter `/upgraderoom 9`
3. Confirm that I want to upgrade.

#### What did you expect?

To see a room upgraded to version 9.

#### What happened instead?

I receive error message saying `Cannot read properties of undefined (reading 'length')`

### Operating system

Fedora 35

### Browser information

Vivaldi 4.3.2439.56 (Stable channel) stable (64-bittinen)

### URL for webapp

develop.element.io

### Application version

Element-versio: 4c4b9b96e7f3-react-92df0a35a9bd-js-7ce0eb26d4aa Olm-versio: 3.2.3

### Homeserver

converser.eu, matrix.org

### Will you send logs?

Yes

**Comment by altsalt** [comment]
I am also encountering this error.

Here's the console log after a `clear cache and reload`:
https://gist.github.com/altsalt/d1fc47abbf526cbc418b2635a9722af3

**Comment by t3chguy** [comment]
@altsalt the fix is not yet in a release.
