### ISSUE TITLE
Loading megolm keys from backup (be it online or offline) has become incredibly slow.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#19778]
### Steps to reproduce

* Log in on new instance
* Restore keys from online or offline backup. (124MB of keys for me)
* Wait three hours.

### Outcome

I have around 100,000 keys from memory, so I'd expect to be able to store them in indexeddb at (say) 50/s on a super speedy laptop (this is on a MacBook Pro Max), which would take ~30 minutes.  Instead it took 3 hours.

### Operating system

macOS 12.0.1 on M1

### Application version

Nightly and App

### Will you send logs?

Yes

**Comment by ara4n** [comment]
it's actually storing 30 keys/s into indexeddb :(

**Comment by Palid** [comment]
That sounds like some very weird case of partially fetching data and blocking the fetch before proper encryption/decryption of the previous part.

**Comment by neilalexander** [comment]
Although not quite as large, a 24MB key backup from the server took somewhere between 20 and 30 minutes to process for me yesterday on an M1 MacBook Pro also.

**Comment by richvdh** [comment]
> it's actually storing 30 keys/s into indexeddb :(

I wonder if this is related to https://github.com/vector-im/element-web/issues/15476, where matthew has seen extreme slowness in encryption operations too.

**Comment by richvdh** [comment]
Closing as a duplicate of #15476
