### ISSUE TITLE
Upload manually imported keys to key backup

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-web#19929]
### Your use case

I hope SSSS (secure secret storage and sharing) is the right term for Encryption -> Secure Backup in Security & Privacy Settings.

Export keys from a device that for any reason does not support SSSS key backup or is bugged out. Import the keys in another session which has working SSSS. The keys then are propagated to all other devices via SSSS.

Export **all** keys from SSSS online backup to file. Delete all sessions and Backup, for example if it has bugged out. Restore all keys by importing.

### Have you considered any alternatives?

is this for some reason unsafe? Impossible?

**Comment by dbkr** [comment]
SSSS == storage & sharing for account keys, I think you just mean room key backup. I've updated the title to reflect that - hopefully that reflects the intention? Although I'm not sure about the 'vice versa' part?

**Comment by HarHarLinks** [comment]
> SSSS == storage & sharing for account keys, I think you just mean room key backup. I've updated the title to reflect that - hopefully that reflects the intention?

I mean this thing: 
![image](https://user-images.githubusercontent.com/2803622/144293706-35164d66-aa81-4fc9-b751-4134ed664e97.png)
It's really confusing and I have not seen it explained so far, what all kinds of keys and sharing mechanisms and backups all exist. Would be nice to get an overview.

---

> Although I'm not sure about the 'vice versa' part?

Vice versa is my second point:
> Export all keys from [the same] online backup to file. Delete all sessions and Backup, for example if it has bugged out. Restore all keys by importing.

This exact case has happened to me recently. I exported the keys from an android phone before logging it out and throwing it away. Set up all kinds of backups and cross signing on desktop and new (i)phone. Imported key backup on desktop. Expected keys to get synced to new phone, but they didn't.

**Comment by richvdh** [comment]
I don't really understand what this issue is asking for. Keys that are imported from a file are indeed then uploaded to key backup.

**Comment by richvdh** [comment]
https://github.com/element-hq/element-web/issues/26468 is an issue about the terrible UI in the backup settings, btw

**Comment by HarHarLinks** [comment]
> I don't really understand what this issue is asking for. Keys that are imported from a file are indeed then uploaded to key backup.

it's been a while, but apparently this did not work when I opened this issue.

1. i want to be able to export all keys contained in the key backup using a session that is connected to my key backup
2. i reset the key backup, e.g. because i lost the security key/passphrase
3. i want to be able to import the previously created export not only to the local session but to the new (empty) key backup.

step 3 according to the reply above should work. unclear about step 1.

**Comment by richvdh** [comment]
step 1 will give you an incomplete export until we fix https://github.com/element-hq/element-meta/issues/2446
