### ISSUE TITLE
Some emojis use Inter instead of Twemoji

### ISSUE THREAD

**Issue by Linerly** [element-hq/element-web#20043]
![sunny](https://user-images.githubusercontent.com/47475676/144725386-d0d2c149-e2ee-4745-b198-a84dc6e80c06.png)
![sunny message](https://user-images.githubusercontent.com/47475676/144725438-5b94ebe3-ad7f-46e9-a453-4146f324ce0c.png)

**Comment by t3chguy** [comment]
This looks to be an issue with one of the generated fonts. I can reproduce in Chromium but in FF it is fine.

![image](https://user-images.githubusercontent.com/2403652/144798995-bd47a3fc-460c-4542-a52c-159349509957.png)

It does have the appropriate ligature entry https://github.com/matrix-org/twemoji-colr/blob/matthew/sbix/extras/ligatures.json#L56

**Comment by Linerly** [comment]
Also happens for the ⚠️ emoji as well

**Comment by robintown** [comment]
This is a Chrome bug, tracked at https://bugs.chromium.org/p/chromium/issues/detail?id=964527

**Comment by ara4n** [comment]
This looks to be fixed in Chrome ~131 (certainly today's nightly gets it right)
