### ISSUE TITLE
The React SDK should not include functionality specific to Synapse Admin endpoints

### ISSUE THREAD

**Issue by reivilibre** [element-hq/element-web#20180]
Directly related: https://github.com/matrix-org/matrix-js-sdk/issues/2068

The user panel in the React SDK seems to invoke Synapse-specific admin endpoints to decide whether to show the option to deactivate a user (and supposedly also to perform the action).

This is not portable across homeserver implementations and also would not work in deployments where a reverse proxy such as Nginx has been configured in the recommended way (see the JS SDK issue linked above).

**Comment by t3chguy** [comment]
I agree to an extent, but both are products of the matrix-org entity so its not entirely insane to have some matrix-org but-not-specced extensions supported. Ideally yes these APIs would be adapted by the Matrix specification but until then they provide very essential tools

**Comment by t3chguy** [comment]
This functionality is no longer in matrix-org code but in element-hq code, relating to element-hq/synapse so it is now fine to keep
