### ISSUE TITLE
Cannot decrypt old message

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-web#20461]
On web, I have an old message (`"event_id": "$lrfVE548vZdC2mVJjoXiGkyBl8PiJdWq2RPRyxp3dPU"`) which is encrypted and I get an option to request keys from other sessions:

![Screenshot from 2022-01-10 13-56-05](https://user-images.githubusercontent.com/51663/148778059-2cebc3b1-df1e-4351-9e43-9d7b0d9c71ae.png)

I can re-request keys and the UI says that the request is sent:

![Screenshot from 2022-01-10 13-59-39](https://user-images.githubusercontent.com/51663/148778159-4b600669-b1b0-43a9-9cac-84a975a78b50.png)

But on Android, I don't see the chat in the correct place in my history and I get a `** Unable to decrypt: The sender's device has not sent us the keys for this message. **` error for the message.

I don't have any other sessions running that have this message decrypted as far as I'm aware. I don't think it's a time issue as I've been waiting for it to be decrypted for a while.

Steps to reproduce may include logging out of all sessions and then restoring keys via a security key and then resetting the security key as well at some point.

I'm triaging as S-Critical because I haven't been able to retrieve some information that I need to get from a chat backlog.
O-Occasional because this is happening in every encrypted chat that I have for ~November.

**Comment by aaronraimist** [comment]
Was the message sent while you were logged out of all sessions?

**Comment by kittykat** [comment]
> Was the message sent while you were logged out of all sessions?

No, I was logged in and actively talking to the other person. I also can't decrypt my own messages that I sent in that conversation.

**Comment by waclaw66** [comment]
Related to #19748 and #20434.

**Comment by claell** [comment]
Can you sign in in another session where you verify with a security key? Does that decrypt your messages?

**Comment by waclaw66** [comment]
Maybe caused by https://github.com/vector-im/element-web/issues/20699
