### ISSUE TITLE
Thread panel and right panel having different widths is jarring with new tabs

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#20499]
Personally, I'd like a wide thread panel but a narrow right panel

**Comment by gsouquet** [comment]
Could you maybe elaborate a bit more on how this would work?
The resize handle lets you change the right panel size. I believe the decision was to not do that to avoid more content shifts when clicking different things

**Comment by toger5** [comment]
I could see how this makes sense if the width is stored per room. If I have a room where threads are used a lot the thread panel will be open there and the right panel for this room will have a large width.

**Comment by uhoreg** [comment]
Closing for now.  Feel free to reopen if you have more input on this issue.

**Comment by t3chguy** [comment]
I would value this also, not sure how to accomplish this in a Good UX way but I often find myself with either a too-narrow thread view or a too-wide member list

**Comment by toger5** [comment]
With the recent change of giving the right panel a tab design I find it does not look good if the size changes when pressing on a different tab. (It feels unintentional and as if it is by mistake)

So I think with the tab design the right approach would be to not change the width when clicking a tab. This however yields the challenge how the width can be controlled appropriately.

**Comment by daniellekirkwood** [comment]
My suggestion is that we make the right panel the same width for all views and it remembers the size you set it at... This needs internal discussion

**Comment by daniellekirkwood** [comment]
@americanrefugee recommendation:
- For normal room views, the sidebar should be 320 px wide by default
- For a video call in a room, the sidebar should be 420 px and show the chat/timeline
- Agree that if the user changes the width, it should stay that size no matter which section the user is viewing (in that room)

@t3chguy WDYT? Does this about cover what's needed to move this forwards? Could we play around with a netlify build when there's one available?

**Comment by daniellekirkwood** [comment]
@t3chguy would it be possible to have an event to track if people change the width manually or if folks leave it alone? 

We were specifically talking about if someone in a video room makes the right panel wider or thinner, but I think just knowing whether the width was changed and then cross-referencing with the room type would work

**Comment by t3chguy** [comment]
@daniellekirkwood Sure we can do that
