### ISSUE TITLE
Move all event subscriptions out of c'tor and into didMount

### ISSUE THREAD

**Issue by t3chguy** [element-hq/element-web#20512]
as per React docs recommendations

> Avoid introducing any side-effects or subscriptions in the constructor. For those use cases, use componentDidMount() instead.

**Comment by SimonBrandner** [comment]
@yaya-usman, I've assigned you to the issue. If you need any help/have any questions be sure to visit [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)!

**Comment by yaya-usman** [comment]
@SimonBrandner Thanks

**Comment by t3chguy** [comment]
This happened as part of the React 18 upgrade
