### ISSUE TITLE
Remove `spaceId` from `IRightPanelCardState[Stored]`

### ISSUE THREAD

**Issue by jryans** [element-hq/element-web#20721]
It seems redundant, since the space ID is always the room ID.

**Comment by jryans** [comment]
@toger5 Any chance you remember why the `spaceId` field is there...? Perhaps I am missing a use case.

**Comment by toger5** [comment]
Not really. It was part of the old reference parameters. I think it is the same debate as with the member parameter of the card state. Either we have somewhat redundant parameters. Like roomMember and verificationUser or we only have member. One is redundant but more explicit and the other one. Well is not redundant but less explicit. I think we can do the same with spaceId and roomId.  I would at least add a comment to the state interface to make clear what the value is used for (for room and space id's)

**Comment by t3chguy** [comment]
At one point you could view the member list for a space without switching to the Space home/hierarchy, so it was needed for that, nowadays SpaceMemberList can probably go away entirely and just use RoomMemberList
