### ISSUE TITLE
User profile "disappeared" in a DM and now they can't see my messages

### ISSUE THREAD

**Issue by daniellekirkwood** [element-hq/element-web#20964]
Chatting to a user in DM and their user name and profile picture changed. They could no longer read messages from me (but I could read theirs). 

Sending messages on iOS worked fine and didn't appear to have changed at all. 

I "Clear Cache and Reload" and it fixed it

### Will you send logs?

Yes

**Comment by daniellekirkwood** [comment]
in a meeting, will add more info ASAP

**Comment by t3chguy** [comment]
@MadLittleMods https://github.com/vector-im/element-web/issues/20064
