### ISSUE TITLE
Timeline "glitches": text moves one pixel soon after entering a room

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#21154]
### Steps to reproduce

1. Switch to a new room (or scroll up in an existing room)
2. Wait for a few seconds

![visual-glitch mp4](https://user-images.githubusercontent.com/76812/155110328-1642adfd-b597-47c7-aa31-975b3d68f9c0.gif)

#### What did you expect?
I would see the messages in a room without visual glitches

#### What happened instead?
Some elements on the page move by 1 pixel.

### Operating system

Ubuntu 21.10

### Browser information

Firefox 96.0 (64-bit)

### URL for webapp

https://app.element.io

### Application version

Element version: 1.10.4 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
Can't seem to reproduce that on macOs Firefox/Chrome/Electron.
Might be OS specific?

**Comment by t3chguy** [comment]
@andybalaam are you still seeing this in newer versions of FF?

**Comment by andybalaam** [comment]
Yes, still seeing this in Firefox 115.0.2 on Ubuntu 22.04:

![pixeljump mp4](https://github.com/vector-im/element-web/assets/76812/4e91e47b-11f9-487c-8eff-a6ed306cca04)

**Comment by andybalaam** [comment]
(Note that it only jumps once, not back and forth as the above gif might imply)

**Comment by t3chguy** [comment]
@andybalaam are you still experiencing this?

**Comment by andybalaam** [comment]
No, I am not seeing this today in:

Element version: 6d84073becc9-react-fff0985bf4a2-js-53201688a6d3
Crypto version: Rust SDK 0.7.1 (431263d), Vodozemac 0.6.0
Firefox 127.0.2
Ubuntu 22.04.4 LTS
