### ISSUE TITLE
Encryption "upgrade" deletes all verifications

### ISSUE THREAD

**Issue by Lykos153** [element-hq/element-web#21370]
### Steps to reproduce

1. Where are you starting? What can you see?
I get the notification "Encryption upgrade available"
3. What do you click?
I click on it and proceed. 

#### What did you expect?
That the security of my encrypted keys would somehow be improved (though I'd appreciate a "learn more" link on such messages)
#### What happened instead?
All my other devices and all my contact were suddenly untrusted. I had to verify all my devices again, but now I'm still left with no verified session with other users. Until I see each of them in person, I'm basically left with an insecure channel now.

### Operating system

NixOS

### Application version

Element Desktop 1.10.1

### How did you install the app?

Via nixpkgs (home-manager)

### Homeserver

Synapse v1.54.0

### Will you send logs?

No

**Comment by richvdh** [comment]
This seems to have bitrotted. The "upgrade" flow is due for removal anyway: https://github.com/element-hq/element-web/issues/27455
