### ISSUE TITLE
Device verification fails if verification events are received/decrypted out of order.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#21488]
### Steps to reproduce

1. Run the E2E tests a bunch; note that SAS Verification tests are flakey and fail with things like:

```
log      | received to_device m.room_key from: @alice:localhost id: undefined 
info     | Storing megolm session S9/CNRwJbOg4dMupzNai3gygRGX+o8jyfpST+ASdVwI/0Ms331jT5qdUM1ypZLkmhARk5yMahZUmVuJ0BXXKOs8 with first index 0 
warning  | Error decrypting event (id=$ai2t4IuooBlBt9_zCt-8eqiMTNm6CddAgrE1GZpy0sI): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: S9/CNRwJbOg4dMupzNai3gygRGX+o8jyfpST+ASdVwI|0Ms331jT5qdUM1ypZLkmhARk5yMahZUmVuJ0BXXKOs8] 

...

info     | Decrypted event on retry (id=$ai2t4IuooBlBt9_zCt-8eqiMTNm6CddAgrE1GZpy0sI) 
warning  | Cancelling, unexpected m.key.verification.ready verification event from @alice:localhost 
```

This is because the verification code incorrectly assumes that it's invalid to receive an `ready` event when you have already started verification and received a `start` event - but in practice, it's completely legitimate, as the events can decrypt out of order (caused by the megolm store racing with receiving the ready timeline event in this example).

Currently the behaviour is to cancel the whole verification(!) rather than attempt to reorder the verification events back into a sensible order (or ignore no-ops, such as a ready arriving after a start).

#### What did you expect?

Verification to be reliable

#### What happened instead?

Verification was flakey, and cancelled a valid verification on seeing a transient UISI (in the E2E tests)

**Comment by richvdh** [comment]
Presumably this was specific to the legacy crypto stack
