### ISSUE TITLE
Can't add space admin after rooms creation

### ISSUE THREAD

**Issue by s0p4LiN** [element-hq/element-web#21511]
### Steps to reproduce

I create a public space, I share the link,

 I can add the admin permissions to the joined user by clicking on the space icon > viewing members > select one user > add the permission.

I can not add the admin permission if a room is already created inside the spaces and that I already click once on the room. Everytime I click on the space, I can not see anymore the icon "View member of the space" and then adding the permission I want. It redirect everytime to the last seen room.

Example show below:

Here a SPACE where i did not join any rooms in it, I still can view members and add admin
![element_space_view_members](https://user-images.githubusercontent.com/68989865/159524277-917ca17f-58b1-4a25-8570-024f5dcdd734.PNG)

If there is a SPACE where I joined one room and now I can't "go back" to the main page of the SPACE to add and view members.

#### What did you expect?

Add admin right to a space member

#### What happened instead?

Can't add admin right to a space member

### Operating system

Windows

### Browser information

Chrome 99.0.4844.74

### Application version

Element version: 1.9.8 Olm version: 3.2.8 Matrix Version 1.49.2

### Will you send logs?

No

**Comment by robintown** [comment]
To access the home page for the space again, either right click on the space and select "Space home", or click on the space's name at the top of the room list, and select "Space home". From there, you should see the members button again.

**Comment by robintown** [comment]
(For visual reference:)

![Screenshot 2022-03-22 at 17-22-48 Element The Spaces feedback space ](https://user-images.githubusercontent.com/48614497/159578395-2cc3b32f-b43b-4107-99f1-1df5e4416e06.png)

**Comment by s0p4LiN** [comment]
Hello @robintown 

I only have theses options:

![matrix_home](https://user-images.githubusercontent.com/68989865/159586978-e979c296-8f73-4d65-9225-62a0df20b6cf.PNG)

Maybe because of my old version of Synapse and Element.

**Comment by robintown** [comment]
Ah right, the "Manage & explore rooms" option should do the same thing. I guess the "Space home" button was added later.

**Comment by s0p4LiN** [comment]
Ah ok I understand, thank you very much.
