### ISSUE TITLE
Drop `focus-visible` polyfill once Safari 15.3 is no longer supported

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#21555]
https://caniuse.com/?search=focus-visible

We use [focus-visible](https://www.npmjs.com/package/focus-visible) to polyfill the `:focus-visible` pseudoclass, which we should remove as soon as we're able.

**Comment by t3chguy** [comment]
FTR it doesn't polyfill `:focus-visible` but instead provides a `.focus-visible` class, so a find-and-replace is needed as well as killing the dep

**Comment by yaya-usman** [comment]
@turt2live let me give this trial

**Comment by turt2live** [comment]
(worth noting that we might not be able to accept contributions on this issue for 6-12 months because of the Safari release cycle)

**Comment by yaya-usman** [comment]
> (worth noting that we might not be able to accept contributions on this issue for 6-12 months because of the Safari release cycle)

Ok, let me check other issues to work on

**Comment by t3chguy** [comment]
This got removed by https://github.com/matrix-org/matrix-react-sdk/pull/11677
