### ISSUE TITLE
Design of secret key dialogs inconsistent

### ISSUE THREAD

**Issue by luixxiul** [element-hq/element-web#21572]
### Steps to reproduce

1. Open a private tab on a browser
2. Log in

#### What did you expect?

The style of the dialogs should be consistent.

![after2](https://user-images.githubusercontent.com/3362943/160281384-74c66d32-7d55-4b6a-a8ea-5e1135ab70e4.png)

![after1](https://user-images.githubusercontent.com/3362943/160692394-66b27b08-2df3-464c-8011-4214c7a8f385.png)

![after](https://user-images.githubusercontent.com/3362943/160693474-cbc08e95-7d40-4d48-a551-543793ed6061.png)

#### What happened instead?

Values of border-radius, color, padding, etc. are decided without a specific policy.

- `Reset all` font color is different.
- One of the footer lacks the warning sign.
- The value of border-radius of the dialogs are slightly different
- The padding of the dialogs are slightly different
- The color of the text is slightly different

### Application version

develop branch

### Will you send logs?

No

**Comment by yaya-usman** [comment]
@luixxiul  can you assign me this issue?

**Comment by yaya-usman** [comment]
> @luixxiul can you assign me this issue?

Figured out there is a pull request already

**Comment by luixxiul** [comment]
FYI I cannot assign anyone as I am not a team member.

**Comment by Prakashh21** [comment]
@gsouquet can you assign this to me I am an outreachy 22 applicant. Thanks !!

**Comment by goelesha** [comment]
@luixxiul I would like to work on the issue if it's still open.

**Comment by SimonBrandner** [comment]
> @luixxiul I would like to work on the issue if it's still open.

https://github.com/matrix-org/matrix-react-sdk/pull/8167 already fixes the issue

**Comment by DevanshRaizada** [comment]
I would like to work on the issue if its still open?

**Comment by SimonBrandner** [comment]
> I would like to work on the issue if its still open?

https://github.com/matrix-org/matrix-react-sdk/pull/8167 already fixes the issue

**Comment by luixxiul** [comment]
I will not work on this issue.
