### ISSUE TITLE
Add a Button to get back to /#/home

### ISSUE THREAD

**Issue by benparsons** [element-hq/element-web#21724]
#### What would you like to do?

Get to /#/home via the UI, so that custom versions of that page are more valuable.

#### Why would you like to do it?

To make use of the page for a customer.

#### How would you like to achieve it?

Add an (optional) button/link somewhere, perhaps above the main menu (Avatar button) or inside the menu itself.

**Comment by benparsons** [comment]
@robintown 6442 looks useful, but do you think it's the same? The per-Space Explore Rooms page isn't a customisable HTML page is it?

**Comment by robintown** [comment]
Actually, this already exists, if this comment from Michael is still true: https://github.com/vector-im/element-web/issues/16691#issuecomment-800111626

**Comment by t3chguy** [comment]
Yup, see chat.mozilla.org for an example

![image](https://user-images.githubusercontent.com/2403652/162469583-5f972b98-87af-4150-b796-ee69601b984b.png)

**Comment by benparsons** [comment]
OK thanks. Will leave this closed but can imagine we would want a better UX (even a top level button) for this to be really useful a a portal/landing page for customers.

**Comment by robintown** [comment]
FTR, the reason I linked https://github.com/matrix-org/matrix-react-sdk/pull/6442 is that it takes you back to the home page if you click on the 'Home' space while it's selected.
