### ISSUE TITLE
Regressions on the right chat panel with bubble message layout enabled

### ISSUE THREAD

**Issue by luixxiul** [element-hq/element-web#21774]
### Steps to reproduce

1. Change the message layout to `Message bubbles`
1. Create a room
2. Add a widget to the room
3. Maximize the widget
4. Post something to the chat
6. Reply in thread

#### What did you expect?

- There should not be overflow of anything.
- The style rules for the chat and thread right panel should be integrated.

#### What happened instead?

- [ ] Read avatar overflow: fixed with ~https://github.com/matrix-org/matrix-react-sdk/pull/8470~
- [x] `MessageActionBar` overflow on a thin window

![before1](https://user-images.githubusercontent.com/3362943/163185812-2dff3692-9f0b-4dde-af20-2de9810b89e7.png)

- [x] Long `TextualEvent` overflow: fixed with https://github.com/matrix-org/matrix-react-sdk/pull/8391

### Operating system

Debian

### Browser information

Firefox

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by luixxiul** [comment]
None of those overflow issues are reproduced on the modern message layout- they are specific to the message bubble layout.

**Comment by frakic** [comment]
Encountered a similar issue during a Community testing session.
1. Have message bubbles turned on 
2. Join a video room
3. Have an iOS/Android user start a conference
4. Have them end the conference
5. See the chat window

Expected: no overflows, video conference events display nicely
Actual: read receipts are cut off, conference event bubble is too tight

![image](https://user-images.githubusercontent.com/18530109/171453840-ac96baab-e566-46b6-b34b-0bdc89db066c.png)

**Comment by weeman1337** [comment]
> Read avatar overflow: fixed with

Is back:

![image](https://user-images.githubusercontent.com/6216686/214858383-ced2a08d-4c21-4e3a-bd5d-7bfab5b1ba44.png)

**Comment by luixxiul** [comment]
The issue should no longer be reproduced both on `TimelineCard` and `ThreadView` with https://github.com/matrix-org/matrix-react-sdk/pull/10335

![Screenshot from 2023-03-09 04-59-05](https://user-images.githubusercontent.com/3362943/223839581-a777bf02-ad11-4ac1-91dc-4c4508cc7ac3.png)
