### ISSUE TITLE
Logout a device if users don't put in their encryption key

### ISSUE THREAD

**Issue by chagai95** [element-hq/element-web#21779]
### Steps to reproduce

When the force encryption setup is configured:

* login
* close the tab

Shouldn't the user be logged out?

#### What did you expect?
The device should be logged out.
#### What happened instead?
All rooms are compromised and the UI is all red everywhere.

### Operating system

Windows

### Browser information

Version 93.0.4577.63 (Official Build) (64-bit)

### URL for webapp

private

### Application version

private fork

### Homeserver

private server

### Will you send logs?

No

**Comment by robintown** [comment]
Unsure whether it's possible to get a /logout request through just before tab close, but it's probably worth a try.

**Comment by chagai95** [comment]
Maybe you can force an alert before closing the tab? Or just logout the device after a while if the encryption key was not set?

**Comment by t3chguy** [comment]
> Or just logout the device after a while if the encryption key was not set?

This would need to be done by the HS - given if Element is closed it can't do anything.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/element-hq/element-web/issues/28464
