### ISSUE TITLE
Editing message with _ to add a mention prepends \ in the plain text

### ISSUE THREAD

**Issue by progval** [element-hq/element-web#21801]
### Steps to reproduce

1. From https://riot.im/app/ or https://app.element.io/ join a room bridge to IRC
2. Type `abc_def`
3. Edit the message to add a mention (`@val:e2e.zone` in the example below)

#### What did you expect?

The edit should send `* val: abc_def` to IRC

#### What happened instead?

The edit sends `* val: abc\_def` to IRC

This is because Element added backslashes in the edit box (escapes the underscore), which end up in the plain text field of the event, but not in the HTML field

Here is the full event:

```json
{
  "content": {
    "body": " * val: abc\\_def",
    "format": "org.matrix.custom.html",
    "formatted_body": " * <a href=\"https://matrix.to/#/@val:e2e.zone\">val</a>: abc_def",
    "m.new_content": {
      "body": "val: abc\\_def",
      "format": "org.matrix.custom.html",
      "formatted_body": "<a href=\"https://matrix.to/#/@val:e2e.zone\">val</a>: abc_def",
      "msgtype": "m.text",
      "org.matrix.msc1767.message": [
        {
          "body": "val: abc\\_def",
          "mimetype": "text/plain"
        },
        {
          "body": "<a href=\"https://matrix.to/#/@val:e2e.zone\">val</a>: abc_def",
          "mimetype": "text/html"
        }
      ]
    },
    "m.relates_to": {
      "event_id": "$XBMc28MHS-DXNdlOG-sbgA-mGAyNPjdyOiE1wZVrAOY",
      "rel_type": "m.replace"
    },
    "msgtype": "m.text",
    "org.matrix.msc1767.message": [
      {
        "body": " * val: abc\\_def",
        "mimetype": "text/plain"
      },
      {
        "body": " * <a href=\"https://matrix.to/#/@val:e2e.zone\">val</a>: abc_def",
        "mimetype": "text/html"
      }
    ]
  },
  "origin_server_ts": 1649949612868,
  "sender": "@pinkie:matrix.org",
  "type": "m.room.message",
  "unsigned": {},
  "event_id": "$oMBhZghlvtAQSb75w1G5rFAJcEkpHCyDKkZqAy3KSq4",
  "room_id": "!sbzvsZTdOjEpyDRhiE:libera.chat"
}
```

### Operating system

Debian 11

### Browser information

91.8.0esr

### URL for webapp

both https://riot.im/app/ and https://app.element.io/

### Application version

1.10.10; this does not seem to happen on 1.10.1

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/22456
