### ISSUE TITLE
Messages are missing from threads

### ISSUE THREAD

**Issue by robintown** [element-hq/element-web#21954]
### Steps to reproduce

1. Use a slow homeserver like matrix.org?
2. Start a thread
3. Maybe have another person add a message to that thread
4. Close the thread panel and reload the page
5. Open the thread again

#### What did you expect?

The thread view should show all messages in the thread

#### What happened instead?

It only shows the root message. If someone sends another message while the thread panel is open like this, it gets added, but none of the other messages appear.

![Screenshot 2022-04-27 at 08-58-23 Element Element Web App Team](https://user-images.githubusercontent.com/48614497/165523355-53093e10-9864-4680-ad47-d4da7da5ce5a.png)

### Operating system

NixOS unstable

### Browser information

Firefox 99.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 7c326f49d9f9-react-5a5a79259313-js-3649cf46d343 Olm version: 3.2.8

### Homeserver

Synapse 1.57.0

### Will you send logs?

No

**Comment by gsouquet** [comment]
@robintown Could you check whether you still experience this issue or not?
I've tested this on my end and it seems to be working as expected!
