### ISSUE TITLE
Claimed to have successfully sent e2ee messages... but hadn't.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#21992]
### Steps to reproduce

1. Element Web (EW) was incremental syncing after unsleeping after being offline for ~12h
2. Said server connection was unavailable while it tried to sync
3. I sent a bunch of messages in an E2EE room
4. They were shown to be sent (i.e. ticks in circles as RRs)
5. Restarted the app to try to unstick the sync
6. They were shown as unsent and hadn't actually sent, despite claiming that they had.

#### What did you expect?

Ticks in circles should mean messages were sent, whatever.

#### What happened instead?

Messages were not sent.

### How did you install the app?

nightly

### Will you send logs?

Yes

**Comment by duxovni** [comment]
(Marking as S-Major, because claiming we've sent messages when we haven't is severely misleading to users around core functionality of a messaging app)

**Comment by t3chguy** [comment]
I'm not sure this is what it seems, the before-reload log shows the target eventId, which means that it was indeed sent to the server, otherwise we wouldn't know its eventId given it is returned by the server as part of sending a message
