### ISSUE TITLE
Date separator lines are barely visible in light mode

### ISSUE THREAD

**Issue by robintown** [element-hq/element-web#22122]
### Steps to reproduce

1. Use light mode
2. Look at a date separator in the timeline

#### What did you expect?

The date separator line should have a decent level of contrast

#### What happened instead?

They're barely visible:

![Screenshot 2022-05-09 at 11-50-00 Element 1 Test room](https://user-images.githubusercontent.com/48614497/167448172-b5a92e33-a569-472c-a72a-3e528b4914e3.png)

For comparison, they have significantly more contrast in dark theme:

![Screenshot 2022-05-09 at 11-50-59 Element 1 Test room](https://user-images.githubusercontent.com/48614497/167448306-dc5b09ad-bb34-4f7e-8624-2d3cd379004a.png)

### Operating system

NixOS unstable

### Browser information

Firefox 99.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 1783645108b8-react-e05a3e644659-js-706b4d605481 Olm version: 3.2.8

### Homeserver

Synapse 1.58.0

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
@nadonomy, do you think they should stand out more?

**Comment by nadonomy** [comment]
Yeah, perhaps @gaelledel you could suggest a better colour variable for us to use from Compound which will look good on both light & dark?

**Comment by rufuskahler** [comment]
Removing 'Needs-Design' as will be resolved through EX work.

**Comment by t3chguy** [comment]
@rufuskahler removing X-Needs-Design means anyone can just start it with assets already provided in the issue, (e.g. community) - that does not appear to be the case, maybe you meant to remove X-Needs-Product - as without knowing how design expects this to look this will be impossible to contribute.

**Comment by germain-gg** [comment]
Removing the a11y label, as it is not a requirement for those decorative lines to pass any contrast check. 
This however could be a stylistic choice
