### ISSUE TITLE
Wide image overflows the thumbnail container

### ISSUE THREAD

**Issue by luixxiul** [element-hq/element-web#22303]
### Steps to reproduce

1. Create a wide image
2. Send the image to a room

#### What did you expect?

The image should not overflow the thumbnail container.

#### What happened instead?

It overflows the container.

![before](https://user-images.githubusercontent.com/3362943/169649918-e52264ff-c93c-4c4e-862b-c644a6626201.png)

### Operating system

Debian

### Browser information

Firefox ESR 99

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by robintown** [comment]
This has been intentionally regressed by https://github.com/matrix-org/matrix-react-sdk/pull/8709 to unblock the release
