### ISSUE TITLE
Placeholders on the new message composer have different styling

### ISSUE THREAD

**Issue by luixxiul** [element-hq/element-web#22522]
### Steps to reproduce

1. Compare placeholders of rooms where you are allowed to post and not allowed

#### What did you expect?

Styling based on a design policy

#### What happened instead?

Font-size, font-style, and color of the placeholders are very different.

![after](https://user-images.githubusercontent.com/3362943/173087663-2dbf81b0-5600-4c83-95ef-e8d5338a2f3f.png)
![after1](https://user-images.githubusercontent.com/3362943/173087705-ffd54fb0-6623-45cc-b5ae-b25a6bf95d44.png)

### Operating system

Debian

### Browser information

Firefox ESR 99

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by turt2live** [comment]
blocked on the future of the composer
