### ISSUE TITLE
Seek bar of audio player on high contrast theme (modern layout) cannot be seen

### ISSUE THREAD

**Issue by luixxiul** [element-hq/element-web#22542]
### Steps to reproduce

1. Change the theme to high contrast
2. Send an audio file

#### What did you expect?

Seek bar should be clearly recognizable.

#### What happened instead?

Seek bar is hidden.

![Untitled](https://user-images.githubusercontent.com/3362943/173195423-ad492521-95cc-4e2e-9205-65523b242c47.png)

### Operating system

Debian

### Browser information

Firefox ESR 99

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by turt2live** [comment]
design: what is this component supposed to look like in high contrast?
