### ISSUE TITLE
Pressing ESC should dismiss the search dialogue

### ISSUE THREAD

**Issue by weeman1337** [element-hq/element-web#22605]
#### What would you like to do?

As a user who likes keyboards, I want be able to dismiss the search dialogue by pressing ESC,  
so that I can quickly close the dialogue if I want to.

#### Why would you like to do it?

Efficiency :slightly_smiling_face:

**Comment by weeman1337** [comment]
Looks like a regression https://github.com/vector-im/element-web/issues/21136

**Comment by justjanne** [comment]
Pressing <kbd>Esc</kbd> *does* dismiss the search dialog, but only while the input is focused. You may have focused a different element, and pressed <kbd>Esc</kbd> then?

**Comment by justjanne** [comment]
If it was an issue with the wrong element being focused, https://github.com/matrix-org/matrix-react-sdk/pull/8919 should have fixed it. Could you please verify if that was the source of your issue?

**Comment by weeman1337** [comment]
Hi @justjanne . Tested on https://develop.element.io/ a few moments ago:
- With focus on the input ESC doesn't work
- If I tab to another item ESC works

**Comment by justjanne** [comment]
@weeman1337 Then I’ll need more context, because I can’t reproduce the issue in Firefox 102 on Ubuntu nor in Chromium 103

**Comment by weeman1337** [comment]
Cannot reproduce any more. Going to close this then.
