### ISSUE TITLE
Loading never finishes

### ISSUE THREAD

**Issue by andrewshadura** [element-hq/element-web#22654]
### Steps to reproduce

After a recent update (yesterday or two days ago?) the startup never finishes, with `Loading…` and a throbber endlessly spinning.

### Outcome

I’d expect the app to load normally.

### Operating system

Linux (Debian unstable)

### Browser information

Firefox 100

### URL for webapp

app.element.io

### Application version

Element version: 1.10.15, Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Since I had to clear the local storage to be able to proceed, I don’t have any logs.

**Comment by dbkr** [comment]
Logs should be in indexeddb so there may still be something useful there if you're able to submit as a bug report.

**Comment by turt2live** [comment]
we'll need logs in order to investigate this. If this happens again, please submit debug logs (even if you clear cache & reloaded) for investigation.

**Comment by andrewshadura** [comment]
I think I still have logs. How can I upload them to make sure I don’t potentially disclose any private info?

**Comment by richvdh** [comment]
Unfortunately nobody seems to have investigated this. Closing for now; we can reopen if it happens again.
