### ISSUE TITLE
Build MSI installers for Electron Desktop

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#22658]
#### What would you like to do?

Enterprise customers expect an MSI rather than an EXE for ease of roll-out.

#### Why would you like to do it?

Make enterprise users happy.

#### How would you like to achieve it?

If we're using https://www.electron.build/configuration/squirrel-windows.html, it looks like you flip the `msi` bit to be true.

**Comment by t3chguy** [comment]
> If we're using https://www.electron.build/configuration/squirrel-windows.html, it looks like you flip the msi bit to be true.

This does not do what you expect https://github.com/vector-im/element-desktop/pull/381#issuecomment-1171093326

**Comment by lxp** [comment]
Thanks for implementing this! But where can I download the MSI packages of releases?

**Comment by t3chguy** [comment]
You'd have to build them yourself

**Comment by PC-SPEZIALIST** [comment]
Do you consider to build the MSI packages? 😅

**Comment by t3chguy** [comment]
We do build them, but they are only available for customers of https://element.io/server-suite/pro

**Comment by PC-SPEZIALIST** [comment]
> Thanks for implementing this! But where can I download the MSI packages of releases?

You may get the .msi builds from the GitHub Actions artifacts. 
Example: https://github.com/element-hq/element-desktop/actions/runs/17406583699/artifacts/3907148548

**Comment by t3chguy** [comment]
@PC-SPEZIALIST keep in mind those won't be signed with a production certificate and may include untrusted code depending on which PR run you download from
