### ISSUE TITLE
Resetting backup will desynchronize 4S and change default 4S key

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#22727]
### Steps to reproduce

On a verified session where all secrets are known:

1. Open Security & Privacy, Secure Backup and select 'reset'
<img width="466" alt="image" src="https://user-images.githubusercontent.com/9841565/177181159-85b0fe3b-360b-4a86-aeb1-de5039d9380b.png">

EW will prompt you to choose passphrase or key.
=> Select passphrase

EW will create a new megolm backup, a new 4S key and will update the default key.

Before:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/9841565/177182881-bb43f825-451d-4f8c-bf86-474c0cab6fb7.png">

After:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/9841565/177182909-d422572c-9e3d-4ae4-909b-495dfe0c11ce.png">

## Actual: 
This will create a out of sync 4S, that will create all sort of strange side effects.
E.g double pass request on verifiy:
![webd](https://user-images.githubusercontent.com/9841565/177183098-bbeca443-1e46-42bc-9637-3c47983c0fca.gif)

^ Here I correctly entered the passphrase that was protecting MSK/USK/SSK, so my session is verified, but the megolm backup key is encrypted with another key, hence the new popup.
And if i cancel, the error will bubble up saying that verification failed.. 

## Expected:

Element should prevent users from desynchronize the 4S.
It's not clear what's the intent of the reset button in this UI:
- Is it to rotate megolm backup? (because user thinks it was compromised?)
- Or is it a `reset` applicable to the 4S? In this case as this session knows all secrets user might just want to rotate the 4S passphrase, not rotate the actual secrets.. So that means that the user intent is more `I forgot my recovery passphrase` please let me set a new one, and is very different than I think my keys are compromised and I want to rotate them

As for now, I think that this reset button should be removed, until the UX is properly fixed ([some inputs here](https://hackmd.io/PN4yQVpeRZWWdgmRr8JzZw))
Notice that the delete looks a bit broken too.
But basically as soon as 4S is setup you should not be able to manually updates cross signing or backup without entering 4S passphrase.

### Will you send logs?

No

**Comment by akoyaxd** [comment]
This has been a super intransparent cause of not decryptable Messegas for us. I think by default Element should logout other sessions, so they can become verified again. Or at least, this behaviour should be configurable.

**Comment by BillCarsonFr** [comment]
Tested on the latest rust stack, and:
- the backup is reset
- All the secrets (3 x-signing and backup), are re-encrypted with the new 4S key that is also set as default.

So closing
