### ISSUE TITLE
Invalid sandbox flag in Brave in self hosted

### ISSUE THREAD

**Issue by ghost** [element-hq/element-web#22794]
### Steps to reproduce

1. Open a encrypted room of a server who have a différents domain
2. Clic on download box (in Private message and/or encrypted room).

#### What did you expect?
File (picture or video) downloaded like on the element.io

#### What happened instead?
Do not downloaded ans this error in the console

- Error while parsing the 'sandbox' attribute: 'allow-downloads-without-user-activation' is an invalid sandbox flag.

### Operating system

Linux Fedora 36 (up to date)

### Browser information

Brave Version 1.40.113 Chromium: 103.0.5060.114

### Application version

Element version: 9abbcd041f63-react-9abbcd041f63-js-9abbcd041f63 Olm version: 3.2.8

### Homeserver

anontier.nl

### Will you send logs?

No

**Comment by t3chguy** [comment]
It is an error thrown by your browser. It is part of iframe sandboxing https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/sandbox

**Comment by t3chguy** [comment]
If its working in the same browser on app.element.io but not on your custom deployment then you'd need to ask the support for your browser. Keep in mind that if you don't have any iframes on the page then the error won't come up. Brave is not a supported environment so we cannot offer any further support for it. Brave might have some weird internal config for sandbox flags that do not comply with any followed standards if it so wished.

**Comment by t3chguy** [comment]
Not unless you can reproduce the issue in Chrome, Firefox or Safari, as per the Supported Environments policy.
