### ISSUE TITLE
GET calls unstable instead of stable

### ISSUE THREAD

**Issue by thepra** [element-hq/element-web#22839]
### Steps to reproduce

1. Where are you starting? What can you see?
Homepage post-login as admin, I can see placeholders of rooms that remain placeholders

#### What did you expect?
The client making calls to `stable` path I guess.
#### What happened instead?
I have the client calling `_matrix/client/unstable/room_keys/version` when I did download the stable version 1.11.0 of the client

### Operating system

Ubuntu

### Browser information

Firefox 103

### URL for webapp

chat.zigzag.academy

### Application version

Element version: 1.11.0, Olm version: 3.2.8

### Homeserver

zigzag.academy, Dendrite

### Will you send logs?

No

**Comment by thepra** [comment]
Is there any fix that I could perform locally to fix this?

**Comment by turt2live** [comment]
not without forking Element, unfortunately.
