### ISSUE TITLE
Do we mark messages as authenticated if a room key turns up late (having meanwhile used keyshare or key-restore to grab an unauthenticated key?)

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#22840]
### Steps to reproduce

1. User receives a message whose megolm keys are delayed for some reason
2. The user now can retrieve the missing megolm key directly from the online backup, meaning they get a "can't authenticate" shield on the message, which is a bit scary.
3. When the missing authenticated key turns up, do we mark the message as authenticated?

#### What did you expect?

When delayed keys arrive, unauthenticated keys should be replaced the authenticated ones.

#### What happened instead?

I have a feeling this doesn't happen.

### Will you send logs?

Yes

**Comment by dkasak** [comment]
Possibly related to https://github.com/vector-im/element-web/issues/16318?
