### ISSUE TITLE
Room list icons misaligned or cut off

### ISSUE THREAD

**Issue by Winterhuman** [element-hq/element-web#22850]
### Steps to reproduce

1. Look at the sidebar when it has rooms.
2. Observe circular icons with a flat side on the bottom.
3. Also observe "public room" icons not being centered in their cut outs.

Example (cut offs and misalignment are subtle, need to zoom in quite far):
![Screenshot_2022-07-14_18-19-49](https://user-images.githubusercontent.com/86165318/179045075-1a3b5ea5-10ef-4439-9797-3cda2ae17ecd.png)

#### What did you expect?

Icons not being cut off, and public icons being centered in their cut outs.

#### What happened instead?

Icons are cut off and misaligned.

### Operating system

Arch Linux

### Application version

Element version: 1.11.0, Olm version: 3.2.8

### How did you install the app?

FlatHub

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Winterhuman** [comment]
For a comparison, look at the image in https://github.com/vector-im/element-web/issues/18723.

**Comment by SimonBrandner** [comment]
I am unable to reproduce - could you please share logs and information about you browser?

**Comment by Winterhuman** [comment]
Ah, it's because of my DPI, anytime it's 100-101, 103-104, 106-107, etc, it causes the icon's to cut off and the public status to misalign

**Comment by Winterhuman** [comment]
Just confirmed, changing my resolution from 1440p to 1080p did not fix the issue, things still appear offset and misaligned by roughly the same amount, so unfortunately I can't pin it down to my resolution.

**Comment by Winterhuman** [comment]
Not able to reproduce with the most recent version of Element. Closing issue
