### ISSUE TITLE
Nightly/desktop build config.json still uses lowerCamelCase config options

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#23097]
It's supposed to be snake_case per sample config (https://github.com/vector-im/element-web/pull/21429)

**Comment by DMRobertson** [comment]
Note that I saw this element-desktop (https://github.com/vector-im/element-desktop/blob/develop/element.io/nightly/config.json#L17is) rather than element web

**Comment by SimonBrandner** [comment]
So does web, I think

**Comment by t3chguy** [comment]
This got fixed at some point
