### ISSUE TITLE
Element wont encrypt messages after restarting computer

### ISSUE THREAD

**Issue by Kate-pa** [element-hq/element-web#23137]
### Steps to reproduce

1. After starting Element if my computer was shut down
2. Element  asked for keys yesterday, and the messages won't encrypt
3. Today it won't start at all "failed to resume session"

### Operating system

Windows

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
I am struggling to see what exactly is happening here, would I be correct to assume that 

1. You restart your computer
2. Start Element
3. Can't send messages into encrypted rooms because they are stuck getting encrypted

Or is this issue actually about decrypting? Could you please fill in the issue template?

**Comment by Kate-pa** [comment]
Well, the issue is both with encrypting and decrypting messages after restarting my computer.

1. I restart my computer
2. Start Element
3. Can't send messages into encrypted rooms because they are stuck getting encrypted. And can't see messages in encrypted rooms because they are stuck getting decrypted.
4. Then I have to restore all my keys and it lasts for over an hour. 

That happened two days in a row. And the next day Element stopped unexpectedly and wouldn't start at all and I had the message "failed to resume session". So I had to restart Element and restore my keys again.

**Comment by Kate-pa** [comment]
Well, the issue is both with encrypting and decrypting messages after restarting my computer.

I restart my computer
Start Element
Can't send messages into encrypted rooms because they are stuck getting encrypted. And can't see messages in encrypted rooms because they are stuck getting decrypted.
Then I have to restore all my keys and it lasts for over an hour.
That happened two days in a row. And the next day Element stopped unexpectedly and wouldn't start at all and I had the message "failed to resume session". So I had to restart Element and restore my keys again.

**Comment by richvdh** [comment]
Sounds like https://github.com/element-hq/element-web/issues/24768
