### ISSUE TITLE
Logs can go mysteriously missing

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#23273]
### Steps to reproduce

Unsure.

@kongo09 tried to send a rageshake to debug a UISI, but there was a gap of 5 days in the logs, and we have no idea why. (It might also have caused the UISI, if indexeddb had gone read-only for some reason).

If nothing else, we should completely panic if indexeddb has problems rather than limp along corrupting ourselves.

#### What did you expect?

Logs in rageshakes

#### What happened instead?

Missing logs

### Operating system

Windows

### Application version

1.11.5

### How did you install the app?

element.io site

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by richvdh** [comment]
Not seen this in a year an a half; closing pending more info
