### ISSUE TITLE
Custom translations for 'English US' does not work for all strings?

### ISSUE THREAD

**Issue by wagner-intevation** [element-hq/element-web#23289]
### Steps to reproduce

1. Where are you starting? What can you see?

We have custom translations configured with `custom_translations_url`.
This is the content (for testing, obviously):
```json
{
    "Welcome to Element": {
        "de": "This is 'de'",
        "en": "This is 'en'",
        "us": "This is 'us'",
        "en_us": "This is 'en_us'",
        "en_US": "This is 'en_US'"
    },
    "Decentralised, encrypted chat &amp; collaboration powered by $matrixLogo": {
        "de": "This is 'de'",
        "en": "This is 'en'"
    }
}
```

2. What do you click?

Opened /#/welcome

#### What did you expect?
Getting translated strings in German, English and English (US)

#### What happened instead?
`Welcome to Element` is not translated in *English (US)*. Tried various common language codes, none of them works.

With *English (US)*:
![image](https://user-images.githubusercontent.com/104974727/190467600-e01dd5ff-1f02-410e-8643-69f9c23986f3.png)

With *English*:
![image](https://user-images.githubusercontent.com/104974727/190467738-f660826a-22ce-4f6b-b99d-395f89d01bb1.png)

With *German*:
![image](https://user-images.githubusercontent.com/104974727/190467866-d5501736-93ce-418e-b4ab-c0a42ff20ccb.png)

### Operating system

Linux

### Browser information

Firefox 104.0.2, caching disabled

### URL for webapp

Element Web version 1.11.4

### Application version

1.11.4

### Homeserver

Synapse 1.66.0

### Will you send logs?

No

**Comment by gabrc52** [comment]
Hmm. I had custom translations for English and I was using just `en`, but it seems that either when upgrading from Element 1.11.39 to Element 1.11.45 or when updating Element 1.11.45 to Element 1.11.48 they stopped working.

Did you figure anything out?

**Comment by sebix** [comment]
No, I could not solve the issue

**Comment by wagner-intevation** [comment]
No, I could not solve the issue

**Comment by t3chguy** [comment]
I cannot reproduce this anymore, but also English US got disabled due to being incomplete in Localazy.
![image](https://github.com/element-hq/element-web/assets/2403652/17a48ba3-659c-4c26-851d-f30383c09033)

**Comment by wagner-intevation** [comment]
As `en_US` is completely removed, this issues is indeed solved.

**Comment by gabrc52** [comment]
@wagner-intevation Can you share your config? I could not get the custom translations to work

**Comment by gabrc52** [comment]
Nevermind, I've gotten it to work. The key format changed from a full string to a path of keys separated by pipes, which is why my old config stopped working.

For example, if you wish to override the `"Remove 1 message"` string, you have to use `"user_info|redact|confirm_button|one"`. The welcome to Element may just be `"welcome_to_element"`, but there is also `"onboarding|welcome_to_brand"`.
