### ISSUE TITLE
Unable to decrypt after verification until reload

### ISSUE THREAD

**Issue by weeman1337** [element-hq/element-web#23333]
### Steps to reproduce

1. Don't set up key backup.
2. Have working session with all keys available.
3. Have an encrypted room with some messages.
4. Sign in to a second session.
5. Open the room in the second session.
6. „Unable to decrypt“ visible.
7. Go to security settings and verify your device with the other session.
8. Look at the room

#### What did you expect?

Messages are now visible

#### What happened instead?

Still „Unable to decrypt“

Reloading the page gives a high chance for the messages to appear.

### Operating system

Ubuntu 22.04.1 LTS

### Browser information

Firefox 105.0 \(64-bit\)

### URL for webapp

https://develop.element.io/

### Application version

Version von Element: 287a73506c29-react-71cf9bf932cc-js-7e24cb6cae8c Version von Olm: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by turt2live** [comment]
I believe this is a race condition: we appear to block decryption until after all the keys are received, so on large-ish backups this can take a while.

**Comment by weeman1337** [comment]
From a user perspective I would still say this is an `S-Major`. Because Element ends up in an unusable state for me = cannot read my messages.

**Comment by giomfo** [comment]
Is there an actual reason to block the decryption until all the keys are received?
- if yes, we may ask for a design to let the user know about this, this would improve at least the user experience. Currently the user just believes the decryption is not working and triggers multiple new key requests
- if no, we should fix it to improve the end user experience

**Comment by weeman1337** [comment]
Reopening this one because we had to roll back the fix. It caused existing sessions to send all the keys around. That eventually leads to thousands of requests.

**Comment by richvdh** [comment]
This sounds like #27009.
