### ISSUE TITLE
Restore keybackup after verification will freeze E2EE for big backups

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#23359]
### Steps to reproduce

1. Need an account with a big key backup (100k keys)
2. Login a new web session
3. Verify with passphrase (or any)
4. Wait a few moment for the keybackup data to be downloaded

#### Actual

As soon as the backup is downloaded the SDK will start looping to decrypt all keys and import them.
Log is full of this
> Storing megolm session aXXXXXXXMD/XXXXXXXwith first index 0

Now you can see incoming messages in e2ee rooms.
If you try to send a message, it will be stuck until all backup is imported

=> For my backup its more than half an hour

Workaround => refresh the page to stop that auto import (at the risk of losing the unprocessed to_device received meanwhile)

#### Expected

It should not import the full backup like that, unless there is a proper way to have it in background, with user feedback, by chunks and priorize per active rooms.
It can just be disabled now, as the backup is queried incrementaly on fail to decrypt.
Full import could still be done from the UI where we have a proper feedback.

I am unsure why it's locking every e2ee related actions. Maybe too many transactions on DB? I am not sure how web is doing things in background

### Will you send logs?

No

**Comment by anoadragon453** [comment]
> Workaround => refresh the page to stop that auto import (at the risk of losing the unprocessed to_device received meanwhile)

In my case, freezes persisted even after refreshing the page.

**Comment by richvdh** [comment]
Related: https://github.com/vector-im/element-meta/issues/2176

**Comment by richvdh** [comment]
Also related: https://github.com/element-hq/element-web/issues/20694
