### ISSUE TITLE
develop.element.io: Unable to restore session

### ISSUE THREAD

**Issue by jaller94** [element-hq/element-web#23522]
### Steps to reproduce

Not sure how to reproduce. Just sending logs for now.

0. Be logged into develop.element.io
1. Open develop.element.io.

#### What did you expect?
Element to start up.

#### What happened instead?
Element not starting and asking me to sign out.

### Operating system

Manjaro Linux

### Browser information

Mozilla Firefox 106.0b8

### URL for webapp

develop.element.io

### Application version

unsure; will add, if I find that out; current build as of 2022-10-18

### Homeserver

An unknown, older 2022 version of Synapse

### Will you send logs?

Yes

**Comment by kittykat** [comment]
@jaller94 Rageshake please
