### ISSUE TITLE
no spinner after starting a DM from spotlight

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#23545]
Open spotlight search; search for a person via the user directory; hit enter to start a DM while on bad connectivity; see absolutely no feedback that the app is trying to start a DM. After a few minutes, suddenly get catapulted into the DM pre-compose screen

**Comment by weeman1337** [comment]
As far as I can see spotlight does not have a loading state, yet
→ we need a design for this

**Comment by gaelledel** [comment]
Need to add the "Joining..." with loader - (already implemented no design required)

**Comment by dbkr** [comment]
Should be a couple of hours to re-use the normal 'joining room' spinner (perhaps with a different title). Should be maintainer sized.

**Comment by t3chguy** [comment]
![image](https://github.com/element-hq/element-web/assets/2403652/198320df-2468-4ec6-919c-a029b6666e39)

Cannot reproduce the flow this is complaining about, @ara4n could you please share a recording of what you're encountering?

**Comment by t3chguy** [comment]
Closing presumed no longer happening
