### ISSUE TITLE
Maximising and then unmaximising a widget results is the chat appearing in two places

### ISSUE THREAD

**Issue by uhoreg** [element-hq/element-web#23591]
### Steps to reproduce

1. Enter a room with a widget
2. Click on the widget's Maximise button
3. Click on the widget's Unmaximise button

#### What did you expect?

The widget should be unmaximised and the chat should only appear under the widget

#### What happened instead?

The chat also appears in the sidebar (which originally appeared after maximising the widget), in addition to showing under the widget

![image](https://user-images.githubusercontent.com/1012976/197840499-5b6ec6cd-6786-45b3-ab74-02f73088f837.png)

### Operating system

Debian Linux

### Application version

Element Nightly version: 2022101201 Olm version: 3.2.12

### How did you install the app?

Debian repo

### Homeserver

uhoreg.ca

### Will you send logs?

No

**Comment by t3chguy** [comment]
Fixed by https://github.com/element-hq/matrix-react-sdk/pull/94

**Comment by t3chguy** [comment]
Fixed by https://github.com/element-hq/matrix-react-sdk/pull/94
