### ISSUE TITLE
Cannot re-login after logout unless I did a security key backup *before* logging out

### ISSUE THREAD

**Issue by RalfJung** [element-hq/element-web#23698]
### Steps to reproduce

1. Log in to an element instance for the first time without even having an account yet (I guess this implicitly creates an account on the same server?), giving it browser permission to store things in persistent storage
2. Chat with people for a bit
3. Log out from element
4. The next day, log back in

The usecase here is to basically use element+matrix as alternative to Slack/Mattermost/Zulip, where most people will only ever log in from a browser.

#### What did you expect?
I should get back to where I was when I logged out.

#### What happened instead?
I get an error saying I need to "verify" this "new device" from another device. However this device is not new (same browser as yesterday) and there is no other device I could use for verification. The only alternative is to reset my security key and lose access to all chat history from the day before.

Element does not make it even remotely clear enough that doing a backup of the security key is needed *to survive logging out and back in* (or even just doing a browser restart, in case that is configured to erase cookies). There were some reminders for doing a key backup, but they made it sound like backups would be needed in exceptional circumstances and were easily dismissed. Given that even the completely normal circumstance of logging out and back in seems to lead to complete data loss without that key backup, Element should probably *force* people to store that key. (And indeed, after re-generating the key on my second login, it *did* force me to store it in a file. When I tried to cancel that it didn't even apply the new key.)

### Operating system

Linux

### Browser information

Firefox 107

### URL for webapp

Element version: 1.11.13, Olm version: 3.2.12

### Application version

Element version: 1.11.13, Olm version: 3.2.12

### Homeserver

no idea, how do I find out?

### Will you send logs?

No

**Comment by t3chguy** [comment]
> However this device is not new (same browser as yesterday)

Logging out deletes all session data from your browser, so there's no way to know this is the same browser as yesterday, this is by design for privacy

**Comment by RalfJung** [comment]
> Logging out deletes all session data from your browser, so there's no way to know this is the same browser as yesterday, this is by design for privacy

That makes sense. But for a user it is confusing to call this a new "device". And it is rather irritating when it tells me to log in with another device when the only device I ever actually logged in with is the one I am using right now -- *there is no other device*.

Those are wording details though, the worst part is that it doesn't make it clear that I need to do a backup to survive a logout. I am quite experienced with cryptographic messengers and even I fell into this trap. (I thought it would use "persistent storage", whatever that is but it has permission to access that, to store whatever keys it needs to store.)

**Comment by florianduros** [comment]
For your information, in the labs settings you can enable a new session manager (in BETA) which replace the device part of Security & Privacy. It will not change the current behaviour but the wording is more friendly and more clear.

**Comment by andybalaam** [comment]
Related: https://github.com/vector-im/element-web/issues/14830

**Comment by andybalaam** [comment]
Related: https://github.com/vector-im/element-web/issues/9444

**Comment by andybalaam** [comment]
Related: https://github.com/vector-im/element-web/issues/3611

**Comment by richvdh** [comment]
>  Cannot re-login after logout unless I did a security key backup *before* logging out

This is incorrect. You can log in just fine. You might not be able to access your encrypted history, but I'm not quite sure what other behaviour you expect.
