### ISSUE TITLE
Unable to trust another session

### ISSUE THREAD

**Issue by Nono-m0le** [element-hq/element-web#23712]
### Steps to reproduce

I'm using my account on 4 devices, among 3 already trusted : Windows with Chrome, Windows with Firefox, Android with Element app and finally Linux with Firefox which I can't trust.

1. I use the verification with another devices. Everything seems to works, until the end
2. When I check the list of trusted devices, the latest one is not.
3. The options "Never send encrypted messages to unverified sessions from this session" is disabled on all devices.

On the firefox logs I got that :
`Verification completed! Marking devices verified:`

But a bit later :

```
user_signing requested by SCTUYNDPNM, but not found in cache rageshake.ts:64:12
Request denied for m.cross_signing.user_signing secret for SCTUYNDPNM rageshake.ts:64:12
session backup key requested by SCTUYNDPNM, but not found in cache rageshake.ts:64:12
Request denied for m.megolm_backup.v1 secret for SCTUYNDPNM
```

#### What did you expect?

my 4th device to be trusted

#### What happened instead?

My 4th devices is still not trusted

### Operating system

Debian 11

### Browser information

Firefox 106.0.5

### URL for webapp

https://app.element.io/

### Application version

Element version 1.5.4

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
@Nono-m0le unfortunately am not seeing your logs, could you please upload them again, from both sides of the verification ideally? Thanks

**Comment by Nono-m0le** [comment]
[issue.txt](https://github.com/vector-im/element-web/files/9955682/issue.txt)
[log-0.log](https://github.com/vector-im/element-web/files/9955683/log-0.log)
[log-1.log](https://github.com/vector-im/element-web/files/9955684/log-1.log)
[log-2.log](https://github.com/vector-im/element-web/files/9955685/log-2.log)
[log-3.log](https://github.com/vector-im/element-web/files/9955686/log-3.log)
[log-4.log](https://github.com/vector-im/element-web/files/9955687/log-4.log)

**Comment by Nono-m0le** [comment]
it turns out, with one of my other 2 devices, I finally suceed to trust my fourth device.
The issue remains (could it be caused because of the App ?). Let me know if I shall close the issue (as solve on my case), or let it open (as the initial issue may still raise at some point).

**Comment by richvdh** [comment]
this seems to have bit-rotted
