### ISSUE TITLE
Keyshare-on-invite should start with most-recently-used sessions

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#23778]
When inviting a user to a room, we share megolm keys for the room history. This can result in thousands of to-device events, which can take a significant amount of time to be sent and received, which means it can take a while before the recipient can decrypt the most recent events, leading to #22999.

If we sent out the most-recently-used sessions first, that would improve the experience.

**Comment by richvdh** [comment]
It's likely we'll "fix" this by [migrating to the rust crypto-sdk](https://github.com/vector-im/element-web/issues/21972) (not that it implements this yet: https://github.com/matrix-org/matrix-rust-sdk/issues/580)

**Comment by BillCarsonFr** [comment]
Closing as this concern the old implementation that we don't support in the rust stack. 
The future MSC and implementation will have requirement to be faster
