### ISSUE TITLE
Permanent stuck unread-notification when starting a thread with a reply message

### ISSUE THREAD

**Issue by quazgar** [element-hq/element-web#23976]
### Steps to reproduce

1. Have threads enabled
2. Person A: write message "text A"
3. Person B: Reply to A without threads
4. Person A: Reply in thread to B

#### What did you expect?

Reading the message should mark it as read.

#### What happened instead?

1. Person B's message will permanently be marked as unread and highlighted (because it's a reply) in A's app.
2. The thread does not show up as unread in the thread overview
3. Workaround: Deleting B's initial message by A will remove the notification.

### Operating system

Debian Bullseye

### Application version

Element version: 1.11.16 Olm version: 3.2.12

### How did you install the app?

From https://packages.riot.im/debian

### Will you send logs?

No

**Comment by gsouquet** [comment]
I don't think I managed to reproduce the issue you're facing, here's a little video of me following your repro steps. 
Could you share some more details regarding the notification settings on your account and the ones that are applicable to the room you're experiencing this problem in?

https://user-images.githubusercontent.com/769871/207801863-9af389c8-053c-4826-8958-497f269d5e6b.mov

**Comment by t3chguy** [comment]
Believed to be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3600
