### ISSUE TITLE
Dismiss action bar after failing to automatically decrypt messages - 'Open another device to load encrypted messages'

### ISSUE THREAD

**Issue by reivilibre** [element-hq/element-web#24067]
#### What would you like to do?

I'd like to be able to dismiss this warning:

> Open another device to load encrypted messages
>
> This device is requesting decryption keys from your other devices. Opening one of your other devices may speed this up.
>
> [View your device list] [Resend key requests]

![](https://user-images.githubusercontent.com/38398653/208718176-d8f9041a-2cec-4f50-bc02-74dad738f5a2.png)

#### Why would you like to do it?

I don't have any other devices to give me the keys.
The warning is distracting and takes up screen space.

#### How would you like to achieve it?

A cross or 'Dismiss' button

**Comment by MadLittleMods** [comment]
> I don't have any other devices to give me the keys.

Dismissing is a good addition in any case but is there another specific hint we can give here for people without any other devices to try?

**Comment by BillCarsonFr** [comment]
It's strange that it's showing up if you don't have any other device, it shouldn't.
Also the banner is there to give a feedabck that there is an active attempt to get the keys from other devices, it will eventually timesout if no replies is coming (and then disappear).
Clients supporting withheld codes would reply saying why they won't/can't share (not authorized, not verified, ..). If all sent a negative reply the banner should disappear

**Comment by OJ** [comment]
I've been playing with multiple clients and homeserver configurations, and along the way have blasted away client installations. I am seeing this message a lot as a result (yup, self inflicted).

I am seeing this message come up a _lot_ and it'd be great for my use case (as well as others I'm sure) to at least have the ability to get rid of it for a given room.

FWIW, I'm using the desktop client on Windows, though I'm sure the issue exists across all platforms. Happy to create another issue in the `element-desktop` repo if that makes more sense.

Thanks!

**Comment by tobast** [comment]
I am having the same issue in a room where one of the members had a problem with their client and sent a message; no one else in the room is able to decrypt this specific message. Yet the banner still shows up on my devices. All of them are online, yet the banner does not disappear.

Another way to handle this issue could maybe be to add an option on messages to ignore them and stop trying to decrypt them?

**Comment by mythsmith** [comment]
Same problem here. Suddenly all 3 of my clients say they cannot decipher messages and are requesting the keys. The banner is still there on all 3 devices after hours and no message gets decrypted.

**Comment by muellerlukas** [comment]
Same here. Also all devices keep trying go get the keys and also show this banner.

**Comment by flochir** [comment]
Same here, with matrix-commander as the only second device. Couldn't quickly figure out how to get matrix-commander to share the keys and also I don't care about the undecryptable messages - dismissal would be a great option.

Also observed the same issue with another account between element and nheko installations and was only able to get rid of the message by booting another device that I didn't intend to use at the time.

element-desktop: 1.11.20-1
matrix-commander: 6.0.1

**Comment by ThiefMaster** [comment]
I think the main point here is that in some cases there is literally nothing I can do even with all of my devices being active. I usually get this when someone sent me a message while on a very poor internet connection - not sure what happens but I have the feeling some keys are not being sent at all. It looks like this is an issue on the sender's side so it's not something that can be fixed in any way on my side... so the notification is just annoying ;x

**Comment by sbrooke** [comment]
I run a home server for a small group of friends. We get key request pop-ups across all of our Element clients (desktop and mobile) almost every day. In most cases they go away (self resolving?) but sometimes they stick around for a day. It's incredibly annoying.

**Comment by richvdh** [comment]
This bar no longer exists
