### ISSUE TITLE
Can't delete a recreate session backup

### ISSUE THREAD

**Issue by germain-gg** [element-hq/element-web#24073]
### Steps to reproduce

1. Needed to reset and recreate my session backup
2. Don't know the exact steps, but i'm attaching a rageshake to this issue.

#### What did you expect?

To be able to

#### What happened instead?

Was not able to

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
At least there are some errors related to this in the logs

**Comment by weeman1337** [comment]
Does it work if you try again @gsouquet ? I would then lower the severity.

**Comment by gsouquet** [comment]
Unfortunately no, I can't recreate a session backup on my test account.

**Comment by richvdh** [comment]
> Can't delete a recreate session backup

I don't really know what these words mean! If this is still a problem, let's clarify and reopen, but I'm closing for now.
