### ISSUE TITLE
error at startup

### ISSUE THREAD

**Issue by Dodrekai** [element-hq/element-web#24283]
### Steps to reproduce

1. Where are you starting? What can you see?
3. What do you click?
4. More steps…

Element start with a screen asking to send debug journals. It happened after pc reboot. At precedent session, element crashed (silently) and asked for login. Login went normally.

#### What did you expect?
Element launch normally
#### What happened instead?
Element is in "error mode" and ask me to delete files and keys

### Operating system

pop!_os (latest)

### Application version

1.11.20

### How did you install the app?

from flatpak

### Homeserver

marcheurs-statiques.org matrix synapse 1.75

### Will you send logs?

Yes

**Comment by richvdh** [comment]
The rageshake logs have rotated. Seems like this has gone stale.
