### ISSUE TITLE
Room stuck as unread after mention in a thread

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#24312]
### Steps to reproduce

Not sure if it happens every time, but here's what happened for me: 
1. Set (encrypted) room to "Mentions Only"
2. Start a thread, have conversation with someone in that thread
3. Other user pings you in that thread (in my case, through a reply to a message in the thread)
4. Room lights up red
5. Open thread, read message. Room drops down to "unread" (`BOLD` state internally)
6. No amount of trying to clear the notification works: reading all threads, sending messages in the thread, etc
7. Someone sends a new message into the main timeline
8. Mark that message as read and the room instantly marks itself as read too, fixing the issue

#### What did you expect?

not that

#### What happened instead?

the steps above describe what happened

### Operating system

Windows 10

### Application version

Nightly (2023-01-24)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by langleyd** [comment]
I tried to reproduce this on the latest and couldn't. We believe it was fixed by https://github.com/matrix-org/matrix-js-sdk/pull/4022. Please report if you see it again though, thanks!
