### ISSUE TITLE
Allow to configure Element Settings after installation / before login

### ISSUE THREAD

**Issue by 8227846265** [element-hq/element-web#24390]
#### What would you like to do?
- After you install Element, allow the user to be able to configure Element settings related to how the desktop app functions.

#### Why would you like to do it?
- On a scenario that I help install Element for another person (e.g. Friend or Colleague), I can't enable important settings such as `Settings > Preference > Enable Element to Start on Login` or `Auto-play GIF or Video`

#### How would you like to achieve it?
- Just make the settings button available without requiring to log in to access it.

**Comment by t3chguy** [comment]
Settings like `Auto-play GIF or Video` get saved to your account, if you're not logged in then there is nowhere to save them.

**Comment by 8227846265** [comment]
Hmm, possible scenario is that it can be saved first on the desktop app before user log in wherein after user logged in:
- Element Desktop App will check `pre-configured app settings` and `account settings` and match account settings to the pre-configured app setting.

**Comment by t3chguy** [comment]
It'd end up overwriting settings and causing change on other clients where a user may not expect it to. If a user changes an option from off to on then back to off then it'd be unclear whether they want the option to be off or untouched if it was already `on` in their account once they log in

**Comment by 8227846265** [comment]
Alright. We can leave the `Auto-play GIF or Video` settings to the Account Settings.

However, the `Start automatically after system login` can be added as settings you can configure on the app before login?

**Comment by gaelledel** [comment]
Thanks for your suggestion. Typically, the expectation of the very first task in the user journey is to log in. We don't think that this is a use case for a majority of users as of today. We are closing this for now but may re consider this in the future if we were to observe more request of this type.
