### ISSUE TITLE
Please make the scroll bars wider so that it can be used more easily.

### ISSUE THREAD

**Issue by beavailable** [element-hq/element-web#24408]
#### What would you like to do?
Double the width of the scroll bars

#### Why would you like to do it?
Current width of the scroll bars is too thin to use.

#### How would you like to achieve it?
No idea.

**Comment by t3chguy** [comment]
We use default overlay scrollbars, the width is up to your browser, I suggest seeking support from the web on how to change it in your browser of choice.

**Comment by beavailable** [comment]
I use chromium on linux, on other websites, the scrollbar's width is about 16px, but on `app.element.io` it's only about 8px.

**Comment by t3chguy** [comment]
An app can request an overlay scrollbar, those behave slightly differently and some browsers tend to make them slimmer

**Comment by beavailable** [comment]
I had googled `overlay scrollbar` and tried `enable` and `disable` options in `chrome://flags`, but no differences, even if I move my cursor to the scrollbar, it was still 8px.

**Comment by robintown** [comment]
https://github.com/vector-im/element-web/issues/22084 related

**Comment by gaelledel** [comment]
This is something we might consider whilst we rework the design language of the web app with compound adoption.
