### ISSUE TITLE
Removing BBB widget for everyone crashes Element

### ISSUE THREAD

**Issue by axelsimon** [element-hq/element-web#24412]
### Steps to reproduce

The Element video call is hooked up to BigBlueButton using Dimension: clicking the button creates a BBB meeting and adds the widget to the room, letting users join the conference.

1. While trying to investigate a different issue with this setup (BBB widget not prompting for permissions for media devices and not finding camera or microphone) i am creating and adding the widget often.
2. I click "remove for everyone", which worked fine up until very recently
3. Element Web crashes, suggesting to either submit debug logs or clear cache and reload

#### What did you expect?
Remove the widget without any issue.

#### What happened instead?
Element Web crashed

### Operating system

Fedora Linux 37 (Workstation Edition)

### Browser information

Firefox 109.0 (64-bit)

### URL for webapp

https://element.hu-berlin.de

### Application version
Element version: 1.11.20
Olm version: 3.2.12

### Homeserver

Synapse 1.75.0

### Will you send logs?

Yes

**Comment by robintown** [comment]
Reproducible with Jitsi by removing the widget while joined to the call
