### ISSUE TITLE
Private MSK wasn't written to 4S after hitting "Reset all"

### ISSUE THREAD

**Issue by bwindels** [element-hq/element-web#24484]
### Steps to reproduce

Background to why I was looking into 4S account data  is that I started to work on cross-signing on Hydrogen and saw that on my test account (@bruno4:matrix.org) the `m.cross_signing.master` 4S key was only encrypted with an old key from a few resets ago. So I wanted to fix that by enable cross signing somehow in Element.

I opened Element and when asked to verify my device after opening Element, I was asked my security key. I entered the one that worked in Hydrogen to enable key backup, but for some reason Element said "That looks wrong". I also used the upload button, that didn't not work.

I proceeded hitting the "Reset all" button. The reset worked but my private MSK in 4S hadn't changed.

After all of this, I have reset just cross-signing which did write the new private MSK to 4S and fixed the situation. Even doing a full reset, I am not able to repro the problem anymore.

### Outcome

A full reset to also reinitialize cross-signing

Instead, it didn't seem to do anything for cross-signing, it just reset key backup and 4S

### Operating system

Fedora 36

### Browser information

Firefox 105

### URL for webapp

develop.element.io

### Application version

Element version: 087ecc8538e2-react-bb4b07fdc9a6-js-c67325ba07bc Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by richvdh** [comment]
Given this would have been the legacy crypto stack, it's probably no longer relevant.
