### ISSUE TITLE
Flaky Percy tests due to variable dropdown size

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#24688]
Example - look at both the login screen and the Create Poll screen:

* https://percy.io/dfde73bd/matrix-react-sdk/builds/25530534/changed/1423244843?browser=chrome&browser_ids=18%2C33%2C34%2C35&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=original&width=1024&widths=1024%2C1920

The size of the dropdowns on these screens seems to vary, causing Percy to object.

![rec-2023-02-28_09 35 26](https://user-images.githubusercontent.com/76812/221812503-53067445-8f69-468e-baeb-42a13a12774d.gif)

The above shows me clicking back and forth between the original and changed image in Percy. Note that the dropdown height seems to vary.

**Comment by andybalaam** [comment]
Example: https://percy.io/dfde73bd/matrix-react-sdk/builds/25531269/changed/1423277393?browser=edge&browser_ids=18%2C33%2C34%2C35&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1920&widths=1024%2C1920

**Comment by andybalaam** [comment]
Example: https://percy.io/dfde73bd/matrix-react-sdk/builds/25532575/changed/1423330721?browser=edge&browser_ids=18%2C33%2C34%2C35&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1024&widths=1024%2C1920

**Comment by luixxiul** [comment]
Waiting to load items inside dropdown should fix the issue?

**Comment by andybalaam** [comment]
> Waiting to load items inside dropdown should fix the issue?

That definitely sounds possible, even plausible.

**Comment by luixxiul** [comment]
Other recent examples: https://percy.io/dfde73bd/matrix-react-sdk/builds/28207096/changed/

**Comment by andybalaam** [comment]
We are not using Percy any more. Closing this.
