### ISSUE TITLE
batching of `m.room_key` to-device messages is suboptimal

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#24680]
When we send out `m.room_key` messages to share a new encryption session, we attempt to batch those messages into groups of 20 per call to `/sendToDevice`. However the batching logic is distinctly suboptimal and we often end up creating much smaller batches.

I'm also not really sure why 20 was chosen as the target.

This leads to lots of requests to the `/sendToDevice` endpoint and general slowness in sending out room keys, potentially causing unable-to-decrypt errors (https://github.com/vector-im/element-meta/issues/245) and causing the recipient to start sending out `m.room_key_request` messages, exacerbating the problem.

**Comment by richvdh** [comment]
Likely we will fix this as part of https://github.com/vector-im/element-web/issues/21972 rather than spending time fixing it in an implementation that will be thrown away.

**Comment by BillCarsonFr** [comment]
Rust [SDK limit is set to 250 ](https://github.com/matrix-org/matrix-rust-sdk/blob/9f75552c9b2e20f683db6b2f088c8e22a7eb552e/crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs#L147)

Added a task in [regression test list](https://github.com/matrix-org/complement-crypto/blob/main/TEST_HITLIST.md#regression-tests) to later implement.

**Comment by richvdh** [comment]
> Rust SDK limit is set to 250 

... and, more importantly, its batching logic looks sensible

**Comment by kegsay** [comment]
Pending complement-crypto test to check that we batch in as large a chunk as possible i.e 250.

**Comment by kegsay** [comment]
This was done.
