### ISSUE TITLE
Failing Percy tests due to roving tab index race

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#24689]
### Steps to reproduce

Some Percy tests are failing due to what appears to be a different tab position. Examples:

* https://percy.io/dfde73bd/matrix-react-sdk/builds/25503306/changed/1421574478?browser=edge&browser_ids=18%2C33%2C34%2C35&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1024&widths=1024%2C1920 
* https://percy.io/dfde73bd/matrix-react-sdk/builds/25492871/changed/1421097784?browser=edge&browser_ids=18%2C33%2C34%2C35&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1920&widths=1024%2C1920
* https://percy.io/dfde73bd/matrix-react-sdk/builds/25492871/changed/1421097783?browser=firefox&browser_ids=18%2C33%2C34%2C35&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1920&widths=1024%2C1920

**Comment by t3chguy** [comment]
This is more likely unrelated to mouseover and not a flake; most likely to be a legitimate bug/race in the roving tab index.

**Comment by andybalaam** [comment]
Example: https://percy.io/dfde73bd/matrix-react-sdk/builds/25531269/changed/1423277393?browser=edge&browser_ids=18%2C33%2C34%2C35&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1920&widths=1024%2C1920

**Comment by t3chguy** [comment]
Percy tests are gone
