### ISSUE TITLE
gfm.css is no longer supported

### ISSUE THREAD

**Issue by t3chguy** [element-hq/element-web#24694]
warning gfm.css@1.1.2: Package no longer supported. Please use github-markdown-css instead.

**Comment by t3chguy** [comment]
This brings visual changes 

Before
![image](https://user-images.githubusercontent.com/2403652/234326749-06263fbb-0027-44a0-a442-2eb2f32b43ae.png)

After
![image](https://user-images.githubusercontent.com/2403652/234326809-87c841c5-c9d8-449a-86ef-4ec3cdb4d01a.png)

Likely to be delegated to Compound

**Comment by Johennes** [comment]
@nadonomy how do you feel about us going ahead with this for now? It'll be a while until we get to touching the timeline as part of the Compound adoption work and would be nice to eliminate the unsupported dependency in the meantime.

**Comment by nadonomy** [comment]
Wfm. We can catch any nasty unintended consequences on develop.
