### ISSUE TITLE
Thread menu doesn't load on desktop app

### ISSUE THREAD

**Issue by NotMyFault** [element-hq/element-web#24715]
### Steps to reproduce

Occasionally, threads aren't loading for me.
1. Open the thread panel of a chat, in this case, https://matrix.to/#/#jenkins/docs:matrix.org
2. See that nothing happens:
![Screenshot 2023-03-01 at 20 08 23](https://user-images.githubusercontent.com/13383509/222240020-cbe089f1-dea3-4217-b6d8-a8945b77c998.png)

#### What did you expect?
The thread panel should load, like it does on mobile and the webapp

#### What happened instead?
The thread panel is not loading.

### Operating system

macOS Ventura 13.2.1 (22D68)

### Application version

Element version: 1.11.24 Olm version: 3.2.12

### How did you install the app?

https://element.io/download

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Unfortunately the logs for this were deleted. If someone experiences this again please open a new issue and submit logs.
