### ISSUE TITLE
Edit `docs/cypress.md` to explain `percySnapshotElement`

### ISSUE THREAD

**Issue by luixxiul** [element-hq/element-web#24749]
#### What would you like to do?

[This part](https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/cypress.md#percy-visual-testing) of docs/cypress.md should explain what `percySnapshotElement` is and how it should be used.

#### Why would you like to do it?

Because it is a custom command which is defined on `/cypress/support/percy.ts`, used widely, and takes care of the issue related to `mx_Spinner`.

#### How would you like to achieve it?

Edit https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/cypress.md#percy-visual-testing

**Comment by richvdh** [comment]
+1. I googled for documentation of `percySnapshotElement`... and ended up here :(.

For the record, it is an extension of [`cy.percySnapshot`](https://docs.percy.io/docs/cypress#configuration), which sets an option called `domTransformation` ... which I also can't find any documentation on?

**Comment by t3chguy** [comment]
Percy tests are gone
