### ISSUE TITLE
element stopped updating content, on refresh reported missing session data

### ISSUE THREAD

**Issue by xloem** [element-hq/element-web#24768]
### Steps to reproduce

This happened after returning to the system after leaving it open for a few days. The messages I had last sent in a room were still the most recent messages, and the room tended to have activity, so I was surprised. When I refreshed to see if anything changed, it said my session data had been lost.

### Outcome

This happened after returning to the system after leaving it open for a few days. The messages I had last sent in a room were still the most recent messages, and the room tended to have activity, so I was surprised. When I refreshed to see if anything changed, it said my session data had been lost.

### Operating system

Linux RHEL 7

### Browser information

Google Chrome Version 110.0.5481.100 (Official Build) (64-bit)

### URL for webapp

app.element.io

### Application version

uncertain

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by xloem** [comment]
When I try to send the logs, I receive the error `Failed to send logs: No connected database` .

**Comment by t3chguy** [comment]
Sounds like your browser's IndexedDB stopped working

**Comment by richvdh** [comment]
duplicate of #27995
