### ISSUE TITLE
Show votes cast for undisclosed polls

### ISSUE THREAD

**Issue by jeffrson** [element-hq/element-web#24875]
#### What would you like to do?

View how many votes have been cast for undisclosed polls before the poll is finished.

#### Why would you like to do it?

This is done already in iOS app and it seems very useful, to estimate whether the poll will be successful at all and could possibly be ended prematurely.

#### How would you like to achieve it?

Similarly to iOS Swift implementation. Though I don't know which data have to be requested. However, it should be possible since we can see this feature working for the same poll.

### Have you considered any alternatives?

no

### Additional context

The same feature would be useful in Element Android - should this be tracked by a seperate issue?

**Comment by robintown** [comment]
Yes, if you would like this feature to be added on Android as well, you should open an issue at https://github.com/vector-im/element-android/

**Comment by gaelledel** [comment]
Good thank you as this is a feature request I will now close this issue.
