### ISSUE TITLE
Fix Percy tests for `ThreadView` on `threads.spec.ts`

### ISSUE THREAD

**Issue by luixxiul** [element-hq/element-web#24883]
### Steps to reproduce

The PR https://github.com/matrix-org/matrix-react-sdk/pull/9016 has added Percy tests to detect visual regressions of `EventTile`s inside `ThreadView`.

- `Initial ThreadView on group layout` and `Initial ThreadView on bubble layout` https://github.com/matrix-org/matrix-react-sdk/commit/f60f7a19af8257d94132bdb413c0416c7b27e333#diff-44347e35ab8f425bcd830646976351b243602f12674e9e306060b0a17697c65bR112-R116
-`ThreadView with reaction and a hidden event on group layout` https://github.com/matrix-org/matrix-react-sdk/commit/f60f7a19af8257d94132bdb413c0416c7b27e333#diff-44347e35ab8f425bcd830646976351b243602f12674e9e306060b0a17697c65bR194-R196
- `ThreadView with reaction and a hidden event on bubble layout` https://github.com/matrix-org/matrix-react-sdk/commit/f60f7a19af8257d94132bdb413c0416c7b27e333#diff-44347e35ab8f425bcd830646976351b243602f12674e9e306060b0a17697c65bR216-R218
- `ThreadView with redacted messages on group layout` and `ThreadView with redacted messages on bubble layout`https://github.com/matrix-org/matrix-react-sdk/commit/f60f7a19af8257d94132bdb413c0416c7b27e333#diff-44347e35ab8f425bcd830646976351b243602f12674e9e306060b0a17697c65bR246-R252
- `Reply to the location on ThreadView` https://github.com/matrix-org/matrix-react-sdk/commit/f60f7a19af8257d94132bdb413c0416c7b27e333#diff-44347e35ab8f425bcd830646976351b243602f12674e9e306060b0a17697c65bR463

It turns out they do not really work how they are supposed to.

- [`ThreadView with reaction and a hidden event on bubble layout`](https://percy.io/dfde73bd/matrix-react-sdk/builds/26063705/unchanged/1452789025?browser=firefox&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=800&widths=1024%2C1920)
- [`Reply to the location on ThreadView`](https://percy.io/dfde73bd/matrix-react-sdk/builds/26063705/unchanged/1452789022?browser=firefox&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=800&widths=1024%2C1920)
- [`ThreadView with redacted messages on group layout`](https://percy.io/dfde73bd/matrix-react-sdk/builds/26063705/unchanged/1452789019?browser=firefox&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=800&widths=1024%2C1920)
- [`ThreadView with redacted messages on bubble layout
`](https://percy.io/dfde73bd/matrix-react-sdk/builds/26063705/unchanged/1452789018?browser=firefox&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=800&widths=1024%2C1920)
- [`ThreadView with reaction and a hidden event on group layout`](https://percy.io/dfde73bd/matrix-react-sdk/builds/26063705/unchanged/1452789017?browser=firefox&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=800&widths=1024%2C1920)
- [`Initial ThreadView on bubble layout`](https://percy.io/dfde73bd/matrix-react-sdk/builds/26063705/unchanged/1452789015?browser=firefox&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=800&widths=1024%2C1920)
- [`Initial ThreadView on group layout`](https://percy.io/dfde73bd/matrix-react-sdk/builds/26063705/unchanged/1452789013?browser=firefox&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=800&widths=1024%2C1920)

![3785632928c7fa75893dd1c60c73ccad6d6458f4f2010b08fe832aa0e0dbfe90](https://user-images.githubusercontent.com/3362943/226743826-af7df474-268c-4acb-80db-62567a840418.png)

All of them seem to have taken snapshots of the right panel without their content. They are supposed to take snapshots `ThreadView` including  `EventTile`s and a poll.

#### What did you expect?

They should take snapshots of contents inside `ThreadView`.

#### What happened instead?

They take snapshots of the `ThreadView` without its content such as `EventTile`s, redacted messages placeholder, etc. on modern layout and bubble layout (note that there is not IRC layout on `ThreadView`).

### Application version

develop branch

### Will you send logs?

No

**Comment by t3chguy** [comment]
Percy tests are gone
