### ISSUE TITLE
Update TypeScript target to `es2022` for updated types like `Error.prototype.cause`

### ISSUE THREAD

**Issue by MadLittleMods** [element-hq/element-web#24913]
Currently, we define the TypeScript target as [`es2016`](https://github.com/matrix-org/matrix-react-sdk/blob/332d1268a46861dc82667ce1e8aa3aaee4481dcc/tsconfig.json#L9).

Is there a specific reason, we're staying behind at that version?

### Why would you like to update?

I would like to update to `es2022` in order get `cause` property on `Error`. Introduced in TypeScript 4.6, see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-6.html#--target-es2022

This is spawning from https://github.com/matrix-org/matrix-react-sdk/pull/10432#discussion_r1145538597 where I might have a usage for the `cause` property and `Error` constructor usage.

MDN reference for `cause` property on `Error` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause

```js
try {
  connectToDatabase();
} catch (err) {
  throw new Error('Connecting to database failed.', { cause: err });
}
```

---

Related TypeScript issues:

 - https://github.com/microsoft/TypeScript/issues/45167
 - https://github.com/microsoft/TypeScript/issues/48098

### Possible alternative

For my specific case, we can probably  just override what we want in [`src/@types/global.d.ts#L189-L196`](https://github.com/matrix-org/matrix-react-sdk/blob/332d1268a46861dc82667ce1e8aa3aaee4481dcc/src/%40types/global.d.ts#L189-L196)

Based off of [TypeScript source, `src/lib/es2022.error.d.ts`](https://github.com/microsoft/TypeScript/blob/3a3146e25f7dfa71acbe5b8b5989e6343bbfd77d/src/lib/es2022.error.d.ts)

```ts
interface ErrorOptions {
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause
    cause?: unknown;
}

interface Error {
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/fileName
    fileName?: string;
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/lineNumber
    lineNumber?: number;
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/columnNumber
    columnNumber?: number;
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause
    cause?: unknown;
}

interface ErrorConstructor {
    new (message?: string, options?: ErrorOptions): Error;
    (message?: string, options?: ErrorOptions): Error;
}

var Error: ErrorConstructor;
```

**Comment by richvdh** [comment]
Looking at the compat table at https://compat-table.github.io/compat-table/es2016plus, I can't see any reason not to do this: all the supported platforms for Element-Web, and the recent nodejs versions supported by matrix-js-sdk, are fine all the way up to ES2024, with a yellow flag for "Regexp Matches Indices", which I don't think is relevant here.

**Comment by t3chguy** [comment]
Bumping to es2022 for React-sdk & element-web causes a lot of errors around react contexts & class property initialisation order. Holding off on that until we upgrade to React 18

**Comment by t3chguy** [comment]
Done
