### ISSUE TITLE
Display why an event caused a (highlight) notification

### ISSUE THREAD

**Issue by clokep** [element-hq/element-web#24927]
Currently users may not understand *why* a particular event caused a highlight notification and is colored red. This can be confusing if e.g. the user configured a keyword that they forgot about (see also vector-im/element-web#8821).

Although this problem exists today, [MSC3952](https://github.com/matrix-org/matrix-spec-proposals/pull/3952) may make it slightly worse as a user can be "CCed" onto a message without actually being mentioned (having a pill) in the text content of the message. It maybe useful to surface:

* Why this caused a notification: "The user explicitly mentioned you."
* A quick action to take if this was abusive: "Block this user? Report this user?"
* Other users which are CCed.

This would benefit from some design help. 😄 

The MSC includes some information about [abuse potential](https://github.com/matrix-org/matrix-spec-proposals/blob/clokep/intentional-mentions/proposals/3952-intentional-mentions.md#abuse-potential) and [ways to combat it](https://github.com/matrix-org/matrix-spec-proposals/blob/clokep/intentional-mentions/proposals/3952-intentional-mentions.md#combating-abuse).

**Comment by t3chguy** [comment]
Keywords or the message event can include the MXID in the intentional mentions part but there's no pill matching the mention in the text, server can't validate it due to encryption

**Comment by clokep** [comment]
> the message event can include the MXID in the intentional mentions part but there's no pill matching the mention in the text, server can't validate it due to encryption

Yeah, this 100%, except there isn't anything to validate -- this is a completely valid thing to do according to the MSC. You can do something similar in today's mentions system, it is just harder.

**Comment by daniellekirkwood** [comment]
How would a user send that message?

**Comment by t3chguy** [comment]
Devtools, API, or a non Element client

**Comment by kerryarchibald** [comment]
Made a very quick experiment adding a tooltip:
<img width="634" alt="Screenshot 2023-04-05 at 17 24 47" src="https://user-images.githubusercontent.com/3055605/229989030-45dea5a1-850a-42ff-a2b0-96b5b7c66544.png">
<img width="630" alt="Screenshot 2023-04-05 at 17 24 29" src="https://user-images.githubusercontent.com/3055605/229989036-fa0acf96-33db-4184-9872-f82fb0b981ee.png">

This takes the matched push rule and attaches it to the event at the same points as `event.pushActions` are set. Notifications from the server are reprocessed to find the rule match on the client (for now).

I'm less sure about the pills approach from the design - to me pills imply an entity/clickability, and for keywords there is none. Push processing also only matches one rule, so a message containing multiple keywords, or an @mention plus a keyword would only pillify one thing.
<img width="443" alt="Screenshot 2023-04-05 at 17 41 19" src="https://user-images.githubusercontent.com/3055605/229991204-846cedad-7206-45d7-b7c8-2a12c77776b2.png">

**Comment by daniellekirkwood** [comment]
> I'm less sure about the pills approach from the design - to me pills imply an entity/clickability, and for keywords there is none. Push processing also only matches one rule, so a message containing multiple keywords, or an @mention plus a keyword would only pillify one thing.

That's really good to know. @janogarcia FYI as I think you're likely to start thinking about how we handle keywords in the timeline in the future

As to the tool tip - I think it looks great. Paging @rufuskahler who's been [working with us on this](https://docs.google.com/document/d/1AvHmbGH3XHN6lU-B9xWyMrU0Rv4Ej6DYIsA2ef_9MIs/edit?usp=sharing)

**Comment by clokep** [comment]
> Made a very quick experiment adding a tooltip:

Just wanted to say that this looks awesome and was what I was naively thinking! 👍

**Comment by kerryarchibald** [comment]
Another quick sketch is to put it in the message action bar:
<img width="443" alt="Screenshot 2023-04-06 at 17 16 08" src="https://user-images.githubusercontent.com/3055605/230278556-4d5bd458-a3cf-44f8-a206-efa9295f3bb3.png">

Which could then open a modal with anti-abuse or notification management options
<img width="648" alt="Screenshot 2023-04-06 at 17 18 24" src="https://user-images.githubusercontent.com/3055605/230278548-b60f6520-b25f-41cf-a4bb-9a0dbd9554ef.png">

**Comment by daniellekirkwood** [comment]
I'm really digging that idea!

**Comment by Johennes** [comment]
The message action bar approach was rejected in design review: https://github.com/matrix-org/matrix-react-sdk/pull/10599#issuecomment-1531084253

> I have my doubts about using the action bar for the reasons Danielle mentioned. Furthermore, I'd like to discuss other ways of solving the problem closer to the root cause, e.g with Compound, we're moving away from red highlighted text for notifications. [...] This sounds like more consensus is needed between Product & Design.

We're in a slightly weird spot now because https://github.com/matrix-org/matrix-js-sdk/pull/3284 was already merged. We need to figure out where to go from here.

**Comment by Johennes** [comment]
I suggest that we do _not_ revert the JS SDK change. It's not excessively big, has test coverage and will be needed once we pick this issue back up.

@kerryarchibald / @andybalaam happy to be vetoed if you disagree.

**Comment by andybalaam** [comment]
Yep, annotating the event with what caused a notification seems helpful to other users of js-sdk, so no need to revert it.

**Comment by gaelledel** [comment]
We are currently re exploring how mentions get displayed in the leftpannel and this may have some repercussion to clarify things in the timeline too. Regarding keywords, it is expected that users know what keyword that have entered in their settings and make the link with the result in the notifications and pills. Unfortunately, it is not possible to make all information visible at first glance for a variety of reasons and users should rely on their own configurations especially for things like setting up specific keywords.
