### ISSUE TITLE
rich text editor remember draft?

### ISSUE THREAD

**Issue by Thatoo** [element-hq/element-web#25135]
#### What would you like to do?
Before RTE, Element was remembering draft of unsent message when we were changing to an other room and coming back. I'd like RTE to be able to do the same.
#### Why would you like to do it?
Using RTE, if I'm composing a message and I need to look for some information in an other room, if I don't think I should copy/paste my draft before leaving the room, when I come back, I have to rewrite all the message as the draft has vanished 
#### How would you like to achieve it?
RTE should remember drafts of last unsent message in each room.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-rich-text-editor is the repo regarding the rich text editor - please open your issue there

**Comment by aringenbach** [comment]
Re-opening this here, as work within the library for this is available. But some of its integration is lacking in the Element-Web side.

**Comment by giomfo** [comment]
Note: The partially typed message is correctly handled on mobile application (at least on the most recent releases: Element-iOS v1.11.6 and Element-Android v1.6.10)

**Comment by langleyd** [comment]
This was added in https://github.com/matrix-org/matrix-react-sdk/pull/12674

**Comment by Thatoo** [comment]
It still isn't working in 
Version de Element : 1.11.75
Version crypto : Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

**Comment by langleyd** [comment]
👍 Thats expected @Thatoo , the fix should be in the RC cut next tuesday and in the release the week that follows.
