### ISSUE TITLE
Create a design policy on capitalization of strings and apply it globally

### ISSUE THREAD

**Issue by luixxiul** [element-hq/element-web#25148]
### Steps to reproduce

1. Open General user settings tab
2. Check `Account` form
![1](https://user-images.githubusercontent.com/3362943/232871297-f2435d0e-4983-4793-b748-a3356f023356.png)

#### What did you expect?

Capitalization of the strings should be consistent.

#### What happened instead?

It seems they are not consistent.

Account:
- Current password - input area
- New **Password** - input area
- Confirm password - input area

Email:
- Email addresses - header
- Email **Address** - input area

Phone:
- Phone numbers - header
- Phone **Number** - input area

If we follow a rule here, "Current password" should be "Current Password", and "Confirm password" should be "Confirm Password".

Please note that `_t("Confirm password")` (mind the capitalization) is found on `/src/components/views/settings/ChangePassword.tsx` and `src/components/views/auth/PassphraseConfirmField.tsx`

### Will you send logs?

No

**Comment by luixxiul** [comment]
I am wondering if there is a policy on capitalization (about difference between strings on header, input area, buttons, etc.)

**Comment by weeman1337** [comment]
Thanks for the issue report @luixxiul . I think it should be „Current password“, „New password“, „Confirm password“ etc..

**Comment by luixxiul** [comment]
Are you sure, as the other placeholder strings on those input area are both capitalized (Email Address, Phone Number)?

**Comment by weeman1337** [comment]
My logic behind this is:
- Capitalise the first character of first the word
- Others then lower cased, even nouns because they are not upper case in English

That is like what others do™

An example :laughing: 

![image](https://user-images.githubusercontent.com/6216686/233285029-be571805-336a-4a91-88d6-c58e5d9fe923.png)

**Comment by weeman1337** [comment]
I've added `X-Needs-Design`. Let the design team take a decision on this.

**Comment by luixxiul** [comment]
Ah I understood. It then will be a global task, not only on this case.

**Comment by gaelledel** [comment]
Dealt with as part of settings redesign and informed design team to 1 respect format throughout the app. @americanrefugee @amshakal
