### ISSUE TITLE
Unable to decrypt message. Unfortunately, there are no other verified devices to request decryption keys from.

### ISSUE THREAD

**Issue by Tbaut** [element-hq/element-web#25185]
### Steps to reproduce

1. I'm in a room, and the message from some people can't be decrypted
2. Either in a room with several other ppl, or this just happened when I am in a new room with someone. Their first messages can't be decrypted. I sent a rageshake.

it says
> Unable to decrypt message

and at the top 
> Some messages could not be decrypted
Unfortunately, there are no other verified devices to request decryption keys from. Signing in and verifying other devices may help avoid this situation in the future.

#### What did you expect?
The message to be visible
#### What happened instead?
the message isn't visible.

### Operating system

Linux

### Browser information

Firefox 112

### URL for webapp

https://riot.im/app/?updated=1.11.17#/room

### Application version

Element version: 1.11.29 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by sjamaan** [comment]
I just had the same thing with the Element desktop version, where it was unable to decrypt *one* message in a one on one chat with someone I'd been in a conversation with for many months without issue. I updated to the latest in NixOS (Element version: 1.11.31, Olm version: 3.2.14) and restarted Element. The funny thing is, after the restart it told me *unable to decrypt* about the message that preceded the one it was unable to decrypt before, while it now *was* able to decrypt the message it originally was *unable* to decrypt.

**Comment by sjamaan** [comment]
In other words, before the update & restart:

```
...a whole lot of messages...
Message n
Message n+1
*unable to decrypt*
Message n+3
...A few more messages...
```

After:

```
...a whole lot of messages...
Message n
*unable to decrypt*
Message n+2
Message n+3
...A few more messages...
```

**Comment by Taubin** [comment]
I've been having this a lot with chats with one person on my  self hosted instance. If I open the chat on my phone, it decrypts no problem, but I get "cannot be decrypted" in the middle of conversations multiple times using the desktop app. It happens across two different computers with the desktop app. I have reset all the room keys, and redone my backups. Everything has been updated and rebooted multiple times.

**Comment by asakura42** [comment]
This bar is so annoying and I can't close it unfortunately. What if I don't want to see this bar at all? Make a small cross at the top right corner please.

**Comment by richvdh** [comment]
https://github.com/vector-im/element-meta/issues/245
