### ISSUE TITLE
Unable to query secret storage status

### ISSUE THREAD

**Issue by podoi17** [element-hq/element-web#25192]
### Steps to reproduce

Nothing really works anymore 
1. I can not create backup keys
2. Resend Key Request does not work
3. Reset of Secure back up does not work with the message Unable to query secret storage status

--> Result is, that everytime I logg out and in again I am loosing all my messages 

### Outcome

I want to see my old messages
I want to be able to create backups 

### Operating system

macOS Ventura 13.3.1

### Application version

Element version: 1.11.29 Olm version: 3.2.12

### How did you install the app?

https://element.io/download

### Will you send logs?

Yes

**Comment by podoi17** [comment]
Any suggestions what could be done? I have no clue abet element/matrix-server. I am just using it and it suddenly stopped working for me

**Comment by richvdh** [comment]
This doesn't look like a bug in element-web.
