### ISSUE TITLE
Unable to decrypt

### ISSUE THREAD

**Issue by Arkaniad** [element-hq/element-web#25221]
### Steps to reproduce

1. Left Element Desktop app open last night, sent a message to a colleague ~5PM CDT. Replies sent to me this morning at 7:44AM CDT and onward are UTD on my Desktop app, but show up fine on my phone app.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/118427/234882378-cd313019-5709-4bc1-9261-9a717ee931f0.png">

2. App presented update dialog, I clicked on it and restarted the app and messages are still UTD.
3. Message box at the top of the client suggests to request decryption keys from my other devices, but this does not appear to happen with my working phone client open

<img width="1793" alt="image" src="https://user-images.githubusercontent.com/118427/234882940-b67cf7d9-971d-48ee-91f4-78c0133d53bc.png">

#### What did you expect?

Messages should have been readable on my desktop in the morning.

#### What happened instead?

UTDs with no clear path to recovery (besides maybe dumping cache?)

### Operating system

MacOS Ventura 13.3.1

### Application version

Element 1.11.30 - Olm version 3.2.13

### How did you install the app?

from Homebrew `element` package

### Homeserver

element.ems.host

### Will you send logs?

Yes

**Comment by jeremiah-k** [comment]
Myself and others are experiencing this too.  I'm only having problems with Element Desktop, messages are coming in fine on my phone. Requesting keys from other devices doesn't help.

![image](https://user-images.githubusercontent.com/17190268/235209200-d660c1f8-d917-4c0d-84aa-03caaaf046f1.png)

**Comment by Ezwen** [comment]
Since a few days, many users of my Matrix homeserver encounter this problem. Upgrading synapse did not help. Many rooms become unusable, and I don't know what to do. Help welcome.

**Comment by Ezwen** [comment]
Some of my users solved the problem by upgrading their faulty matrix rooms to version room version 10.

**Comment by hedimdev** [comment]
I've had this problem for a while until yesterday I opened the device list and signed out of all devices except for one active Android client. I use the web app in an incognito browser window so over time I had accumulated many inactive devices.
Maybe this is a hint as to the origin of the problem others are having.

**Comment by Arkaniad** [comment]
FTR, woke up again today and logged in and I've got even more rooms with UTDs. It's getting a bit unusable. Rage-shook again if that helps at all

**Comment by bhauer** [comment]
I have seen this issue steadily become more prominent and problematic on my home server and those of a few friends. More channels and users are being affected. Once a channel is affected, users will see a banner dialog that says "Open another device to load encrypted message" which cannot be dismissed and is ineffectual in resolving the issue.

Anecdotal evidence seems to suggest the issue arises when an iOS client sends a photo to the channel. Once the issue has appeared, not just photos are affected, however.

**Comment by Arkaniad** [comment]
This actually tracks with what I've seen too - I'll frequently sent images as attachements in Element from the iOS share dialog, only to find them failed to send when I go check back & other messages stuck as well behind it

**Comment by t3chguy** [comment]
The iOS issue is/was https://github.com/vector-im/element-ios/issues/7376

**Comment by richvdh** [comment]
Duplicate https://github.com/vector-im/element-meta/issues/245
