### ISSUE TITLE
"Unable to decrypt message" is shown for majority of the messages in the room (but not for all of them)

### ISSUE THREAD

**Issue by daniel-abramov** [element-hq/element-web#25272]
### Steps to reproduce

1. I've opened Element Web on one of the verified devices I have not used for 2 or 3 days.
2. Majority of the messages from today are shown as "Unable to decrypt message" except for a message from a single user in a middle of a conversation that is correctly decrypted.
3. The messages from days ago are properly decrypted and visible albeit with a "The authenticity of this encrypted message can't be guaranteed on this device" warning.
4. The messages remain unencrypted no matter what I try (reload the page, click the "Resend keys" button until it disappears and turns into the "Open another device to load encrypted messages" button). The conversation remains unreadable despite me seeing the read receipts of others who read my new messages where I inform them that I can't see their messages.

#### What did you expect?

That I can see the conversation history. After all, it's a verified device and there is no reason why the messages in the room should be unavailable.

#### What happened instead?

The notorious "Unable to decrypt message".

### Operating system

macOS

### Browser information

Chromium 112.0.5615.165

### URL for webapp

https://app.element.io/

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by lmangani** [comment]
Element is next to unusable due to this very common bug I hear more and more users experience daily.
Are there any updates or feedback or suggestions for those experiencing this?

**Comment by leofang** [comment]
In my case I had to fix it using the private key in Settings => Security & Privacy => Cross-signing to sign every session. I don't know what to do if the key is lost, but luckily I found it after a while.

**Comment by jonas2515** [comment]
Same bug here (I'm on gnome.element.io), the messages are shown just fine on a different device using Element Web, but apparently the encryption keys are not synced between devices.

**Comment by richvdh** [comment]
https://github.com/vector-im/element-meta/issues/245

**Comment by keeganquigley** [comment]
I had this happen on MacOS while the Element session on my iOS device was still active. I fixed it by manually exporting the keys from my iOS device (you will have to set a password), moved the file to my computer, then imported it there with the password.
