### ISSUE TITLE
Spacing on "Help & About" tab seems not right

### ISSUE THREAD

**Issue by luixxiul** [element-hq/element-web#25442]
### Steps to reproduce

1. Open "Help & About" tab

#### What did you expect?

Sections should be split with spacing, so that elements in them can be perceived as grouped.

#### What happened instead?

- The gaps between the texts and buttons seem wide, which is almost enough to give perception that buttons are not in the same group as the text above. This is why `Keyboard shortcuts` button, which is not clear by itself that it belongs to FAQ section, seems a little bit out of order ("Does it belong to FAQ, or is it on the same level as the headers?"). 
- The gaps between the headers and the rectangle about version information, the list, and Homeserver address seem wide, and it is perceived as if texts to describe the section lacked there.

![Screenshot from 2023-05-25 15-46-41](https://github.com/vector-im/element-web/assets/3362943/a74d30c9-bf12-49bc-8637-9d6dfc2b574e)

It is recommended to check on the actual UI since the screenshot above does not express the actual spacing on the monitor.

For comparison, this is a cropped screenshot of the same tab on 1.11.31. Here it is possible to see which items are grouped to which section clearly, though there is not consistency of spacing code-wise.

![Screenshot from 2023-05-25 15-46-10](https://github.com/vector-im/element-web/assets/3362943/ce79924e-98f7-450f-a177-f5721b5abb7e)

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
Spacing is as defined [in design ](https://www.figma.com/file/jI0ZdCeKKa51BDORmXdnRU/Settings%3A-UI-Refresh?type=design&node-id=500-14448&t=gV4Oa6UF7pH5wye2-0)
Further design tweaks should be addressed by Compound

**Comment by luixxiul** [comment]
> Spacing is as defined [in design ](https://www.figma.com/file/jI0ZdCeKKa51BDORmXdnRU/Settings%3A-UI-Refresh?type=design&node-id=500-14448&t=gV4Oa6UF7pH5wye2-0)

(The design is not public; you need to log in to Figma.)

**Comment by weeman1337** [comment]
I would say we should just use the same spacing as in the new device manager

![image](https://github.com/vector-im/element-web/assets/6216686/74cd43f4-328f-4108-977f-8c8c893e4f6c)

„Show QR code“ in the screenshot above.

**Comment by manancodes** [comment]
Every group has 3 components.
A heading, a description and Content, and description is not present in every group.
 
 Description has a margin top of 8px. (Distance from the heading)
 Content has a margin top of 24px. (Distance from heading or description if present)
 This is consistent in all the pages with similar components.
 
<img width="762" alt="Screenshot 2023-09-29 at 1 26 20 AM" src="https://github.com/vector-im/element-web/assets/54790263/783f5f56-eede-4a51-aad0-559a0e6d66e9">




Content having a margin of 24px is too much. Using 14px makes thinks much better. In the image below, 14px is used.

<img width="632" alt="Screenshot 2023-09-29 at 1 32 07 AM" src="https://github.com/vector-im/element-web/assets/54790263/8121ab88-5315-48b7-81b1-7b057b952c71">

**Comment by manancodes** [comment]
@weeman1337 @luixxiul @kerryarchibald Any update on this?
