### ISSUE TITLE
Stuck notifications due to edits in threads

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#25482]
### Steps to reproduce

1. Have someone else start a thread
2. Have them edit their last message in that thread
3. Stuck notification when you try to read it (without reading the original message)

#### What did you expect?

No stuck notifications.

#### What happened instead?

Stuck notifications.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023053001 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by weeman1337** [comment]
Can reproduce very easily following the steps from the description.

**Comment by t3chguy** [comment]
I can no longer reproduce this, presuming fixed by prior stuck notifications work
