### ISSUE TITLE
Ping in a thread followed by a non-ping makes the room go red->unread

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#25523]
### Steps to reproduce

1. Have an (encrypted) room set to Mentions Only
2. Start a thread, sending a couple messages yourself
3. Without looking at the room, have someone else *reply* to one of your messages in the thread, pinging you as a result.
4. Again, without looking at the room, have that same person send a followup, non-ping, message

#### What did you expect?

The room to stay red.

#### What happened instead?

It went from red at step 3 to unread (dot) at step 4.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023060501 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by xoder499** [comment]
Have an (encrypted) room set to Mentions Only
Start a thread, sending a couple messages yourself
Without looking at the room, have someone else reply to one of your messages in the thread, pinging you as a result.
Again, without looking at the room, have that same person send a followup, non-ping, message

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/68b1fc4f-76a6-4c1b-a4a4-84f3529184d1)
![image](https://github.com/vector-im/element-web/assets/2403652/3574cb28-4bd7-4956-b145-b1613158751e)
![image](https://github.com/vector-im/element-web/assets/2403652/37f10506-2332-466a-a8cc-ebc0b953d117)
<img width="461" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/b9060bc5-efa2-42cd-ba27-f336246b623f">

I can still reproduce this

**Comment by dbkr** [comment]
I can't repro this now: the room stays red in the TAC as expected.

**Comment by dbkr** [comment]
wait, yes I can
