### ISSUE TITLE
Ability to mark room as read from topbar context menu

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#25534]
#### What would you like to do?

I want to mark a room as unread from its titlebar at the top of the window.

#### Why would you like to do it?

I have a room with stuck notifs. I want to mark the room as unread. I cannot find it in the room list. I just want to mark it as unread, and the context menu in the top of the window gives me loads of options... but not mark as unread. Other context menus give me mark as unread as an option.

**Comment by t3chguy** [comment]
As far as I am aware that top context menu is going away with the work to simplify top and right panels

**Comment by ara4n** [comment]
if that's happening, then the roomlist needs to be fixed to visibly display the currently selected room, otherwise there is no way to get at the context menu on the current room (short of looking it up via cmd-k :-/)

**Comment by nadonomy** [comment]
@americanrefugee reading this through - in the new model we simplify everything to a single panel on the right. Do you see a case for us including this in that panel?

**Comment by americanrefugee** [comment]
Assuming I understand this correctly...
- There will be no indicators in the new room header or right panel (besides online status of people)
- Unread message indicators will show only in the new room list and the new spaces directory (Search)
- Unread thread indicators will only show along with the new bell/alert icon in the lower left

So, once everything we've designed is implemented there should no longer be stuck notifications / indicators anywhere in an actual room.

**Comment by daniellekirkwood** [comment]
@americanrefugee this is referencing "Mark as Unread" not "Mark as Read"... 

Would you provide us with updated thoughts on whether this is something we will choose to handle from the right hand panel/room header, and your suggested alternatives?

**Comment by daniellekirkwood** [comment]
So there's a "mark all threads as read" button in the threads panel now, and if you're in the room looking at the timeline then your read receipt should move to mark the room as read for you (and if you're using mark as read to fix a bug then we should be fixing the bug not changing the UI to make users fix the bug...)

We do need to address the room list and how someone would mark the room they're in as **unread** (i misspoke earlier) and I think we should include that in the AC of the room list work @gaelledel is looking at...

**Comment by daniellekirkwood** [comment]
this has now been captured in the req.s for room list updates. Closing as will not do
