### ISSUE TITLE
Increase understandability of `Show all rooms` context menu option on room list header

### ISSUE THREAD

**Issue by luixxiul** [element-hq/element-web#25552]
#### What would you like to do?

Make the option `Show all rooms` context menu item on room list header on LeftPanel intuitively understandable for *ordinary users*.

![0](https://github.com/vector-im/element-web/assets/3362943/8597b9ef-48a7-48e7-b6aa-7e77485fb94c)

#### Why would you like to do it?

Because it is not clear at first glance what this option does and what is going to be hidden if the option is disabled, and only careful and power users, and developers of course, can understand it. 

#### How would you like to achieve it?

I am not sure. Displaying a tooltip to explain what the option does might work.

### Additional context

I'm one of the heavy users but I could not see at first what the option worked for.

**Comment by gaelledel** [comment]
Thanks for your feedback. This will be dealt with the new Left Panel design.
