### ISSUE TITLE
Many 404 failing key backup requests

### ISSUE THREAD

**Issue by weeman1337** [element-hq/element-web#25566]
### Steps to reproduce

1. Start Element
2. Look at the network tab

#### What did you expect?

Not so many 404 requests :shrug: 

#### What happened instead?

Many requests are send to `/_matrix/client/v3/room_keys/keys/!…`  .  They all return a 404.

### Operating system

Ubuntu 22.04.2 LTS

### Application version

Element Nightly version: 2023061101 Olm version: 3.2.14

### How did you install the app?

https://packages.element.io/debian/

### Homeserver

https://element.ems.host/

### Will you send logs?

Yes

**Comment by richvdh** [comment]
@weeman1337 presumably these are GET requests, rather than PUT or DELETE?

(unfortunately I can't tell from the rageshake, because https://github.com/vector-im/element-web/issues/25570)

**Comment by richvdh** [comment]
As long the path parameters are different between the requests (ie, different room ids or session ids), I don't think this is a particular problem.

**Comment by weeman1337** [comment]
> @weeman1337 presumably these are GET requests, rather than PUT or DELETE?

Yes

It happened when starting Element Desktop nightly. Maybe something went wrong and all (missing) keys were requested? :man_shrugging: There were thousands of them.

I will keep an eye on it.

**Comment by richvdh** [comment]
I think this is expected behaviour.
