### ISSUE TITLE
Flash of timeline on load, then disappears

### ISSUE THREAD

**Issue by davidegirardi** [element-hq/element-web#25567]
### Steps to reproduce

After receiving a message, part of the timeline is not rendered in a room. It shows for a split second and then disappears. Only on Element Nightly version: 2023061101Olm version: 3.2.14. It does not happen on develop or Desktop stable.

Details in rageshake.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2023061101 Olm version: 3.2.14

### How did you install the app?

From the website

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
This morning I had the same thing. Re-entering the room „fixed“ it.

**Comment by davidegirardi** [comment]
Not for me, not even a full refresh. I just noticed the timeline appears briefly. Updating the post and adding info to the rageshake.

**Comment by davidegirardi** [comment]
Now that more events landed, and a fourth hard refresh, I can see all the content.

**Comment by davidegirardi** [comment]
I added the room Id in my previous rageshakes.

**Comment by Johennes** [comment]
The web app team would love to tackle this but it's below our agreed upon threshold for escalating regressions and, sadly, we're currently occupied with other more pressing issues, namely stuck notifications.

**Comment by richvdh** [comment]
presumably, after 9 months, this is no longer limited to nightly.

**Comment by davidegirardi** [comment]
I don't think this is happening anymore. Closing.
