### ISSUE TITLE
Many calls of `/_matrix/client/v3/room_keys/version`

### ISSUE THREAD

**Issue by weeman1337** [element-hq/element-web#25565]
### Steps to reproduce

1. Start Element Desktop
2. Look at the network tab

#### What did you expect?

Only as many requests as required for Element to work

#### What happened instead?

Many requests of the `/_matrix/client/v3/room_keys/version` Endpoint. No special request data. Always the same result.

### Operating system

Ubuntu 22.04.2 LTS

### Application version

Element Nightly version: 2023061101 Olm version: 3.2.14

### How did you install the app?

https://packages.element.io/debian/

### Homeserver

https://element.ems.host/

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
If this is normal behaviour - should we cache it?

**Comment by reekystive** [comment]
Same issue. Using Element Web ([app.element.io](https://app.element.io/)). It keep requesting a 404 API, and console keeps printing errors.

Synapse version: Docker Image
[`matrixdotorg/synapse:latest@sha256:8f727ebb83f13126d775e5ed992a65834b4b67a1df991741802c132d7f3ddc26`](https://hub.docker.com/layers/matrixdotorg/synapse/latest/images/sha256-8f727ebb83f13126d775e5ed992a65834b4b67a1df991741802c132d7f3ddc26)
Element version: `1.11.36`
Olm version: `3.2.14`

<details>
<summary>Screenshots</summary>
Request:<br />
<p>
<img width="808" alt="Screenshot 2023-08-01 at 17 18 08" src="https://github.com/vector-im/element-web/assets/26853900/45d4f4f2-4334-4297-b42c-efde18208c0f">
</p>
<p>
Response:<br />
<img width="670" alt="Screenshot 2023-08-01 at 17 18 18" src="https://github.com/vector-im/element-web/assets/26853900/05328fca-c50f-4d0c-9f23-1bc623180a29">
</p>
<p>
Call stack:<br />
<img width="622" alt="Screenshot 2023-08-01 at 17 17 23" src="https://github.com/vector-im/element-web/assets/26853900/1b9acfb2-1d50-45e4-948f-db2c46e9422e">
</p>
<p>
Console:<br />
<img width="812" alt="Screenshot 2023-08-01 at 17 22 55" src="https://github.com/vector-im/element-web/assets/26853900/a7295e76-c707-4e1c-9415-ef6c21d3c324">
</p>
</details>
