### ISSUE TITLE
`/op` command has disappeared

### ISSUE THREAD

**Issue by Twi1ightSparkle** [element-hq/element-web#25572]
### Steps to reproduce

The `/op` command is no longer available on Element Desktop (Mac) and Web (Firefox) v1.11.33

#### What did you expect?

`/op` command to be available

#### What happened instead?

![Screenshot 2023-06-12 at 4 53 55 PM](https://github.com/vector-im/element-web/assets/19155609/2da4d326-0de5-4d20-99f7-d00ad37ba430)

OPing the user from the right user menu worked as a workaround

### Operating system

macOS

### Application version

Element version: 1.11.33 Olm version: 3.2.14

### How did you install the app?

Homebrew

### Homeserver

element.io and matrix.org

### Will you send logs?

Yes

**Comment by bkil** [comment]
@t3chguy   `/op` is still not restored. Are you sure you closed the right issue? Slash commands in general **are** available, it's only `/op` that had disappeared.

**Comment by t3chguy** [comment]
@bkil are you running a version containing my fix? 

I can see it on develop.element.io in rooms where I have sufficient permissions to perform the action

![image](https://github.com/vector-im/element-web/assets/2403652/b106dbb2-5058-490d-b246-118f64d1a581)

**Comment by bkil** [comment]
Missing on app.element.io

**Comment by t3chguy** [comment]
Yes, because the fix landed after the release candidate, so it hasn't yet been released.
