### ISSUE TITLE
No support for Page Translation in Google Chrome

### ISSUE THREAD

**Issue by lukaszpolowczyk** [element-hq/element-web#25594]
### Steps to reproduce

 I notice that matrix.org (element.io) is not translated by the site translator.

The element.io page does not translate in Google Chrome.

Just go to any chat on element.io, and try to translate it in Google Chrome, using the built-in translator. It won't work.

### Outcome

The content of chat messages, but also perhaps titles and descriptions, should easily be translated by Google Chrome's built-in page translator.

For example, Discord can be translated using this translator.

### Operating system

Arch Linux

### Browser information

Wersja 114.0.5735.106 (Oficjalna wersja) (64-bitowa)

### URL for webapp

develop.element.io, app.element.io

### Will you send logs?

Yes

**Comment by pydeveloperashish** [comment]
its getting translated using google builtin translator. Check again

**Comment by lukaszpolowczyk** [comment]
@t3chguy Definitely projects in React can somehow handle this. Maybe not perfectly, but they can.
Even Facebook can handle it.
So perhaps there is a fault on the vector-im side after all?

**Comment by t3chguy** [comment]
@lukaszpolowczyk the "fault" is we specify `notranslate` because without it React would crash when translation was done. https://github.com/vector-im/element-web/issues/13557#issuecomment-628014409

**Comment by lukaszpolowczyk** [comment]
@t3chguy So please, at least for individual chat messages add class "translate" - Chrome supports this.

Then the whole page is not translated, but this particular element with text is.
Mastodon, which is in vue, copes via class "translate", see for yourself - https://toot.cafe/@rich_harris/with_replies
It can be done, React can also handle it.

I know that React can also play in the message, for example, if someone edits their post, but that should already work.
But even **if** something breaks, I can refresh the web.element.io page, - that's not a bad thing!

**Comment by t3chguy** [comment]
> that's not a bad thing!

It is though, as it looks like the app is broken, there's zero indication it was broken by your browser doing unexpected things.

Contributions are welcome here, it isn't something that the web app team is likely to have any time to work on any time soon.

**Comment by lukaszpolowczyk** [comment]
In web.element.io, just add class "translate" to an element that has class "mx_EventTile_body markdown-body" - then Google Chrome translates only those elements.

I could make a dynamic UserScript that adds such a class to a chat message, and then Google Translator in Chrome would detect it for itself and translate the messages. :D

**Comment by t3chguy** [comment]
Be my guest.

> Contributions are welcome here

**Comment by lukaszpolowczyk** [comment]
@t3chguy I can't even find this element in the source code. I would need help, direction.

**Comment by t3chguy** [comment]
Pretty much all the timeline code is in https://github.com/matrix-org/matrix-react-sdk

**Comment by richvdh** [comment]
> I notice that matrix.org (element.io) is not translated by the site translator.
>
> The element.io page does not translate in Google Chrome.

I think/assume this is talking about the Element webapp, rather than https://element.io
