### ISSUE TITLE
Focus the message box automatically when scrolled to the bottom upon clicking empty space in the timeline

### ISSUE THREAD

**Issue by Kommynct** [element-hq/element-web#25599]
#### What would you like to do?
I'd like it if element automatically focused the text box when you click on any empty space in the timeline
#### Why would you like to do it?
Because it's slightly more annoying to go and click on the text box
#### How would you like to achieve it?
n/a

### Have you considered any alternatives?

Always focusing the textbox when regaining focus if you're at the bottom of the window would also probably work well, might even be better!

**Comment by gaelledel** [comment]
Thanks for your request. This is not a behaviour that we are likely to adopt as it doesn't match most users expectations.

**Comment by Kommynct** [comment]
This is the behavior of telegram, i'm not sure why it wouldn't match most users expectations, it's quite intuitive and I don't see a downside?

**Comment by gaelledel** [comment]
There are many interactive components in the timeline and so the risk on inadvertently selecting something unintended is high when clicking on blank areas. The composer section is always sticky which eases the users' capacity to interact with it. So I would see this as a usability risk. The fact that Telegram does it this way does not mean it is justified in our context as their app is very different.

**Comment by Kommynct** [comment]
I believe you completely fundamentally misunderstand the nature of this request based on that comment, allow me to better explain


If i click to the left of where I have written text, before I start typing, the composer section is not showing a blinking caret anymore, I do notice that I can still type in it, however, the caret being hidden leads me to the conclusion that I cannot type on it, unless I have clicked where it says "Send an encrypted message"

This request is to show this caret at all times, essentially, there is no risk of inadvertently selecting something when clicking on blank areas, as this is simply a visual change.
