### ISSUE TITLE
to-device messages can be processed out-of-order, causing dropped keys and decryption errors

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#25723]
Events - including to-device messages - received over /sync are decrypted in parallel. libolm can handle some reordering of to-device messages: it remembers up to 40 "skipped keys", but in extreme cases, this parallelisation can cause reordering so bad that message keys are forgotten.

**Comment by richvdh** [comment]
related to https://github.com/vector-im/element-meta/issues/762

**Comment by BillCarsonFr** [comment]
Adding a test to the complement crypto test list

**Comment by kegsay** [comment]
Test written and passing, closing.
