### ISSUE TITLE
Calls are sometimes stuck in a "connecting" state

### ISSUE THREAD

**Issue by Oh-My-Lands** [element-hq/element-web#25880]
### Steps to reproduce

1. Call someone
2. They accept
3. Call stuck in "connecting"

#### What did you expect?
The call to work
#### What happened instead?
It did not.

### Operating system

Fedora 38 Workstation

### Browser information

Firefox 155.0.2

### URL for webapp

https://chat.tchncs.de/#/room/!DjyDIsUHDKPqOMGJPg:tchncs.de

### Application version

Element version: 1.11.36 Olm version: 3.2.14

### Homeserver

chat.tchncs.de

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Closing due to lack of reproduction in over a year
