### ISSUE TITLE
⋯ in left panel next to "All rooms" doesn't do anything on develop

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-web#25896]
### Steps to reproduce

1. Expand the left left panel
2. Next to "All rooms", click on ⋯

#### What did you expect?
See a menu

#### What happened instead?
Nothing

### Browser information

Chromium Version 115.0.5790.110 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: a0558a82873f-react-5ec2c354977d-js-88ba4fad716a Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/10703
