### ISSUE TITLE
Unable to silence "joined the room" notifications

### ISSUE THREAD

**Issue by austinbutler** [element-hq/element-web#25911]
### Steps to reproduce

1. Enroll in the "Notifications Settings" beta
2. Leave the beta

#### What did you expect?

Notifications would go back to how they were and/or having the ability to silence "joined the room" notifications in the settings.

#### What happened instead?

I can't find a way to silence these notifications now.

### Operating system

NixOS

### Application version

1.11.36

### How did you install the app?

nixpkgs

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by yash1378** [comment]
@germain-gg  can you assign this issue to me

**Comment by austinbutler** [comment]
Still happens and is really annoying. Is there even a workaround available? For a while I wasn't getting notifications period so I stopped using Element entirely. Tried it again recently and I get a notification any time someone joins a room.

**Comment by t3chguy** [comment]
<img width="416" alt="image" src="https://github.com/element-hq/element-web/assets/2403652/e19a14d9-0a52-4cb6-8283-4b244406fd65">

This is controlled by this setting.

**Comment by austinbutler** [comment]
Ah, well if the point of labs is to get feedback here it is: that's not clear at all what it does. But thank you for letting me know what to toggle.
