### ISSUE TITLE
Element Choosing Year Old Key Backup

### ISSUE THREAD

**Issue by Snomwan** [element-hq/element-web#25944]
### Steps to reproduce

1. I can't see any of my messages from about a year ago to now.
2. I clicked on restore from key backup but it is out of date by about a year.

### Outcome

I was hoping to get all my keys back so I could look at my messages.

In reality I can only see my messages I just send or messages from last year.

### Operating system

Arch Linux

### Application version

Element version: 1.11.38 Olm version: 3.2.14

### How did you install the app?

AUR

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Snomwan** [comment]
[log-0.log](https://github.com/vector-im/element-web/files/12294641/log-0.log)

**Comment by t3chguy** [comment]
@Snomwan what makes you think your key backup contains the keys for the messages in that gap?

**Comment by Snomwan** [comment]
> @Snomwan what makes you think your key backup contains the keys for the messages in that gap?

Because it has worked for me before but it didn't this time. Because I've signed in on another device about 3 or so months ago and I was able to get up to date keys. Sadly the session has been signed out so I have no way of getting the keys that way.

**Comment by richvdh** [comment]
If this is still an issue, please send a bug report from within the application

**Comment by t3chguy** [comment]
Hi, I'm going to close this issue for now as there is not enough info here for us to be able to action it. Please feel welcome to reopen or ask me to reopen the issue if you update the description with steps/screenshots/video/more details so our developers can have a look at it.
