### ISSUE TITLE
"Database unexpectedly closed" is a bad error message

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#25948]
### Steps to reproduce

1. Fill up your OS disk

#### What did you expect?

I'm on desktop in this scenario, so I would have expected an error message that didn't reference "tabs". The error also doesn't cover my situation: I diskfilled myself, so the indexeddb closed. 

A better title might be "%brand stopped working" and description related to the platform:

* Web: "If you cleared browsing data then this message is expected. %brand may also be open in another tab, or your disk is full. Please clear up some space and reload."
* Desktop: "Your disk may be full. Please clear up some space and reload."

The close button also probably shouldn't be there at all.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/37600691-ce66-4774-a06c-ca2944771c1a)

### Operating system

Windows 11

### Application version

Today's Nightly (unsure, app reloaded and version info isn't available)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by Decoder-25** [comment]
hey can you assign me this issue. I am a newbie but I will try to solve this.

**Comment by RohanMishra315** [comment]
Hey, @turt2live I think the issue is here 
![Screenshot 2023-08-13 225419](https://github.com/vector-im/element-web/assets/121561397/db10e8c0-edd0-4b42-9a7c-6ef197e1ac1d)
  
Should I put both funtionality for Web and Desktop in the code .

**Comment by thecodereule** [comment]
I will work on this.

**Comment by benparsons** [comment]
I am experiencing this when using multiple Element Web instances on different domains.
