### ISSUE TITLE
Connecting session to Key Backup does not work

### ISSUE THREAD

**Issue by Olf0** [element-hq/element-web#25959]
### Steps to reproduce

1. Where are you starting? What can you see?
   ![Screenshot from 2023-08-12 20-52-52](https://github.com/vector-im/element-web/assets/16547876/028776ef-153f-47fa-84cd-22963a23a325)
2. What do you click?
   [Connect this session to Key Backup] button
3. More steps…
   Inputting the *correct* passphrase or, alternatively Backup Key (confusingly called "Security key" in that dialogue; please do unify the wording) always yields:
   ![Screenshot from 2023-08-12 21-00-05](https://github.com/vector-im/element-web/assets/16547876/e7021af5-3554-4502-9342-4be43d5a6ca6)
   or
   ![Screenshot from 2023-08-12 21-04-35](https://github.com/vector-im/element-web/assets/16547876/513bb928-195a-4d86-bbe8-a2b1aa4a76c0)
   ultimately result in
   ![Screenshot from 2023-08-12 21-05-49](https://github.com/vector-im/element-web/assets/16547876/f1d7ee8b-a653-43d9-8d34-3e147f5a9874)
5. Counter-check
   Importing the Key Backup between the Android apps Riot.im and miniVector works fine (in either direction, both directions tested), both via passphrase and via Backup Key.
   I.e., these *four* test worked absolutely fine.

### What did you expect?
Backup keys are imported.

### What happened instead?
Error message, as depicted above.

## Additional information
As mentioned in step 5 above, the key backup was generated and successfully connected to between the older Android clients miniVector 0.9.12 and Riot 0.9.13.  Newer Matrix clients do not support Android 4.4, hence cannot be installed.

It looks like the format and maybe also the encryption (originally `m.megolm_backup.v1.curve25519-aes-sha2`) was altered; nevertheless, modern clients (like the elements web-app used) shall be able to use / import the old format / encryption!

### Operating system

Ubuntu 20.04 LTS (x86-64)

### Browser information

Firefox 116.0.2 (64-bit)

### URL for webapp

https://app.element.io/#/room/!xyz:matrix.org

### Application version

Element version: 1.11.38 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes, if requested / required.
IMO this is unambiguous without logs, so I did not generate and submit them now.

**Comment by richvdh** [comment]
Unfortunately we have no plans to support the old backup encryption format.

**Comment by Olf0** [comment]
Not even having considered backward compatibility when altering the backup format is …, as this reassigns all old backups to be "one way backups", i.e. useless, random data.

IMO there is no better way to lecture people that creating backups is a superfluous, futile effort.

**Comment by richvdh** [comment]
Sorry, I don't know what I was smoking last week. `m.megolm_backup.v1.curve25519-aes-sha2` is the *current* key backup algorithm. ([MSC3270](https://github.com/matrix-org/matrix-spec-proposals/pull/3270) proposes a new algorithm, but that's not yet live. And yes, we will need to consider backwards compatibility.)

So there is something different going on here. If you can still reproduce it, please submit debug logs from within the application.

**Comment by Olf0** [comment]
Thank you for rereading, reinvestigating and reconsidering this issue.

> So there is something different going on here. If you can still reproduce it, please submit debug logs from within the application.

I will try to (reproduce it again, which should not be an issue) and to "submit debug logs from within the application" (never did that before).

**Comment by schildbach** [comment]
This might be related to #23497.

**Comment by richvdh** [comment]
Hi, I'm going to close this issue for now as there is not enough info here for us to be able to action it. Please feel welcome to reopen or ask me to reopen the issue if you update the description with steps/screenshots/video/more details so our developers can have a look at it.
