### ISSUE TITLE
Persistent stuck unread in encrypted room

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#25984]
### Steps to reproduce

Report from an Element employee, who included confidential logs in the [rageshake](https://github.com/matrix-org/element-web-rageshakes/issues/22466):

> I have a room that has 2 unread notifications, with no new events, every time I start Element Nightly. If I click on it the unread counter skyrockets. If I mark it as read and then start pressing page up the unread count skyrockets again.

Version: 2023081601

**Comment by benjaoming** [comment]
I still experience this, currently with 1 room. "Mark as read" has no effect on the encrypted room, and there is no unread messages, no unread threads, and no encryption errors to explain it.

This has happened many times in the past, but I think that some kind of event has made the "stuck unread" disappear on other rooms. Will have to pay closer attention to that.. but there's been a lot of upgrades and bug fixes in the mix of possible explanations :)

**Comment by langleyd** [comment]
We believe this is fixed now, I checked in with the reporter and they have not seen it in weeks.
