### ISSUE TITLE
Element assumes user already has a Security Key, whether or not they actually do.

### ISSUE THREAD

**Issue by vaguerant** [element-hq/element-web#26019]
### Steps to reproduce

1. When launching Element Desktop, receive the "Set up Secure Backup" notification.
2. Hit the "Later" button on that notification for multiple years (probably two or three).
3. Finally hit Continue, Element Desktop asks for the Security Key to continue, or to reset the key if it's been lost.
4. I don't know what a Security Key is, I don't have a Security Key, I've never had a Security Key. Help, police!

#### What did you expect?
It should have offered to **generate** a Security Key, because up to this point I did not have one.

#### What happened instead?
I was forced to either reset my session, with big red warning about losing access to encrypted messages, or cancel setting up Secure Backup.

#### Wow, that's crazy, what did you do next?
I was confident that I had never set up a Security Key, so I decided to see what the Secure Backup dialogue looked like on element-android. In there, I was given a prompt to **generate** a Security Key. I chose this option and generated my Security Key on mobile and set up Secure Backup.

#### And?!
Now everything works perfectly. Both desktop and Android confirm that I have Secure Backup enabled. I saved the Security Key backup txt file offered in the element-android app. I no longer have the issue this filing is about, because I **do** have a Security Key now. I do not know why desktop expected me to already have one when I did not.

### Operating system

Windows 10

### Application version

Element version: 1.11.39, Olm version: 3.2.14

### How did you install the app?

Presumably element.io, it was years ago. I didn't do anything weird or stupid.

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by richvdh** [comment]
I'm pretty sure this isn't the case. If anyone can reproduce it, we can re-open, but I'm closing for now.

**Comment by gavv** [comment]
Reproducing for me all the time.

**Comment by richvdh** [comment]
@gavv please open a new issue, and send debug logs from within your client.
