### ISSUE TITLE
Flaky cypress test "Spotlight > should be able to add and remove filters via keyboard"

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#26053]
I got this failure: https://cloud.cypress.io/projects/ppvnzg/runs/17651/test-results/e1150166-7a80-4155-9428-76e9ec118440 when I was trying to merge a PR for an unrelated change.

```
Timed out retrying after 10000ms: expected '<li#mx_SpotlightDialog_button_explorePublicRooms.mx_AccessibleButton.mx_SpotlightDialog_explorePublicRooms.mx_SpotlightDialog_option>' to have attribute 'aria-selected' with the value 'true', but the value was 'false'

cypress/e2e/spotlight/spotlight.spec.ts at line154 
```

**Comment by andybalaam** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/6069472488/job/16463907578

**Comment by andybalaam** [comment]
Spent some time trying to debug this. I ran it ~10 times locally and couldn't get it to happen, even with `--browser=chromium`

**Comment by andybalaam** [comment]
Ah, after another few tries it did happen.

**Comment by andybalaam** [comment]
The failure was on the SECOND time it asserted that `aria-selected==true`

**Comment by andybalaam** [comment]
I added a longer timeout and left this running over and over in the hope that I can get it to fail and stick in the failing state.

**Comment by andybalaam** [comment]
The "Explore Public Spaces" option is selected and we are expecting "Explore Pubic Rooms" to be.

**Comment by andybalaam** [comment]
![image](https://github.com/vector-im/element-web/assets/76812/243ad8a2-4a80-43f6-8c5b-0456b78d2887)

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6349567009/job/17247955477#step:8:23738

**Comment by richvdh** [comment]
since this hasn't been reported for several months, let's assume for now that it is fixed.
