### ISSUE TITLE
Regression: room list loading often takes multiple minutes after UI already has come up

### ISSUE THREAD

**Issue by ell1e** [element-hq/element-web#26050]
### Steps to reproduce

1. Room list loading often takes multiple minutes after UI already has come up. See here:

![Screenshot from 2023-08-24 17-01-53](https://github.com/vector-im/element-web/assets/64124388/bd2ad51c-27d4-4558-a481-a8929c3904d2)

#### What did you expect?
Room/channel list loads after seconds at most on a normal laptop

#### What happened instead?
Room list remains blank for multiple minutes, element basically unusable unless you only want to chat in the last viewed room

### Operating system

openSUSE Leap 15.5

### Browser information

117.0b9 (64-bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.39 Olm version: 3.2.14

### Homeserver

matrix.org latest

### Will you send logs?

No

**Comment by andybalaam** [comment]
@ell1e if you were able to send logs it might help us debug what is happening here. You can do it by going to Setting -> Help and About -> Submit debug logs and pasting the URL of this issue when prompted. Thanks!
