### ISSUE TITLE
"Changed room avatar" notice in timeline has v-offset on thumbnail

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-web#26070]
### Steps to reproduce

1. set room avatar

#### What did you expect?
avatar is in line with text (vertically centered on the line)
#### What happened instead?
![image](https://github.com/vector-im/element-web/assets/2803622/db2d4cea-de5b-4ddc-a4fe-07b34673941e)

### Operating system

arch

### Browser information

firefox 116.0.3

### URL for webapp

https://develop.element.io

### Application version

Element version: fcd805255c26-react-64f762d7b0f3-js-5788d9744b76 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by lalitkumawat1m** [comment]
I want to work on this issue please assign it to me

**Comment by t3chguy** [comment]
Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)
