### ISSUE TITLE
New room header buttons not using styled tooltips

### ISSUE THREAD

**Issue by t3chguy** [element-hq/element-web#26096]
### Steps to reproduce

1. Enable labs flag
2. Find a room where you lack permission to call
3. Hover over disabled icons

### Outcome

The new room header UI is sleek but has a major usability regression around tooltips. Using the native `title` attribute instead of tooltips is fine for accessible technologies but not great for sighted users having to hover for ~5s for the tiny tooltip to appear

#### What did you expect?

<img width="281" alt="image" src="https://github.com/matrix-org/matrix-web-i18n/assets/2403652/745834f2-043b-4d8a-afb2-45c7db90df6c">

#### What happened instead?

<img width="141" alt="image" src="https://github.com/matrix-org/matrix-web-i18n/assets/2403652/3f93d6cf-2bf1-4877-abdf-23e9173a31d4">

### Will you send logs?

No

**Comment by germain-gg** [comment]
https://www.radix-ui.com/primitives/docs/components/tooltip#displaying-a-tooltip-from-a-disabled-button being the solution to this. We need to figure out whether we can encompass that directly in the Tooltip component in Compound Web, as this sounds like a fairly common thing to happen

**Comment by Aziz-4980** [comment]
is this issue still open? @t3chguy

**Comment by t3chguy** [comment]
<img width="510" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/e17c1fde-f576-4866-a126-7fe4f4594d6f">

@Aziz-4980 yup.

**Comment by lalitkumawat1m** [comment]
I want to work on this issue please assign it to me

**Comment by t3chguy** [comment]
Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)

**Comment by daniellekirkwood** [comment]
@t3chguy given our work on this topic (header and tooltips), has this work been done ?

**Comment by t3chguy** [comment]
This was done by Florian going and updating all existing tooltips to use Compound.
