### ISSUE TITLE
Element R: Persistent room list

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26108]
Legacy crypto has a `RoomList` which maintains a list of encrypted rooms inside the `CryptoStore`. We probably need to do something with this (otherwise the server could trick us into resetting the encryption settings of a room).

* [x] Add support to matrix-sdk-crypto for getting and setting room settings (https://github.com/matrix-org/matrix-rust-sdk/pull/3042)
* [c] Expose those methods in wasm bindings (https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/95)
* [x] Get rid of `MatrixClient.roomList`, and let legacy Crypto instantiate its own. Replace the two references to it inside `MatrixClient` with a `CryptoBackend.isRoomEncrypted` or similar. (Done in https://github.com/matrix-org/matrix-js-sdk/pull/3944)
* [x] Implement for RustCrypto via bindings added above
* [x] In RustCrypto.onCryptoEvent, check existing setting, and store updates.
* [x] In `MatrixClient.encryptEventIfNeeded`, make sure that the crypto store is checked. (https://github.com/matrix-org/matrix-js-sdk/pull/4035)

(https://docs.google.com/document/d/18LuSmlaoeZpsOsiPKIdAxKYsbr9V1etMAYm2vxMId7A/edit#heading=h.t75m7z578qe4)

**Comment by andybalaam** [comment]
The `RoomList` module is referred to as `matrix-js-sdk/src/crypto/RoomList` in matrix-react-sdk. The `RoomList` class is not actually used, but `IRoomEncryption` from that module is used.

I am wondering whether we should deprecate `RoomList` since we want to make it more of an implementation detail of the crypto.
