### ISSUE TITLE
Flaky Percy test: Configured room on IRC layout

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#26151]
### Steps to reproduce

E.g. this Percy test: https://percy.io/dfde73bd/matrix-react-sdk/builds/30076401/changed/1664921294?browser=chrome&browser_ids=47%2C48%2C49&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1920&widths=120%2C260%2C285%2C500%2C1024%2C1920 failed with a spinner appearing instead of the date divider:

#### What did you expect?
![image](https://github.com/vector-im/element-web/assets/76812/2a3863e4-c268-49a7-a083-e8cd4cf40d10)

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/76812/db8d3e94-8448-47c0-b383-9ab3b9ac72ad)

**Comment by kerryarchibald** [comment]
https://percy.io/dfde73bd/matrix-react-sdk/builds/30602275/changed/1690802900?browser=firefox&browser_ids=47%2C48%2C49&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=original&width=1024&widths=264%2C580%2C796%2C1024%2C1920

**Comment by kerryarchibald** [comment]
Attempted a fix here: https://github.com/matrix-org/matrix-react-sdk/pull/11769
Should be disabled next time if that doesn't help as per https://handbook.element.io/books/web-app-team-wat/page/wat-flaky-test-policy

**Comment by richvdh** [comment]
seems like kerry's fix worked!
