### ISSUE TITLE
Avatars in call timeline tiles deformed when window is too narrow

### ISSUE THREAD

**Issue by YamatoRyou** [element-hq/element-web#26183]
### Steps to reproduce

n/a

#### What did you expect?
n/a

#### What happened instead?
As shown in the figure, some avatar is stretched vertically.
![{4FA45B7F-E917-7CF7-3654-9863EA8C3114}](https://github.com/vector-im/element-web/assets/48104960/f3eab991-f086-41ca-a75e-67436faa2e30)

### Operating system

x64 Windows 11 (10.0.22621)

### Application version

Element Desktop 1.11.43

### How did you install the app?

https://packages.element.io/desktop/update/win32/x64

### Homeserver

Synapse 1.92.1

### Will you send logs?

No

**Comment by florianduros** [comment]
Fixed by github.com/element-hq/element-web/issues/27427

**Comment by t3chguy** [comment]
@florianduros what happened here? I presume it shouldn't be in `Done`

**Comment by t3chguy** [comment]
![image](https://github.com/element-hq/element-web/assets/2403652/ff1faafe-2ead-4975-9da8-3a26f1e7929e)

Should probably move it back then

**Comment by florianduros** [comment]
Yep, I'm trying to find how to do it
