### ISSUE TITLE
Element-R: Restore Key Backup dialog prompts me to enter security key

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26247]
I have no idea what my security key is (I have a passphase, but that is different, and is rejected, and anyway I just entered it)

STR:
 * Have an account where 4S is set up and key backups exist.
 * On that account, have an EWR session where key backup is not enabled, somehow (I am in this situation due to a [bug](https://github.com/vector-im/element-web/issues/26244), but it is probably possible to achieve it other ways too)
 * In "Security and Privacy" settings, click "Connect to backup" (or something to that effect)
 * Enter security passphrase
 * Some popup about restoring happens
 * Observe: 
![image](https://github.com/vector-im/element-web/assets/1389908/7dcfa3cc-6ce7-422d-8f44-60d3f30f224a)

**Comment by richvdh** [comment]
Presumably it is trying to upload the key to 4S or something, but (a) it's already there (b) it should allow me to enter a passphrase as well as a security key (c) I just entered it like 5 seconds before

**Comment by BillCarsonFr** [comment]
happens with legacy also
