### ISSUE TITLE
Element-R: User info panel not updated when user creates or deletes devices

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26263]
The user info panel displays a list of the user's current devices:

![image](https://github.com/vector-im/element-web/assets/1389908/12091d60-17ad-4d71-9d5f-a46ebe546711)

This list is not updated when the user logs in on a new device or logs out an existing device. (You have to close and re-open the userinfo panel).

**Comment by pmaier1** [comment]
The same seems to happen for the session manager in settings. Likely this changes the priority to something more critical.

**Comment by hughns** [comment]
The session manager case is as follows -

The use can view their own list of devices in Settings:

<img width="887" alt="image" src="https://github.com/element-hq/element-web/assets/6955675/3aab4671-a6cf-4a16-8c47-5f1cb5ea3b8d">

The "Other sessions" list is not updated if the user signs in (or out) on a new device. Instead you have to close and re-open the Sessions tab.
