### ISSUE TITLE
Respect theme avatar-background-colors

### ISSUE THREAD

**Issue by aceArt-GmbH** [element-hq/element-web#26285]
On element 1.11.42, the [theme `avatar-background-colors`](https://github.com/vector-im/element-web/blob/361941e5d44c27a28c2dd893ae15d9a1f4c75172/docs/theming.md?plain=1#L67) do not seem to be respected for avatar colors.

The CSS variables are set as `--avatar-background-colors_0` but never read.

It would be nice to support theming again with the new design system

**Comment by estellecomment** [comment]
The colors are now hardcoded in matrix-react-sdk, so they ignore the theme customisation : 
https://github.com/matrix-org/matrix-react-sdk/blob/81c62e51c474581c3d3f0f1e72aa0d1eb26ac45a/src/Avatar.ts#L30

**Comment by aceArt-GmbH** [comment]
@estellecomment  hm, shouldn't the variables still be read:
https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/Avatar.ts#L112-L114 ?

**Comment by PeterKleinTele2** [comment]
Not sure if this is the correct way to make my opinion heard, but... being able to control the colors of the imageless avatars is very important to my company. We are creating a suite with multiple collaboration tools which must share the same look-and feel throughout the suite. We had  been able to reach a point with the old system where it looked good enough for our UX-department, now however this is broken and it has become a blocker for launching the suite. Please let us know if/when this can be rectified. Looking through the css it looks like a quick fix to add this support just by tweaking the CSS and allow for more variables inside config.json

**Comment by t3chguy** [comment]
The Avatars are drawn by https://github.com/element-hq/compound-web and Element Web can't override them as there's no variables other than the ones which represent the raw colour palette. It'd be up to the people working on that layer to unblock this.

**Comment by giomfo** [comment]
Thx @t3chguy, would it be possible for you to create the issue in the compound-web repo and link it here?
I noticed that the original issue was created there, but it has been [transferred](https://github.com/element-hq/element-web/issues/26285#issuecomment-1744799309) here...

**Comment by t3chguy** [comment]
@giomfo I don't have enough context on it. Germain previously said its an implementation bug. I originally instructed the reporter to report it to Compound and then it was transferred. So clearly my context is incorrect.

**Comment by langleyd** [comment]
@robintown , Could you provide any clarity from the compound side regarding @t3chguy 's  comment [above](https://github.com/element-hq/element-web/issues/26285#issuecomment-1856343009)?

**Comment by PeterKleinTele2** [comment]
Hello

This issue seems to have stuck here. @robintown you mentioned that you'd like to "have a chat with the designers". Do you know who we need to contact for this and is there any way I can help with pushing this forward?

I would be very grateful for any feedback

**Comment by robintown** [comment]
Hi @PeterKleinTele2, thanks for the reminder, I admittedly lost track of this over the new year but will bring it up with the Compound team next week. I don't think there's anything that you can help with externally on this issue at the moment, but I'll try to get this unblocked and put the design tokens in place soon.

**Comment by PeterKleinTele2** [comment]
Hello @robintown , have you had any luck with the design team to see if this is fixable?

**Comment by robintown** [comment]
@PeterKleinTele2 Hello, yes, after aligning our approach last week, the design team has now created the design tokens that I recommended to unblock this, and I will be creating the necessary theming mechanisms in Compound this week. Then there remains one last task in Element Web to wire up those theming mechanisms to its existing config.json custom themes system, which I expect we can do trivially.

Even though this issue is about a single component, we're currently seeing a need to establish a scalable approach to theming all of Compound, which is why we're trying to be more deliberate here. So, thank you for your patience! If not this week, I expect we can get those final pieces together before end of next week.

**Comment by PeterKleinTele2** [comment]
Hello, it looks like you've come a long way towards fixing this in https://github.com/matrix-org/matrix-react-sdk/pull/12209 but there is some check that did not complete. Looking forward to testing once this is resolved.

**Comment by robintown** [comment]
Hi, this issue is not yet ready for testing, but it is continuing to move forward. I still expect the full Compound theming mechanism to be in place by the end of this week.

**Comment by robintown** [comment]
This is resolved now, please see the [updated theme documentation](https://github.com/element-hq/element-web/blob/develop/docs/theming.md#custom-themes) for links to the full list of customizable tokens, but the gist is that you can now override avatar and username colors like this:

```jsonc
{
  ...
  "setting_defaults": {
    "custom_themes": [
      {
        "name": "My Theme",
        "is_dark": false,
        "fonts": {
          ...
        },
        "colors": {
          ...
        },
        "compound": {
          "--cpd-color-text-decorative-1": "var(--cpd-color-red-1100)",
          "--cpd-color-text-decorative-2": "var(--cpd-color-orange-1100)",
          "--cpd-color-text-decorative-3": "var(--cpd-color-yellow-1100)",
          "--cpd-color-text-decorative-4": "var(--cpd-color-green-1100)",
          "--cpd-color-text-decorative-5": "var(--cpd-color-blue-1100)",
          "--cpd-color-text-decorative-6": "var(--cpd-color-purple-1100)",
          "--cpd-color-bg-decorative-1": "var(--cpd-color-alpha-red-400)",
          "--cpd-color-bg-decorative-2": "var(--cpd-color-alpha-orange-400)",
          "--cpd-color-bg-decorative-3": "var(--cpd-color-alpha-yellow-400)",
          "--cpd-color-bg-decorative-4": "var(--cpd-color-alpha-green-400)",
          "--cpd-color-bg-decorative-5": "var(--cpd-color-alpha-blue-400)",
          "--cpd-color-bg-decorative-6": "var(--cpd-color-alpha-purple-400)"
        }
      }
    ]
  }
}
```

**Comment by PeterKleinTele2** [comment]
Yes, I saw that, that's great.

When should we be able to test it, wpuld that be in the nightly build?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by robintown** [comment]
The change will be available in tomorrow's Nightly build, yes, so that's likely the easiest way to test it
