### ISSUE TITLE
Lost access to all messages after restoring from security key

### ISSUE THREAD

**Issue by RalfJung** [element-hq/element-web#26284]
### Steps to reproduce

1. Backup the security key from the element web UI
2. Delete all storage in the browser
3. Log back in to element, and when prompted to restore the key, select the previously created backup

#### What did you expect?

I am back exactly where I left the session before deleting the browser storage.

#### What happened instead?

I seem to have lost access to all my messages. It just says "Unable to decrypt message" everywhere. This is a disaster. I will have to switch to a different chat system (one that doesn't eat all my data despite creating a backup) if there is no way to solve this problem.

### Operating system

Debian Linux

### Browser information

Firefox 118.0.1

### Application version

Riot version: 1.11.43 Olm version: 3.2.14

### Will you send logs?

No

**Comment by RalfJung** [comment]
I have reloaded the page many times since restoring the backup, but the old messages remain lost.

**Comment by RalfJung** [comment]
> Do the messages show up if you click „Restore from backup“ in security settings?

There is no "Restore from Backup" in that screen:

![image](https://github.com/vector-im/element-web/assets/330628/caab976c-aa96-4137-9ae6-f532598ccd57)

I have no idea what that "connecting a session to a key backup" means. I created a backup early on when Element said there was something to backup, I don't think I have ever been in the security settings menu before. Is there more than one kind of backup? I did the one that Element guided me towards using, obviously assuming that that is all I have to backup.

**Comment by PascalinDe** [comment]
Hello (and thank you for all your great work!),

I'm experiencing a similar issue on our instance (Element version: 1.11.47, Olm version: 3.2.14).

**Steps to reproduce**

1. set up both security phrase and security key
2. log in, send some messages, receive some messages
3. log out, clear browser data
4. log back in
5. verify session w/ either security phrase or security key (both seem to show the same behaviour)
6. reload several times as proposed

**Expected outcome**

- all messages from both me and other users are readable

**Actual outcome**

- my messages are readable :heavy_check_mark: 
- messages that I received while I was still connected are readable :heavy_check_mark:
- only some of the messages that I received while disconnected are readable, others cannot be decrypted, with seemingly no pattern :x: 

We will be looking into this issue on our side, and I'll post any updates on what we find here - do you have any pointers where would be a good place to start looking? Thank you in advance!

**Comment by RalfJung** [comment]
Sorry, I've stopped using element-web (and matrix altogether) so I can't provide screenshots.

**Comment by richvdh** [comment]
Ok, I'm sorry it didn't work out for you.

**Comment by tester1121** [comment]
This is happening with a friend of mine, he had to delete backup completely, and is now seeing if that fixed the issue. He had to delete two backups, though.
