### ISSUE TITLE
Element-R: "Reset cross signing" button prompts for security phrase 3 times

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26321]
* In settings, under "Cross Signing", click "Reset"
 * Confirm that you really want to
 * Enter security phrase/key (not sure what you'd do if you'd forgotten?)
 * and again
 * and again

**Comment by richvdh** [comment]
Possibly related to https://github.com/vector-im/crypto-internal/issues/154

**Comment by richvdh** [comment]
> Enter security phrase/key (not sure what you'd do if you'd forgotten?)

Answer: somewhat unintuitively IMHO, you'd have to click "Reset" under "Secure Backup"

**Comment by richvdh** [comment]
Related: https://github.com/vector-im/element-web/issues/26468

**Comment by BillCarsonFr** [comment]
Not a blocker. Notice that this flow will be deprecated by OIDC

**Comment by richvdh** [comment]
This works on legacy because there is a cache of the secret storage keys in legacy crypto (https://github.com/matrix-org/matrix-js-sdk/blob/v30.2.0/src/crypto/EncryptionSetup.ts#L326), in *addition* to the application-side cache in `SecurityManager.getSecretStorageKey`. 

I think we just need to call `accessSecretStorage` in `CrossSigningPanel`.
