### ISSUE TITLE
Element-R: "Set up key backup" button doesn't work

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26323]
* Start with an account with working 4S/cross-signing, but no key backup on the server. (One way to achieve this is to delete any existing key backup.)
* On "Security & Privacy" settings, under "Secure Backup", click "Set up"
* Enter 4S Security key/phrase

Observe:

![Image](https://github.com/vector-im/element-web/assets/1389908/1cc9efc8-9238-4b3a-aea4-1a2258cc8060)

In the console:

```
13:43:38.876 Error: End-to-end encryption disabled
    prepareKeyBackupVersion client.ts:3456
    CreateKeyBackupDialog CreateKeyBackupDialog.tsx:90
```

**Comment by andybalaam** [comment]
Steps to reproduce:

Add this to Element Web config and restart:

```
    "features": {
        "feature_rust_crypto": true
    },
```

* Log out and register a brand new user
* Go to Settings > Security and Privacy
* Under Secure Backup choose Set up
* Generate security key and keep a copy
* Delete the backup
* Under Secure Backup choose Set up again
* Observe the error message "Unable to create key backup"

**Comment by BillCarsonFr** [comment]
Reopened because the fixing PR got reverted
