### ISSUE TITLE
Element-R: support for QR code login

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26350]
Element web currently has some support for the experimental QR code login ([MSC3906](https://github.com/matrix-org/matrix-spec-proposals/pull/3906)), but apparently it doesn't work with rust crypto.

Not really sure what needs doing to fix this.

**Comment by richvdh** [comment]
The scope of this is to support @hughns in updating "legacy" QR code login (ie MSC3906) to work with Rust crypto. (There are plans to rework QR code login, but they are out of scope here.

@hughns has done most of the necessary work in https://github.com/matrix-org/matrix-js-sdk/pull/3761.

**Comment by hughns** [comment]
As requested by @pmaier1, my understanding of the state of this is that there are two parts needed:

- https://github.com/matrix-org/matrix-js-sdk/pull/3761 - I think this is now ready for review
- https://github.com/matrix-org/matrix-react-sdk/pull/12139 - the mocks in the test need updating to match the new logic

**Comment by pmaier1** [comment]
> After the QR sign in is completed the list of devices shown in the Sessions tab does not automatically update to show the new device.

I think you've hit this bug which we've not prioritised so far https://github.com/element-hq/element-web/issues/26263. Should be independent of QR code login, if I'm not mistaken.

**Comment by BillCarsonFr** [comment]
Closed as https://github.com/matrix-org/matrix-js-sdk/pull/3761  is merged , and https://github.com/matrix-org/matrix-react-sdk/pull/12139 is closed
