### ISSUE TITLE
OIDC: doesn't discover wk config for default server

### ISSUE THREAD

**Issue by kerryarchibald** [element-hq/element-web#26466]
### Steps to reproduce

1. open https://element-oidc.lab.element.dev/, which has default server `https://synapse-oidc.lab.element.dev`
2. click continue to authenticate
3. notice that you are redirected to a compatibility login on MAS, and that there is no wk request in network
4. change the server to 'synapse-oidc.lab.element.dev' (same server, without https)
5. click continue
6. notice you are redirected to native OIDC login

#### What happened instead?

/config
```
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://synapse-oidc.lab.element.dev",
            "server_name": "synapse-oidc.lab.element.dev"
        }
    },
    "disable_guests": true,
    "dummy_end": "placeholder",
    "embedded_pages": {
        "login_for_welcome": true
    },
    "features": {
        **"feature_oidc_native_flow": true**
    },
    "show_labs_settings": true
}
```

Reasoning here: https://github.com/matrix-org/matrix-js-sdk/pull/3426

### Will you send logs?

No

**Comment by Johennes** [comment]
I spoke to @pixlwave today and the [logic](https://github.com/matrix-org/matrix-rust-sdk/blob/8895ce40d13faa79012144c97044990284215758/bindings/matrix-sdk-ffi/src/authentication_service.rs#L214-L237) on EIX is:

* Drop the URL scheme (but remember if its using TLS or not) and take whatever the user input as a server name, trying to do the `.well-known` look-up
* If it succeeds yay. If not, deny login with an error message (copy being dependent on whether the input is a valid URL or not)

IIUC this is essentially what was attempted to be implemented in https://github.com/matrix-org/matrix-js-sdk/pull/3426.

Other than it being possible that there is no `.well-known` on the home server URL (as on matrix.org), @t3chguy raised in https://github.com/matrix-org/matrix-js-sdk/pull/3426#issuecomment-1573745046 that different server names with different `.well-known`s could be pointing to the same home server URL.

So I think we're right in not implementing this logic and should rather pursue a holistic solution on the spec level.

Given that EX already has the same problem, this shouldn't block us from offering native OIDC as a labsed feature on EW though.

**Comment by Johennes** [comment]
Descoping from https://github.com/vector-im/element-internal/issues/412 since EX has the same problem (not considered blocking there) and a spec change is needed to fix this.

**Comment by hughns** [comment]
https://github.com/vector-im/backend-internal/issues/5 now exists to track changing the discovery mechanism.

**Comment by t3chguy** [comment]
This is by design, 

```
"default_server_config": {
        "m.homeserver": {
            "base_url": "https://synapse-oidc.lab.element.dev/",
            "server_name": "synapse-oidc.lab.element.dev"
        }
    },
```

means do not make the request, here is the value. As per the docs. I suggest using `default_server_name` if you want a WK look-up
