### ISSUE TITLE
Better understand perceived UI bugs and draft a list of ways we might be able to reduce them

### ISSUE THREAD

**Issue by daniellekirkwood** [element-hq/element-web#26497]
We receive a number of bugs reports today from users who are not really running into https://github.com/vector-im/element-web/issues/24392 but due to our design of threaded notifications, they believe that notifications are stuck.

**In this issue we should:** 
- [x] Run competitive analysis with other apps that have systems like threads or similar to threads and share how this looks like elsewhere
- [ ] Craft a low-fi screen of what it might look like in the room list to separate thread unread notifications from main timeline notifications
- [ ] Craft other low-fi screens of any other ideas that come up during research 

Once this list is complete we'll work with the engineers to get each idea sized/ reviewed for technical capabilities or limitations and then move them forward as appropriate! 

**To note:** There's a difference between Unreads and Notifications. Let's not get caught up on that right now and instead focus on the tightly scoped problem of: 
- **"There's a message in a thread in a room that I haven't read yet, how do I know which room and that it's not in the main timeline"**

**Comment by gaelledel** [comment]
List of bugs

1. Mentions in a thread aren't marked red in the room header. Confusion also exists in Figma where we talk about having a red dot and red badges. What was the final choice?
2. If a user receives several mentions inside a Thread, they only see 1x red badge notif at the room list level.
![room list](https://github.com/vector-im/element-web/assets/76945183/fe396b22-073a-4448-9095-3a03ffb3786d)
<img width="1292" alt="Screenshot 2023-11-09 at 11 08 05" src="https://github.com/vector-im/element-web/assets/76945183/e5e6993d-a907-4135-a18a-b42079f1e545">
3. [Figma](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?type=design&node-id=1935-253459&mode=design&t=HmtL592Ed5UN3g7F-4) reffers to display red count badge at room header level for Mentions. This is not happening in the implemented version. The thread icon remains grey with a grey dot at all times

**Comment by gaelledel** [comment]
List of bugs // Unread No mentions

1. Figma Threads fille says we should show a counter badge for threads that the user has participated in when receiving a new reply. Meaning: I participate in 2 thread topics A and B > I receive 8 replies in Thread A ---> We should see a 1x count grey badge in the room list as well as in the room header. 
This behaviour is not happening in implemented version. We never see a badge neither in room list or room header. We only see a black dot.

**Comment by gaelledel** [comment]
I realise reading this that the Thread notification model described in Figma is not in sync with general Notification behaviour implemented in Element. This is evidently creating bugs as currently the notification logic model implemented is the same for Threads and for regular messages.

**Comment by daniellekirkwood** [comment]
Discussed with @gaelledel today morning: 
- Other products have a clear behaviour separation between Threads notifications and Room notifications
- The original design of Threads notifications is buggy in reality (see above comments)

Things to discuss further with the team: 
- Can we put a number on the Thread icon in the room header?
- Can we make the Thread icon dot/number red when it's a highlight ping?
- Can we write out the maths for the numbers throughout the product?
- Can we have a Slack model with a Threads 'space'/area
- Why is there confetti when the threads panel opens?
- Can we default the drop down list in the room to "My threads" ?

**Comment by daniellekirkwood** [comment]
@gaelledel do you consider this as done?

**Comment by daniellekirkwood** [comment]
@gaelledel do you consider this done?

**Comment by gaelledel** [comment]
resolved
