### ISSUE TITLE
Exported chats have broken avatars due to inclusion of `crossorigin="anonymous"`, this `<img>` attribute should be removed in exports

### ISSUE THREAD

**Issue by ctrlcctrlv** [element-hq/element-web#26491]
### Steps to reproduce

1. Where are you starting? What can you see?

I export chats, avatars are broken despite existing in `users/` dir in zip.

#### What did you expect?

Avatars to not be broken.

#### What happened instead?

Broken avatars. Console reads:

```
Access to image at 'file:///tmp/Element%20-%20[SNIP]%20-%20Chat%20Export%20-%202023-11-01T21-10-56.369Z/users/@copypaste-matrix.mfek.org.png' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
Access to image at 'file:///tmp/img/e2e/normal.33e0430.svg' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
```

### Operating system

Arch GNU/Linux

### Application version

Element version: 1.11.45 Olm version: 3.2.14

### How did you install the app?

pacman package `element-desktop`

### Homeserver

matrix.mfek.org runs Synapse version №1.88.0-1

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is blocked on https://github.com/element-hq/compound/issues/293

Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/11448
