### ISSUE TITLE
Can't edit from search

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-web#26508]
### Steps to reproduce

1. Use the search to find one of your own messages
2. Hovering your mouse over the message makes the normal menu to interact with timeline messages appear to the top right of the message
3. Click the edit button

#### What did you expect?
message becomes editable
#### What happened instead?
nothing

### Operating system

w10

### Application version

Element version: 1.11.47 Olm version: 3.2.14

### Homeserver

synapse

### Will you send logs?

No

**Comment by weeman1337** [comment]
Can reproduce. If you go back to the timeline the message is in edit mode.
