### ISSUE TITLE
UX : "Notifications" onboarding task should be named "Desktop notifications"

### ISSUE THREAD

**Issue by estellecomment** [element-hq/element-web#26549]
### Steps to reproduce

Edit 2024-07-04 : added screenshots

1. Where are you starting? What can you see?
Create account. The "Notifications" task is not complete (as expected).
<img width="1642" alt="Screenshot 2024-07-04 at 10 47 33 AM" src="https://github.com/element-hq/element-web/assets/911434/35f27274-6c92-49a0-a389-a78441740839">

2. What do you click?
Go to user settings > notifications, enable notifications
<img width="1636" alt="Screenshot 2024-07-04 at 10 48 15 AM" src="https://github.com/element-hq/element-web/assets/911434/dffed8e2-edd8-465e-b6cf-f877f7da1027">

#### What did you expect?

Notifications onboarding task is marked complete.

#### What happened instead?

Even after a refresh, it is still not marked complete.

#### Why is this happening ?

Because the word "Notifications" is used both for app notifications and for desktop notifications. 
What this task checks for is whether the browser has permission to display desktop notifications. It's confusing. 

#### How to fix it ? 

Rename the onboarding task "Desktop notifications" instead of "Notifications".

### Will you send logs?

No

**Comment by Aziz-4980** [comment]
hi @estellecomment can you please assign this to me? I've understood the assignment.

**Comment by t3chguy** [comment]
@estellecomment is a member of the community like yourself, they cannot assign issues nor make decisions on behalf of the product.

**Comment by gaelledel** [comment]
@estellecomment Hi Estelle, could you please provide more information and attach screenshot here? I don't fully understand what you mean by "notification task" Thanks

**Comment by gaelledel** [comment]
I see thank you. I'm not convinced we need to make a task checklist for this purpose at all.  @amshakal  do you have information on this? Can the step on "notifications" be removed? I am missing context for the reasoning.

**Comment by amshakal** [comment]
I think it's quite standard to ask people to enable notifications to make sure they recieve messages in real time. It's similar to how on mobile if your notifications are not enabled, you recieve a prompt to enable them as a part of the onboarding flow. Now the question we have to clarify is if we want to enable 'desktop notifications' through this step or just simply enable 'notifications' for the account or device? Regardless, we probably need to clarify through the copy.

**Comment by gaelledel** [comment]
Reviewed : we should change the title to "Turn on desktop notifications" and when the user presses on the CTA "enable desktop notifications" we should mark it as Checked regardless if you have changed anything in the toggles or not.

**Comment by gaelledel** [comment]
@t3chguy Yes to change the string button to "Open settings". Can we have the task marked as complete when the settings window is opened right after enabling permissions via the browser dialog. This should mark the "Turn on notification" task as complete without the need to activate toggles. 
If the user doesn't allow Notifs to be turned  in the Browser Permissions dialog then the task should remain as Unchecked as the settings window will not open in this case. The settings window opening acts as an activator for the task to be marked as checked.

**Comment by gaelledel** [comment]
Is this issue a good candidate for a maintainer task?

**Comment by t3chguy** [comment]
Yeah it should be <1h of work
