### ISSUE TITLE
Room details: tab navigation

### ISSUE THREAD

**Issue by kerryarchibald** [element-hq/element-web#26597]
https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=667-440&mode=design&t=PifxQQLUULHatXkK-4

<img width="641" alt="Screenshot 2023-11-16 at 17 52 38" src="https://github.com/vector-im/element-web/assets/3055605/b4772cba-d6bc-4906-969d-98bfd5097a6e">
<img width="169" alt="Screenshot 2023-11-16 at 17 52 16" src="https://github.com/vector-im/element-web/assets/3055605/05104a8a-b2eb-4546-baac-1048084cec5d">
<img width="316" alt="Screenshot 2023-11-16 at 17 52 01" src="https://github.com/vector-im/element-web/assets/3055605/bbb7f0e2-f0f2-41dc-a813-4fb0e9e4106a">

Depends on https://github.com/vector-im/compound/issues/201

AC:
- room info view uses tab navigation that matches designs
- Threads, files, people have tab navigation header

**Comment by dbkr** [comment]
This feels like about a day, especially if we want to add a compound tab bar component (maybe a touch more then).

**Comment by daniellekirkwood** [comment]
I think we can close this out, right @MidhunSureshR ? Is there anything left to do here ? :)

**Comment by MidhunSureshR** [comment]
> I think we can close this out, right @MidhunSureshR ? Is there anything left to do here ? :)

Yep :)
