### ISSUE TITLE
Room details: room description

### ISSUE THREAD

**Issue by kerryarchibald** [element-hq/element-web#26595]
https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=1073-6237&mode=design&t=PifxQQLUULHatXkK-4

https://www.figma.com/file/wqgXVb7RVaIybfRsXdWEiL/Element-Web-Room-Header-%26-Details?node-id=1478%3A102982&mode=dev

<img width="541" alt="Screenshot 2023-11-16 at 17 40 07" src="https://github.com/vector-im/element-web/assets/3055605/73e7e39e-6d5a-431f-842c-49ddfc322664">

<img width="1054" alt="Screenshot 2023-11-22 at 14 59 54" src="https://github.com/vector-im/element-web/assets/3055605/03690302-8a16-49c2-929b-88c142c37268">
https://www.figma.com/file/wqgXVb7RVaIybfRsXdWEiL/Element-Web-Room-Header-%26-Details?node-id=454%3A51346&mode=dev

AC:
- When room has no topic and user has no edit rights, display nothing
- When room has no topic and user has edit rights, display: 'Add topic' cta that opens room settings dialog
- Rich text topics are rendered correctly
- Emoji in topic is rendered correctly
- Topic is truncated to two lines
- Clicking the caret expands to show the full topic
- When the topic is expanded and the user has rights, an edit button is displayed that opens room settings dialog

**Comment by dbkr** [comment]
I'm guessing we would probably want to add a compound component for this (I don't see one) so maybe a day for this. I'm also not seeing what the edit link does? If that needs an edit view we don't have, then more.
