### ISSUE TITLE
Stray semicolon on sign out confirm modal

### ISSUE THREAD

**Issue by kerryarchibald** [element-hq/element-web#26623]
### Steps to reproduce

1. Have a session with encryption setup
2. Open user menu and click sign out

### Outcome

https://github.com/vector-im/element-web/assets/3055605/89b162d6-4053-481c-a60b-dfcbd5c611b5

### Expected
Loading screen for sign out confirm modal should not have a `;`

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/11645

**Comment by mingjuu** [comment]
Can I try to resolve this issue?

**Comment by mingjuu** [comment]
Can I try to resolve this issue?

**Comment by kimhyeonju** [comment]
@kerryarchibald Is there still an issue unresolved? If so, I would like to be involved in addressing this problem. Would that be possible?

**Comment by kerryarchibald** [comment]
@kimhyeonju you're welcome to open a PR to solve this issue! Check out our [contributing guide](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md) for some pointers on how to get started.

**Comment by zahidhussain998** [comment]
hey i would like to work on this issue can anybody tell me is this issue is open??

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/aebfc11a-db70-40d7-9330-2e071b9a61f9)
