### ISSUE TITLE
Element Web and Desktop both appear to have lost their "OIDC-awareness" with respect to account management

### ISSUE THREAD

**Issue by hughns** [element-hq/element-web#26638]
Things that I have noticed no longer work:

- the button to open the account management UI on the OIDC Provider is no longer shown
- the deactivate account button shouldn't be shown
- the sign out button no longer does the right thing: https://github.com/matrix-org/matrix-react-sdk/pull/11432
- multi-device sign out: https://github.com/matrix-org/matrix-react-sdk/pull/11431

<img width="736" alt="image" src="https://github.com/vector-im/element-web/assets/6955675/cfca008f-f09b-485e-9345-1e947265da36">

I suspect something is broken in the discovery part. I'll have a quick look myself to see if anything obvious.

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/be2159db-5dde-4412-91fa-baf5a00186e0)
![image](https://github.com/vector-im/element-web/assets/2403652/083b984c-5ea9-414e-93c7-b2fb36d0999a)

It looks like it uses session storage so forgets it was an OIDC session when you close the tab possibly

**Comment by hughns** [comment]
I'm seeing it immediately after a fresh login.

I think the issue was introduced by https://github.com/matrix-org/matrix-react-sdk/pull/11723. The new implementation from the PR only works with a OIDC-native sessions, whereas we want the implementation to work with both OIDC-native and OIDC-aware sessions.

**Comment by t3chguy** [comment]
Looks like it - regressed by getDelegatedAuthAccountUrl

**Comment by langleyd** [comment]
This still looks broken to @pmaier1 and myself. @t3chguy mind taking a a look?

**Comment by t3chguy** [comment]
You'll need to sign in again, can't bring back forgotten data

**Comment by t3chguy** [comment]
@pmaier1 please open a new issue with repro steps and logs on a version containing the fix

**Comment by langleyd** [comment]
I have opened https://github.com/element-hq/element-web/issues/26997
