### ISSUE TITLE
"Compact modern layout" option sometimes cannot be selected when Modern is enabled

### ISSUE THREAD

**Issue by timmc** [element-hq/element-web#26648]
### Steps to reproduce

1. Go to Settings -> Appearance
2. Select IRC layout
3. Expand advanced options (under custom size). If it was *already* expanded, collapse it first.
4. Select Modern layout

#### What did you expect?

The "Use a more compact 'Modern' layout" checkbox should be toggleable.

#### What happened instead?

The checkbox instead cannot be toggled.

#### Workaround

Collapse and expand the options again while Modern is selected.

### Operating system

Debian Linux

### Browser information

Firefox 115.5.0esr (64-bit)

### URL for webapp

v1.11.48

### Application version

Element version: 1.11.48 Crypto version: Olm 3.2.15

### Homeserver

Dendrite v0.13.4

### Will you send logs?

No (`/rageshake` doesn't seem to do anything)

**Comment by dbkr** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/12125
