### ISSUE TITLE
Support browser font size settings

### ISSUE THREAD

**Issue by kerryarchibald** [element-hq/element-web#26669]
#### What would you like to do?
Set HTML base font size to 100% instead of 16px

#### How would you like to achieve it?
Note: Once we set the html element font size to 100%, we'll still need to make sure the text scales when using the slider in Settings > Appearance > Font size. We should honor both the browser font size plus the font size slider setting. For example, by setting html font size to something like calc(100% + 1px), calc(100% + 2px) and so on. We'd also need to change the values displayed in the slider to something relative, default instead of 16, large or +1 instead of 17, and so on.

### Additional context

https://github.com/vector-im/customer-retainer/issues/47

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/12246
