### ISSUE TITLE
Please add the function that auto-delete messages by timer.

### ISSUE THREAD

**Issue by DeeEi** [element-hq/element-web#26686]
### Your use case

I like the function that auto-delete messages by timer.
For example, I set the timer in chat room for 1 days.
The message should be auto-deleted tomorrow.

### Have you considered any alternatives?

I really hope that element can add this function and a lot of people need it.
Sometimes I talk about some privacy information with my friend.
And I always need to delete the messages by hand.
It's too troublesome.

**Comment by zahidhussain998** [comment]
plase asign me this issue?
