### ISSUE TITLE
Element-R: Occurence of messages encrypted with current outbound session marked with gray shield

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#26695]
https://github.com/matrix-org/element-web-rageshakes/issues/23323

**Comment by ara4n** [comment]
vdh says it's likely https://github.com/vector-im/element-web/issues/26526

**Comment by BillCarsonFr** [comment]
duplicate

**Comment by t3chguy** [comment]
@BillCarsonFr of which issue? Can you use the github syntax `Duplicate of #ISSUE_NUMBER` so all of our automation happens as expected. https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate#marking-duplicates

**Comment by BillCarsonFr** [comment]
Duplicate of https://github.com/element-hq/element-web/issues/26526
