### ISSUE TITLE
Incorrect/Old messages are prepended to the current day and room is unexpectedly moved to `Historical `

### ISSUE THREAD

**Issue by langleyd** [element-hq/element-web#26716]
Observed:
2 Users reported an incorrect/old(6 months previous)  message being prepended to the current day's messages in place of the correct historical timeline events.

1 of the users also reported that the room was placed under `Historical` until they rejoined the room to fix it.

Expected:
The correct historical events are loaded on back pagination.

The messages in questions in `This week in Matrix` room are [here](https://matrix.to/#/!QQpfJfZvqxbCfeDgCj:matrix.org/$-BUbDsaU4cKfoA_pXNnuMD9-zBdRvti9jZo4COSysEI?via=matrix.org&via=envs.net&via=beeper.com).

**Comment by t3chguy** [comment]
@langleyd can you please fill the issue template, without versions, logs, etc its not going to be feasible to dig into this.

**Comment by t3chguy** [comment]
Hi, I'm going to close this issue for now as there is not enough info here for us to be able to action it. Please feel welcome to reopen or ask me to reopen the issue if you update the description with steps/screenshots/video/more details so our developers can have a look at it.
