### ISSUE TITLE
unread notifications in threads ineffective/difficult to use.

### ISSUE THREAD

**Issue by syadnom** [element-hq/element-web#26726]
### Steps to reproduce

essentially background task, do nothing to reproduce except wait around for people to chat in threads.  Client shows unread messages indicator but cannot find unread messages in client anywhere.

### Outcome

Some method to jump to unread threads easily.  It's very difficult to follow along on threaded conversations when the unread notifications are non-functional

### Operating system

macos, windows

### Application version

always current to date of post

### How did you install the app?

download from matrix.org featured clients

### Will you send logs?

Yes

**Comment by ronnyaa** [comment]
was going to submit the same issue.  but probably better to just comment here. 
It is very hard to find the right thread with the unread message.  you have to scroll for days to find the small dot. 

perhaps an addition to the top right dropdown that today contain "All threads" and "My threads"  to also have the entry "unread threads"  

Element version: 1.11.51
Crypto version: Olm 3.2.15

I can send logs if any are requested but the feature request is self evident in any larger room with many active threads.

**Comment by dimm0** [comment]
Same here. Old threads are randomly becoming unread, need to scroll for tens of threads to find one. The global channel "Mark as read" sometimes doesn't work (sometimes works), but after that new threads are becoming unread.

**Comment by ronnyaa** [comment]
tens ? i have some hundreds, and it takes an hour to scroll thru them all to hunt the small white dot's that are scattered around. 99% of them are just old threads with nothing new in them.   

It seems to be a bigger issue in rooms with bridges.  but the request is mostly about how to deal with it when it have   happened, then to stop it from happening.   hence a filter to show only threads with unread, or a way to mark all threads as read. or preferably both :)
  
what kind of info is needed ?

**Comment by t3chguy** [comment]
Closing due to lack of response on the 2 prompts

**Comment by ronnyaa** [comment]
It was not my original issue. but i can provide info if that is needed. 

not sure what logs are needed on a feature request. but the element version i use is 
Element version: 1.11.65
Crypto version: Olm 3.2.15

Basically any method to find the threads with unread messages in them. 
![image](https://github.com/element-hq/element-web/assets/80334347/1a58b324-b0d9-4de5-b557-e0f957165d1b)

on the top dropdown a "unread threads" would work. 

a bonus would be a "mark all threads read" to mark all as read on this matrix room.
