### ISSUE TITLE
ElementR: Key Storage | When adding a new key to 4S the key encryption check is not added to the key info

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#26721]
As per [spec](https://spec.matrix.org/v1.8/client-server-api/#msecret_storagev1aes-hmac-sha2), when adding a new key to the secret storage the client must encrypt a "zero"/dummy secret to allow for key checks.
WebR is not doing it

Actual:
```
{
  "type": "m.secret_storage.key.abcdef",
  "content": {
    "algorithm": "m.secret_storage.v1.aes-hmac-sha2",
    "passphrase": { ... },
  }
} 
```

Expected:
```
{
  "type": "m.secret_storage.key.abcdef",
  "content": {
    "algorithm": "m.secret_storage.v1.aes-hmac-sha2",
    "passphrase": { ... },
    "iv": "2ZB0AAR+nsEoaX4owqA7ag==",
    "mac": "Wf6C9nDzIESogoikSW7uLJjDSU+BKtqpe/7tRMi/Y7E="
  }
} 
```

As a consequence if you try to use the key on EX (that is more strict) it will fail with `(UnsupportedAlgorithm("m.secret_storage.v1.aes-hmac-sha2"))` if you try to verifiy with a key generated from webR

**Comment by richvdh** [comment]
> As per [spec](https://spec.matrix.org/v1.8/client-server-api/#msecret_storagev1aes-hmac-sha2), when adding a new key to the secret storage the client must encrypt a "zero"/dummy secret to allow for key checks.

It is incorrect that it *must* do that. It is optional.
