### ISSUE TITLE
Old discussion suddenly started generating new notiifcations

### ISSUE THREAD

**Issue by mcclure** [element-hq/element-web#26731]
### Steps to reproduce

In a private chat room, I was trying to file a bug for #26719. With the tab open, I rebooted Chrome.

When I came back, I found the private room showed 25 notifications. There is a red
![image](https://github.com/element-hq/element-web/assets/277318/c5c2f890-678b-40fa-bc8b-1d1f268367a6)
next to it. No one has spoken in the channel since yesterday at 4 PM. After scrolling upward in the chat a bit, it moved continuously upward, eventually higher than a hundred. I can reload the page and it goes back down to 25, but scrolling upward or just waiting causes it to rise again. Looking at the chat is not causing the badge to dismiss like usual.

I see this in the up right of the chat

![image](https://github.com/element-hq/element-web/assets/277318/1489a23c-fb19-49f9-bbc5-2a1394906bcf)

Clicking the ^ symbol causes the entire page to go white

![image](https://github.com/element-hq/element-web/assets/277318/0bf51eca-4bc0-4b27-a3d8-24569b9c1924)

The little X has a "mark all as read" tooltip, but it doesn't do anything when I click on it

### Outcome

Expected behavior: None of the above should be occurring, there are no unread messages in this channel

### Operating system

Windows 10

### Browser information

Chrome 120.0.6099.71 , uBlock Origin but it says it's blocking nothing on app.element.io

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.11.51 Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by mcclure** [comment]
It says "Logs Sent Thank You"

**Comment by mcclure** [comment]
Note, the Android app does not show any unread messages for the same channel

**Comment by t3chguy** [comment]
This is tracked under https://github.com/vector-im/element-web/issues/24392
