### ISSUE TITLE
Room scroll state is broken mk2

### ISSUE THREAD

**Issue by greentore** [element-hq/element-web#26759]
### Steps to reproduce

Follow-up to https://github.com/element-hq/element-web/issues/25810
Room scroll position isn't properly maintained again since Element v1.11.50 (matrix-react-sdk v3.85.0). I confirmed it works properly in v1.11.49.
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/01e7e01153300b5f6dd118d2051b603fa50a38e8 / https://github.com/matrix-org/matrix-react-sdk/pull/11799
More specifically, the issue goes away if you comment out `dis.dispatch<ActionPayload>({ action: Action.RoomLoaded });` in `src/components/structures/RoomView.tsx`, but obviously the real bug is somewhere deeper.

#### What did you expect?
The room's scroll position is restored.

#### What happened instead?
The room's scroll position is restored only to scroll to the bottom a moment later.

### Will you send logs?

No

**Comment by florianduros** [comment]
My analysis:

1. The https://github.com/matrix-org/matrix-react-sdk/pull/11799 PR added the dispatch of a new event [`Action.RoomLoaded`](https://github.com/matrix-org/matrix-react-sdk/blob/088710811d43090c72a4b1ca50fd90fdd25fe6b7/src/components/structures/RoomView.tsx#L1411)
2. This event is catched by the [`RoomViewStore`](https://github.com/matrix-org/matrix-react-sdk/blob/088710811d43090c72a4b1ca50fd90fdd25fe6b7/src/stores/RoomViewStore.tsx#L378) and the [`RoomViewStore is updated`](https://github.com/matrix-org/matrix-react-sdk/blob/088710811d43090c72a4b1ca50fd90fdd25fe6b7/src/stores/RoomViewStore.tsx#L835)
3. This update triggers an extra call of `RoomView#onRoomViewStoreUpdate`. 
4. However `RoomView#onRoomViewStoreUpdate` was already called when the `RoomView` component was mount. The `newState.initialEventId` field [is computed only on the first call of `RoomView#onRoomViewStoreUpdate`](https://github.com/matrix-org/matrix-react-sdk/blob/088710811d43090c72a4b1ca50fd90fdd25fe6b7/src/components/structures/RoomView.tsx#L788)
5. `RoomView#state.initialEventId` is `undefined` and the `TimelinePanel` position is set to the end
