### ISSUE TITLE
No chat right hand panel with new room header

### ISSUE THREAD

**Issue by toger5** [element-hq/element-web#26764]
The new room header does not give the option to show the chat right panel with fullscreen widgets or a Element Call.

**Comment by daniellekirkwood** [comment]
<img width="1071" alt="Screenshot 2023-12-15 at 09 20 53" src="https://github.com/element-hq/element-web/assets/89144281/af55f752-6f82-41d3-a240-f919c5ef08fa">

i see this with an expanded widget and the new room header - is this not what you mean?

**Comment by toger5** [comment]
> is this not what you mean?

I am not sure how exactly you reached this view. My issue is, that I cannot toggle the chat. If its open its always open. If its closed, I cannot open it.

For calls in particular (which are also widgets) It starts with the chat closed -> no way to open it.
For actual widgets it might have some "default to chat beeing open" logic which makes it less broken.

**Comment by toger5** [comment]
This is only part in video rooms but not element calls in normal rooms. So the issue is still relevant and the linked PR should take care of it.
