### ISSUE TITLE
Clicking a message link does not highlight the message that it jumps to

### ISSUE THREAD

**Issue by K4LCIFER** [element-hq/element-web#26768]
### Steps to reproduce

1. Copy a message link (triple dots, share, copy link)
2. Send the link in chat
3. click on it
4. observe that, after the jump, it doesn't highlight the message.

#### What did you expect?

I would expect that the message would get highlighted

#### What happened instead?

It jumped without a highlight

### Operating system

Arch Linux, Kernel v6.6.7-arch1-1

### Application version

Element version: 1.11.51 Crypto version: Olm 3.2.15

### How did you install the app?

Flatpak

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Cannot reproduce

<img width="1055" alt="image" src="https://github.com/element-hq/element-web/assets/2403652/93746455-8070-4820-9843-ea541bfdd5e5">

The version of Element you are using is unsupported, https://github.com/flathub/im.riot.Riot/ for issues with the Flatpak

**Comment by K4LCIFER** [comment]
> Cannot reproduce

I have since found that this issue was a mistake on my part. I changed Element's theme, and I think I just accidentally overlooked the link highlight.
