### ISSUE TITLE
All threads in some rooms stuck as unread

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#26765]
### Steps to reproduce

Steps unclear.

#### What did you expect?

"Mark as read" to mark the room as read.

#### What happened instead?

For Element Web/Desktop, Matrix HQ, and Element X Android, all of my threads have a dot but zero messages unread. No amount of marking the room as read helps, and neither does looping over them in the js console to try and mark them read that way. The issue persists through reloads (it can take a while to actually trigger though - roughly 8ish hours)

![image](https://github.com/element-hq/element-web/assets/1190097/8ad2e782-7da1-4067-a673-a442da982501)

*Possibly* related to https://github.com/element-hq/element-web/issues/25480

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023121201 Crypto version: Olm 3.2.15

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by daniellekirkwood** [comment]
I believe this has been fixed recently and the new changes with the TAC should also address this issue, thoughts @dbkr @langleyd @florianduros ?

**Comment by florianduros** [comment]
> I believe this has been fixed recently and the new changes with the TAC should also address this issue, thoughts @dbkr @langleyd @florianduros ?

You are right

**Comment by langleyd** [comment]
We believe this to be fixed
