### ISSUE TITLE
Share screen button dose not work

### ISSUE THREAD

**Issue by Foox-dev** [element-hq/element-web#26777]
### Steps to reproduce

I press the share screen button in the call panel and it dose nothing

#### What did you expect?
It to share my screen to my friend

#### What happened instead?
nothing (maybe a little bit of lag)

### Operating system

Windows 11

### Application version

Element version: 1.11.51

### How did you install the app?

https://element.io/app-for-productivity

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Will you send logs?
Yes

Not seeing any logs from you.

**Comment by Thatoo** [comment]
I face a more subtil issue.
I can share unless I have cancel when choosing what screen/app I wanted to share, then the button stops working.

**Comment by t3chguy** [comment]
@Thatoo sounds like https://github.com/element-hq/element-desktop/issues/1367

Closing this issue due to lack of requested logs.
