### ISSUE TITLE
Missing room search

### ISSUE THREAD

**Issue by jtojnar** [element-hq/element-web#26781]
### Steps to reproduce

1. Click Search box (<kbd>Ctrl</kbd>-<kbd>K</kbd>)
2. Type some text
3. Notice the instructions saying:
![To search messages, look for this icon at the top of a room](https://github.com/element-hq/element-web/assets/705123/7367908b-18bb-4c2f-b57e-e7f8e7492b8f)

#### What did you expect?

The search button should be present as mentioned in the hint.

#### What happened instead?

No button is in the header bar:

![](https://github.com/element-hq/element-web/assets/705123/93f95ef1-b07a-4879-8e79-75cb98f3230f)

### Operating system

NixOS Linux

### Browser information

Firefox 120.0.1

### URL for webapp

develop.element.io

### Application version

Element version: e9f0a8cddc19-react-7508e62eda8b-js-68898aeff2c5

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by jtojnar** [comment]
Never mind, found the instructions in https://github.com/element-hq/element-web/issues/25883. I need to click the channel title in the header bar, which will open a side panel containing the button.

**Comment by t3chguy** [comment]
Develop uses the experimental new room header which has different instructions, they will be updates as part of delabsing.

**Comment by denschub** [comment]
@t3chguy given the new room header is out of beta, and the instructions were *not* updated - can we reopen this bug, or should I file a new one?

**Comment by t3chguy** [comment]
Please open a new one, reopening this would not send it through the triage properly and it wouldn't get handled as it should.
