### ISSUE TITLE
ElementR keeps re-uploading the same set of keys to backup?

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#26782]
https://rageshakes.element.io/api/listing/2023-12-18/103011-ZTCQB6U3/logs-0000.log.gz

```
2023-12-18T10:25:19.180Z I INFO matrix_sdk_crypto::backups: Successfully created a room keys backup request
 key_count=100 keys={"!LDsvXjAOHNvAHItERH:matrix.org": {"/3hJH4D8r9Va7dH9PDSgI4HX960v3ujcA3ps0LfpJU4": {"IRy0EZ9Y27MAx3f0JpkNrq2rYw0TgZ3WOPmMeXsc1Kc"}, 
```

```
2023-12-18T10:26:16.937Z I INFO matrix_sdk_crypto::backups: Successfully created a room keys backup request
    key_count=100 keys={"!LDsvXjAOHNvAHItERH:matrix.org": {"/3hJH4D8r9Va7dH9PDSgI4HX960v3ujcA3ps0LfpJU4": {"IRy0EZ9Y27MAx3f0JpkNrq2rYw0TgZ3WOPmMeXsc1Kc"}, 
```

```
2023-12-18T10:27:37.813Z I INFO matrix_sdk_crypto::backups: Successfully created a room keys backup request
    key_count=100 keys={"!LDsvXjAOHNvAHItERH:matrix.org": {"/3hJH4D8r9Va7dH9PDSgI4HX960v3ujcA3ps0LfpJU4": {"IRy0EZ9Y27MAx3f0JpkNrq2rYw0TgZ3WOPmMeXsc1Kc"}, 
```

```
2023-12-18T10:28:15.442Z I INFO matrix_sdk_crypto::backups: Successfully created a room keys backup request
    key_count=100 keys={"!LDsvXjAOHNvAHItERH:matrix.org": {"/3hJH4D8r9Va7dH9PDSgI4HX960v3ujcA3ps0LfpJU4": {"IRy0EZ9Y27MAx3f0JpkNrq2rYw0TgZ3WOPmMeXsc1Kc"}, 
```

```
2023-12-18T10:28:52.980Z I INFO matrix_sdk_crypto::backups: Successfully created a room keys backup request
    key_count=100 keys={"!LDsvXjAOHNvAHItERH:matrix.org": {"/3hJH4D8r9Va7dH9PDSgI4HX960v3ujcA3ps0LfpJU4": {"IRy0EZ9Y27MAx3f0JpkNrq2rYw0TgZ3WOPmMeXsc1Kc"}, 
```

etc..

**Comment by robintown** [comment]
@BillCarsonFr  / @richvdh Has this fix actually made it into Element Web yet? Two weeks later, I'm seeing what appears to be the same issue judging from the console logs and high CPU usage of my client.

**Comment by andybalaam** [comment]
Me too. It has not made it yet.

For my own reference: [the fix](https://github.com/matrix-org/matrix-rust-sdk/pull/2957) was merged on 21st Dec 2023, and the [latest release](https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/releases/tag/v3.5.0) of matrix-rust-sdk-crypto-wasm was on 15th Dec 2023, and this is still what is referred to in matrix-js-sdk's [package.json](https://github.com/matrix-org/matrix-js-sdk/blob/develop/package.json#L55).

**Comment by andybalaam** [comment]
I think I saw a comment from @richvdh that he was planning a release of matrix-rust-sdk-crypto-wasm soon. If not, I can do one.

**Comment by richvdh** [comment]
Sorry, I shouldn't have let this be closed until the dependency on matrix-rust-sdk-crypto-wasm was updated.

**Comment by richvdh** [comment]
cc @toger5 who I think was also complaining about this recently

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/3989 was reverted
