### ISSUE TITLE
Read receipts are falling from the sky again

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#26798]
### Steps to reproduce

1. Send a message.
2. Someone reads it.
3. Send another message.
4. Same person reads it, but this time their read receipt comes from the heavens.

#### What did you expect?

A suitbly small gap between read receipt positions should be a smooth transition.

#### What happened instead?

The read receipt flies in despite starting 16px above the target. Typically this has meant the read receipt velocity code has lost track of where "previous" was, or the DOM changed in an incompatible way.

Started happening 2 nightlies ago.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023122101 Crypto version: Olm 3.2.15

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by bmarty** [comment]
I also noticed this and was about to report an issue. For once I found the existing issue doing a GitHub search. This behavior is a bit disturbing.

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/12063
