### ISSUE TITLE
Threads not showing in sidebar

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26799]
### Steps to reproduce

Sometimes, threads which are shown in the timeline do not appear in the sidebar.

Example, timeline shows this:

![image](https://github.com/element-hq/element-web/assets/1389908/341c2f80-5c7c-4ebd-b550-81f0198df2e2)

... but there is no sign of that thread in the sidebar

#### What did you expect?

Threads should appear in the sidebar

#### What happened instead?

Some threads are missing

### Operating system

Ubuntu

### Application version

Element Nightly 1234 version: 2023122001 Crypto version: Rust SDK 0.6.0 (438880a), Vodozemac 0.5.0

### How did you install the app?

nightly debian

### Homeserver

synapse 1.96

### Will you send logs?

No

**Comment by richvdh** [comment]
This is still happening intermittently, by the way.

**Comment by dbkr** [comment]
I can reproduce this reliably, I'll take a look.

**Comment by dbkr** [comment]
This doesn't appear to be a regression from app at least in that I can repro the same behaviour on app.element.io. Right now I can't see any evidence that it has ever worked at all.

Repro steps:

1. Get an Element Web and another login in something
2. Load element web, open a room, open the threads panel.
3. Send a message in that room in your other client.
4. Send a threaded reply to that message in your other client.
5. Open the threads panel in other client, observe that the thread has appeared.
6. Open the threads panel in EW. Observe that the thread has not appeared.
