### ISSUE TITLE
People count has gone missing

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#26800]
### Steps to reproduce

1. Search the UI to see how many people are in a room

#### What did you expect?

We used to have a number on the Info card that said how many people were there.

#### What happened instead?

That number seems to have gone missing. I have no idea how many people are in a given room.

### Operating system

Windows 11

### Application version

Nightly

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
Its now in the New Room Header (labs, default on for develop), the new right panel redesign doesn't really make sense with it off which is unfortunate due to the project stalling

<img width="1063" alt="image" src="https://github.com/element-hq/element-web/assets/2403652/0437a900-130d-43a0-9d59-aa83b7d60e1c">

**Comment by turt2live** [comment]
for some reason the new room header is disabled for me - that would be it.

**Comment by t3chguy** [comment]
Its only enabled on Develop, not Nightly, for whatever product testing reason

**Comment by turt2live** [comment]
oh. 

well, that's an interesting choice. I'd encourage us to make a decision that retains the people count :p

**Comment by turt2live** [comment]
Mentioned in #element-web, the count is available from the room name context menu on the old header design:

![image](https://github.com/element-hq/element-web/assets/1190097/88ef5ec5-fa4e-4cd0-8bd0-872f7fa34993)
