### ISSUE TITLE
Unexpected online status

### ISSUE THREAD

**Issue by rda0** [element-hq/element-web#26803]
### Steps to reproduce

1. Use Element actively
2. Continue to work productive on the same computer while not using Element actively, but still leaving it open on screen.

#### What did you expect?

Others see me as online (green)

#### What happened instead?

After some minutes (2?) others see me as away (yellow)

### Operating system

Linux, Windows

### Application version

D-PHYS Element Labs version: 1.11.52 Crypto version: Olm 3.2.15

### How did you install the app?

deb package, msi, tar.gz

### Homeserver

phys.ethz.ch

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please send logs

**Comment by rda0** [comment]
OK, I will do next year.

Happy holidays and thank you for Element/Matrix 👍❄️🚀

**Comment by rda0** [comment]
Logs sent from Element Desktop Linux

**Comment by t3chguy** [comment]
Both clients are definitely sending the unavailable presence state

![image](https://github.com/element-hq/element-web/assets/2403652/ec97c8ad-3d42-40b9-b9f1-657ed3aa55f2)

Seems like your problem is elsewhere.
