### ISSUE TITLE
Disabled Playwright test "Should show a grey padlock for a key restored from backup"

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26811]
https://github.com/matrix-org/matrix-react-sdk/blob/develop/playwright/e2e/crypto/crypto.spec.ts#L434-L435

@t3chguy please can you not just disable tests - especially those covering the crypto stack - without at least filing issues about them?

**Comment by t3chguy** [comment]
@richvdh wasn't this already discussed in #element-dev and @MidhunSureshR is already on it?

https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$foNLem3fuaam602PuzlMRzFHd8tN-XmuZsmbcjoDWOE?via=matrix.org&via=element.io&via=envs.net

**Comment by richvdh** [comment]
Yes, but that was two weeks ago. If work is immediately happening on a bug then it's reasonable to skip the tracking issue, but if other priorities get in the way then we should have a tracking issue.

**Comment by t3chguy** [comment]
I suggest chasing that with the person on that project, I've been off the Playwright project for 2-3 weeks at this point.

**Comment by richvdh** [comment]
I'm just asking that, in future, anyone who disables a test makes sure that there is a tracking issue for it.
