### ISSUE TITLE
Option to disable searching/browsing for public groups & profiles

### ISSUE THREAD

**Issue by RasheedAZ** [element-hq/element-web#26813]
### Your use case

Hi all. Would it be possible to add an option to disable browsing public Matrix rooms, spaces and profiles? 

I'm a school teacher and have migrated my students to FOSS options like Linux, Firefox, LibreOffice, etc and am trying to do the same for communication on Matrix. However, most of the students need the option to disable NSFW stuff from appearing, so many of the public rooms and profiles that show up in the search are a problem in that regard and many of them are not even marked 18+. 

A simple disable toggle for searching or browsing public groups and profiles would be enough for most students, and it should hopefully be easy to implement. 

With it disabled, Element web and desktop could function like email clients in that you would need to know the exact address to communicate with a user or join a group. That way it'll be relatively safer for kids and we can onboard a new generation of Matrix users :)

Thanks for considering this!

### Have you considered any alternatives?

Yes, tried other clients... Thunderbird looks great for this except that it doesn't have Matrix calling feature so it will deter users from migrating from Google Meet, Zoom, etc. We need a cross platform, feature complete client to promote and Element appears to be one of the very few that could  fulfil this need.

**Comment by t3chguy** [comment]
@RasheedAZ this would be a setting on your server, not a client. If it was set on the client the student could just use a different Matrix client or Element instance (e.g. Element Desktop) to get around it.
