### ISSUE TITLE
Microphone dropdown doesn't work In legacy call 

### ISSUE THREAD

**Issue by muratersin** [element-hq/element-web#26824]
### Steps to reproduce

1. Call a friend
2. When in ringin or ongoing call try to change microphone or camera

<img width="197" alt="image" src="https://github.com/element-hq/element-web/assets/12091220/c7b01822-9924-4922-9232-e38e859d3388">

#### What did you expect?
opening list of microphone or camera

#### What happened instead?
Nothing. Couldn't access to microphone or camera list and can't change its.

### Operating system

Windows 11

### Browser information

Chrome Version 120.0.6099.130

### URL for webapp

https://develop.element.io

### Application version

Element version: 8ea729e98f19-react-def4b728d06a-js-ffc9fb34d057 Crypto version: Rust SDK 0.6.0 (438880a), Vodozemac 0.5.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/12054
