### ISSUE TITLE
não funciona a busqueda nas mensagens 

### ISSUE THREAD

**Issue by lisandrovb** [element-hq/element-web#26829]
### Steps to reproduce

sempre que tentamos buscar alguma palavra chave nas mensagens sejam privadas ou das salas não entrega nenhum resultado, não funciona em absoluto, ja tentamos consertar seguindo as indicações das ajudas de vocês para esse problema porem não deu resultado seguimos com o mesmo problema

### Outcome

ajuda!

### Operating system

todos

### Application version

versão do Element: 1.11.52 Crypto version: Olm 3.2.15

### How did you install the app?

element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This issue tracker is English only, please open a new issue in English.
