### ISSUE TITLE
crashes after clicking on recently visited chat at the toolbar

### ISSUE THREAD

**Issue by danijel1124** [element-hq/element-web#26836]
### Steps to reproduce

1. Where are you starting? What can you see?
I'm currently on the homepage. I see my spaces, four pieces, and I think a supspace.
2. What do you click?
Now I click on any chat in the bar where the most recently visited chats are listed. I haven't changed any settings.
3. More steps...
No, instead of loading the chat as normal, the screen appears with the message that Element has gone into eternal void.

#### What did you expect?
should load the requested chatroom
#### What happened instead?
crashes

### Operating system

windows 11

### Application version

1.8.5

### How did you install the app?

generated portable-app

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Application version
1.8.5


We don't support versions which are 846 days old.
