### ISSUE TITLE
I modified the room settings, but I still can't get new members to see the previous messages

### ISSUE THREAD

**Issue by lisandrovb** [element-hq/element-web#26834]
### Steps to reproduce

I modified the room settings, but I still can't get new members to see the previous messages

### Outcome

solution urgent!

### Operating system

linux mint

### Application version

versão do Element: 1.11.53 Crypto version: Olm 3.2.15

### How did you install the app?

element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is an issue tracker, not a support room. Try #element-web:matrix.org if you want support, if you have reproduction steps and can fill the template then open a new issue.
