### ISSUE TITLE
Can't set identity server

### ISSUE THREAD

**Issue by mikezackles** [element-hq/element-web#26833]
### Steps to reproduce

I'm hoping there's just a configuration issue somewhere. I have a self-hosted synapse instance running behind cloudflare using their proxying. The federation tester finds no issues, and thus far I haven't found any indication of issues in my proxy logs. The latest Arch package of element-web (1.11.52-1) is running on a different subdomain. Note that the same issues happen with both element-web and element-desktop.

I have verified an email address, but I cannot set `vector.im` as the identity server.

I can see requests made to `vector.im`:
![vector im](https://github.com/element-hq/element-web/assets/77851/f18d64a0-66a4-4348-b59b-05510c80ecbd)

The 403 seems to just indicate that I need to sign the TOS, for which I get a dialog:
![tos](https://github.com/element-hq/element-web/assets/77851/669dfff1-488f-45c1-9a32-b9edd4d92fe6)

Note that there is only a checkbox for privacy and not terms of service as I think I've seen in another screenshot.

### Outcome

 After agreeing to the privacy notice, I get this error:
![error](https://github.com/element-hq/element-web/assets/77851/9b8bd062-5f41-4da5-b021-961500be25ea)

`homeserver.yaml`:
```
server_name: mydomain.com
public_baseurl: https://matrix.mydomain.com
default_identity_server: https://vector.im
```

`.well-known/matrix/client`:
```
{
    "m.homeserver": {
        "base_url": "https://matrix.mydomain.com"
    },
    "m.identity_server": {
        "base_url": "https://vector.im"
    }
}
```

Additionally I am getting a sync error every 5 syncs or so. It seems unrelated, but I'm including for completeness. According to the matrix logs the client disconnects prematurely:
```
Jan 05 08:22:39 matrix synapse[7322]: 2024-01-05 08:22:39,988 - synapse.http.site - 377 - INFO - GET-131 - Connection from client lost before response was sent
Jan 05 08:22:39 matrix synapse[7322]: 2024-01-05 08:22:39,997 - synapse.rest.client.sync - 224 - INFO - GET-131 - Client has disconnected; not serializing response.
Jan 05 08:22:39 matrix synapse[7322]: 2024-01-05 08:22:39,997 - synapse.http.server - 776 - WARNING - GET-131 - Not sending response to request <XForwardedForRequest at 0x6fcda41e3910 method='GET' uri='/_matrix/client/v3/sync?filter=0&timeout=30000&set_presence=online&since=s229_17231_0_121_331_1_124_30_0_1' clientproto='HTTP/1.1' site='unix'>, already disconnected.
```
Cloudflare then times out waiting for a response that doesn't come.

Note that I tried `/rageshake` and it didn't work, but I'm probably missing something simple.

Thanks in advance for any help!

### Operating system

Arch Linux

### Browser information

firefox 120.0.1 chrome 120.0.6099.109

### URL for webapp

1.11.52

### Application version

1.11.52

### Homeserver

Synapse 1.95.1

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/10984
