### ISSUE TITLE
Context menu for search results in room search dialog is behind the dialog.

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#26839]
### Steps to reproduce

1. Open the room search dialog with Ctrl-K
2. Search for a room name
3. Click the context menu button "..." on the right of a search result

#### What did you expect?

I expected to see and be able to click the context menu items

#### What happened instead?

![image](https://github.com/element-hq/element-web/assets/76812/4fffee8e-e48f-4ca2-a467-8c94a4e033fb)

The context menu appeared behind the dialog and I was not able to click items in it

### Operating system

Ubuntu 22.04

### Browser information

Firefox 119.0.1

### URL for webapp

https://develop.element.io

### Application version

Element version: 922f16812cc2-react-82840a19f9ce-js-a597a9d660da Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
![image](https://github.com/element-hq/element-web/assets/2403652/0aa60684-3e86-458e-a6c0-1b24848d5a6b)

Cannot reproduce.

**Comment by andybalaam** [comment]
It appears to work fine in Chromium, so I'm guessing this is Firefox-specific.

**Comment by t3chguy** [comment]
Turns out it only happens if you open a context menu before opening spotlight

**Comment by andybalaam** [comment]
> Turns out it only happens if you open a context menu before opening spotlight

Nice spot!

**Comment by andybalaam** [comment]
Confirmed fixed; thank you.
