### ISSUE TITLE
Maunium sticker widget broken in v1.11.54-rc.0

### ISSUE THREAD

**Issue by finnurthorisson** [element-hq/element-web#26853]
### Steps to reproduce

1.11.53
![mynd](https://github.com/element-hq/element-web/assets/153488719/7dd414d3-64d3-413b-832a-4f419a577017)

1.11.54-rc.0
![mynd](https://github.com/element-hq/element-web/assets/153488719/31ec9408-e57b-43d4-8db3-60427798c367)

#### What did you expect?
Stickers to show up as in 1.11.53 and before

#### What happened instead?
Borked. The <iframe> is pushed down almost entirely

### Operating system

Arch Linux

### Browser information

LibreWolf 119.0.1-1

### URL for webapp

1.11.54-rc.0

### Homeserver

Synapse 1.98.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/12126
