### ISSUE TITLE
ElementR: Import backup progress doesn't report progress when decrypting

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#26856]
## Step to reproduce

- Have an account with a "big" backup
- Login, verify
- Go to settings and click on Restore from backup

## Expected
- It should download the encrypted backup and report that it's fetching from server
- When download is complete ER should report that server fetch is done and that it's decrypting/importing keys

## Actual

- After the download, the keys are beeing decrypted but the progress status is not updated until all keys have been decrypted
<img width="783" alt="image" src="https://github.com/element-hq/element-web/assets/9841565/b37d404b-dbd3-4c7b-a818-bc66430d81f3">

While the sdk is actually decrypting the keys:
https://github.com/matrix-org/matrix-js-sdk/blob/8df30ed068997aa74f21aa5be3c8df30f7dd07c5/src/client.ts#L3938-L3947

But progress step is still `fetch`

https://github.com/matrix-org/matrix-js-sdk/blob/8df30ed068997aa74f21aa5be3c8df30f7dd07c5/src/client.ts#L3923-L3927

So it's like there is no progress, and this operations can be 10s of minutes

**Comment by richvdh** [comment]
somewhat related: https://github.com/element-hq/element-meta/issues/2176

**Comment by BillCarsonFr** [comment]
related https://github.com/element-hq/element-web/issues/23359
