### ISSUE TITLE
Public subspace not being listed even when member of a room within

### ISSUE THREAD

**Issue by deepadmax** [element-hq/element-web#26855]
### Steps to reproduce
I'm a member of a private room. This room is in a subspace of a space of which I'm currently a member. E.g. **Space&nbsp;(joined)** / **Subspace&nbsp;(not&nbsp;joined)** / **Private&nbsp;room&nbsp;(joined)**. The subspace is public though the rooms within require invitation.

I searched in the space for the subspace but it wasn't being listed. After somebody linked me to the subspace and I had joined that way, it did show up in the space.

#### What did you expect?
I expected that since I was in one of the rooms of that subspace (and the subspace is public), the subspace would've been listed in the space to be joined from there.

#### What happened instead?
It wasn't being listed.

### Operating system
Manjaro Linux

### Application version
Element Nightly: 2024010802, Olm: 3.2.15

### How did you install the app?
yay -S element-desktop-nightly-bin

### Homeserver
Synapse 1.98.0

### Will you send logs?
No

**Comment by t3chguy** [comment]
The list is built by your server and served over the `/hierarchy` API - I suggest asking Synapse for help

**Comment by deepadmax** [comment]
While writing an issue for Synapse, I thought I'd go through the steps again; I left the subspace and searched for it. This time, it decided to show up. I haven't updated my server. So I'm thinking it *could* still be a bug in Element. It could be a bug in Synapse, but reading what's required to be filled in for the issue, I don't think I'm qualified enough to be useful. 

_(Also: the links to documentation in the [bug report template](https://github.com/element-hq/synapse/issues/new?assignees=&labels=&projects=&template=BUG_REPORT.yml) lead to nowhere.)_

**Comment by t3chguy** [comment]
Closing as believed to not be an Element issue.
