### ISSUE TITLE
Composer input field misaligned with shield

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#26851]
### Steps to reproduce

1. In an encrypted room where someone is using an unknown session
2. The red shield is not aligned with the input entry box of the composer

(I think this has been around for several weeks. Apologies for the delay reporting it)

#### What did you expect?

The shield to be vertically centred relative to the input box.

#### What happened instead?

![image](https://github.com/element-hq/element-web/assets/76812/42259654-b473-43ed-93b6-28688275707a)

### Operating system

Ubuntu 22.04

### Browser information

Recent Firefox and Chromium

### URL for webapp

https://develop.element.io

### Application version

Element version: 9ea88438f965-react-1333456fc82b-js-49624d5d7308 Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by nadonomy** [comment]
@dbkr I came to report this bug but I'm surprised it's triaged as severity tolerable (the defect is extremely visible) and occasional (it effects all shields - so _everyone_ sees it).

Imo this should be a release blocker even.

**Comment by t3chguy** [comment]
Release blocker has a defined bar - https://handbook.element.io/books/element-web-team/page/release-blockers - this would not qualify even being bumped to S-Minor & O-Frequent

**Comment by Cyberes** [comment]
So it will never get fixed?

**Comment by t3chguy** [comment]
@Cyberes if it was to never be fixed then the issue would be closed.

**Comment by nadonomy** [comment]
> Release blocker has a defined bar - https://handbook.element.io/books/element-web-team/page/release-blockers - this would not qualify even being bumped to `S-Minor` & `O-Frequent`

Thx for the pointers on the new processes. I think something is broken somewhere wise if the sum of the stated processes is visible low hanging fruit like this ships to production. The app is visibly broken, to everyone.

What's the best way for us to take more of a common sense approach on this kind of stuff?

**Comment by t3chguy** [comment]
> What's the best way for us to take more of a common sense approach on this kind of stuff?

The bar was set by the last EM, I suggest speaking to the new EM about it
