### ISSUE TITLE
Self-redacted message still appears in room list preview

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#26866]
### Steps to reproduce

1. Send a message in a room
2. Redact it (potentially from a different device?)
3. Look at the roomlist preview
4. See it leaks the redacted message contents still.

#### What did you expect?

Hide redacted content.

#### What happened instead?

Leaked redacted content.

### Application version

today's nightly

### Will you send logs?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/element-hq/element-web/issues/17893
