### ISSUE TITLE
Migrating to IndexeddbCryptoStore Version 8 takes 5 minutes and doesn't warn you that it's doing a migration.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#26865]
### Steps to reproduce

1. Upgrade nightly to 2024011101
2. Stare at a spinner for 5 minutes
3. Assume the app has crashed
4. Turns out it was doing a migration; it's a fluke i didn't give up and force-quit the app and start over.
See also 

#### What did you expect?

If the app is doing a migration which might take a long time it *MUST* tell the user (even with a simple msg on the launch screen) that it's upgrading itself and that the user should be patient.  Ideally it'd provide a progress bar too.

#### What happened instead?

No user feedback at all.

### Application version

2024011101

### Will you send logs?

No

**Comment by BillCarsonFr** [comment]
We will add a migration UX before doing a new big migration.
