### ISSUE TITLE
Session Data Missing

### ISSUE THREAD

**Issue by F13** [element-hq/element-web#26874]
### Steps to reproduce

My system began to hang; I have no idea if this was related to Element or not. I forcibly shut down my computer, then restarted it. I updated all packages (element-desktop was not among those to be updated) and did a clean shutdown. On next power up, I opened Element, and was given the Session Data Missing error message.

I have no idea if this is reproduce-able or if it's even really a bug, but I wanted to submit just in case.

#### What did you expect?
I expected Element to launch normally

#### What happened instead?
I received an error message

### Operating system

Arch Linux

### Application version

The package version is 1.11.53-1; I can't go to settings without closing the debug logs prompt.

### How did you install the app?

extra/element-desktop from the Arch repositories.

### Homeserver

Synapse 1.95.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please report issues with the community maintained packages to the respective maintainers

**Comment by F13** [comment]
I was just following the links provided in the app. I don't know anything about who maintains what.

**Comment by t3chguy** [comment]
See https://archlinux.org/packages/extra/x86_64/element-desktop/
