### ISSUE TITLE
Unify German wording of Security Keys

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-web#26872]
#### What would you like to do?
![image](https://github.com/element-hq/element-web/assets/2803622/e81d706e-5b35-447d-8e5c-04f003da2645)
Pretty sure these mean the same thing, they're both Security Key in English.

#### Why would you like to do it?
Avoid confusion using different names for a single thing.

#### How would you like to achieve it?
Somebody that knows how to use the new translation system.

**Comment by t3chguy** [comment]
The translations are maintained by the community - see https://web-docs.element.dev/Element%20Web/translating.html

**Comment by HarHarLinks** [comment]
I suggest you reconsider based on the fact you are *selling* (or trying to) this product to markets with non English language.

Imo Element needs to spend time on defining a process to avoid this situation in the first place. Element also needs to spend time maintaining i18ns it is selling.

I will also not join a discussion or sign up to yet another service. I'd be happy to open an issue on a community bugtracker which to my knowledge does not exist.
