### ISSUE TITLE
Message takes very long (minutes) to encrypt and send

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#26873]
### Steps to reproduce

1. I'm in a room
2. Reply by sending a message
3. It shows with a circle bubble and doesn't send

#### What did you expect?
Message goes out right away

#### What happened instead?
It's still sitting there as I write this, not going out

### Operating system

Windows 11

### Application version

Element version: 1.11.53 Crypto version: Olm 3.2.15

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Duplicate of https://github.com/element-hq/element-web/issues/15476
