### ISSUE TITLE
Something went wrong when I clicked button to register

### ISSUE THREAD

**Issue by JeanPaulLucien** [element-hq/element-web#26887]
### Steps to reproduce

Open Element Web and press button to register.

#### What did you expect?
Register form
#### What happened instead?
Something went wrong message

### Operating system

Windows

### Browser information

Firefox

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
`2024-01-17T21:16:28.336Z E Intl.DisplayNames is not a constructor`

Your browser is not supported - "MyPal" does not conform to the support policy - https://github.com/element-hq/element-web#supported-environments

**Comment by JeanPaulLucien** [comment]
I did not reproduce this issue with 1.11.53. Does you answer mean that you made a broken Element Web for more amount of browsers in 1.11.54?

**Comment by t3chguy** [comment]
`Intl.DisplayNames` has been used for quite some time now, but its possible that through dependency upgrades the polyfilling has gone away.
