### ISSUE TITLE
Feature request : Make it possible to configure keyboard shortcuts

### ISSUE THREAD

**Issue by LutzLange** [element-hq/element-web#26881]
#### What would you like to do?

I would like to be able to reconfigure keyboard shortcuts in ElementWeb/Desktop

#### Why would you like to do it?

I'm using a different keyboard layout and the standard shortcuts don't work well for me.

#### How would you like to achieve it?

It should be possible in the Settings menu to change the keyboard shortcuts.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/element-hq/element-web/issues/15076
