### ISSUE TITLE
Cannot log out with: Uncaught (in promise) Error: DomException UnknownError

### ISSUE THREAD

**Issue by toger5** [element-hq/element-web#26897]
### Steps to reproduce

Press logout,
Console shows:
```
Uncaught (in promise) Error: DomException UnknownError (0): The operation failed for reasons unrelated to the database itself and not covered by any other error code.
```

### Outcome
Nothing happens.
### Operating system
MacOS

### Browser information

Firefox

### URL for webapp

develop.element.io

### Application version
Element version: a410f968022f-react-b3ab5fc2c3fb-js-5333d0e0ba51
Crypto version: Rust SDK 0.7.0 (746c5db), Vodozemac 0.5.0

### Homeserver
matrix.org

### Will you send logs?

No

**Comment by MidhunSureshR** [comment]
I can't repro this on develop or https://pr12153--matrix-react-sdk.netlify.app/

**Comment by toger5** [comment]
I logged out the session via elementX.
trying to log back in now but getting: 
<img width="200" alt="Screenshot 2024-01-19 at 12 09 17" src="https://github.com/element-hq/element-web/assets/16718859/2ba59b4c-f35c-4123-92a8-bb3dedb0dd0c">
I will update this issue if I am logged back in and run into it again.

**Comment by toger5** [comment]
Now this seems to work proeperly closing this as it seems to be fixed now.
