### ISSUE TITLE
Восстановление сеанса не удалось

### ISSUE THREAD

**Issue by Lyumus** [element-hq/element-web#26909]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

### Operating system

Windows 11

### Application version

element 2

### How did you install the app?

element.io/get-started

### Homeserver

riotim.olegb.ru

### Will you send logs?

No

**Comment by t3chguy** [comment]
This issue tracker is English-only, please open a new issue in English and fill all sections including steps to reproduce.
