### ISSUE TITLE
ElementR: mark everything in js-sdk that is no longer supported as deprecated

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26919]
There are quite a lot of methods in `MatrixClient` that will not work correctly with Element-R, and which have been replaced, but have yet to be marked as deprecated. Examples:

* `isEventSenderVerified`
* `getEventSenderDeviceInfo`
* `getOutgoingRoomKeyRequest`
* `requestSecret`

We should audit for places that use `MatrixClient.crypto`, and either deprecate them, or plan to fix them.

**Comment by BillCarsonFr** [comment]
There is this also `sendSharedHistoryKeys`

**Comment by BillCarsonFr** [comment]
Quick not on `requestSecret` there is an API (since 3.5.0) on rust that allows to `requestMissingSecrets`. It's not an exact mapping but there might be a way to replace it.

**Comment by BillCarsonFr** [comment]
Looks like there is a slash command called `remakeolm` that was available in legacy crypto. No effect in rust

https://github.com/matrix-org/matrix-react-sdk/blob/618462ba06d1d2f64fc589402198529dceae8fe2/src/SlashCommands.tsx#L761
