### ISSUE TITLE
Element R: IDBDatabase.transaction: Can't start a transaction on a closed database

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#26918]
### Steps to reproduce

1. Using Element Web R as normal
2. Noticed weird receipt behaviour, then later noticed messages were not arriving even though I saw them on other clients.
3. Checked the logs

#### What did you expect?

To receive messages.

#### What happened instead?

No messages received, this message in logs:

```
12:45:08.251 IndexedDBStore failure, degrading to MemoryStore InvalidStateError: IDBDatabase.transaction: Can't start a transaction on a closed database
    RemoteIndexedDBStoreBackend https://develop.element.io/bundles/7b3472464609c5d70af1/bundle.js:138593
bundle.js:260370:19
```

### Operating system

Ubuntu 20.04

### Browser information

Firefox 119.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 6e1f842351ce-react-aea55eb0801e-js-ab217bdc3552
Crypto version: Rust SDK 0.7.0 (500c68b), Vodozemac 0.5.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by andybalaam** [comment]
Rageshake attached, including a comment with a manual export of the logs from when Indexed DB was not working.

**Comment by BillCarsonFr** [comment]
Can't reproduce
