### ISSUE TITLE
Custom Branding for OIDC Providers

### ISSUE THREAD

**Issue by whoracle** [element-hq/element-web#26936]
#### What would you like to do?

I would like to be able to configure a custom Icon for the "Continue with $SSO_PROVIDER" buttons on the Sign in page

#### Why would you like to do it?

I am moving away from GitLab as my OIDC Provider, to Authentik. Authentik currently has no preconfigured branding in Element-Web, and I don't think the Element Team should be tasked with keeping a List of Brandings for the various OIDC providers that crop up.

However, having a blank Button is not helpful for my users.

#### How would you like to achieve it?

Ideally, I'd pass a custom identifier in the "idp_brand" parameter in synapse, and then configure a matching asset/icon in element somewhere.

Maybe the feature already exists, but if so, I have not found any docs for this.

### Have you considered any alternatives?

The alternative would be for me to edit the CSS somewhere in the Element source, which would mean I would have to do this every time Element gets updated by my Distro.

**Comment by t3chguy** [comment]
Custom branding is already supported, your server has to send an `icon` in the `identity_providers` field - https://spec.matrix.org/v1.9/client-server-api/#client-login-via-sso
