### ISSUE TITLE
Notification for unread redacted message in thread gets stuck

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#26933]
### Steps to reproduce

1. Get 2 clients.
2. From one client, create room, post message.
3. Read that event in the other client, then click off the room
4. Post another message creating a thread from that message. Make sure it's a message that notifis the other client.
5. In the same client that posted it (without viewing it the other), redact that message.
6. Observe you now have a notification with no matching message in the other client, so no way to clear it.
7. Clear cache & reload in the client with the stuck notif, observe that you *still* have a stuck notif.

#### What did you expect?
Redacting a message in the main timeline causes the notification to vanish, so probably that, although getting notifications that can then disappear without a trace seems problematic.

#### What happened instead?
Stuck notif with no obvious cause & no way to clear.

### Will you send logs?

No

**Comment by florianduros** [comment]
Unable to reproduce it. Maybe fix by https://github.com/matrix-org/matrix-js-sdk/pull/4022?

**Comment by dbkr** [comment]
Just retested before and after pulling latest js-sdk and indeed, I could repro it before but not after, so I'm going to say this is fixed!
