### ISSUE TITLE
Accessibility: Minimal contrast of "unread" indicator (gray-on-gray)

### ISSUE THREAD

**Issue by Philantrop** [element-hq/element-web#26952]
### Steps to reproduce

In Element-Web 1.11.57 the colour of the "unread" indicator in the default dark mode has a very low contrast since it's gray on gray:

![image](https://github.com/element-hq/element-web/assets/54220/473578e7-c571-4ad9-b934-9d48713a95b1)

And:

![image](https://github.com/element-hq/element-web/assets/54220/9789e846-0510-4df7-a425-5420be9f54cb)

Even I, with minimal visual challenges, have a hard time even seeing these indicators which used to be primarily white up until 1.11.56.

Please consider enhancing the contrast and, thus, the visibility of the indicators.

#### What did you expect?

Being able to actually see indicators. :)

#### What happened instead?

I have to squint and hope for the best.

### Operating system

Fedora 39

### Browser information

Chrome 120.0.6099.224 (Official Build) (64-bit)

### URL for webapp

https://element.mailstation.de/ which runs an unmodified 1.11.57

### Application version

Element-Web 1.11.57

### Homeserver

Synapse 1.99.0

### Will you send logs?

No

**Comment by dbkr** [comment]
These are black/white in develop so will be changed in the next release.
