### ISSUE TITLE
Can't invite people into a room via email

### ISSUE THREAD

**Issue by quantazelle** [element-hq/element-web#26950]
### Steps to reproduce

1. Where are you starting? What can you see?
![image](https://github.com/element-hq/element-web/assets/13591815/31c19713-b391-45b5-8410-834158bef0d0)

![image](https://github.com/element-hq/element-web/assets/13591815/e9715a6b-6f22-4d8f-a0ed-44dd061941aa)

Am admin of the group, but when I try to invite a user through email to  the group, it says Cannot invite user.
![image](https://github.com/element-hq/element-web/assets/13591815/0389123f-acb4-4497-bf55-5e608a7e112f)

3. What do you click?
4. More steps…

#### What did you expect?
Yay, invited user.
#### What happened instead?
Error screen

### Operating system

Windows 10

### Application version

Element version: 1.11.57 Crypto version: Olm 3.2.15

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Will you send logs?
Yes

Not seeing any logs from you.

**Comment by t3chguy** [comment]
Closing due to lack of logs
