### ISSUE TITLE
Element fails to start in some Firefox instances

### ISSUE THREAD

**Issue by young-d-a** [element-hq/element-web#26969]
### Steps to reproduce

1. Where are you starting? What can you see? 
![image](https://github.com/element-hq/element-web/assets/76250016/27111327-459b-4066-a7d9-7d021f6d010b)
![image](https://github.com/element-hq/element-web/assets/76250016/549bc31e-acc7-439e-9d52-58cdbc72ebd9)

2. What do you click?
3. More steps…

#### What did you expect?
Normal start
#### What happened instead?
Error message

### Operating system

linux mint 17.3

### Browser information

Firefox 78.7.1esr

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by florianduros** [comment]
Hello!

You are using an outdated version for firefox, `Firefox 78.7.1esr` which was released 3 years ago. Can you updated it and try again?
