### ISSUE TITLE
ElementR | Unexpected upgrade encryption toast after migrating from legacy to rust via lab

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#26977]
## What happened

I went to the labs settings in dev mode in order to test migrate to rust using the lab option (staging 1.11.58-rc.1).

The migration was very quick then this toast was displayed
![image](https://github.com/element-hq/element-web/assets/9841565/135e677f-bfb1-454f-a3fa-79833da361c7)

The english copy is `Encryption upgrade available`, the button is `Upgrade`

Clicking on the upgrade button asks for the passphrase but is no-op 

## Expected

Should not show that.

## First analysis

This looks like an old migration flow that was used prior to cross-signing was a thing.
It was supposed to help you migrate to the new cross-signing and 4S.

Looks like there is a race in the rust crypto flow where you start checking things on the identity before the first keys/query has completed.
It doesn't happen in the login flow compared to the migrate flow because in postLogin there is a call to `userHasCrossSigningKeys` that ensures that the initial key query has been done?

Key words:  ElementR, migration, trust, legacy

**Comment by BillCarsonFr** [comment]
I set a low severity because the toast action is a no-op and doesn't break/reset any keys/recovery

**Comment by richvdh** [comment]
To help with search, the English translation of this dialog is:

> Encryption upgrade available
>
> Safeguard against losing access to encrypted messages & data

... And it is shown when there is a key backup on the server, but one or both of 4S or cross-signing is not correctly configured.
