### ISSUE TITLE
My messages are received as UTDs

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#26973]
### Steps to reproduce

1. Where are you starting? What can you see?
Send a message

#### What did you expect?
it goes through

#### What happened instead?
my counterpart writes that he cannot decrypt

### Operating system

Windows 11

### Application version

Element version: 1.11.57 Crypto version: Olm 3.2.15

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by ara4n** [comment]
given this is pre ER, suggest ignoring

**Comment by kegsay** [comment]
Logs https://github.com/matrix-org/element-web-rageshakes/issues/24225

**Comment by richvdh** [comment]
This turns out to have been due to https://github.com/matrix-org/matrix-rust-sdk/issues/3110.
