### ISSUE TITLE
Replies broke

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#26986]
### Steps to reproduce

1. Observe a message with a reply

#### What did you expect?

Some sort of quote line or indication that the reply is from someone else

#### What happened instead?
![image](https://github.com/element-hq/element-web/assets/1190097/482ccec4-364e-40c5-90a0-0216baa26719)

Both replies from Tom there are noticibley missing the left-side bar. Display name colours are #

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2024020701 Crypto version: Olm 3.2.15

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
this was fixed in https://github.com/matrix-org/matrix-react-sdk/pull/12234 for me (note that Matthew's displayname is also missing a color in your screenshot, which is the same issue)

**Comment by dbkr** [comment]
Indeed, I can't repro this on latest develop.
