### ISSUE TITLE
avatar placeholders are transparent

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-web#26987]
### Steps to reproduce

look at pills and read receipts

#### What did you expect?
contrast etc

#### What happened instead?
![image](https://github.com/element-hq/element-web/assets/2803622/0bbda180-8d66-459c-9d7d-25e0c6205711)

![image](https://github.com/element-hq/element-web/assets/2803622/dcd37cab-e3ee-42fe-b2ca-f9a11fadddbb)

### Operating system

arch

### Browser information

firefox 121

### URL for webapp

https://develop.element.io

### Application version

Element version: c64af5671a49-react-b4226412585a-js-f4a796ca2fa0 Crypto version: Rust SDK 0.7.0 (fac36bc), Vodozemac 0.5.1

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
also in typing notifications.

**Comment by robintown** [comment]
This will be fixed by upgrading to compound-design-tokens 1.2.0
https://github.com/element-hq/compound-design-tokens/releases/tag/v1.2.0
