### ISSUE TITLE
Display name colours changed

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#26984]
### Steps to reproduce

1. Open app on yesterday's build
2. Note colours of names
3. Update
4. Note colours of names again

#### What did you expect?

Colours assigned to names to be consistent.

#### What happened instead?

Looks like everything rotated by 1 place in the array.

I was red, now blue. Matthew was some colour, now white (indicating an out of bounds condition).

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2024020701 Crypto version: Olm 3.2.15

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
seems intentional from https://github.com/matrix-org/matrix-react-sdk/pull/12209 + https://github.com/matrix-org/matrix-react-sdk/pull/12234

**Comment by robintown** [comment]
Yes, this was intentional - design decided to limit avatar and username colors to a smaller pallette of 6 colors, and this change also brings avatar colors into sync across all platforms. The out-of-bounds condition was fixed by https://github.com/matrix-org/matrix-react-sdk/pull/12234.

**Comment by MTRNord** [comment]
https://xkcd.com/1172/

**Comment by justjanne** [comment]
> Yes, this was intentional - design decided to limit avatar and username colors to a smaller pallette of 6 colors, and this change also brings avatar colors into sync across all platforms. The out-of-bounds condition was fixed by https://github.com/matrix-org/matrix-react-sdk/pull/12234.

Wouldn't it have broken fewer people's workflow to use the web color palette as standard across all platforms instead?

**Comment by WolfspiritM** [comment]
Can you stop changing user name colors every now and then and instead provide a way to set custom user name colors, please? Last time (just a few month ago) it switched the colors around so I had the color of the person I'm constantly chatting with and vise versa which was VERY confusing. Now that I finally got used to the reversed colors we both have the same (ugly) color after todays element desktop update...

Luckily it can't get even worse except for getting the background color in a few month so you can't even read the name anymore...

**Comment by t3chguy** [comment]
> instead provide a way to set custom user name colors

This exists - see https://github.com/matrix-org/matrix-react-sdk/pull/12240#issue-2126522380.

I suggest moving whatever complaints you have about Compound's colours to https://github.com/element-hq/compound

**Comment by WolfspiritM** [comment]
> This exists - see [matrix-org/matrix-react-sdk#12240 (comment)](https://github.com/matrix-org/matrix-react-sdk/pull/12240#issue-2126522380).

This sadly doesn't solve the problem. Sure, I can change the theme color, but that doesn't help if two users have the same initial color assigned. I know that matrix doesn't yet support setting a custom color but at least the android element client allows changing the color of a specific user (locally for yourself). That's what I'm missing in the other clients like web and desktop...
