### ISSUE TITLE
No "Cancel" possible while forced to submit this issue 

### ISSUE THREAD

**Issue by modnerd** [element-hq/element-web#26998]
### Steps to reproduce

1. Element was just sending messages, so I restarted the app
2. I was forced to create an issue while the app was working correctly in the background!
3. I can't cancel the modal window

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> How did you install the app?
No response

Please don't leave these fields blank.

**Comment by t3chguy** [comment]
`M_UNKNOWN: MatrixError: [429] Server is unavailable (https://matrix-client.matrix.org/_matrix/client/v3/room_keys/version)`

Looks like this issue is due to matrix.org maintenance. https://status.matrix.org/ doesn't seem to have anything about it. I suggest seeking help from support@matrix.org
