### ISSUE TITLE
dont even know what happend

### ISSUE THREAD

**Issue by dot-qwerty** [element-hq/element-web#26999]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

1. just started a pc and opened element app and this submit debug logs opened
2. nothing
3. did nothing more

### Operating system

Windows 11 Home, 23H2, 22631.3085, Windows Feature Experience Pack 1000.22684.1000.0

### Application version

1.11.57

### How did you install the app?

from you website

### Homeserver

matrix

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
`M_UNKNOWN: MatrixError: [429] Server is unavailable (https://matrix-client.matrix.org/_matrix/client/v3/room_keys/version)` this is an issue with matrix.org - seek help from support@matrix.org

**Comment by dot-qwerty** [comment]
after sending logs everything got fixed
