### ISSUE TITLE
Signing out of sessions

### ISSUE THREAD

**Issue by iDevelopAtNight** [element-hq/element-web#26995]
### Steps to reproduce

When one tries to log out of a session and they enter an incorrect password for the confirmation it says that they entered a wrong password or a username, which doesn't have to be entered.

#### What did you expect?
I expected it to say that the password is wrong.
#### What happened instead?
It said that the password or username is wrong.
![Screenshot from 2024-02-10 20-20-36](https://github.com/element-hq/element-web/assets/159652085/da433be6-bdca-4aeb-a384-7bf5b8d14d30)
r username is wrong

### Operating system

Ubuntu

### Browser information

Chromium Version 123.0.6286.0 (Official Build) snap (64-bit)

### URL for webapp

element.envs.net

### Application version

Element version: 1.11.57 Crypto version: Olm 3.2.15

### Homeserver

envs.net

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This error is sent by the server, I suggest seeking help from the server implementation which you are using

![image](https://github.com/element-hq/element-web/assets/2403652/8adaecc7-6a00-41ff-b3eb-70e39da31180)
