### ISSUE TITLE
Yesterday is after today

### ISSUE THREAD

**Issue by exuvo** [element-hq/element-web#27003]
### Steps to reproduce

1. In an encrypted room chat, i see one of yesterdays messages at the bottom after todays messages.
2. If i write a new message it is at the bottom for 1s then jumps up to above yesterdays message.
![2024-02-12-19:38:51](https://github.com/element-hq/element-web/assets/2049338/43f08ec3-2fff-4afe-8522-edae27711ef9)

#### What did you expect?
For yesterday to be before today
#### What happened instead?
Yesterday is after today (monday)

### Operating system

Arch linux

### Application version

Element desktop 1.11.54

### How did you install the app?

distro package manager

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Events in Matrix are eventually consistent, this is normal and can happen if your server or the originating server is having federation issues causing the events to be delivered late.

**Comment by t3chguy** [comment]
There is no "main" server, if you mean matrix.org then I suggest support@matrix.org

**Comment by exuvo** [comment]
How many hours is the expected time for the "eventually consistent" to show things in the right order? Is a day too little?

**Comment by t3chguy** [comment]
The eventual consistency happens on the server, not the client.

**Comment by exuvo** [comment]
This client is on 24/7 and i wrote that message that is in the wrong place yesterday ca 20 hours ago on the very same client that is showing it out of order. My other android client is showing it correctly.

**Comment by t3chguy** [comment]
I suggest Settings > Help & About > Clear cache and reload

Different clients might see different things as matrix.org has many workers and your clients may be being served by different such workers causing a mismatch.
