### ISSUE TITLE
element-desktop under Arch/Hyprland keeps locking up every few minutes

### ISSUE THREAD

**Issue by christiansacks** [element-hq/element-web#27007]
### Steps to reproduce

1. Where are you starting? What can you see? Launch element-desktop, wait for it to show chats/rooms.
2. What do you click? Start typing a message
3. More steps… every few minutes it will completely lock up, then after a few minutes be usable again for a few minutes.

#### What did you expect?
To be able to use element-desktop without any lock ups

#### What happened instead?
Unusable due to such frequent lock ups.

### Operating system

Arch Linux

### Application version

Element version: 1.11.57 Crypto version: Olm 3.2.15

### How did you install the app?

sudo pacman -S element-desktop

### Homeserver

matrix.erb.pw

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The Arch package isn't maintained by us, please seek support from its maintainer

**Comment by christiansacks** [comment]
Not sure if it's related, seems maybe coincidence, but often when I select text and copy to the clipboard in any other app, then switch to the workspace with element on, element has locked up.

I don't see anything in journalctl that would indicate any issues with anything, element is just plain frozen.

**Comment by t3chguy** [comment]
> Also, could you point me in the right direction of getting info on what is causing the lock ups so that I might be able to help the maintainer of the Arch package?

It'd be an electron issue most likely

> While I appreciate that it isn't supported by you guys, is there any supported package that I could install instead?

We only maintain the deb and tarball packages for Linux

**Comment by christiansacks** [comment]
This can't be the reason it's suddenly working ok... but I just edited /usr/lib/element/webapp/config.json and changed the following;

"show_labs_settings": false,

to

"show_labs_settings": true,

Restarted element, and now it seems to be working fine!

Gonna do some more testing, but it hasn't been un-locked up this long since I installed it 🤣

**Comment by christiansacks** [comment]
I can say that since making that seemingly unrelated modification, I haven't had a single lock up for element-desktop at all!

How strange.
