### ISSUE TITLE
Cross-user verification is broken.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27000]
### Steps to reproduce

1. Verify a user (in this instance, `@matthew:matrix.org` trying to verify `@matthew:element.io`) from the memberinfo
2. The target user receives a DM
3. They accept the DM, which looks like:

![Screenshot 2024-02-12 at 11 25 29](https://github.com/element-hq/element-web/assets/1294269/03c05a59-4c68-441a-9962-370c87131935)

However, no verification prompt comes up at all. 

4. Refresh the app, at which point the verification prompt actually appears.

#### What did you expect?

Actually receive a verification prompt

#### What happened instead?

Got a "foo wants to verify" msg in the timeline with no way to action it.

### Application version

Element version: 1.11.57 Crypto version: Olm 3.2.15

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by Pritam-sd-dev** [comment]
please assign this task to me, i will be very happy to work on this.

**Comment by MidhunSureshR** [comment]
@Pritam-sd-dev 
Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)

**Comment by richvdh** [comment]
Assuming this isn't easy to reproduce, I think it's stale.
