### ISSUE TITLE
Element R: Automatically Migrate 10% of existing users to rust sdk - Target Date: EW release 04/04

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#27002]
Change the default value of `RustCrypto.staged_rollout_percent` to 10

```
    "setting_defaults": {
        "RustCrypto.staged_rollout_percent": 10
    },
```

Depends on the following PRs:
-  https://github.com/matrix-org/matrix-js-sdk/pull/4059
- https://github.com/matrix-org/matrix-react-sdk/pull/12251

**Comment by BillCarsonFr** [comment]
Blocked by https://github.com/element-hq/element-web/issues/26967

**Comment by BillCarsonFr** [comment]
Delayed due to new blocker: https://github.com/element-hq/element-web/issues/27079

**Comment by richvdh** [comment]
No longer blocked; we are doing this today.

**Comment by richvdh** [comment]
PRs: https://github.com/element-hq/element-web/pull/27032, https://github.com/element-hq/element-desktop/pull/1518/files
