### ISSUE TITLE
Messages are not sent but stay unsent in the chat without error

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#27005]
### Steps to reproduce

1. Enter a room
2. Try to send a message

#### What did you expect?
Message is sent

#### What happened instead?
Message stays unsent, the read receipt bubble is an empty circle. No error message.

![image](https://github.com/element-hq/element-web/assets/640121/8f459c9b-4eab-4307-92b3-e233979a7857)

### Operating system

Windows 11

### Application version

Element version: 1.11.57 Crypto version: Olm 3.2.15

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
What are the IDs of these events so the logs can be parsed?

**Comment by kongo09** [comment]
room_id: !ZZVNrANIxNgftdLcEU:matrix.org

event_id:

- $UT8A3ZrOChJILDAuTsGeSLbOMzDqYChWXByDsY_4HxY
- $SngzwgNOul4DuqpbcR2nu8G-UQEQqWFLh3aOnXCgKBQ
- $O97Z9v2HD6fyoMrdn5axCiUg5SQQAzEJeKIKDXDKNhA
- $QcFurEZpMn_ZWMA9HD0pTYWyKaTSuL2ALx9uizw7xS8
- $pyytdSIjQy8aFqtIrOXfImOFHP1ne5JsNhMbbuHCUsg

When I now send messages, they go through and appear above the stuck ones. There is no way to resend stuck ones.

**Comment by kongo09** [comment]
The recipient just tells me that he did indeed receive those five messages, was able to read and respond. I never got these responses, though.

**Comment by kongo09** [comment]
The same five messages seem to show us UTD of myself above in the timeline:

![image](https://github.com/element-hq/element-web/assets/640121/aeb83430-891f-4b6b-8082-ad1edd39e82d)

**Comment by kongo09** [comment]
How can it be a Synapse problem if it looks ok and normal on mobile?

**Comment by t3chguy** [comment]
Because the sync stream for all client's isn't the same, the transaction ID should only be sent back to the sender, and when Synapse is running in worker mode different sync workers can fall out of sync with each other causing some data to not be sent into certain streams.

**Comment by kongo09** [comment]
Understood. Is there any way to transfer the issue?

**Comment by t3chguy** [comment]
For someone with sufficient permissions in both repos, maybe (not me). But then that team will likely have insufficient information given their issue template will have been ignored
