### ISSUE TITLE
"migrating_crypto" translation should use "%(brand)s" instead of "Element"

### ISSUE THREAD

**Issue by estellecomment** [element-hq/element-web#27021]
### Steps to reproduce

(sorry if I should be doing this in localazy : I couldn't find where. Maybe I don't have access for that task.)

1. Where are you starting? What can you see?
In localazy, translation for "migrating_crypto" in english is : "Hang tight. We are updating Element to make encryption faster and more reliable."
https://localazy.com/p/element-web/phrases/521/edit/_a7510213276586093000

#### What did you expect?
"Hang tight. We are updating %(brand)s to make encryption faster and more reliable." 

#### What happened instead?
Element, not %(brand)s

### Will you send logs?

No

**Comment by richvdh** [comment]
cf https://github.com/matrix-org/matrix-react-sdk/pull/12104
