### ISSUE TITLE
Room pings are not pillified or red anymore

### ISSUE THREAD

**Issue by MTRNord** [element-hq/element-web#27022]
### Steps to reproduce

1. @room ping (with tab completion) in a room with enough permission

#### What did you expect?

A red message and a pill around @room

#### What happened instead?

![image](https://github.com/element-hq/element-web/assets/1374914/409af8b8-ad4b-4bd7-93f9-482cd4ef9c29)

It does contain the intentional mention json though:

```
    "m.mentions": {
      "room": true
    },
```

### Operating system

Fedora Silverblue 39

### Browser information

Firefox 121.0.1 (64-bit)

### URL for webapp

develop.element.io

### Application version

Version von Element: 92c831094d11-react-b5048bf63e3b-js-2cf7d819d90a Krypto-Version: Rust SDK 0.7.0 (fac36bc), Vodozemac 0.5.1

### Homeserver

matrix.midnightthoughts.space

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
https://github.com/element-hq/element-web/issues/26719

**Comment by florianduros** [comment]
Closing in favor of https://github.com/element-hq/element-web/issues/26719
