### ISSUE TITLE
Accessibility : with a screen reader, it's difficult to find the latest messages in a room 

### ISSUE THREAD

**Issue by estellecomment** [element-hq/element-web#27038]
### Steps to reproduce

1. Where are you starting? What can you see?
I have impaired vision and use a screen reader. I open a room. I want to check the latest messages in the room, to know what's going on. 

#### What did you expect?
A quick way to navigate through messages. 
For example, my screen reader can display all titles (< h1 >, < h2 >, etc) in a tree view and navigate through them. Titles can represent the same structure as the visible structure.
```
<h1> Yesterday
   ...
<h1> Today
  <h2> User A
    <h3> Hello
    <h3> How are you ?
  <h2> Me - User B
    <h3> fine
```

I also expect a quick way to find unread messages.

#### What happened instead?
To navigate through messages, I have to tab a lot. I tab through all messages, and for each message I tab more than 5 times through lots of useless divs. It takes a long time and is hard to keep track of. 
I am also not sure that I have the latest message, I am going through the list but it's hard to know where.

### Details
This was reported by a screen-reader user, we can share a video (in french) privately.

Here is the Aria view of the Element Announcements room, as an illustration : the user tabs through profile picture, time of message, reactions, read receipts, guessing what they are.
<img width="810" alt="Screen Shot 2024-02-20 at 10 40 47 AM" src="https://github.com/element-hq/element-web/assets/911434/8e1d7075-466c-4728-9e09-e5e317fe6921">

### Operating system

Windows

### Browser information

Firefox, with NVDA screen reader

### Will you send logs?

No

**Comment by t3chguy** [comment]
titles are completely incorrect semantically, we use list items and separators which is more appropriate for this sort of content - closing in favour of https://github.com/element-hq/element-web/issues/25123
