### ISSUE TITLE
Element R: Perf logs spamming

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#27031]
From conversation:

> is it really necessary for EW’s logs to be spammed with huge amounts of

> [!EYtEinqiWbAglxNFKg:[matrix.org](http://matrix.org/) encryption] [Perf]: updateTrackedUsers took 5ms
19:41:23.858 

atm?
it’s starving out legitimate logs by rotating the rageshakes

**Comment by BillCarsonFr** [comment]
Probably need to check why it's called so often also. Ideally should be called on new membership events and after lazy loading resolved. But web stores state a bit differently

**Comment by andybalaam** [comment]
These logs were added 6 weeks ago, but it seems like something happened recently to make it happen much more often.

**Comment by BillCarsonFr** [comment]
Note: It's not doing small transactions because there is an in-memory cache so won't hammer the DB.
maybe for now just remove that log.
