### ISSUE TITLE
Can't open devtools in read-only room with new room header

### ISSUE THREAD

**Issue by tulir** [element-hq/element-web#27042]
### Steps to reproduce

1. Enable developer mode in /devtools
2. Join a room where you don't have permissions to send events
3. Try to find a button to open devtools in that room

#### What did you expect?

A button to open devtools. Originally it was in settings -> advanced, later it was in the dropdown menu in the room header

#### What happened instead?

The button is gone and there's no way to open devtools in a read-only room

### Operating system

Ubuntu

### Browser information

Firefox 123

### URL for webapp

develop.element.io

### Application version

Element version: 3ac096619b38-react-96a33b800a01-js-b4744392563b Crypto version: Rust SDK 0.7.0 (fac36bc), Vodozemac 0.5.1

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
<img width="227" alt="image" src="https://github.com/element-hq/element-web/assets/2403652/c622dd62-4799-44b6-a548-522b8cfdbdd7">

There's one under Quick Settings

**Comment by tulir** [comment]
That's very well hidden, I didn't even know there's a settings button there 😹
