### ISSUE TITLE
Translation : labs.threads_activity_centre_description should use "%(brand)s", not "Element"

### ISSUE THREAD

**Issue by estellecomment** [element-hq/element-web#27040]
### Steps to reproduce

1. Where are you starting? What can you see?
In localazy, translating labs.threads_activity_centre_description, the en_EN version is "Warning: Under active development; reloads Element."

#### What did you expect?
"Warning: Under active development; reloads %(brand)s."

#### What happened instead?
"Warning: Under active development; reloads Element."

### Will you send logs?

No

**Comment by richvdh** [comment]
Similar problem to https://github.com/element-hq/element-web/issues/27021
