### ISSUE TITLE
Enabling the new notification settings cause a notification for every nick update

### ISSUE THREAD

**Issue by bnjbvr** [element-hq/element-web#27055]
### Steps to reproduce

My push rule `.m.rule.member_event` looked like this before:

```json
{
          "conditions": [
            {
              "kind": "event_match",
              "key": "type",
              "pattern": "m.room.member"
            }
          ],
          "actions": [],
          "rule_id": ".m.rule.member_event",
          "default": true,
          "enabled": true
        }
```

After enabling the new notification settings, it looked like this:

```json
{
          "conditions": [
            {
              "kind": "event_match",
              "key": "type",
              "pattern": "m.room.member"
            }
          ],
          "actions": [
            "notify",
            {
              "set_tweak": "highlight",
              "value": false
            }
          ],
          "rule_id": ".m.rule.member_event",
          "default": true,
          "enabled": true
}
```

#### What did you expect?

My push rules to not change.

#### What happened instead?

My push rules have changed, and this is confusing on EX, where the "notify" action adds a green dot (unread notification) on the associated room in the room list, whenever someone changes their nick.

### Will you send logs?

No

**Comment by t3chguy** [comment]
Yes, you can turn this off with

![image](https://github.com/element-hq/element-web/assets/2403652/dbe91329-6927-452b-a8fa-3efb0de634f4)

Its a "status message"
