### ISSUE TITLE
Since more than a month Element logs out after reboot!

### ISSUE THREAD

**Issue by AlperShal** [element-hq/element-web#27067]
### Steps to reproduce

1. I reboot.
2. I see I am logged out. No error or something until today. (Error asks me if I want to make a bug submission, no detail)
3. I do login again until I reboot.

#### What did you expect?
To be logged in after I reboot.

#### What happened instead?
I got logged out.

Note: Other user on my homeserver, also using EndeavourOS, doesn't have such problem.
Note: I have re-installed my OS. Did not fix the problem.
### Operating system

Arch Linux/EndeavourOS 6.7.5-arch1-1 (64-bit)

### Application version

1.11.58

### How did you install the app?

From Linux extra repositories

### Homeserver

matrix.sal.web.tr

### Will you send logs?

Yes, sent it.

**Comment by t3chguy** [comment]
The Arch package isn't maintained by us, seek support from its maintainers
