### ISSUE TITLE
Thread list not loading

### ISSUE THREAD

**Issue by omyno** [element-hq/element-web#27069]
### Steps to reproduce

When clicking on the threads icon to see the list of threads, a loading icon keeps spinning.

### Outcome

Individual threads still show up when clicking on them directly. The sidebar with the thread list always shows a loading icon only. Tested on Ubuntu, Arch and macOS with different users.

Element developer console when clicking on the threads icon:

```
room.ts:1955 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'latest_event')
    at room.ts:1955:40
    at Array.sort (<anonymous>)
    at z.fetchRoomThreads (room.ts:1942:74)
(anonymous) @ room.ts:1955
fetchRoomThreads @ room.ts:1942
Promise.then (async)
(anonymous) @ ThreadPanel.tsx:210
Bl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ki @ react-dom.production.min.js:122
Pl @ react-dom.production.min.js:261
yl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ki @ react-dom.production.min.js:122
$i @ react-dom.production.min.js:123
Hi @ react-dom.production.min.js:122
Oe @ react-dom.production.min.js:292
Wt @ react-dom.production.min.js:73
Show 15 more frames
Show less

```

### Operating system

macOS

### Application version

Element 1.11.58

### Homeserver

Dendrite 0.13.6+87f028d

**Comment by t3chguy** [comment]
Sounds like Dendrite isn't spec conforming - https://spec.matrix.org/v1.9/client-server-api/#server-side-aggregation-of-mthread-relationships
