### ISSUE TITLE
Unreliable thread notifications in Linux

### ISSUE THREAD

**Issue by irm-codebase** [element-hq/element-web#27062]
### Steps to reproduce

1. When receiving replies in threads (within group chats), finding out where a specific message was posted is incredibly buggy.
2. Normally I try to clock on the notification "arrow" that appears on the top right corner of the group chat, but this rarely works, as it does not take the user anywhere.
3. Unfortunately repeating this issue is a bit complicated for me, but it happens often enough that repeating it in isolation should be easy.

#### What did you expect?
Clicking the arrow to go to the most resent thread reply should work.

#### What happened instead?
It does not work!

### Operating system

Fedora Linux

### Application version

Element version: 1.11.58 Crypto version: Olm 3.2.15

### How did you install the app?

From Flatpak (through the Gnome software app)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The Flatpak isn't maintained by us, seek help from https://github.com/flathub/im.riot.Riot
