### ISSUE TITLE
Variable playback speed for voice msgs

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27077]
#### What would you like to do?

Speed up playback for VMs

#### Why would you like to do it?

Accessibility, and to deal with people who speak slowly.

#### How would you like to achieve it?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate

### Additional context

Surprisingly useful feature in youtube.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/element-hq/element-meta/issues/2148
