### ISSUE TITLE
Roles and permissions - saving changes should be on button click, not on combo box change

### ISSUE THREAD

**Issue by lszczygielek** [element-hq/element-web#27083]
### Steps to reproduce

1. Create space or room.
2. Go to Setting -> Roles & Permissions
3. Start changing your role (Privileged User).

#### What did you expect?
I can change the setting to Moderator or custom Power Level (to 10, as an example), but I can change my mind and return to the previous option.

Saving should be on button click, but there is no Save button, but save on the option change.

#### What happened instead?
The option is saved after the combo box selection. I cannot revert the action, so I lost permission in my space. 

### Operating system

Windows 10

### Browser information

Firefox

### URL for webapp

app.element.io

### Application version

Element version: 1.11.59

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by dbkr** [comment]
<img width="951" alt="Screenshot 2024-03-05 at 13 10 23" src="https://github.com/element-hq/element-web/assets/986903/1a8269fa-2e96-4a5a-8975-5a21304e500a">

For context, above is the screen where the 'Add privileged users' section has an apply button, but the section above doesn't.
