### ISSUE TITLE
Unable to restore session error

### ISSUE THREAD

**Issue by emilvincentz** [element-hq/element-web#27089]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

We encountered an error trying to restore your previous session.

If you have previously used a more recent version of Element, your session may be incompatible with this version. Close this window and return to the more recent version.

Clearing your browser's storage may fix the problem, but will sign you out and cause any encrypted chat history to become unreadable.

### Outcome

We encountered an error trying to restore your previous session.

If you have previously used a more recent version of Element, your session may be incompatible with this version. Close this window and return to the more recent version.

Clearing your browser's storage may fix the problem, but will sign you out and cause any encrypted chat history to become unreadable.

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This was fixed on 1.11.59.
