### ISSUE TITLE
Keine teilnahme über Link möglich - Fehler

### ISSUE THREAD

**Issue by MareikePli** [element-hq/element-web#27084]
### Steps to reproduce

1. Auf den Link geklickt
2. Etwas ist schiefgelaufen!
Bitte [erstelle ein neues Issue](https://github.com/vector-im/element-web/issues/new/choose) auf GitHub, damit wir diesen Fehler untersuchen können.

Wenn du uns einen Bug auf GitHub gemeldet hast, können uns Debug-Logs helfen, das Problem zu finden. Fehlerberichte enthalten Nutzungsdaten wie Nutzernamen von dir und anderen Personen, Raum-IDs deiner beigetretenen Räume sowie mit welchen Elementen der Oberfläche du kürzlich interagiert hast. Sie enthalten keine Nachrichten.

### Outcome

/

### Will you send logs?

Yes

**Comment by florianduros** [comment]
Hi !
Please report the issue using english only.
Thanks
