### ISSUE TITLE
TAC: thread with a mention isn't added

### ISSUE THREAD

**Issue by florianduros** [element-hq/element-web#27097]
### Steps to reproduce

 A thread you didn't ever read but were mentioned in didn't get added to the TAC

### Outcome

I'm expecting the thread to be added to the TAC

**Comment by dbkr** [comment]
I can't repro this, so hopefully this was the first message in the thread being a mention which was broken, but now is fixed. I'm going to say this is fixed then, we can reopen if we see it again.
