### ISSUE TITLE
Crash on click.

### ISSUE THREAD

**Issue by grinapo** [element-hq/element-web#27138]
### Steps to reproduce

1. Just clicked into the window.

#### What happened instead?

Crash.

### Operating system

Linux Debian/sid, xwindow, xfce4

### Browser information

firefox nightly

### URL for webapp

https://riot.grin.hu/#/room/#osm:grin.hu

### Homeserver

synapse 

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Duplicate of https://github.com/element-hq/element-web/issues/25435
