### ISSUE TITLE
Add a button in room header to open user list directly

### ISSUE THREAD

**Issue by iwalkalone69** [element-hq/element-web#27136]
#### What would you like to do?
Make easier to view users that are inside a room.

#### Why would you like to do it?
Now it takes too many steps for something that most users do it all the time.

#### How would you like to achieve it?
Adding a button with user icon just before info button that opens right panel. This button should open right panel too but showing user list instead room info.

**Comment by t3chguy** [comment]
It is there in the new room header (labs)

<img width="933" alt="image" src="https://github.com/element-hq/element-web/assets/2403652/d70db548-9dcf-4d43-bfc3-654641d3c914">
