### ISSUE TITLE
Letting change the size of font more than 21 pt

### ISSUE THREAD

**Issue by ravilacoya** [element-hq/element-web#27131]
### Your use case

For me, and probably more people, 21 pt of font size is too small. I imagine it wouldn't be that difficult to implement the possibility to have bigger size, let's say up to 28-30 pt.

**Comment by t3chguy** [comment]
Update your Element.

<img width="137" alt="image" src="https://github.com/element-hq/element-web/assets/2403652/6474fd63-acad-483a-bf59-9289e6eaa1c4">
