### ISSUE TITLE
Nightly and develop spam "global push rule" messages in the console

### ISSUE THREAD

**Issue by davidegirardi** [element-hq/element-web#27147]
### Steps to reproduce

1. Open Element Desktop Nightly or develop.element.io
2. Open the Electron/browser console
3. See hundreds of these messages per  second:
```
Missing default global push rule .m.rule.suppress_notices
Missing default global push rule .m.rule.invite_for_me
Missing default global push rule .m.rule.member_event
Missing default global push rule .m.rule.is_user_mention
Missing default global push rule .m.rule.contains_display_name
Adding default global push rule .m.rule.is_room_mention
Missing default global push rule .m.rule.roomnotif
Missing default global push rule .m.rule.tombstone
Adding default global push rule .m.rule.reaction
Missing default global push rule .m.rule.room.server_acl
Adding default global push rule .org.matrix.msc3786.rule.room.server_acl
Missing default global push rule .m.rule.suppress_edits
Missing default global push rule .m.rule.encrypted_room_one_to_one
```

#### What did you expect?
A semi-quiet console

#### What happened instead?
Spamming.

### Operating system

Arch linux

### Application version

Element Nightly version: 2024031001 Crypto version: Olm 3.2.15 and Element version: a0c90f96571f-react-8e68d5d6be14-js-30311524443d Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is expected, the server has left your client in an invalid (not spec compliant state) due to a bug: https://github.com/element-hq/synapse/issues/16987
