### ISSUE TITLE
"Some of your messages have not been sent" reported when the message has been sent

### ISSUE THREAD

**Issue by bjherbison** [element-hq/element-web#27142]
### Steps to reproduce

See #20042 . It's still happening. I just sent more debug logs today.

#### What did you expect?
See #20042
#### What happened instead?
See #20042

### Operating system

Ubuntu

### Browser information

Firefox Nightly 125.0a1

### URL for webapp

https://chat.mozilla.org/#/room/#general:mozilla.org

### Application version

Element version: 1.11.59 Crypto version: Olm 3.2.15

### Homeserver

mozilla.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Firefox Nightly 125.0a1

Please open a new issue if you can reproduce from a browser within the support policy: https://github.com/element-hq/element-web#supported-environments

> Definition: Issues only affecting unsupported environments are closed
