### ISSUE TITLE
Element-R should no longer get a Z-Labs label

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#27151]
When you label an issue with A-Element-R, it automatically gets a Z-Labs flag. But, since everyone gets ER by default now, it's no longer right to consider it a "Labs" feature.

**Comment by t3chguy** [comment]
https://github.com/element-hq/element-web/blob/develop/.github/workflows/triage-labelled.yml#L28 could've made a PR quicker than this issue :P
