### ISSUE TITLE
Client does not start (due to CORS errors?)

### ISSUE THREAD

**Issue by robintown** [element-hq/element-web#27154]
### Steps to reproduce

1. Go to develop.element.io
2. Wait for my client to start

#### What did you expect?

It starts

#### What happened instead?

It loads forever. In the console I see these 3 errors:

Security Error: Content at https://develop.element.io/ may not load data from https://element-web-develop.element.io/bundles/3eadc54aa913d27aaf27/blurhash.worker.js.
Security Error: Content at https://develop.element.io/ may not load data from https://element-web-develop.element.io/bundles/3eadc54aa913d27aaf27/indexeddb.worker.js.
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

The same happens if I force-reload the page (Ctrl+Shift+R), and if I try to open develop.element.io in a private window.

### Operating system

NixOS unstable

### Browser information

Firefox 122.0.1

### URL for webapp

develop.element.io

### Application version

8d04ce42553f-react-431ae32304c2-js-3711ad7e6159

### Homeserver

Synapse 1.99.0

### Will you send logs?

I would if I knew of a way to do so from the console before the app has loaded

**Comment by BillCarsonFr** [comment]
On firefox the errors I see are `NS_ERROR_CORRUPTED_CONTENT` for *.worker.js (in FF devtools)

**Comment by florianduros** [comment]
It's working again.

I needed to have a new commit on the `react-sdk` and a new deployment. Just redeploy wasn't enough.

**Comment by t3chguy** [comment]
> It's working again.

@florianduros should this issue be closed?
