### ISSUE TITLE
EW incorrectly claims "Invited people will be able to read old messages"

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#27150]
When inviting someone to an encrypted room:

![image](https://github.com/element-hq/element-web/assets/1389908/591e3ee2-e86d-49ec-9495-cceb5a66e683)

Since we haven't implemented this (https://github.com/element-hq/element-web/issues/26867), that's a total lie.

**Comment by BillCarsonFr** [comment]
Related https://github.com/element-hq/element-web/issues/26919
