### ISSUE TITLE
Calls not connecting

### ISSUE THREAD

**Issue by gragorther** [element-hq/element-web#27157]
### Steps to reproduce

1. Where are you starting? What can you see?
I call my friend via Element.
2. What do you click?
I click the call button in a DM.

#### What did you expect?
I expected the call to connect and be able to talk to my friend.
#### What happened instead?
It just says that the call is connecting, but never actually connecting.

### Operating system

ZorinOS, Windows

### Application version

Element Nightly version: 2024031001 Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1, the other side uses 

### How did you install the app?

https://element.io/download

### Homeserver

envs.net

### Will you send logs?

No

**Comment by MidhunSureshR** [comment]
It would be nice to have some more information and ideally also the logs.
Does this issue occur for all calls?

**Comment by t3chguy** [comment]
Closing due to lack of info
