### ISSUE TITLE
Repeated setting of `.m.rule.is_room_mention` push rule

### ISSUE THREAD

**Issue by erikjohnston** [element-hq/element-web#27173]
### Steps to reproduce

Element web seems to be sending the following requests in a loop:

- `PUT /_matrix/client/v3/pushrules/global/override/.m.rule.is_room_mention/enabled`
- `PUT /_matrix/client/v3/pushrules/global/override/.m.rule.is_room_mention/actions`

#### What did you expect?

For it to not repeatedly send those requests

#### What happened instead?

It gets stuck in a loop?

### Operating system

Ubuntu

### Browser information

Firefox/123.0

### Application version

54ba0873dada-react-0f251d8a55a6-js-78d05942a35a

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Likely caused by https://github.com/element-hq/synapse/issues/16987

**Comment by AndrewKvalheim** [comment]
This is hammering at 2000 requests per minute. What can I do now but just close Element?

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/4100
