### ISSUE TITLE
Favorited are assigned a order value stored as a string and not as a number value.

### ISSUE THREAD

**Issue by Doty1154** [element-hq/element-web#27182]
### Steps to reproduce

When favoriting a channel/room, the element desktop app commits to the homeserver a number associated with it's place within the favorites list for the client to parse. Per the spec this value needs to be a number https://spec.matrix.org/latest/client-server-api/#mtag 

### Outcome

These values need to be stored as a number value rather than a string value, as other matrix clients that are following the spec are able to correctly parse this information.
Here is the json output of the snippet per a room
```
{
  "content": {
    "tags": {
      "m.favourite": {
        "order": "0.25"
      }
    }
  },
  "type": "m.tag"
}
```

Here is what the value should be

```
{
  "content": {
    "tags": {
      "m.favourite": {
        "order": 0.25
      }
    }
  },
  "type": "m.tag"
}
```

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Yeah that isn't being sent by Element Web/Desktop. We specify numbers only.

![image](https://github.com/element-hq/element-web/assets/2403652/929e0db6-1549-4830-aef3-d042d2795245)
![image](https://github.com/element-hq/element-web/assets/2403652/e73e75fb-1677-4fd9-b132-8518d0e011b0)
