### ISSUE TITLE
Visual appearance of action buttons inconsistent

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#27180]
### Steps to reproduce

1. Go to settings
2. Observe various action buttons

#### What did you expect?
Consisten appearance

#### What happened instead?
Inconsistent appearance, some outlined, some filled

![image](https://github.com/element-hq/element-web/assets/640121/1aa85ce5-1b5c-41bd-8c7c-c9048d276886)
![image](https://github.com/element-hq/element-web/assets/640121/49d74f66-ab10-4599-b834-54e2643fa74f)

### Operating system

Windows 11

### Application version

Element version: 1.11.60 Crypto version: Olm 3.2.15

### Homeserver

element.io

### Will you send logs?

No

**Comment by bblacher** [comment]
I think that's on purpose, the "more important" buttons are filled.

**Comment by bblacher** [comment]
It's literally being handeled in the same way as it's always been, the only difference is the color and shape:
![image](https://github.com/element-hq/element-web/assets/42916911/01d0ba68-468e-4c38-b02c-e4c5b3fe4401)
![image](https://github.com/element-hq/element-web/assets/42916911/e200466c-e731-43eb-94fe-ff85d9e8264d)

I can't seem to find where the screenshot you've got in the issue description comes from.

**Comment by kongo09** [comment]
The color is a step back and eliminates our brand further, but that's a different discussion as per: https://github.com/element-hq/element-internal/issues/536

In the example above I can relate to "Save" being the primary CTA and thus trying to keep the user in the flow of guiding along the next best action.

My screenshots from above are: 
- Manage: Security & Privacy -> Message search (clearly not the next best action for that section)
- Submit debug logs: Help & About -> Bug reporting (actually the only action for that section)

**Comment by bblacher** [comment]
In those places I can't see a clear pattern why one button is filled and the other one is not, I agree.

**Comment by americanrefugee** [comment]
Jumping in here...

There seem to be 2 different, but related topics here:
1. ) The logic and appearance of primary vs. secondary actions
2. ) The perceived (im)balance of accessibility vs. the Element brand

What you see now is only a temporary in-between place. We haven't had the resources to do anything more than update some of the existing components with our new styles. But we've known for a long time that Settings needs to be rethought entirely with fresh eyes to address many issues besides the presentation of buttons.

Meanwhile, there was a time-limited effort last month to introduce more of the brand color into the components, including toggles and radio buttons. During that mini-sprint we explored other ways to infuse the interface with more of our brand. A lot of that thinking can easily be applied to Settings.

Fortunately, the next big project I'll be working on in the coming weeks will be Settings :) So, I'll be sure to take both of the above points into consideration when working on it.

@nadonomy feel free to add any more context in case I forgot something
