### ISSUE TITLE
Users do not see topics in new RoomHeader

### ISSUE THREAD

**Issue by estellecomment** [element-hq/element-web#27183]
### Steps to reproduce

Reported by at least 3 users, 2 of which have jobs of community managers.

1. Where are you starting? What can you see?
Use the new RoomHeader (currently in labs)

2. What do you click?
Change the topic of a room to add important information for my community (links, latest info, link to an important message ...)

#### What did you expect?
Users in my community see the change of topic and get the info.

#### What happened instead?
Users do not see the topic. 

#### Why is this happening ?
Because the topic is displayed only if you hover on the room name, which you might do accidentally but not regularly. 
(Hovering is also an "advanced" interaction, users with more basic skills sometimes struggle with it. They have seen something happen but they didn't understand how and have problems reproducing it.)

#### Possible solution
Go back to displaying the topic all the time, rather than on hover. 

### Application version

Element 1.11.58, with new RoomHeader activated in labs

### Will you send logs?

No

**Comment by estellecomment** [comment]
Another possible solution would be to add a configurable setting, so that the topic can be always displayed or hover-displayed.

I don't have design context on this issue, is there a good reason for this design choice that I don't know ? (saving space seems the most obvious reason but I may not have thought of everything)

We could also revert to the old RoomHeader which doesn't have that problem. For that, I am lacking info : is the new RoomHeader actively developed, almost ready, or conversely is the experiment not working and it will be trashed ?

**Comment by BurnyBoi** [comment]
Even if hovering is changed to always displayed, there's currently no way for a user to read a longer topic that goes beyond the one displayed line. Being able to click the topic to open up the whole thing should also be brought into the new header as it is in the current one.

**Comment by gaelledel** [comment]
@americanrefugee wdyt?

**Comment by t3chguy** [comment]
The topic now lives in the right panel and will be leaving the room header

**Comment by dali99** [comment]
Please reconsider, users close out the right panel, or have it on people/threads all the time.

The topic is more important than to be hidden away behind potentially multiple clicks
