### ISSUE TITLE
Element is doing it again - disappearing messages in non-encrypted public rooms

### ISSUE THREAD

**Issue by tallship** [element-hq/element-web#27204]
### Steps to reproduce

1. Where are you starting? What can you see?

## Inside the app

3. What do you click?

## The room icon

5. More steps…

## The message disappeared before my eyes 
![Screenshot_2024-03-19_01-57-09](https://github.com/element-hq/element-web/assets/561994/60cdcdb7-5668-42c8-bd42-613c964ef11f)
as I was reading it.

### Operating system

Debian Trixie

### Application version

Element version: 1.10.15 Olm version: 3.2.8

### How did you install the app?

From your element package repo added to /etc/apt/sources.d as per your instructions

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by tallship** [comment]
[issue.txt](https://github.com/element-hq/element-web/files/14648166/issue.txt)
[log-0.log](https://github.com/element-hq/element-web/files/14648167/log-0.log)
[log-1.log](https
[log-2.log](https://github.com/element-hq/element-web/files/14648171/log-2.log)
://github.com/
[log-3.log](https://github.com/element-hq/element-web/files/14648173/log-3.log)
element-hq/element-web/files/14648168/log-1.log)
[log-4.log](https://github.com
[log-5.log](https://github.com/element-hq/element-web/files/14648178/log-5.log)
/element-hq/element-web/files/14
[log-6.log](https://github.com/eleme
[log-7.log](https://github.com/elem
[log-8.log](https://github.com/element-hq/element-web/files/14648186/log-8.log)
ent-hq/element-web/files/14648182/log-7.log)
nt-hq/element-web/files/14648181/log-6.log)
648176/log-4.log)

**Comment by tallship** [comment]
Second try uploading... I tried `/rage...` method - nothing was updated here. So manually seems to work.

[issue.txt](https://github.com/element-hq/element-web/files/14648295/issue.txt)
[log-0.log](https://github.com/element-hq/element-web/files/14648296/log-0.log)
[log-1.log](https://github.com/element-hq/element-web/files/14648297/log-1.log)
[log-2.log](https://github.com/element-hq/element-web/files/14648298/log-2.log)
[log-3.log](https://github.com/element-hq/element-web/files/14648299/log-3.log)
[log-4.log](https://github.com/element-hq/element-web/files/14648300/log-4.log)
[log-5.log](https://github.com/element-hq/element-web/files/14648301/log-5.log)
[log-6.log](https://github.com/element-hq/element-web/files/14648302/log-6.log)
[log-7.log](https://github.com/element-hq/element-web/files/14648303/log-7.log)
[log-8.log](https://github.com/element-hq/element-web/files/14648304/log-8.log)

**Comment by tallship** [comment]
## And now it's back:

More than anything, this is more a matter of occasional frustration. Fixing this bug is important, but more important than that, since I'm not really confident that this is just a simple bug squash fix, is ***Why this is happening*** - Not just on Linux Desktop, but Windows and Android too, across all devices, at various times, and not all of the clients at once, necessarily.

What causes this?

Here's the other screenie of that message, now that it's appearing as it's supposed to once again:
![Screenshot_2024-03-19_03-06-12](https://github.com/element-hq/element-web/assets/561994/2c7a8652-efe3-4bbe-ac66-477a2dca6696)

Thank you for your assistance in this matter. Sometimes an explanation as to why a bug is rearing its ugly head is more important than the (eventual) fix itself :)

:boat: 

.

**Comment by t3chguy** [comment]
> 1.10.15
> 644 days ago

This version is nearly 2 years old. Please update
