### ISSUE TITLE
Promote Element desktop app by registering a protocol handler on installation

### ISSUE THREAD

**Issue by giomfo** [element-hq/element-web#27207]
#### What would you like to do?
The improvement we are suggesting/requesting is to promote the desktop client (the electron-wrapped client) by registering a protocol handler on installation (protocols, https, ssh, wss et.c. are items that an application can register itself as compatible with and available as a default handler).

When a user clicks a link to a protocol that has available compatible programs installed on their machine, the user is offered a choice to open that link with one of the compatible programs. for this custom protocol it would mean that the user could on click be transported to their already running instance of the element desktop app, instead of having links open a new tab or a new browser.

This would of course only work for users that actually have a desktop client installed (as no other application knows what to do with matrix:// ).

It is not a replacement of https://matrix.to/ or the permalink options, it is an added-value feature.

#### Why would you like to do it?
This would enable users to send links to each other, like invitations to rooms that would open up in the desktop client

#### How would you like to achieve it?
The idea is to have the application register a scheme on installation, much like tel: or mailto:
Ideally there might be options to control how links to matrix-objects open in the desktop application, where a preference can be put in the data in the scheme-call, but ultimately be controllable by user preferences (allow the suggested/preferred preference from the link or set personal preferences per user).

**Comment by daniellekirkwood** [comment]
So it would look like this? @giomfo 

<img width="539" alt="Screenshot 2024-03-19 at 16 27 11" src="https://github.com/element-hq/element-web/assets/89144281/3c7cd6db-d647-4e91-8b99-72776aec2b23">

**Comment by t3chguy** [comment]
matrix.to already supports this as per @daniellekirkwood's screenshot above so not sure what is the ask here

**Comment by giomfo** [comment]
>  is this just a duplicate of #16875

Yes this is a duplicate of this existing ticket "Support matrix URI scheme". 
The request is to have the Desktop application register a scheme on installation to promote it without having to visit "https://matrix.to/".
It is not a replacement of https://matrix.to/ or the permalink options, it is an added-value feature.
