### ISSUE TITLE
Manual Device Verification (eyeballing the key) doesn't work in ER

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27201]
### Steps to reproduce

1. Log in on a new device
2. Don't verify it (e.g. because it doesn't implement verification on its side)
3. Go to your user in EWR to check the untrusted device
4. Manually verify it by comparing fingerprint
5. Discover nothing happens when clicking manual verification.

#### What did you expect?

You should get a prompt to compare fingerprint, and hit 'yes' if they match.

#### What happened instead?

Nothing; the button ignores the presses. Nothing in the JS console either.

### Application version

Element Nightly version: 2024031801 Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### Will you send logs?

No

**Comment by BasilYes** [comment]
> I'm not sure this is a thing we want to expose: it sounds very much like a dev tool to me. So I think the action here is to remove it from the UI

Without this I can't verify [maubot](https://github.com/maubot/maubot/issues/145), may be this feature can be hidden somewhere? Or you it's must be done on maubot side?

**Comment by KsmoinO** [comment]
In addition to the information given in #27497, I would also like to point out that I use a version 6 key backup.

**Comment by JuniorJPDJ** [comment]
still an issue

**Comment by jadedeane** [comment]
> This is a real problem if you're trying to use or develop a simple client that will never have the more complex verification methods.
> 
> For example, I have a lightweight unread message notifier with nearly zero dependencies and no UI of its own. Its sessions have device keys, but no crypto beyond that. Element was the only way of verifying them, and that's now broken. Using it anyway would trigger alerts and brand the account with red badges of shame, which is no good for anyone, so AFAICT, it's effectively shut out of the ecosystem because of this bug.
> 
> I see several other reports have already been filed (now marked as dupes), but just in case it helps, here's what appears on the firefox console when I click the (unresponsive) Verify Session button:
> 
> ```
> Uncaught Error: End-to-end encryption disabled
>     checkKeyBackup client.ts:3324
>     setDeviceVerified client.ts:2439
>     o UntrustedDeviceDialog.tsx:77
>     d QuestionDialog.tsx:42
>     React 11
>     unstable_runWithPriority scheduler.production.min.js:17
>     React 3
> client.ts:3324:12
> Uncaught (in promise) Error: End-to-end encryption disabled
>     setDeviceVerification client.ts:2490
>     setDeviceVerified client.ts:2433
>     o UntrustedDeviceDialog.tsx:77
>     d QuestionDialog.tsx:42
>     React 11
>     unstable_runWithPriority scheduler.production.min.js:17
>     React 3
> client.ts:2490:12
> ```

Yup, see [this](https://github.com/element-hq/element-desktop/issues/1710#issuecomment-2153602509).

**Comment by chagai95** [comment]
I just sent logs, some clients are very buggy and this is a really important feature imho, it makes everything everywhere red, which means that in really annoys everyone...

**Comment by MRAAGH** [comment]
@chagai95 I found a workaround: log in in an older version of Element and verify it via any method. And then you will be able to use text verification from there. For security reasons, I recommend logging out from old Element immediately after you're done.

@foresto if you need a quick verification for testing, I put up Element v1.11.19 at https://element.mazie.rocks/oldversion - but for a private account you should use a trusted source, not from random person on the internet ^^

**Comment by chagai95** [comment]
Thx for thinking of me too, already did that but it kind of didn't work on some clients, it's very weird. Anyway check out riots.im

**Comment by t3chguy** [comment]
I suggest making a suggestion to the https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm project to support such a thing in that case, though that won't mean the Element product team wants that feature in its UX, that'd be up to the Product team if the technical problem was lifted.

**Comment by steadfasterX** [comment]
so as far as I understood there is a feature which was working fine before which is still present in the web UI and desktop client (Element version: 1.11.86
Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0) and which is not working anymore.

![image](https://github.com/user-attachments/assets/5b7fcef6-d0ad-40d5-b92f-640698b3b146)

To clarify @t3chguy is this a bug in the mentioned [rust project ](https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm) which broke the functionality in element or what happened? I am happy to provide any logs or open new issues wherever needed to get this functionality back..

**Comment by t3chguy** [comment]
Its a case of the crypto team along with product choosing to not bring that feature over to the rust crypto stack in matrix-js-sdk, apparently it is supported in the linked rust project.

**Comment by MRAAGH** [comment]
in the end, not every program needs every feature. But that's the magic of open source and open standards - if we don't like Element, we can use a different client

**Comment by t3chguy** [comment]
or even fork it
