### ISSUE TITLE
Add a way to open devtools for invite rooms

### ISSUE THREAD

**Issue by Twi1ightSparkle** [element-hq/element-web#27222]
#### What would you like to do?

Add a way to open devtools for rooms you're invited to.

#### Why would you like to do it?

To be able to easily see more info about a room before deciding to accept or reject.

#### How would you like to achieve it?

Maybe add the Element right click menu on invite rooms? Currently you just get the normal browser or OS right click menu when right clicking an invite.

![Screenshot 2024-03-20 at 10 59 22 AM](https://github.com/element-hq/element-web/assets/19155609/2eee71ae-d411-4e3a-b2bc-1bd98495ca72)

### Have you considered any alternatives?

Manually using the CS or Admin API to look at the room state, not very convenient, especially since it's [not trivial to get the room ID on Element Desktop](https://github.com/element-hq/element-meta/issues/2366).

**Comment by t3chguy** [comment]
Enable developer mode, then its in the bottom left corner Quick Settings menu.

<img width="225" alt="image" src="https://github.com/element-hq/element-web/assets/2403652/0053014a-fa3c-4a11-98e2-138baa75cb49">

**Comment by Twi1ightSparkle** [comment]
Ohhh, TIL about Quick Settings. Thanks
