### ISSUE TITLE
Redacting a poll vote makes the poll widget crash

### ISSUE THREAD

**Issue by jaller94** [element-hq/element-web#27223]
### Steps to reproduce

1. Have someone create a poll
2. Vote
3. Enable hidden events in the dev tools
4. Redact your `org.matrix.msc3381.poll.response` event

#### What did you expect?
The poll widget resets to what it looked like before I voted.

#### What happened instead?
The poll widget got replaced with `Can't load this message (org.matrix.msc3381.poll.start) Submit debug logs`

### Operating system

Manjaro Linux (based on the Arch repo)

### Browser information

Mozilla Firefox 124.0

### URL for webapp

element.nordeck.io

### Application version

Element version: 1.11.60 Crypto version: Olm 3.2.15

### Homeserver

Some Synapse

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Revoke your org.matrix.msc3381.poll.response event

What does this mean? The verb `Revoke` is only used in the context of permissions and 3pids in the app.

**Comment by HarHarLinks** [comment]
from context: "redact"
