### ISSUE TITLE
Verification @x:bit.ovh <-> @sneaker-net:matrix.org went quite wrong

### ISSUE THREAD

**Issue by sneaker-net** [element-hq/element-web#27241]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

### Will you send logs?

Yes

**Comment by MidhunSureshR** [comment]
Is the lack of information here intentional?

**Comment by t3chguy** [comment]
> Many requests coming in from Lewis, had no button to accept. Sending from x to Lewis worked fine ultimately. Lewis' first message in the room was plaintext also. Rust crypto on both sides

**Comment by richvdh** [comment]
Closing this for now as the information is hidden. Everyone who looks at this has to do a bunch of work to decipher it.

@t3chguy or @sneaker-net feel free to clarify the description and reopen.
