### ISSUE TITLE
Translation - FR - small grammar error

### ISSUE THREAD

**Issue by Epy** [element-hq/element-web#27256]
### Steps to reproduce

Hello
I didn't find the string in "src/i18n/strings/fr.json" file, so I made an issue. Hope this is ok

1. On Parameters > Sessions (also at first login a few versions ago)
2. When I'm using a not yet verified session (re-login after clearing cookies & data for example) I click on "Vérifier la session"
3. This popup appears: 
![image](https://github.com/element-hq/element-web/assets/450856/5bfda140-11ed-42f0-910b-b1408e4e4efa)

#### What did you expect ?
For the buttons "_Vérifier avec.._ " is the good grammar in this case, "_Vérifié avec ..._" is wrong in this situation (it would be ok when saying "session **has been verified** with ... "

It has been there for some versions, I thought someone would have catch it before :smile: 
Thanks !

### Operating system

any

### Browser information

Any

### URL for webapp

https://element.underworld.fr

### Application version

Version de https://element.underworld.fr : 1.11.63 Version crypto : Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### Will you send logs?

No

**Comment by t3chguy** [comment]
Translations are maintained by the community, we do not track issues for them. See https://web-docs.element.dev/Element%20Web/translating.html

**Comment by Epy** [comment]
Ok, sorry
