### ISSUE TITLE
Unable to attach a label with URI command

### ISSUE THREAD

**Issue by DarkExist** [element-hq/element-web#27258]
### Steps to reproduce

1. I'm in a chat room with a user.
2. I click "Attachment" and in the explorer that opens, I select the shortcut with the URI

#### I got destructive interruption

https://github.com/element-hq/element-web/assets/120075133/5a777d9e-76c7-428d-8eb6-551eb28c973e

### Operating system

Windows 10

### Browser information

Yandex 120.0.6099.736

### URL for webapp

app.element.io

### Application version

Element version: 1.11.63 Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### Will you send logs?

No

**Comment by t3chguy** [comment]
That modal is part of your browser. Web apps Can't create native error dialogs like the one in your video. This is not an element issue.
