### ISSUE TITLE
Can't see or scroll to latest messages (possibly only limited to Ferdium?)

### ISSUE THREAD

**Issue by mprasil** [element-hq/element-web#27251]
### Steps to reproduce

I can't quite pinpoint the version it started happening in, but last couple weeks I started observing an issue where Element won't let me scroll to latest messages.

1. Visit a room, leave it open, wait for new message
2. The message notification will show, the unread count ticker will update, but messages aren't visible in the chat window: ![image](https://github.com/element-hq/element-web/assets/8255364/cadcf15e-6728-4523-97f1-66fad4c1da3b)
3. Notice, that the scrollbar is at the very bottom, I can't even scroll down to new messages. Also notice the unread message count is showing 2 messages that I can't currently see.
4. Clicking the "jump to last message" button or switching to another room and back shows the last message as usual.

## Some notes

I could only reproduce this in [Ferdium](https://github.com/ferdium/ferdium-app) - it's a wrapper for web apps. Here are the versions of electron/chrome as reported by the app: 
![image](https://github.com/element-hq/element-web/assets/8255364/491c3754-2289-42a7-b4f2-523682293e13)

I could not reproduce this in firefox and haven't tested with other browser.

#### What did you expect?

I expect that Element will just scroll to latest message as they arrive.

#### What happened instead?

See description above.

### Browser information

Ferdium 6.7.2

### Application version

Element version: 1.11.62 Crypto version: Olm 3.2.15

### Homeserver

Synapse 1.103.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
See https://github.com/element-hq/element-web#supported-environments

> Issues only affecting unsupported environments are closed
