### ISSUE TITLE
Shift key + hovering over a message show options without needing to click the icon.

### ISSUE THREAD

**Issue by ARBoyGo** [element-hq/element-web#27260]
#### What would you like to do?
An feature to show options without the need to click the icon, By using shift key. I have seen it in discord, It would be good to move (react, reply and reply in thread) into options when hovering over message using shift key. 

#### Why would you like to do it?
Helps user to access message options more efficiently
 
#### How would you like to achieve it?
Shift key + hovering over a message 

It is small detail... I hope it doesn't take much time as well..

**Comment by t3chguy** [comment]
Duplicate of https://github.com/element-hq/element-web/issues/18711
