### ISSUE TITLE
Can't go back to threads overview after selecting a thread in the timeline while one is already open

### ISSUE THREAD

**Issue by iw0nderhow** [element-hq/element-web#27271]
### Steps to reproduce

1. Open a thread from the timeline.
2. Go back and forth between thread timeline view and thread list.
3. While the thread is open, select another one from the main timeline.
    Alternatively, try clicking the "Back" button in the Thread sidebar.

#### What did you expect?
I can go back to the threads overview. I can also open another thread from the main timeline.
#### What happened instead?
I can't go back to the threads overview. Clicking "Back" briefly blinks the overview and throws me back to the thread I was looking at before.
I can't open another thread. Clicking it in the main timeline briefly blinks its contents and throws me back to thread I was looking at before.
Selecting another room, waiting a short while and then switching back makes it possible to close the sidebar in the original room.

### Operating system

macOS

### Application version

Version von Element: 1.11.63 Krypto-Version: Olm 3.2.15

### How did you install the app?

From the website

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by richvdh** [comment]
+1. seeing the same here

**Comment by woffs** [comment]
> Selecting another room, waiting a short while and then switching back makes it possible to close the sidebar in the original room.

no longer seems to be helping

**Comment by kosmos** [comment]
+1

**Comment by kosmos** [comment]
I can't reproduce it in element-web, but in element-desktop the problem is reproduced very often

**Comment by kosmos** [comment]
Still reproduced in version 1.11.64.

**Comment by t3chguy** [comment]
> Still reproduced in version 1.11.64.

Yup, it hasn't been fixed, this issue is still open.

**Comment by florianduros** [comment]
Bug due to https://github.com/matrix-org/matrix-react-sdk/pull/12288

**Comment by kosmos** [comment]
> Bug due to [matrix-org/matrix-react-sdk#12288](https://github.com/matrix-org/matrix-react-sdk/pull/12288)

Do you know when the fix might be released for element-desktop?

**Comment by florianduros** [comment]
> > Bug due to [matrix-org/matrix-react-sdk#12288](https://github.com/matrix-org/matrix-react-sdk/pull/12288)
> 
> Do you know when the fix might be released for element-desktop?

There is no fix yet, please be patient.

**Comment by kosmos** [comment]
@florianduros  Is there any chance this fix will make it into the next version of element-desktop?

**Comment by florianduros** [comment]
> @florianduros Is there any chance this fix will make it into the next version of element-desktop?

Normally, it should

**Comment by kosmos** [comment]
Thanks
