### ISSUE TITLE
Message history no longer loads reliably (may get hidden behind spurious "You can't see earlier messages")

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27274]
### Steps to reproduce

See rageshake

#### What did you expect?

Visible history. Especially in non-E2EE rooms like this one.

#### What happened instead?

Incorrect "you can't see earlier messages" notification

### Application version

Element Nightly version: 2024040301 Crypto version: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ara4n** [comment]
This is completely reproduceable in the rageshaked room (which is unfortunate, as it's one of my main demo rooms)

**Comment by richvdh** [comment]
duplicate of https://github.com/element-hq/element-web/issues/22671
