### ISSUE TITLE
media download buttons do different things

### ISSUE THREAD

**Issue by 532910** [element-hq/element-web#27290]
### Steps to reproduce

1. Upload an image to the room.
2. Try to download it with two different buttons (see screenshots).

True download button:
![image](https://github.com/element-hq/element-web/assets/14617699/ad4c1eb9-d737-43ce-a804-d210e3656dbd)

Not a download button:
![image](https://github.com/element-hq/element-web/assets/14617699/537dbcd7-b701-409e-829d-c36abdc88514)

### Outcome

The first button saves file, the second one opens it in a new tab. The same for the desktop client.

### Operating system

linux

### Browser information

doen't matter

### Application version

1.11.63 

### Will you send logs?

No

**Comment by MidhunSureshR** [comment]
Can't repro, they both download the image for me. Tested with chromium and firefox on Ubuntu.

**Comment by 532910** [comment]
it's reproducible even in electron client for me

**Comment by 532910** [comment]
@MidhunSureshR, could you check it in the electron client?

**Comment by t3chguy** [comment]
This got fixed
