### ISSUE TITLE
User registration does not work

### ISSUE THREAD

**Issue by Malvineous** [element-hq/element-web#27294]
### Steps to reproduce

I am trying to use Matrix for the first time.  The instructions recommend using the web version of Element to register an account, but neither the web version or the desktop version allow accounts to be created.

I tried to create a Q&A for this instead of a bug report, but of course that just asks me to register for an account which currently cannot be done.

With the desktop version, I can get up to the point where I have to tick the "are you a robot" tickbox, then I repeatedly get asked to identify motorbikes, traffic lights, fire hydrants, etc.  After identifying about 20 of these one after the other I got sick of it and gave up.  This is just too onerous on people, requiring them to identify so many images just to create an account.  Other sites only ask you to identify one or at most two images, but 20+ is just going to make people like me go somewhere else.

Then I tried on the web version in Firefox instead, and it came up with a red message saying something about reCAPTCHA already having been rendered, but in Firefox it allowed me through without asking me to identify any sort of street furniture.  However then it required me to confirm my e-mail address.  When I clicked on the link in my e-mail to do so, it says "return to your client" but the client still says "Check your e-mail to continue".  I clicked on the link in my e-mail three or four times and each time it said to return to my client, but each time the client still remained with the same message telling me to check my e-mail.

I refreshed the page but this just took me back to the start of the registration process, asking for all my information all over again!

I'm not sure what's going on but I have to say, if this is the experience you expect people to have when trying out your service, it's never going to go anywhere.  For now I am going to give up and try something else as this service is clearly not ready for real world use.  I just thought it best to pass along my frustrating experience before I go, otherwise you may not realise why people are choosing other services over your own.

#### What did you expect?

To register and account so I could see if Matrix is worth using.

#### What happened instead?

I became frustrated with two buggy interfaces that did not work and gave up.

It says at the bottom of this bug report I can type `/rageshake` to generate logs, but all this does is open the browser search bar and tell me "rageshake" could not be found on the registration page.

### Operating system

Arch Linux

### Browser information

Firefox 124.0.2

### URL for webapp

https://app.element.io/#/register

### Homeserver

Unable to register with matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> I can get up to the point where I have to tick the "are you a robot" tickbox, then I repeatedly get asked to identify motorbikes, traffic lights, fire hydrants, etc. After identifying about 20 of these one after the other I got sick of it and gave up. This is just too onerous on people, requiring them to identify so many images just to create an account.

The recaptcha requirement comes from your chosen Matrix server, not the client. You would need to seek help from them. 

This sounds like an issue with the server, I suggest seeking help from them. Element is just a client for the Matrix network and connects to a specified Matrix server.

If that is matrix.org then that would be support@matrix.org
