### ISSUE TITLE
Failed HTTP requests for /config.json, missing in /usr/share/nginx/html/

### ISSUE THREAD

**Issue by valankar** [element-hq/element-web#27303]
### Steps to reproduce

I'm using the docker version of element-web: `vectorim/element-web`

I notice the following request in the logs (replaced my real domain with MYDOMAIN):

```
2024/04/09 06:33:47 [error] 22#22: *1 open() "/usr/share/nginx/html/config.MYDOMAIN.json" failed (2: No such file or directory), client: 172.29.0.1, server: localhost, request: "GET /config.MYDOMAIN.json?cachebuster=1712644427649 HTTP/1.1", host: "MYDOMAIN"
172.29.0.1 - - [09/Apr/2024:06:33:47 +0000] "GET /config.MYDOMAIN.json?cachebuster=1712644427649 HTTP/1.1" 404 555 ...
```

My config.json looks like:

```
{
    "default_server_name": "MYDOMAIN"
}
```

What is this request for and is there a way to configure it properly?

#### What did you expect?
config.json to by retrieved properly.

#### What happened instead?
404 error.

### Operating system

Windows

### Browser information

Microsoft Edge Version 123.0.2420.81

### Application version

Element version: 1.11.63 Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### Homeserver

Synapse docker from matrixdotorg/synapse:latest

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The file is optional, for if you are using a single CDN on multiple domains and want a different config per-domain. I suggest reading the docs. https://github.com/element-hq/element-web/blob/develop/docs/config.md
