### ISSUE TITLE
More Discord like voice

### ISSUE THREAD

**Issue by BasilYes** [element-hq/element-web#27304]
#### What would you like to do?
Ability to disable outgoing voice call sound, ability to disable this type of notification for room
![image](https://github.com/element-hq/element-web/assets/36816595/b5d5ab3c-4f99-4493-b5cb-e69a30610ee4)
 or more convenient, ability to move this notification some where to room widget (like on image below) 
![image](https://github.com/element-hq/element-web/assets/36816595/ff3fcdf7-3b30-4945-b87c-5f23991fe49c)
and last, not least ability to stay in call without other people 
#### Why would you like to do it?
I want to stay in room where my friends can join me
#### How would you like to achieve it?
Just check button in room settings (maybe multiple)

### Have you considered any alternatives?

Discord?

**Comment by t3chguy** [comment]
> I want to stay in room where my friends can join me

This is possible via Video Rooms in beta (you can turn off your webcam obviously)

**Comment by BasilYes** [comment]
> > I want to stay in room where my friends can join me
> 
> This is possible via Video Rooms in beta (you can turn off your webcam obviously)
> <img alt="image" width="1000" src="https://private-user-images.githubusercontent.com/2403652/320757083-738a854a-5b39-433a-9a45-b082c0464338.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDc4MDUsIm5iZiI6MTcxMjY0NzUwNSwicGF0aCI6Ii8yNDAzNjUyLzMyMDc1NzA4My03MzhhODU0YS01YjM5LTQzM2EtOWE0NS1iMDgyYzA0NjQzMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDcyNTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmE1MDc4NjE0MTJhNjAxZjU2YjJmMzVhZWVhNGY5YjlkODllZWFiMGUyNjViYTM0MzFkZGQ3M2IzYWQxOGM1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Tn6WCv-tOyZiOewD_iYcPu8VahyvbF1ouq9V7rSqiZs">

Oh, Big thanks. Didn't noticed it
