### ISSUE TITLE
With v1.11.64 sending a message in a room fails

### ISSUE THREAD

**Issue by Fail-Unsafe** [element-hq/element-web#27322]
### Steps to reproduce

I upgraded Element Web (and Desktop) to version v1.11.64 coming from v1.11.63. We have a public room, comparatively large with >2000 users, and one account that serves as a moderator to send messages. All others accounts are read-only, i.e. it's basically a room for public announcements. This moderator account and newly created accounts with moderator rights are no longer able to send messages to that room. This apparently only happens on v1.11.64. We downgraded again and the message went through. The room version is 6.

![grafik](https://github.com/element-hq/element-web/assets/26485846/3b8c517b-3165-47cb-8636-c17736095c83)

#### What did you expect?
Write messages from that moderator account as before

#### What happened instead?
I receive an error message just like the one in the screenshot.

### Operating system

Windows

### Browser information

Firefox 115.9.1esr (64-Bit)

### URL for webapp

v1.11.64

### Application version

Version: 1.11.64 Krypto-Version: Olm 3.2.15

### Homeserver

Synapse Version 1.104.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Will you send logs?
No

Without logs there is nothing to go off here
