### ISSUE TITLE
suddenly? as of recently? no session backs up keys any more? linux-application,  android (classic and X) and web sessions involved only

### ISSUE THREAD

**Issue by subscribernamegoeshere** [element-hq/element-web#27357]
### Steps to reproduce

long term matix.org user and coming a long way with a very simple (only chatting to a friend) account

I only have a linux (rpm, suse) application session which DID back up the keys so far in the past years or so. only today I found out, when the android "element X" app updated (shows version: 0.4.9) itself that this app/session was suddenly asking me to verify itself via another device/session of mine. i successfully did so. but then I went into to the security details on my other (linux firefox) web session and into my linux (rpm,suse) application and there it showed that none of my sessions?devices? were backing up my keys any more.

there is one black/white button/area that says "connect this session to key backup" and above that a huge load of text warning that I should just yet NOT LOG OUT before I enable key backup before etc.

I click this button, and it briefly flickers a popup and says like 80keys imported or so, then this settings/security box vanishes but when I revisit this (in linux rpm application) its back and the same state again no key backup yet and reconnect this session to key backup over and over. the same fail and same 80keys import and button and re-connect to key backup is possible in the linux firefox web session but also doesnt progress there as well.

this used to be backed-up and fine for a long time now in the past all without a problem.

i am not sure if the todays android "element x" app update was involed in any way in this scenario, but this was the reason I was looking into this area to begin with.

i did back up? write down? the keys or some keys? recovery? in the past before I think or even exported some kind of recovery file or so, something rings a bell.

please help I dont want to lose any chat or history and the account itself and ID etc. how to resolve this matter?

using element-web and element-desktop rpm packages 1.11.64 both on the linux, rpm  machine, and simply surfing the app.element.io webpage on the linux, firefox browser session.

thanks in advance.

#### What did you expect?
key backup to work normally continuing to work normally
#### What happened instead?
key backup apparently dislocated or disconnected from the matrix.org? backends etc or so I understand.

### Operating system

opensuse linux 15.5

### Application version

element-desktop-1.11.64 and element-web-1.11.64 (opensuse build)

### How did you install the app?

rpm on opensuse leap 15.5

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by subscribernamegoeshere** [comment]
maybe? related reports at:
https://github.com/element-hq/element-web/issues/27330
https://github.com/element-hq/element-web/issues/27327

**Comment by t3chguy** [comment]
Please report issues with community maintained applications to their maintainer, we do not maintain the opensuse build.
