### ISSUE TITLE
Nachricht nicht lesbar, weil nicht entschluesselt.

### ISSUE THREAD

**Issue by YannickD73** [element-hq/element-web#27364]
### Steps to reproduce

im private Raum einen Nachricht schreiben.
Auf Antwort warten. PC ausschalten. PC neu starten. Einloggen.
Antwort angekommen, aber "Nachrichten-Entschlüsselung nicht möglich
Nachrichten-Entschlüsselung nicht möglich".
alles mögliche versucht... aber ohne Erfolg.

#### What did you expect?
Antwort lesen können.
#### What happened instead?
Nachrichten-Entschlüsselung nicht möglich

### Operating system

Windows 10 Pro

### Browser information

Firefox 125.0.1 (64-Bit)

### URL for webapp

https://messenger.bycs.de/#/room/!EZADIKOokOvWNmMNGP:messenger.bycs.de

### Application version

Version von ByCS-Messenger: 3.2.1-production Version von Olm: 3.2.12

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This issue tracker is English-only.

> ByCS-Messenger: 3.2.1-production

This isn't a product we support, I suggest seeking help from ByCS.
