### ISSUE TITLE
Paste into Message Edit Field Not Working

### ISSUE THREAD

**Issue by JamesPC44** [element-hq/element-web#27367]
#### What did you expect?
Clipboard content to be pasted
#### What happened instead?
Nothing

This works on Chromium Version 123.0.6312.122 (Official Build) snap (64-bit) on the same machine. All FF extensions were disabled for testing. Has been an issue for probably over a year. Has not been an issue on any other website that I have seen in the meantime. Ctrl+v and pasting from the right-click menu are both affected.

### Operating system

Ubuntu 20.04

### Browser information

Firefox 124.0.2

### URL for webapp

app.element.io

### Application version

Element version: 1.11.64 Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by JamesPC44** [comment]
Logs sent!

**Comment by t3chguy** [comment]
Can you check `about:config` for `dom.event.clipboardevents.enabled` - if it is `false` (disabled) then the is a non-standard behaviour in the web and unsupported. See https://github.com/element-hq/element-web/issues/25544

**Comment by JamesPC44** [comment]
It is `false`

This is very disappointing to see not planned. I've had that on for well over a year, and this is the only site I have this issue with. Disabling clipboard events is valuable as it prevents pages from blocking copy/paste. Since Element (presumably) isn't doing that, I fail to see why we can't let "normal" copy/paste work. This not working lead to me moving away from Element, I figured it would start working again.

**Comment by JamesPC44** [comment]
What are "pills"?

**Comment by t3chguy** [comment]
<img width="771" alt="image" src="https://github.com/element-hq/element-web/assets/2403652/b5e914a1-2253-4a4b-97d7-06e583578246">

The room link in this message is an example of a [room] pill
