### ISSUE TITLE
Incorrect event ID sent when redacting via devtools

### ISSUE THREAD

**Issue by Kladki** [element-hq/element-web#27379]
### Steps to reproduce

1. Send an event
2. Copy it's event ID via "view source"
3. Open `/devtools`
4. Press "Send custom timeline event"
5. Send the `m.room.redaction` event with a body such as:
```json
{
  "redacts": "$lOT5IEprRf1g749wrHZrQA0CllCNkLGXlGf8X_EFhC0"
}
```
6. Send the event

#### What did you expect?
For the event to be redacted
#### What happened instead?
Got the following error:
```
Failed to send event! (MatrixError: [404] M_NOT_FOUND: Event is not known to the server (https://conduit-test-server.ahouansou.cz/_matrix/client/v3/rooms/!gZzrVztZOax5VSZ6qv%3Aconduit-test-server.ahouansou.cz/redact/$redactsEventId/m1713812489664.1))
```
The "$redactsEventId" was not added by me, this is literally what element sent as the event ID even when I set the `redacts` field to `$lOT5IEprRf1g749wrHZrQA0CllCNkLGXlGf8X_EFhC0`,

### Operating system

Alpine Linux Edge

### Browser information

Firefox 125.0.1

### URL for webapp

app.element.io

### Application version

Element version: 1.11.64 Crypto version: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1

### Homeserver

Conduit 0.7.0-alpha (27753b1), but I can also reproduce the issue with Synapse 1.104, which in that case the error is the following:
```
Failed to send event! (MatrixError: [400] Cannot provide a redacts value incoherent with the event_id of the URL parameter (https://synapse-test-server.ahouansou.cz/_matrix/client/v3/rooms/!EIsxy1xoEzjgNqVKQY%3Aconduit-test-server.ahouansou.cz/redact/$redactsEventId/m1713813549902.8))
```

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The devtools does not have the `/redact` API. Only `/state` and `/send`.

**Comment by t3chguy** [comment]
Ah looks like the js-sdk has the same codepath under the hood. That's unexpected and undocumented.

![image](https://github.com/element-hq/element-web/assets/2403652/1d3deed3-2f26-40be-a378-af36724dd9a7)

**Comment by Kladki** [comment]
> given the `/send` API does not work for redactions.

Where in the spec does it state this? Because I cannot find it.

**Comment by t3chguy** [comment]
It isn't explicit but it is between the lines.

https://spec.matrix.org/v1.10/client-server-api/#mroomredaction

> This event is created by the server to describe which event has been redacted

then the very next block tells you how to instruct your server to send such an event https://spec.matrix.org/v1.10/client-server-api/#put_matrixclientv3roomsroomidredacteventidtxnid

Looking at the Synapse source code, only this API `"/rooms/(?P<room_id>[^/]*)/redact/(?P<event_id>[^/]*)"` handles redactions correctly.

**Comment by Kladki** [comment]
Ah ok. Well if you decide not to handle it, please make some sort of client-side error saying that these events cannot be sent using the devtools.

**Comment by t3chguy** [comment]
> please make some sort of client-side error saying that these events cannot be sent using the devtools.

Really it should be down to whatever error the server provides for `m.room.redaction` over `/send` - the fact it tries to send it via `/redact` and breaks is a bug but likely not one we'll fix given we have too much roadmap work to focus on devtools.

**Comment by t3chguy** [comment]
Turns out Synapse gets really upset if you try redact via the send endpoint

![image](https://github.com/element-hq/element-web/assets/2403652/bce0b040-e4cc-4618-8218-e3f6e4d2a119)
