### ISSUE TITLE
Big and empty grey notification dot upon marking room as read

### ISSUE THREAD

**Issue by Johennes** [element-hq/element-web#27372]
### Steps to reproduce

1. Had a stuck notification in the Matrix & Ex-Matrix Room, I assume due to the latest thread
2. Marked room as read via context menu
3. Big grey dot appeared instead of normal notification dot / badge
4. Marked room as read _again_
5. Big grey dot disappeared

![Screenshot 2024-04-22 at 08 10 59](https://github.com/element-hq/element-web/assets/1137962/9fa32ed9-7147-4764-bd0a-31b004f172a5)
![Screenshot 2024-04-22 at 08 11 07](https://github.com/element-hq/element-web/assets/1137962/0bdf329e-2d3d-43d2-8241-d8f1fca3ae2d)

#### What did you expect?

No big grey dot

#### What happened instead?

The big grey dot

### Operating system

macOS

### Browser information

Firefox 124.0.2

### URL for webapp

app.element.io

### Application version

Element version: 1.11.64 Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Marked room as read via context menu

Are you sure you didn't mark it as *unread* at any point? That's the only way I can repro this

<img width="195" alt="image" src="https://github.com/element-hq/element-web/assets/2403652/e4e7fc7a-332e-43a6-9c66-339e5581b89c">

**Comment by Johennes** [comment]
Oh! Yeah, that might be it. I frantically clicked the top button in that popup to clear the stuck notification and might not have realized that it had changed to "Mark _un_read". While I can't reproduce this anymore without a new stuck notification and it might have been user error, it's probably ok to close this.
