### ISSUE TITLE
Screensharing crashes a call on Chrome 124

### ISSUE THREAD

**Issue by Dziango** [element-hq/element-web#27373]
### Steps to reproduce

1. Audio call another person
2. Attempt to share your screen
3. Call immediately crashes

#### What did you expect?
Screensharing working as usual.
#### What happened instead?
The call crashed. It seems that the problem applies exclusively to Chrome version 124.0.6367.60. The previous version, 123.0.6312.122, works just fine, as does Firefox.

At first, I noticed such behavior on our own server. However, I checked, and the same problem applies for app.element.io.

From what I can gather, there seems to be a problem with the AV1 codec:
```
`DEBUG: Call 1713532391264S7TWnfigHdEhMFKK gotLocalOffer() failed to create offer: {\"stack\":\"Error: Failed to execute 'setCodecPreferences' on 'RTCRtpTransceiver': Invalid codec preferences: invalid codec with name \\\"AV1\\\".\\n at R.getRidOfRTXCodecs (https://[redacted]/bundles/79a6ead0638f088928c8/bundle.js:2:765354)\\n at R.gotLocalOffer (https://[redacted]//bundles/79a6ead0638f088928c8/bundle.js:2:763018)\\n at R.wrappedGotLocalOffer (https://[redacted]//bundles/79a6ead0638f088928c8/bundle.js:2:762673)\\n at https://[redacted]//bundles/79a6ead0638f088928c8/bundle.js:2:762530\"}",`
```

### Operating system

Debian12

### Browser information

Chrome Version 124.0.6367.60

### URL for webapp

app.element.io

### Application version

Wersja Element: 1.11.64 Wersja krypto: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1

### Homeserver

Synapse 1.98.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This looks like an upstream issue https://issues.chromium.org/issues/331565934
