### ISSUE TITLE
Migrating key backup to 4s fails

### ISSUE THREAD

**Issue by MichaelErjemenko** [element-hq/element-web#27383]
### Steps to reproduce

1. Sign in with a new account via SSO at the Android-Client
2. Create a private room and send a message
3. Open the "Security & Privacy" settings, click on "Encrypted Messages Recovery" / German: "Wiederherstellung verschlüsselter Nachrichten", then select "Start Using Key Backup" / German: "Richte Schlüsselsicherung ein" and complete the setup process.
4. Sign out and sign in again with the android client.
5. After restoring the history in the settings ("Restore From Backup") all messages are decrypted and nothing indicates that there are problems. (The 4S was not setup with this process on purpose.)
6. Sign out
7. Sign in with the web-client
8. Click on ```Upgrade``` in the ```Encryption upgrade available``` dialog / modal. The ```Upgrade your encryption``` dialog opens
9. Click on ```Restore``` and enter your passphrase / recovery key.
	=> The message is decrypted but the ```Upgrade your encryption``` dialog remains.
		The Security & Privacy page shows ```Thsi session inot backing up your keys, [...]```, ```Cross-signing is ready but keys are not backed up.``` and the session is not trusted.
10. Send a message.
1.. Try to sign out
	=> It is shown that this session is not backed up. So connect with the secure storage but this doesn't help. If you try to sign out it is shown again.

Images for the steps:

**1-sign-in-android**
<img width="400" alt="1-sign-in-android" src="https://github.com/element-hq/element-web/assets/74231838/0a7ba173-6a76-44cd-b92e-bf64ae104cd8">

**2-1-create-private-room**
<img width="400" alt="2-1-create-private-room" src="https://github.com/element-hq/element-web/assets/74231838/dc6c9722-8c03-45d0-9498-849d49146147">

**2-2-send-message** 
<img width="400" alt="2-2-send-message" src="https://github.com/element-hq/element-web/assets/74231838/25fd8b48-e42a-404a-ba73-5aa03edd6d5f">

**3-1-set-up-key-backup**
<img width="400" alt="3-1-set-up-key-backup" src="https://github.com/element-hq/element-web/assets/74231838/09fccdb8-2bcf-439a-9fd9-6dc43a071b5d">

**3-2-set-up-key-backup**
<img width="400" alt="3-2-set-up-key-backup" src="https://github.com/element-hq/element-web/assets/74231838/d956c6ef-1508-49da-a98d-8c1eb0642540">

**3-3-set-up-key-backup**
<img width="400" alt="3-3-set-up-key-backup" src="https://github.com/element-hq/element-web/assets/74231838/fac2de37-cf6c-45f1-b062-8613979dc682">

**5-1-restore-from-backup**
<img width="400" alt="5-1-restore-from-backup" src="https://github.com/element-hq/element-web/assets/74231838/63051368-0ea6-4378-86cd-339160cbd054">

**5-2-message-decrypted**
<img width="400" alt="5-2-message-decrypted" src="https://github.com/element-hq/element-web/assets/74231838/a5e6d23b-775e-4c4c-9df8-a9853c75eba3">

**7-sign-in-web**
<img width="696" alt="7-sign-in-web" src="https://github.com/element-hq/element-web/assets/74231838/95217543-3313-4083-a8bf-51e7102e2bc8">

**8-upgrade-encryption**
<img width="696" alt="8-upgrade-encryption" src="https://github.com/element-hq/element-web/assets/74231838/ee9f3112-9fc9-4dd7-b706-7a1f9d4431c1">

**9-1-upgrade-encryption**
<img width="696" alt="9-1-upgrade-encryption" src="https://github.com/element-hq/element-web/assets/74231838/78f0c13e-ceee-47e5-a690-78daaa0100dd">

**9-2-decrypted-messages-but-dialog-remains**
<img width="696" alt="9-2-decrypted-messages-but-dialog-remains" src="https://github.com/element-hq/element-web/assets/74231838/d73b70a1-796c-4a16-a3c0-e050ead778e0">

**9-3-not-backing-up-keys**
<img width="696" alt="9-3-not-backing-up-keys" src="https://github.com/element-hq/element-web/assets/74231838/9232e415-7aa5-4ccc-8848-a5684745f46e">

**9-4-unverified-session**
<img width="696" alt="9-4-unverified-session" src="https://github.com/element-hq/element-web/assets/74231838/c024f99b-4cb5-4d0d-a8fd-924d67b8978d">

**10.1-1-sign-out**
<img width="696" alt="10 1-1-sign-out" src="https://github.com/element-hq/element-web/assets/74231838/f0836a52-8c4d-4870-9a0f-11ecff125ee1">

**10.1-2-sign-out**
<img width="696" alt="10 1-2-sign-out" src="https://github.com/element-hq/element-web/assets/74231838/cebaa22d-e6aa-4e64-ba91-36701eec0efe">

#### What did you expect?
After step 9: The messages should be decrypted.
At step 10: The session should be connected to the secret storage / key backup and no warning should be shown.

#### What happened instead?
After step 9: The message(s) are not decrypted.

### Operating system

Windows

### Browser information

Google Chrome 123.0.6312.124

### Application version

Element Web v1.11.64, Android 1.6.14

### Homeserver

Synapse v1.101.0

### Will you send logs?

No

**Comment by richvdh** [comment]
To me, this feels like a bug in the Android client. I'm unconvinced that we should support this migration flow just to deal with the brokenness of another client. Will see what the rest of the team thinks.

**Comment by MichaelErjemenko** [comment]
Perhaps I don't know about some specifications or similar, but shouldn't the server ensure that such a situation cannot occur? I mean otherwise any client could just "break" any account by using key backups but not 4s. (While some other clients still would / could handle this situation.)
Furthermore, what is in the case that one come from a client (version) where key backups without 4s were supported and now just wants to use the web client. At the moment the user would just observ an unexpected behaviour (in the best case) and changes in the android client (or any other client) wouldn't help him/her.

**Comment by richvdh** [comment]
> Perhaps I don't know about some specifications or similar, but shouldn't the server ensure that such a situation cannot occur? I mean otherwise any client could just "break" any account by using key backups but not 4s.

Possibly, though the scenario is allowed by the Matrix spec, even if Element-Web doesn't support it, so we'd need changes to the spec before we can enforce it on the server. Maybe that could be done, but it's a bunch of work nobody has time for right now.

> Furthermore, what is in the case that one come from a client (version) where key backups without 4s were supported and now just wants to use the web client.

I don't really understand this question. If you're saying "Element-Web should fail gracefully in this situation", then I agree.
