### ISSUE TITLE
Search is broken after message edits

### ISSUE THREAD

**Issue by rda0** [element-hq/element-web#27386]
### Steps to reproduce

1. Create a new room
2. Send message: `foo`
3. Send message: `bar`
4. Search for `foo` or `bar` works :heavy_check_mark: 
5. Edit the `bar` message: `bar` -> `foo`

#### What did you expect?
6. Search for `foo` shows 2 `foo` results
7. Search for `bar` shows nothing (I think I would not expect to find the original message before the edit)
 #### What happened instead?
6. Search for `foo`: shows nothing (`No more results`)
7. Search for `bar`: shows 2(1) `foo` result (I think it only finds 1 message and the other is shown as surrounding text)

### Operating system

Linux

### Browser information

Firefox 125.0.2 (64-bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.65

### Homeserver

multiple

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The search is done by the Matrix Server, so you'd have to open your issue there. You haven't specified which server you are using so I cannot point you to the appropriate repository.

**Comment by rda0** [comment]
@t3chguy Done.
update: homeserver info (matrix.org). It happens in encrypted and unencrypted rooms.

**Comment by t3chguy** [comment]
matrix.org uses https://github.com/element-hq/synapse/
