### ISSUE TITLE
Incoming user verification request toast says "Verify Session"

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#27393]
* Alice sends Bob a verification request
* Bob sees a toast with "Verify Session".
 
It should be "Verify User".

**Comment by dhananjay0610** [comment]
Hey, I am raising pr for this, small fix

**Comment by richvdh** [comment]
@dhananjay0610:

> Hey, I am raising pr for this, small fix

did you get anywhere on this? As you say it's a small fix so if you're not able to work on it please say so, so someone else can pick it up.

**Comment by gongarher** [comment]
This would be the cause of #27056

**Comment by richvdh** [comment]
> This would be the cause of #27056

No, I don't think so. This is literally just a wording change in the UI.
