### ISSUE TITLE
Add a button to access to room user list directly

### ISSUE THREAD

**Issue by iwalkalone69** [element-hq/element-web#27391]
#### What would you like to do?
Adding a button in the room header to open room user list directly.

#### Why would you like to do it?
There are too many steps to see the room user list.

#### How would you like to achieve it?
Just adding a button in the room header like we have to access threads.

**Comment by t3chguy** [comment]
This is already done in the New Room header which is in labs on develop.element.io
<img width="302" alt="image" src="https://github.com/element-hq/element-web/assets/2403652/6744ce1c-48c2-4694-99bc-ab4428b692eb">
