### ISSUE TITLE
Cannot find type definition file for 'testing-library__jest-dom'

### ISSUE THREAD

**Issue by MarcWadai** [element-hq/element-web#27392]
### Steps to reproduce

1. Where are you starting? What can you see?
I have a [fork](https://github.com/tchapgouv/matrix-react-sdk-tchap) of matrix-react-sdk that I use as a subtree in my project.
When trying to build my fork, it fails when running the command :
yarn build:types

output :

error TS2688: Cannot find type definition file for 'testing-library__jest-dom'.
  The file is in the program because:
    Entry point for implicit type library 'testing-library__jest-dom'

Found 1 error.

I didn't touch any configuration files or added any dependencies in the project.

#### What did you expect?
To build my matrix-react-sdk fork in my project

#### What happened instead?
An error occurred 

### Operating system

ArchLinux, node 18.19.1 

### Application version

matrix-react-sdk 3.95.0

### Will you send logs?

Yes

**Comment by MidhunSureshR** [comment]
Hey :wave: ,
Can you pull the latest upstream and see if this is still an issue?

**Comment by t3chguy** [comment]
Closing due to lack of response
