### ISSUE TITLE
number of people in a room has disappeared with Element version 1.11.65 / Crypto version: Olm 3.2.15

### ISSUE THREAD

**Issue by D4n2021** [element-hq/element-web#27403]
### Steps to reproduce

1. select a room
2. open information sidebar ("i" in top right corner)

#### What did you expect?

To see the amount of people in the room. So either right there it should say "xxx People", or once you click on "People" it should display the number above the "Invite to this room" button in the empty area

#### What happened instead?

Only says "People" there.

![grafik](https://github.com/element-hq/element-web/assets/20766261/de81a9d2-f92a-46e0-9cc3-924b930c296f)

![grafik](https://github.com/element-hq/element-web/assets/20766261/3568dc91-7229-489f-a776-96bade082927)

### Operating system

Win 10

### Browser information

Firefox 125.0.3

### URL for webapp

https://chat.mozilla.org

### Application version

Element version 1.11.65 / Crypto version: Olm 3.2.15

### Homeserver

mozilla.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is an intentional change as with the new room header (labs) the count moved there

![image](https://github.com/element-hq/element-web/assets/2403652/163db33b-d512-439e-8369-eb8a5acb0fc7)

**Comment by t3chguy** [comment]
Yes

**Comment by t3chguy** [comment]
Your screenshot shows the old room header.

I suggest you read my comment again


> the new room header (labs) the count moved there

**Comment by t3chguy** [comment]
chat.mozilla.org has most of the labs flags hidden, you can try develop.element.io

**Comment by t3chguy** [comment]
@D4n2021 https://github.com/element-hq/element-meta/wiki/Issue-labelling
