### ISSUE TITLE
Avatar display issue on 1:1 call

### ISSUE THREAD

**Issue by I-lander** [element-hq/element-web#27427]
### Steps to reproduce

In a 1:1 private conversation with another person, when receiving a call, the avatar icon is stretch :

#### What did you expect?
![2024-05-03_10-20](https://github.com/element-hq/element-web/assets/91682618/e5464638-9f48-479e-a1c1-47c1fd8e214a)

#### What happened instead?
![2024-05-03_10-21](https://github.com/element-hq/element-web/assets/91682618/9f25e293-ee73-4bd2-8387-298883cd49a4)
### Operating system

any

### Application version

Version de Element : 1.11.65

### Homeserver

any

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
dupe of #26598, possibly #26183
