### ISSUE TITLE
No Notifications in Systray / Taskbar (Kubuntu)

### ISSUE THREAD

**Issue by JPRuehmann** [element-hq/element-web#27428]
### Steps to reproduce

1. Where are you starting? What can you see?
Desktop
3. What do you click?
Nothing
5. More steps…
Nothing

#### What did you expect?
little red Dot with a number of new Messages at an App Icon.
#### What happened instead?
nothing

### Operating system

Kubuntu 24.04 LTS

### Application version

1.11.64

### How did you install the app?

From the Repository (SNAP)

### Homeserver

matrix.piratenpartei.de

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The snap package is not made by us, you'd have to seek support from its maintainer.
