### ISSUE TITLE
CSS is broken when using firefox < 96 since recent updates (1.11.65)

### ISSUE THREAD

**Issue by MarcWadai** [element-hq/element-web#27435]
### Steps to reproduce

1. Where are you starting? What can you see?
Using version 91.4 of firefox and latest element web 1.11.65 (and every version of firefox before 97).  The UI is broken, modals, font and icons are not showing up correctly.

![image](https://github.com/element-hq/element-web/assets/10048869/9ab3cb65-5ab8-47fa-9082-9ab4e77949b5)
![image](https://github.com/element-hq/element-web/assets/10048869/d58b4758-ef30-4cbf-b582-4f04499a40ec)

3. What do you click?
The general behavior seems to be working fine 

5. More steps…
We can see in the console that  error, to a lot of css files : 
![image](https://github.com/element-hq/element-web/assets/10048869/19748fc1-5aa5-4049-b404-847b8876a79b)
It has difficulty loading resources.

#### What did you expect?
To have normal behavior with vesion 91.4 at least of firefox. It used to work correctly with element 1.11.58 for sure, but i don't know from which version it started to break from there.  Maybe since the refine of styles to match compound ? https://github.com/matrix-org/matrix-react-sdk/pull/12299

#### What happened instead?
The UI is broken, modals, font and icons are not showing up correctly when using oldere version of firefox 

### Operating system

windows 11

### Browser information

Firefox 91.4

### URL for webapp

element.io

### Application version

1.11.65

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by florianduros** [comment]
Hi,

Firefox 91.4 is 2.5 years old and according to https://github.com/element-hq/element-web#supported-environments we don't support it.
