### ISSUE TITLE
Meta: Unsorted Web-R rollout issues (bug reports)

### ISSUE THREAD

**Issue by kegsay** [element-hq/element-web#27430]
### Steps to reproduce

We've been keeping a closer eye on web rageshakes during the rollout process of Element-Web R. This issue tracks a bunch of bug reports the crypto team have seen:

 - https://github.com/element-hq/element-web/issues/27445
 - https://github.com/element-hq/element-web/issues/27424
 - [Failed to read large IndexedDB value](https://github.com/matrix-org/element-web-rageshakes/issues/25744) - `at matrix_sdk_crypto_wasm::machine::OlmMachine::init_helper::{{closure}}::hdee547490c4871f2 (wasm://wasm/015ea1ee:wasm-function[228]:0x46c83)`
 - https://github.com/element-hq/element-web/issues/27447
 - [Unable to load session Loading chunk 5484 failed](https://github.com/matrix-org/element-web-rageshakes/issues/25782) -> https://github.com/element-hq/element-web/issues/27361
 - [Unable to load session The pickle uses an unsupported version](https://github.com/matrix-org/element-web-rageshakes/issues/25762) -> https://github.com/element-hq/element-web/issues/27449
 - [Unable to load session Can't find variable: WebAssembly](https://github.com/matrix-org/element-web-rageshakes/issues/25759) -> https://github.com/element-hq/element-web/issues/27424
 - https://github.com/element-hq/element-web/issues/27450
   - [Unable to load session invalid type: map, expected a sequence at line 1 column 0](https://github.com/matrix-org/element-web-rageshakes/issues/25758)
   - [Unable to load session invalid type: null, expected a sequence at line 1 column 4](https://github.com/matrix-org/element-web-rageshakes/issues/25757)
   - [Unable to load session invalid type: integer `123`, expected a string at line 1 column 4](https://github.com/matrix-org/element-web-rageshakes/issues/25745)

### Outcome

If rust crypto needs some new fangled things, we should fail gracefully if said things do not exist e.g use Modernizr.

### Will you send logs?

No

**Comment by richvdh** [comment]
I've been through these and filed bugs for most of them (now linked above). The only thing I think we need to worry about immediately is https://github.com/element-hq/element-web/issues/27447; the others are weird corner-cases that I don't think should block rollout.
