### ISSUE TITLE
Seeing threads notifications in room list

### ISSUE THREAD

**Issue by daniellekirkwood** [element-hq/element-web#27440]
### Steps to reproduce

1. Where are you starting? What can you see?
 i can see notifications for threads in the room list (but i have TAC)
3. What do you click?
i click to open the room to the main timeline from the room list but the notification count does not clear
5. More steps…
the only thing that clears the count is manually marking all threads as read from the thread panel

#### What did you expect?
not to see the thread notification count in the room list

#### What happened instead?
saw the thread notification count in the room list :/

### Operating system

MacOS

### Application version

2024050701

### How did you install the app?

nightly updated

### Homeserver

ems

### Will you send logs?

Yes

**Comment by daniellekirkwood** [comment]
video attached here: https://github.com/element-hq/wat-internal/issues/210

**Comment by daniellekirkwood** [comment]
this might be a release blocker @langleyd @dbkr @florianduros ... i'm tempted to mark it as such unless y'all tell me this is expected and i'm just missing something

**Comment by t3chguy** [comment]
With it affecting the release at such a late stage, if this is considered a release blocker then the TAC de-labsing would be backed out of the current release cycle.

**Comment by daniellekirkwood** [comment]
we can't reproduce it anywhere so probably not a blocker

**Comment by daniellekirkwood** [comment]
> the 'defect' mentioned here is my desired behaviour, but i can't find if/where i can disable TAC.

It's not possible to disable the new icon. Thread messages will remain detached from the main room list
