### ISSUE TITLE
"Upgrade your encryption" flow is broken and should be removed

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#27455]
If we detect that you have key backup, but no 4S, we pop up a toast prompting you to "Upgrade your encryption".

This is broken in several ways:
 * We also show the toast in the situation that you have 4S, but the backup key is not stored in 4S [at least, not under the current 4S key]: see https://github.com/element-hq/element-web/issues/27100#issuecomment-2101113562. This is not a situation we can "upgrade" from.
 * It produces errors like `Error bootstrapping secret storage createSecretStorageKey() callback did not return a secret storage key` which then produces obscure UI feedback like "Unable to set up secret storage" (https://github.com/element-hq/element-desktop/issues/1910)
 * It doesn't report any failures correctly (see https://github.com/element-hq/element-web/issues/27383).
 * It's not tested (as is evident from the catalogue of fail above)

Frankly, I don't think this is a flow we should be supporting at all. We should remove the "upgrade your encryption" flow.

**Comment by richvdh** [comment]
After discussion with the team today: we're agreed that this flow should be removed altogether. When logging into an account that has key backup but the keys for that backup are not available in 4S, the only option will be to create a new key backup.

**Comment by richvdh** [comment]
If we're removing the "upgrade" flow, we should also remove the behaviour in `RestoreKeyBackupDialog` which prompts you to enter your backup key directly (referring to it, confusingly, as "security key"). Related: https://github.com/element-hq/element-web/issues/27469

**Comment by crjo** [comment]
Hi there, every new user on our on prem instance is unable to have a correct key backup at first login, is there a workaround ?
It's not occasionally for us, it's every time.

**Comment by florianduros** [comment]
@richvdh So what do we need to do "If we detect that you have key backup, but no 4S" instead of showing this broken flow?

**Comment by richvdh** [comment]
Treat it the same as having no 4S

**Comment by florianduros** [comment]
Done https://github.com/element-hq/element-web/pull/28290 & https://github.com/element-hq/element-web/pull/28299
