### ISSUE TITLE
Crash on startup (failed to restore session)

### ISSUE THREAD

**Issue by linuxtim** [element-hq/element-web#27462]
### Steps to reproduce

Failure at startup, after clean shutdown.

#### What did you expect?

Normal startup.

#### What happened instead?

Startup failure, with "Unable to restore session
We encountered an error trying to restore your previous session."

### Operating system

Debian 12 Linux

### Application version

1.11.66

### How did you install the app?

Debian package

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Duplicate of https://github.com/element-hq/element-desktop/issues/1568
