### ISSUE TITLE
Rare crash when dragging spaces

### ISSUE THREAD

**Issue by morguldir** [element-hq/element-web#27465]
### Steps to reproduce

1. Using the app normally
2. I try to navigate to another space
3. I accidentally drag the space for a second (apparently i do this a lot)

#### What happened instead?

Element says something went wrong and asks me to submit debug logs

It goes away if i refresh, but this takes ages on my account

### Operating system

Arch Linux

### Browser information

Electron 30.0.1 / Chrome 124.0.6367.60 / Ferdium 6.3.7

### URL for webapp

develop.element.io

### Application version

Element Web 1.11.66 (02fd35dad069-react-4ed6da4eba01-js-b78a1ad889c7)

### Homeserver

Synapse 1.106.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Browser information
Electron 30.0.1 / Chrome 124.0.6367.60 / Ferdium 6.3.7

This is not a supported environment - please open a new issue if you can reproduce it in a supported environment: https://github.com/element-hq/element-web#supported-environments
