### ISSUE TITLE
Delayed receipt of incoming and outgoing messages

### ISSUE THREAD

**Issue by PriorityK** [element-hq/element-web#27487]
### Steps to reproduce

All correspondence are incredibly delayed - message reads that either messages have not been delivered or don't reflect  incoming or outgoing messages until much later and then sometimes out of order. This has been taking place over a period of days.  I also have Element on my cell phone - as I have for several years. Just now on my cell phone, the message appeared that the server was not connected.  What is going on?  I have deleted the app on my phone today and re-installed at least twice. This issue began several days ago and is worse today than it has been since it started. 

### Operating system

Windows

### Browser information

Firefox

### URL for webapp

https://app.element.io/?pk_vid=19c8de359fcd42bb1673065457050cdd#/room/!gRwdOJZCwcohuenAGg:matrix.org

### Application version

Element version: 1.11.66 Crypto version: Olm 3.2.15

### Homeserver

https://matrix-client.matrix.org

### Will you send logs?

No

**Comment by AnarcoPunkRJ** [comment]
Same here, it is impossible to use Element on Windows right now.

**Comment by Behodar** [comment]
Yep, looks to be server-side because I'm having no end of trouble on MacOS and iOS as well.

**Comment by t3chguy** [comment]
https://status.matrix.org/

Not a problem with the element web project
