### ISSUE TITLE
.mx_MessagePanel_myReadMarker has invalid css

### ISSUE THREAD

**Issue by IceMinePenguin** [element-hq/element-web#27482]
### Steps to reproduce

I was creating a custom theme for element web. I noticed the unread bar that appears when you go into a room with unread messages wasn't themed correctly. I opened the inspector and found the css. it is trying to set the color to "--accent" which doesn't exist, so it falls back to green.

![image](https://github.com/element-hq/element-web/assets/71886556/c28cd493-f208-44ea-a461-f0384c5be96e)

#### What did you expect?
I would expect the element to either use --accent-color or for --accent to exist and the style to not fall back to the default green.

#### What happened instead?
It is referencing a variable that does not exist. 

### Operating system

Arch Linux

### Browser information

Firefox 125.0.3-2

### URL for webapp

Private self hosted instance, 

### Application version

Version 1.11.60

### Homeserver

Private homeserver, Synapse, 1.102.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
@MidhunSureshR `--accent` and `$accent` are not the same. The latter is inlined at build time given it is a pcss variable.
