### ISSUE TITLE
Unable to do self-verification with legacy crypto

### ISSUE THREAD

**Issue by florianduros** [element-hq/element-web#27485]
### Steps to reproduce

1. Session A is verified
2. Session B is unverified
3. Launch session verification between the 2 sessions
4. Use emji SAS
5. Click on match in both sessions

#### What did you expect?

I'm expecting the sessions B to be verified

#### What happened instead?

<img width="810" alt="fffd29a7-b38f-454f-9d73-d3609c04675e" src="https://github.com/element-hq/element-web/assets/2621378/9f735175-ddfd-4a59-b9c5-81631f0751de">

After the click of the two matchs button, this request is made:
`/v3/sendToDevice/m.key.verification.cancel/*****`

### Application version

Local develop, Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ara4n** [comment]
if this only impacts legacy crypto, i'd ignore it, and focus on rolling forwads E-R

**Comment by florianduros** [comment]
So let's change it to major instead of critical.

**Comment by florianduros** [comment]
all my devices are migrated to the new crypto, I can't reproduce it

**Comment by richvdh** [comment]
let's close then
