### ISSUE TITLE
Dark mode changes appearance of verification shield

### ISSUE THREAD

**Issue by edent** [element-hq/element-web#27492]
### Steps to reproduce

1. On https://app.element.io in Firefox for Linux and the Element app for Android from F-Droid
2. Sign in on the web.
3. Sign in on the app.
4. Go through session verification.
5. The verification shield on the web looks like this: 
![Screenshot 2024-05-21 at 15-45-45 Element Electromagnetic Field](https://github.com/element-hq/element-web/assets/837136/bf0d3c7f-88ad-4814-b4c4-7664a58e0c7d) A green shield with a grey tick.
6. The Android shield looks like this: 
![IMG_20240521_154933](https://github.com/element-hq/element-web/assets/837136/123b20b1-34f3-42ba-b656-0fd9d9bcd3fe)

#### What did you expect?

The shields should look identical.

#### What happened instead?

They do not.

### Operating system

Pop_OS

### Browser information

Firefox

### URL for webapp

https://app.element.io

### Application version

1.6.14

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is the new design, the Android app is wrong but it likely won't be fixed in Element Android, only in Element Android X.
