### ISSUE TITLE
Lots of previously corrected DM rooms not showing up as a DM room anymore

### ISSUE THREAD

**Issue by JMoVS** [element-hq/element-web#27495]
### Steps to reproduce

1. Use Element for years
2. Suddenly wonder why the DM rooms don't show an avatar image anymore
3. Realise it's because they're not marked as a DM room
4. Then figure out how work around this bug which is:
5. Go to the room, then navigate to the user
6. then click "message" which opens a new DM room
7. then go to the old room and only then run `/converttodm` - when the DM room is not created beforehand, it doesn't work

#### What did you expect?
My DM rooms to stay DM rooms
#### What happened instead?
They at some point recently got changed to non-DM rooms without user interaction

### Operating system

macOS

### Application version

Element 1.11.67

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please share the contents of `m.direct` from `/devtools` > `Explore Account Data` - there are known issues with other Matrix clients which corrupt this data causing rooms to become not DMs.

**Comment by JMoVS** [comment]
```
{
  "type": "m.direct",
  "content": {
    "@support:matrix.org": [
      "!YkeAwQesBBjDuIBmpW:matrix.org"
    ],
    "@genissia:phelas.com": [
      "!PiTaQZdDsUQvbsoGYZ:phelas.com"
    ],
    "@appservice-irc:hackint.org": [
      "!uVmxvElIwbACiqGqHN:hackint.org"
    ],
    "@ahmad:phelas.com": [
      "!FOIKIiGaKNaGXuoMZN:phelas.com"
    ],
    "@leon:phelas.com": [
      "!lNNIevPgyRuuggFAhD:phelas.com"
    ],
    "@masoud:phelas.com": [
      "!WGBaGMyCgVeEWLxlsj:phelas.com"
    ],
    "@christopher:phelas.com": [
      "!SjDRmcBnRsUycvYlMK:phelas.com"
    ],
    "@pit:phelas.com": [
      "!PMQfFeisLouqEGLGNU:phelas.com"
    ],
    "@leonardo:phelas.com": [
      "!wtErHRinyjKuNcFjqa:phelas.com"
    ],
    "@carolina:phelas.com": [
      "!IbGnZVNEpwSTSNVtSJ:phelas.com"
    ],
    "@nora:phelas.com": [
      "!cKmuAaCJlkybLTWzdc:phelas.com"
    ],
    "@carlos:phelas.com": [
      "!GuaBrVKRDrJAPkBNnt:phelas.com"
    ],
    "@christian:phelas.com": [
      "!GJnROCUqoPxIYqMlMT:phelas.com"
    ],
    "@mathieu:phelas.com": [
      "!ZddTWwFOujiYprpNjz:phelas.com"
    ],
    "@miguel:phelas.com": [
      "!VvRHBRKcekmRoNjbNP:phelas.com"
    ],
    "@dominik:phelas.com": [
      "!iIDBVzXcCWCGgzooPz:phelas.com"
    ],
    "@darragh:phelas.com": [
      "!lQTKBseocPuIVNHUer:phelas.com"
    ],
    "@gfaerber:phelas.com": [
      "!gYAxrvXCOExKruYkuT:phelas.com"
    ],
    "@florian_kaufmann:phelas.com": [
      "!nqevVDZxVpftVcGeeB:phelas.com"
    ]
  }
}
```

I only use Element classic and Element X as clients though

**Comment by t3chguy** [comment]
Yup that looks corrupted. Caused by Element X https://github.com/matrix-org/matrix-rust-sdk/issues/3410
