### ISSUE TITLE
Chromebook cannot type alt-shift-arrowdown

### ISSUE THREAD

**Issue by Mc-polo** [element-hq/element-web#27506]
### Steps to reproduce

Open Element Web in chromebook. 
Press alt - shift - arrowdown
Element window makes pagedown and does not advance to next unread room.

#### What did you expect?
next unread messages
#### What happened instead?
nothing (page down)

### Operating system

Chromebook latest ver. 124.0.6367.225 

### Browser information

Chrome ver 124.0.6367.225

### URL for webapp

Kapsi Element-versio: 1.11.66 Crypto version: Olm 3.2.15

### Application version

Kapsi Element-versio: 1.11.66 Crypto version: Olm 3.2.15

### Homeserver

i don't know

### Will you send logs?

No

**Comment by t3chguy** [comment]
Chromebook/ChromeOS is not a supported environment as per https://github.com/element-hq/element-web#supported-environments and as such we close such issues.
