### ISSUE TITLE
"Missing session data" screen: Logout button not working

### ISSUE THREAD

**Issue by tordans** [element-hq/element-web#27508]
### Steps to reproduce

Something happened and Elements does not start anymore.

I see <img width="906" alt="Bildschirmfoto 2024-05-31 um 09 59 37" src="https://github.com/element-hq/element-web/assets/111561/a82a68c9-8745-4d86-b046-d86dc9f83009">

However…
1. I cannot click the "Sign out" ("Abmelden") button. Clicking it does nothing

I can click the link. However…

On that screen, I cannot click anything except for two links that I circled in the screenshot. All other clicks do nothging.
<img width="858" alt="image" src="https://github.com/element-hq/element-web/assets/111561/86789bf6-c85d-4ac0-b5cb-644c77dde6d3">

### Outcome

-

### Operating system

mcOS

### Application version

Version 1.11.67 (1.11.67) now but updated today so the initial issue might have been an older version

### How did you install the app?

brew

### Homeserver

-

### Will you send logs?

Yes

==> How should I do this? Is there an email address?

**Comment by t3chguy** [comment]
> How did you install the app?
brew

The brew package isn't maintained by us, please use official installation means or seek support from its maintainer.
