### ISSUE TITLE
Latvian language is not listed in Settings dropdown despite translations present

### ISSUE THREAD

**Issue by tlpbu** [element-hq/element-web#27500]
### Steps to reproduce

At some point Latvian is no longer listed in available languages list for Element Web despite Latvian being partially translated. Cannot give exact time but that was working some time ago whn I was also participating in translation efforts.

![Screenshot 2024-05-26 at 16 39 02](https://github.com/element-hq/element-web/assets/8039755/1a12561c-f974-4741-8ce5-7af90cf9858c)

### Outcome

Expected to have option to choose UI language in Latvian.

### Operating system

Any

### Browser information

Any

### URL for webapp

Hosted locally

### Application version

Element version: 1.11.67 Crypto version: Olm 3.2.15

### Homeserver

Synapse

### Will you send logs?

No

**Comment by t3chguy** [comment]
> At some point Latvian is no longer listed in available languages list for Element Web despite Latvian being partially translated.

Yes, the language is disabled in Localazy until it has ~80% translation approved

![image](https://github.com/element-hq/element-web/assets/2403652/c41e9677-c1d8-4ec5-b94d-67b06a3c5976)

**Comment by tlpbu** [comment]
Good to know this principle. 
I see other languages still available despite being significantly below 80% translated.

Anyhow please consider adding Latvian again - now it is at least 83% translated.
![Screenshot 2024-06-02 at 23 22 14](https://github.com/element-hq/element-web/assets/8039755/ed514a17-a3b6-4e66-ac93-fa6353c60b6c)

**Comment by t3chguy** [comment]
@tlpbu they have not yet been approved, so you have to wait for the team to approve them. 

![image](https://github.com/element-hq/element-web/assets/2403652/efb2b5fd-4b66-48f5-bd0c-f2396b913ece)

> I see other languages still available despite being significantly below 80% translated.

Those are from before migrating to Localazy, we only disabled languages which were low like below <40% to not drop support for languages which were previously enabled but fell behind somewhat.

**Comment by tlpbu** [comment]
@t3chguy I am sure there is no actively involved other translators for latvian language that would approve translations since most of work was done by me even before migration to Localazy. So it might very well be that noone will review and approve translation for years.
Can it be autoapproved by someone else based on some AI results or somehow?

**Comment by t3chguy** [comment]
This isn't the place to get support with translations, see docs. https://github.com/element-hq/element-web/blob/develop/docs/translating.md#join-element-translationsmatrixorg
