### ISSUE TITLE
Search relies on optional `count` field in response

### ISSUE THREAD

**Issue by Benjamin-L** [element-hq/element-web#27517]
### Steps to reproduce

1. Spin up a server that does not return a value for the optional `count` field in the response body for the `/client/v3/search` endpoint.
2. Use the search function in a non-E2EE room

For a server implementation reproducing the element bug, you can use commit [`5c39c7c5`][1] of grapevine, conduit [`df16b2ba`][2] (before a workaround for element was added in [`edfd3c1f`][3]), or conduwuit [`a2ee6b41`][4] with the `element-hacks` feature disabled (before the workaround was made unconditional in [`0214caea`][5]).

[1]: https://gitlab.computer.surgery/matrix/grapevine-fork/-/tree/5c39c7c5fff0e1a59999f0c13bf4aa48cb159129
[2]: https://gitlab.com/famedly/conduit/-/commit/df16b2ba9817bf56d7b125db33c9539cfacf56d5
[3]: https://gitlab.com/famedly/conduit/-/commit/edfd3c1f34aae8ec29461cf8a5f529a54291c714
[4]: https://github.com/girlbossceo/conduwuit/commit/a2ee6b410e03190b3e330b7dfc1c2d246f0cd339
[5]: https://github.com/girlbossceo/conduwuit/commit/0214caeaeaa7af72b33e51cdc7069878217a3f96

#### What did you expect?

Either some search results appear or it shows that there were no results. The `count` field is marked as optional in the spec, so it's absence should not break search client-side.

#### What happened instead?

Hangs indefinitely, showing the loading animation:

![image](https://github.com/element-hq/element-web/assets/6504174/18f95dc8-3253-4692-ad33-2e62bb872f20)

Returning any value in the `count` field causes search to function as expected.

### Operating system

NixOS (linux)

### Browser information

Firefox 126.0

### URL for webapp

app.element.io

### Application version

Element version: 1.11.67 Crypto version: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1

### Homeserver

Grapevine 5c39c7c5fff0e1a59999f0c13bf4aa48cb159129

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Will you send logs?
Yes

Not seeing any logs from you

**Comment by Benjamin-L** [comment]
> > Will you send logs?
> > Yes
> 
> Not seeing any logs from you

Ah, sorry, I forgot to do that yesterday. I've uploaded logs now.

Thanks for putting together a fix so quickly! I'll be able to test it later today :)

**Comment by richvdh** [comment]
For links, the result of the `/search` endpoint is specified at https://spec.matrix.org/v1.10/client-server-api/#_matrixclientv3search_results, and the `count` property is a member of [Result Room Events](https://spec.matrix.org/v1.10/client-server-api/#_matrixclientv3search_result-room-events).

`count` is indeed optional. It seems unfortunate (and probably not really intended?) that *all* of the properties in that structure, including `results`, are optional, but that's what the spec says.
