### ISSUE TITLE
Voice call failure when trying to share the screen

### ISSUE THREAD

**Issue by kosmos** [element-hq/element-web#27522]
### Steps to reproduce

1. During a voice call
2. Click the "Share Screen" button

#### What did you expect?

The screen is expected to be shared with the participants of the call.

#### What happened instead?

The call is interrupted during a voice call after pressing the “Expand Screen” key.

### Operating system

MacOS

### Application version

Element Version 1.11.68

### Homeserver

Synapse 1.106

### Will you send logs?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/element-hq/element-desktop/issues/1703
