### ISSUE TITLE
option to suppress auto-raise

### ISSUE THREAD

**Issue by aebenjam** [element-hq/element-web#27537]
#### What would you like to do?
When new messages/notifications come in I would like the option to have the window to NOT auto-raise and pull focus.   That "feature" seems to have arrived with the latest update:
Element version: 1.11.68
Crypto version: Rust SDK 0.7.0 (068a0af), Vodozemac 0.6.0
#### Why would you like to do it?
It's VERY frustrating to throw a window into the background only to have it jump in the way, pull your cursor, steal your typed text, etc.
#### How would you like to achieve it?
A switch in the notifications settings would be sufficient.

### Have you considered any alternatives?

I do not know of a way to have my window manager catch and suppress the raise/focus-pull.  I would have to consider an alternate matrix client and, in general, I've been quite happy with Element.

**Comment by t3chguy** [comment]
This is not a feature we added, please fill in a bug report template.
