### ISSUE TITLE
Session logged out after restart

### ISSUE THREAD

**Issue by mikwee** [element-hq/element-web#27543]
### Steps to reproduce

1. Log into Element, as I had to do this morning
3. Restart suddenly (I did so with a button on my PC)
4. Open Element to see that the session couldn't be restored

#### What did you expect?
I expected my session to persist, as it did previously.
#### What happened instead?
The session could not be restored, I even got an error.

### Operating system

Fedora

### Application version

Element 1.11.68

### How did you install the app?

Flathub, through KDE Discover

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by mikwee** [comment]
I don't see that it sent the logs, so here they are.
[issue.txt](https://github.com/user-attachments/files/15754122/issue.txt)
[log-0.log](https://github.com/user-attachments/files/15754123/log-0.log)
[log-1.log](https://github.com/user-attachments/files/15754124/log-1.log)
[log-2.log](https://github.com/user-attachments/files/15754125/log-2.log)
[log-3.log](https://github.com/user-attachments/files/15754126/log-3.log)
[log-4.log](https://github.com/user-attachments/files/15754127/log-4.log)

**Comment by t3chguy** [comment]
Issues with the community maintained flatpak live at https://github.com/flathub/im.riot.Riot/
