### ISSUE TITLE
UI not showing that don't have rights to update room logo

### ISSUE THREAD

**Issue by happylolonly** [element-hq/element-web#27540]
### Your use case

Tried to update room logo, spent 5 mins to understand that I don't have rights to do it.
UI should show this.

<img width="658" alt="image" src="https://github.com/element-hq/element-web/assets/18665326/a557a01b-cb7d-4c48-99d5-1ad332f8c2a2">

**Comment by dbkr** [comment]
This should now be fixed with the latest round of UI updates.
