### ISSUE TITLE
Uploading and downloading attachments consumes a lot of `GPU`

### ISSUE THREAD

**Issue by qupig** [element-hq/element-web#27542]
### Steps to reproduce

Just upload or download files, you can observe that the GPU is almost full, and the GPU is released immediately after completion.

I'm not sure if the GPU is used for rendering the progress bar or encrypting and decrypting the attachment content, but it still consumes too much (almost all of it).

#### What did you expect?
It should not use nearly all of the GPU, whether for rendering or encryption and decryption.

#### What happened instead?
Every time an attachment is uploaded or downloaded, the GPU is almost full.

### Operating system

macOS

### Application version

Element version: 1.11.68 Crypto version: Olm 3.2.15

### How did you install the app?

brew install element

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
The brew package is not maintained by us, please try an official package or seek support from the maintainer of the package which you choose to use.
