### ISSUE TITLE
Device Dehydration v2 - Device fails to rehydrate. Extra Security Key popup that will not accept a valid key.

### ISSUE THREAD

**Issue by mjw3428** [element-hq/element-web#27546]
### Steps to reproduce

1. After logging in with SSO an pop for Security Key appears. 
2. Entering a valid key is considered invalid in the dialog box and the continue button is never activated. 
![image](https://github.com/element-hq/element-web/assets/45126022/4352756f-7a73-4707-b34c-5c582fee8b01)

4. Clicking the close button on this dialog box will result in the verify device dialog box appearing. Clicking verify with securtiy key here will show the same dialog box as before, but this time the same key will be accepted. 
![image](https://github.com/element-hq/element-web/assets/45126022/b8d6b8a2-052c-401b-aee2-99a45ca9be63)

This is with device dehydration set on within the Element config. 

It looks to me like it is trying to access the Security Key before the session has initialised and, since this fails, the dialog box doesn't know what your Secret Key is and so it will never match. 

![image](https://github.com/element-hq/element-web/assets/45126022/5f07625b-5c6d-435e-9bb9-6a34b320c936)

As a result it looks like it never rehydrates the device on subsequent logins. 

#### What did you expect?

Valid Security Keys should be accepted and device rehydration should work. 

#### What happened instead?

The error 'Invalid Security Key is shown and the continue button is disabled.

### Operating system

Docker Container (Alpine?)

### Browser information

Chrome 125

### URL for webapp

1.11.68

### Application version

Riot version: 153d0c36b88d-react-ab6a94aa8f76-js-131e81401a04 Crypto version: Rust SDK 0.7.0 (068a0af), Vodozemac 0.6.0

### Homeserver

Synapse v1.108.0

### Will you send logs?

Yes

**Comment by mattw-hatake** [comment]
This appears to relate to msc2697 device dehydration and not the newer msc3814. This explains why it is very similar to https://github.com/element-hq/element-web/issues/18977. Going to close this issue as it is already covered there and probably not relevant anyway.

**Comment by t3chguy** [comment]
> Will you send logs?
Yes

Not seeing any logs.

**Comment by mjw3428** [comment]
This relates to msc2697 and not the newer 3814. Closing as no longer relevant.
