### ISSUE TITLE
I can't leave the Rust Room 

### ISSUE THREAD

**Issue by jgarte** [element-hq/element-web#27557]
### Steps to reproduce

1. Where are you starting? What can you see?
![image](https://github.com/element-hq/element-web/assets/47760695/e18e144a-480b-42d7-990d-0674278aac50)

3. What do you click?

I clicked the leave button

4. More steps…

The room I was trying to leave is the following:

https://matrix.to/#/#rust:matrix.org

#### What did you expect?

I expect to leave the Rust room.

#### What happened instead?

I wasn't able to leave the Rust room.

### Operating system

Fedora

### Browser information

Firefox

### Homeserver

Default main homeserver

**Comment by t3chguy** [comment]
That is an error from your server, it isn't something your Matrix client can do anything about.
