### ISSUE TITLE
Make Element Call widget URL configurable

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-web#27555]
### Your use case

Please see and discuss the details in the meta issue.

**Comment by ara4n** [comment]
Don't we already have this via config.json?

```json
    "element_call": {
        "participants_limits": 8,
        "url": "https://example.com",
        "use_exclusively": false
    },
```

Or is the point that the URL should be switched to use `.well-known/element/call.json` instead?

**Comment by manuroe** [comment]
EW has already a mechanism to configure the widget URL within its own config file. No need for a change now.

**Comment by schelmo** [comment]
But ED (element-desktop) can only be configured via a local config.json.
It would be nice to make the Element Call url configurable via the `.well-known/element/element.json` url, so ED will use the right Element Call instance

**Comment by plui29989** [comment]
We also need this to work with Element Desktop...

**Comment by t3chguy** [comment]
You deploy Element Desktop configs in the exact same way as Element Web.

https://github.com/element-hq/element-desktop#user-specified-configjson or bake them in at build time: https://github.com/element-hq/element-desktop#config
