### ISSUE TITLE
Something went wrong!

### ISSUE THREAD

**Issue by mightyiam** [element-hq/element-web#27559]
### Steps to reproduce

Not sure what I was doing exactly.

### Outcome

Dunno

### Operating system

NixOS

### Browser information

Firefox 126.0.1 (64-bit)

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by mightyiam** [comment]
Logs sent.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/element-hq/element-web/issues/27503
