### ISSUE TITLE
Live sharing UI is inconsistent with the selected theme

### ISSUE THREAD

**Issue by areox-net** [element-hq/element-web#27571]
### Steps to reproduce
When a user is sharing a live location on a room, the color of the box containing the map is inconsistent with the current theme (light or dark mode).

#### What did you expect?
The box displaying the map on Element Web should respect the colors of the selected theme. It should have a white background on Light mode and a Black one in dark mode.

#### What happened instead?
The box has a black background in the light theme. The first line of text is therefore not visible because it is black on black.
![Screenshot 2024-06-10 at 17 44 02](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/2b1ada92-f0fb-4a30-9238-dbc6f9e25a56)

The same thing happens when in dark mode, only the other way around. 
![Screenshot 2024-06-10 at 17 43 51](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/c3b4e4f5-9657-44bc-a91d-c672c3afabe5)

As a reference, here is the iOS app with the right colors:
![Screenshot 2024-06-10 at 17 49 12](https://github.com/tchapgouv/tchap-web-v4/assets/1255251/1f2fe8f1-e0ed-4964-829d-07b417fa4c2a)
in

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Will you send logs?
Yes

Not seeing any logs from you

**Comment by areox-net** [comment]
@t3chguy Sorry, that should have been "No"
