### ISSUE TITLE
Notification badge is not showing the counter on windows 11 pwa

### ISSUE THREAD

**Issue by chagai95** [element-hq/element-web#27575]
### Steps to reproduce

install element as a pwa

#### What did you expect?
notification counter
#### What happened instead?
none is shown

### Operating system

Windows 11

### Browser information

Chrome

### Will you send logs?

No

**Comment by t3chguy** [comment]
Logs would be needed here. We do call `setAppBadge` so something in the browser is stopping it working. https://developer.mozilla.org/en-US/docs/Web/API/Navigator/setAppBadge claims to work on Chrome on Windows

**Comment by chagai95** [comment]
Somehow it started working now, I refreshed, maybe it was stuck somewhere, I also sent logs, thx!

**Comment by t3chguy** [comment]
Unfortunately the logs do not shed any light on any failures with `Navigator::setAppBadge` so this issue seems to be entirely on the browser's side. In light of that + the fact that a refresh fixed it I will be closing this issue
