### ISSUE TITLE
Persistent unread (also in browser)

### ISSUE THREAD

**Issue by bschnei3** [element-hq/element-web#27581]
### Steps to reproduce

One of my rooms in the app (both desktop and browser) has been showing a persistent "unread messages" notification (at first 3 for the browser app and 5 for the desktop app) symbol that I cannot seem to get rid of. If I click on the arrow to go to the first unread message, the room goes blank.
I have tried:
- uninstalling and reinstalling (desktop app) -> nothing happened
- deleting the cache inside the settings (desktop app) -> (number increased to 7)
- deleting the cache and browser data -> (here also number increased to 7)

#### What did you expect?
- uninstalling and reinstalling (desktop app) -> reset (but then again, I didn't delete the cache...)
- deleting the cache inside the settings (desktop app) -> reset
- deleting the cache and browser data -> reset

#### What happened instead?
- uninstalling and reinstalling (desktop app) -> nothing happened
- deleting the cache inside the settings (desktop app) -> (number increased to 7)
- deleting the cache and browser data -> (here also number increased to 7)

### Operating system

Windows 11

### Application version

Element version 1.11.68

### How did you install the app?

https://element.io/download

### Will you send logs?

No

**Comment by dbkr** [comment]
dup of https://github.com/element-hq/element-web/issues/27582
