### ISSUE TITLE
Should remove allow-downloads-without-user-activation for iframes

### ISSUE THREAD

**Issue by MarcWadai** [element-hq/element-web#27587]
### Steps to reproduce

1. Where are you starting? What can you see?
An error from a user appearedon the console while downloading a file 

![image](https://github.com/element-hq/element-web/assets/10048869/1e043ae7-cbbf-4e83-9a46-109a03ce13ec)

linked to this issue https://github.com/tchapgouv/tchap-web-v4/issues/1029

3. What do you click?
Download a file

5. More steps…

#### What did you expect?
No error to appear on the console

#### What happened instead?
The error above appeared. On element code, the directive `allow-downloads-without-user-activation` on the iframe seems to be used next to `allow-downloads`. According to the documentation https://github.com/mdn/content/pull/33409, it seems that this directive has been removed and shouldn't be used.

### Operating system

Mac OS

### Browser information

Chrome 126

### Application version

1.11.67

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
If it has been abandoned then I wonder why https://github.com/w3c/webappsec-permissions-policy/issues/289 isn't closed
