### ISSUE TITLE
Cannot terminate video calls

### ISSUE THREAD

**Issue by aoloe** [element-hq/element-web#27599]
### Steps to reproduce

1. In the past I have started video calls.
2. Now, two widgets are stuck at the top and I can't remove them.
3. As the adminstrator of the room I can terminate the call, but they show up again after a few seconds.  
    ![video-calls](https://github.com/element-hq/element-web/assets/1857016/53aa614c-e747-4dcf-964a-1666fde29e2b)
4. No message in the timeline.
5. Other people also see the widgets at the top.
6. From the Browser I can't start any call anymore.
7. From the tablet I can create new calls and stop them. They show in the timeline of the Desktop (started and ended)

#### What did you expect?

I expect to be able to stop the existing call

#### What happened instead?

The call shows up again and can't be stopped.

### Browser information

Firefox developer edition (it has been happening for some time now)

### URL for webapp

https://app.element.io/#/room/#ots-zh:matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This looks like network or server issues:

```
2023-03-09T15:54:19.859Z E /sync error %s fetch failed: NetworkError when attempting to fetch resource.
s@https://app.element.io/bundles/e983d51f78647cc601c0/vendors~init.js:2:1259225
requestOtherUrl@https://app.element.io/bundles/e983d51f78647cc601c0/vendors~init.js:2:3563279
```

You'd need to seek help from your homeserver operator

**Comment by aoloe** [comment]
for future reference (if this tickets ever gets referenced in search engines...):

it seems to be an issue with the web client: clearing the cache and reload (in the user settings > help & about) removed the video calls.
