### ISSUE TITLE
Blinking shields

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27591]
### Steps to reproduce

1. Write a msg in an encrypted room
2. See the green shield flicker like this:

https://github.com/element-hq/element-web/assets/1294269/bf0d1c35-7db8-45fb-a936-5e69960b4091

#### What did you expect?

Shield should rapidly show the correct state on switching to a room and not flicker all the time.

#### What happened instead?

Unsettling flickering making it feel like encryption might be flakey.

### Application version

2024061701

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/12606
