### ISSUE TITLE
Default power levels settings in autorisation are not correct

### ISSUE THREAD

**Issue by MarcWadai** [element-hq/element-web#27610]
#### What would you like to do?
Remove Power level settings of element group call when it is not activated. When it is activated we have the correct labels

![image](https://github.com/element-hq/element-web/assets/10048869/c54511de-3421-4a95-a968-f1de6963b223)

But when it is not, i expect it not to show. Instead we have a label that is not really meaningful for users : 
![image](https://github.com/element-hq/element-web/assets/10048869/a4a5120f-8333-4e97-9f44-3a61fb894030)

#### Why would you like to do it?
Remove unecessary power levels section from default settings

#### How would you like to achieve it?
In the code `RolesRoomSettingsTabs.tsx`, the list of plEventsToShow :
`const plEventsToShow: Record<string, IEventShowOpts> = {
    // If an event is listed here, it will be shown in the PL settings. Defaults will be calculated.
    [EventType.RoomAvatar]: { isState: true },
    [EventType.RoomName]: { isState: true },
    [EventType.RoomCanonicalAlias]: { isState: true },
    [EventType.SpaceChild]: { isState: true, hideForRoom: true },
    [EventType.RoomHistoryVisibility]: { isState: true, hideForSpace: true },
    [EventType.RoomPowerLevels]: { isState: true },
    [EventType.RoomTopic]: { isState: true },
    [EventType.RoomTombstone]: { isState: true, hideForSpace: true },
    [EventType.RoomEncryption]: { isState: true, hideForSpace: true },
    [EventType.RoomServerAcl]: { isState: true, hideForSpace: true },
    [EventType.RoomPinnedEvents]: { isState: true, hideForSpace: true },
    [EventType.Reaction]: { isState: false, hideForSpace: true },
    [EventType.RoomRedaction]: { isState: false, hideForSpace: true },

    // MSC3401: Native Group VoIP signaling
    [ElementCall.CALL_EVENT_TYPE.name]: { isState: true, hideForSpace: true },
    [ElementCall.MEMBER_EVENT_TYPE.name]: { isState: true, hideForSpace: true },

    // TODO: Enable support for m.widget event type (https://github.com/vector-im/element-web/issues/13111)
    "im.vector.modular.widgets": { isState: true, hideForSpace: true },
    [VoiceBroadcastInfoEventType]: { isState: true, hideForSpace: true },
};
`
ElementCall is cited by default in the code, in my opinion it should be removed from this list unless there are technicals issues with that ?

**Comment by t3chguy** [comment]
All power levels present in the room must be shown even if the client does not understand them otherwise you cannot modify that power level and thus potentially not be able to control the room. Even if those lines you found were removed the behaviour would be the same. See here for example:

![image](https://github.com/element-hq/element-web/assets/2403652/22d8c06e-c7f5-4668-9538-1c583e02880d)
![image](https://github.com/element-hq/element-web/assets/2403652/2d11d12f-3fe0-4876-affd-134d081ab793)

**Comment by MarcWadai** [comment]
Oh yes I understand the point. Thx for the quick answer. In that case, there shoud'nt be any conditions around the translations of the labels no ?

**Comment by t3chguy** [comment]
The policy is that all code pertaining to a labs flag is behind said labs flag so it can be developed without product review
