### ISSUE TITLE
Unable to decrypt message, keys aren't getting transferred from other devices

### ISSUE THREAD

**Issue by TellowKrinkle** [element-hq/element-web#27623]
### Steps to reproduce

1. Sign into your account on a new device
2. Verify the session from an already signed in device
3. Try to view encrypted messages on the new device
4. According to https://joinmatrix.org/guide/fix-decryption-error/, if you view the same messages on a device that has the keys, they will be transferred to the new device in a "few moments"

#### What did you expect?
The messages will be decrypted in less than a minute

#### What happened instead?
Still shows unable to decrypt message after multiple minutes

### Operating system

Fedora Linux

### Browser information

Firefox 127.0

### URL for webapp

app.element.io

### Application version

Element version 1.11.69, Crypto version Rust SDK 0.7.0 (068a0af), Vodozemac 0.6.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by kegsay** [comment]
This is due to the other client (not the new one) not having the `m.megolm_backup.v1` secret, but it has the other 3 (SSK, USK, MSK).

Confusingly, functions which get access to the backup key are producing different results:
 - [this code](https://github.com/matrix-org/matrix-js-sdk/blob/65b9c31f9b9b24d3ebe95656e4429b17a1f84285/src/rust-crypto/rust-crypto.ts#L1125) produces a truthy response, but
 - [this code](https://github.com/matrix-org/matrix-rust-sdk/blob/d41af396cc01fcc7a50f2c50a542ea71d6077b0a/crates/matrix-sdk-crypto/src/store/mod.rs#L1187) produces `None`.

**Comment by knkski** [comment]
@richvdh I can reproduce the issue:

- Create an account on app.element.io
- Export a file named `<username>-element-security-key.txt`
- Log out of session, clear all cookies
- Log in again
- When prompted, enter contents of `<username>-element-security-key.txt`
- Look at message history, see only messages shown as `Unable to decrypt message`
- `View source` on the messages shows this:
  ```
  {
    "type": "m.room.message",
    "content": {
      "msgtype": "m.bad.encrypted",
      "body": "** Unable to decrypt: DecryptionError: This message was sent before this device logged in, and key backup is not working. **"
    }
  }
  ```
- Have no indication of what exactly is wrong or how to fix it

I don't have this on another account where I always have at least one device signed in and always use it to verify new devices. In the `Security & Privacy` settings, I see this:

```
Backup key stored:	in secret storage
Backup key cached:	cached locally, well formed
Secret storage public key:	in account data
Secret storage:	ready
Latest backup version on server:	1 (Algorithm: m.megolm_backup.v1.curve25519-aes-sha2)
Active backup version:	None
This backup can be restored on this session
```

It says "This session is not backing up your keys, but you do have an existing backup you can restore from and add to going forward.". When I click `Connect this session to Key Backup`, it says `Successfully restored 10 keys`, but nothing changes. I was able to "fix" the issue by resetting the backup key and losing all history before, which is not ideal.

Are there any diagnosing/debugging steps I can take to help fix the issue?

**Comment by richvdh** [comment]
@knkski please open a new issue describing your symptoms, and send debug logs from within the app

**Comment by miro5lav** [comment]
I had similar issue: ** Unable to decrypt:...*** msg. When I use restore key i did not see messages.
In my case I was using private mode in browser, when I switched it off it worked.
