### ISSUE TITLE
The hover state for the new header should be "snappier"

### ISSUE THREAD

**Issue by daniellekirkwood** [element-hq/element-web#27648]
#### What would you like to do?
The hover state on the room header should be snappier -- this was raised in a testing session before release and is not a blocker.

**Comment by daniellekirkwood** [comment]
@americanrefugee I think you raised this feedback? Would you be able to describe what you mean? 

If it wasn't you (sorry) then let me know if you think it's accurate feedback :)

**Comment by americanrefugee** [comment]
The hover animation for the room header should take 200ms, not 300ms.
