### ISSUE TITLE
Element-R: withheld messages are no longer shown as such

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#27653]
If the sender chooses to only send e2e messages to verified devices, then unverified devices will receive a notification of a withheld key. (Specifically, a to-device message of type [`m.room_key.withheld`](https://spec.matrix.org/v1.11/client-server-api/#mroom_keywithheld) with a code of `m.unverified` or `m.blacklisted`.)

We should reflect these notifications in the UI, rather than just showing a generic "Unable to decrypt message" error. (This used to work with legacy crypto, but has not been re-implemented for Rust Crypto).

We should also give them a different error code in the Posthog analytics, so that they can be treated as "expected UTDs".

**Comment by andybalaam** [comment]
Added to top of backlog because:

* it is a quick win
* it is UTD+Trust+WebR

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/4310 is the final part of this
