### ISSUE TITLE
Cannot re-enable sliding-sync after the client was logged out

### ISSUE THREAD

**Issue by MichaelSasser** [element-hq/element-web#27652]
### Steps to reproduce

1. sliding-sync is enabled and working properly
2. log-out, clear browser cache
3. log back in and try to enable sliding-sync
4. the SS button in labs is disabled and shows "Your server lacks support"

#### What did you expect?
Sliding-sync can be enabled just like before / works like in my other sessions (in other web browsers), where sliding-sync is still enabled and working.

#### What happened instead?
The client doesn't allow me to enable sliding sync and tells me "Your server lacks support"

#### Additional information
[client well-known](https://matrix.michaelsasser.org/.well-known/matrix/client)

Initially, sliding-sync was configured before element-web read the client well known (https://github.com/matrix-org/matrix-react-sdk/pull/12307) and the client has been updated regularly since then.
 
The client with the issue only shows the following line in the logs. The working ones continue with `Sliding sync activated at https://matrix.michaelsasser.org/sliding-sync`.

```plain
getProxyFromWellKnown: client well-known declares sliding sync proxy at https://matrix.michaelsasser.org/sliding-sync rageshake.ts:77:16
```

### Operating system

Arch Linux

### Browser information

Mozilla Firefox 127.0.2

### URL for webapp

https://element.michaelsasser.org

### Application version

vectorim/element-web:v1.11.69

### Homeserver

ghcr.io/element-hq/synapse:v1.109.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The sliding sync MSC provides an absolute path, which means sub-directory hosting is not supported. I suggest you get the MSC to change that. Related https://github.com/matrix-org/matrix-react-sdk/pull/12658
