### ISSUE TITLE
Can not send messages in specific encrypted room

### ISSUE THREAD

**Issue by NicolasGoeddel** [element-hq/element-web#27658]
### Steps to reproduce

1. I started with creating a fresh account and verifying my mail address.
2. I then joined `#gadgetbridge:matrix.org` because I wanted to ask questions.
3. I said hello but a few seconds later I got the message that my message could not be sent.

#### What did you expect?
I expected to be able to just write in that room.

#### What happened instead?
I can not read the existing messages because they can not be decrypted and I am also not able to write a message because they could not be sent.

### Operating system

Ubuntu

### Browser information

Firefox 127.0.2 (64-Bit)

### URL for webapp

https://app.element.io/#/room/#gadgetbridge:matrix.org

### Application version

Version von Element: 1.11.69 Krypto-Version: Rust SDK 0.7.0 (068a0af), Vodozemac 0.6.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by NicolasGoeddel** [comment]
Hm, I just tried to send the protocols but nothing happened. I wasn't even able to download it somehow. It also showed this URL instead: https://github.com/vector-im/element-web/

**Comment by NicolasGoeddel** [comment]
I also have a long list of DEBUG and WARN messages in my browsers console if you are interested in that. It shows stuff like this:
- WARN matrix_sdk_crypto::session_manager::sessions: Can't establish an Olm session with some devices due to missing Olm support or bad keys
- WARN matrix_sdk_crypto::session_manager::sessions: Tried to create new Olm sessions, but the signed one-time key was missing for some devices
- WARN matrix_sdk_crypto::session_manager::sessions: Error creating Olm session

**Comment by t3chguy** [comment]
`2024-06-30T15:51:26.765Z E Error sending event failed to read or write to the crypto store DomException UnknownError (0): IDBObjectStore.put: The serialized value is too large (size=437672260 bytes, max=267386880 bytes).`

@richvdh any ideas?

**Comment by richvdh** [comment]
I was able to reproduce this. It appears to be specific to the `#gadgetbridge:matrix.org` room.

**Comment by NicolasGoeddel** [comment]
Wow. First time using Matrix just to join this specific room and directly found a weird bug.
Thanks guys for looking into it.

Btw. since today I am able to chat in this room using Thunderbird. It didn't work yesterday with Thunderbird but since today it is fine.

**Comment by richvdh** [comment]
The problem here is that there are a very large number of users in the room, and storing all the data about which users we have shared the keys with is blowing a storage limit.

We can fix it by making our storage more efficient.
