### ISSUE TITLE
Development branch shows blank page in Firefox 115.12.0esr

### ISSUE THREAD

**Issue by bartvdbraak** [element-hq/element-web#27676]
### Steps to reproduce

1. Where are you starting? What can you see?
- Opening https://develop.element.io in Firefox ESR 115
![Screenshot_20240705_114613](https://github.com/element-hq/element-web/assets/3996360/fcc026e5-38fa-4114-aefd-1cf2cb01b7cf)

2. What do you click?
- Nothing, the whole page is blank

[Screencast_20240705_114613.webm](https://github.com/element-hq/element-web/assets/3996360/e32ac2a7-a8ca-4628-a9eb-953dfd093788)

#### What did you expect?
The application showing a login page or a guest view

#### What happened instead?
The application shows a blank page

### Operating system

Debian GNU/Linux trixie trixie/sid x86_64, Linux 6.9.7-amd64, GNOME 44.9

### Browser information

Firefox 115.12.0esr (Extended Support Release)

### URL for webapp

develop.element.io

### Application version

Commit b4d343053d2fef1ced860aceaf3673ea66a4484d

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
See https://github.com/element-hq/element-web#supported-environments

> Last 2 major versions of Chrome, Firefox, and Edge on desktop OSes

That would be Firefox 126 & 127.

**Comment by seangenabe** [comment]
Just showing a blank page without any error message is toxic and not user-friendly. At least show a message that the user's browser is not supported.

**Comment by t3chguy** [comment]
@seangenabe yup: https://github.com/element-hq/element-web/pull/27677

**Comment by konomikitten** [comment]
Debian Stable only ships with Firefox ESR, there's probably a bunch of corporations who also use Firefox ESR. Surely a browser that's still being updated should be supported?

**Comment by t3chguy** [comment]
Delaying features by ~42 weeks that ESR claims to update every would not really be an option. We never claimed support for ESR and it working was entirely incidental by virtue of us using feature detection rather than browser listing

**Comment by wodny** [comment]
And here is a thread after it deployed to production - #27682 and a request to support Firefox ESR - #27684.
