### ISSUE TITLE
🌱 Enhancement Request — Download/Save Attachment Only Once

### ISSUE THREAD

**Issue by 8227846265** [element-hq/element-web#27679]
## What would you like to do?
- Step 1: Download and save an attachment to a folder on my computer.
- Step 2: Moments later, I want to view that downloaded file again and click the same attachment once more in Element.

## Expected Result
- The file opens since it's already downloaded and saved to my computer.

## Actual Result:
- It asks me to download and save it again.

## System Details:
- Windows 11
- Element version: 1.11.69
- Crypto version: Rust SDK 0.7.0 (068a0af), Vodozemac 0.6.0

**Comment by t3chguy** [comment]
A Web application cannot open files on your system for security reasons, browser won't let it. it's up to your browser to handle any de-duplication and opening of files.

**Comment by 8227846265** [comment]
> A Web application cannot open files on your system for security reasons, browser won't let it. it's up to your browser to handle any de-duplication and opening of files.

Hello, does this also apply to the Element Desktop App? 

I forgot to mention that this enhancement request is for the Element Desktop App. I couldn't find a specific repository for the desktop app, so I just posted this ticket on the web app repository.

**Comment by t3chguy** [comment]
https://github.com/element-hq/element-desktop

**Comment by 8227846265** [comment]
> https://github.com/element-hq/element-desktop

Got it. Will post it there.
