### ISSUE TITLE
Issue with Element Web App Version 1.11.66

### ISSUE THREAD

**Issue by FawadAhmed322** [element-hq/element-web#27670]
### Steps to reproduce

1. Open the Element Web App.
2. Attempt to connect to the Matrix homeserver.
3. Observe the error messages related to the identity server configuration.

#### What did you expect?

The application should correctly identify and use the preferred identity server without errors.

#### What happened instead?

An error occurs indicating an invalid base URL for m.identity_server, and there is an error determining the preferred identity server.

### Operating system

Windows 10

### Application version

Element version 1.11.66 olm version: (unable to retrieve at the moment)

### How did you install the app?

Installed app from the browser version of element.

### Homeserver

FAU Matrix (https://chat.fau.de) Synapse 1.108.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Experimental as per https://github.com/element-hq/element-web#supported-environments for PWA environment

**Comment by dbkr** [comment]
It looks like this is getting a timeout error loading a chunk of the app, so this is likely to be an issue with the client or server's connection. There's probably not a lot of action we can take on this on the code side.

For next time:
 * The title here doesn't really give much information (it could apply to almost any bug)
 * A screenshot would be useful
 * 1.11.66 is almost a month old
