### ISSUE TITLE
Device dehydration not working

### ISSUE THREAD

**Issue by chagai95** [element-hq/element-web#27680]
### Steps to reproduce

I search for a ticket for this issue but could not find any, I'm not sure if this is a synapse issue or an Element issue, but I'm betting on Element, also I don't have access to the synapse logs, so I am putting this here with the Element logs. If there is another issue already/the issue is synapse , then I'm sorry just ignore this issue.

1. Activate the device dehydration feature.
2. log out of all sessions.
3. send a message from another account.
4. login and enter passphrase.

Here is a video showing us trying:
https://fair.tube/w/2t6GdDmrcfLLYHHc52zbY8

#### What did you expect?
The message should be visible

#### What happened instead?
The message was not decrypted:
```
{
  "type": "[m.room](http://m.room/).message",
  "content": {
    "msgtype": "m.bad.encrypted",
    "body": "** Unable to decrypt: DecryptionError: This message was sent before this device logged in. Key backup is working, but we still do not (yet) have the key. **"
  }
}
``` 

### Operating system

Ubuntu

### Browser information

Firefox

### URL for webapp

app.element.io

### Application version

Element version: 1.11.69 Crypto version: Rust SDK 0.7.0 (068a0af), Vodozemac 0.6.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Your steps are the problem. When you log out you deactivate the dehydration labs flag, so you'd need to use an instance which has it enabled in the config otherwise dehydration will not be used at login to bootstrap your new session. `app.element.io` does not have such labs config.

**Comment by chagai95** [comment]
Thx, that's very useful information, we actually tried this with an element web instance that does have labs activated by default, do you mean we need to also have device dehydration enabled in the config? Or just the labs?

**Comment by t3chguy** [comment]
> do you mean we need to also have device dehydration enabled in the config?

Yes

**Comment by chagai95** [comment]
do you mean the labs feature "feature_dehydration"? Thx so much!
