### ISSUE TITLE
Completely broken - Uncaught TypeError: Intl.Segmenter is not a constructor

### ISSUE THREAD

**Issue by yakumi9x** [element-hq/element-web#27686]
### Steps to reproduce

Open app.element.io on latest Firefox ESR.

### Outcome

Blank page, with error in console: Uncaught TypeError: Intl.Segmenter is not a constructor

### Operating system

Linux

### Browser information

Firefox ESR

### URL for webapp

app.element.io

### Application version

Element version 1.11.70

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please use a supported browser: https://github.com/element-hq/element-web#supported-environments

**Comment by t3chguy** [comment]
Feel free to gift your data to Discord, no one is stopping you. The support policy re Firefox hasn't changed in a very long time, ESR only ever worked incidentally. ESR 115 is from over a year ago, they claim their updates are every ~42 weeks so they're overdue one.

**Comment by wodny** [comment]
Longer thread in #27682.
