### ISSUE TITLE
app.element.io web app does not load on Firefox; just a blank screen.

### ISSUE THREAD

**Issue by issuehaver2** [element-hq/element-web#27693]
### Steps to reproduce

1. Where are you starting? What can you see?

Everything was working as of yesterday afternoon. However, since last night, when I attempt to go to any app.element.io link, I just get a blank screen. Nothing loads at all. The regular element.io website works fine, so it is definitely something with the web app specifically. I can confirm that refreshing the browser and deleting cookies doesn't work. Desktop app still works fine, but my verified device is Firefox, and I use element via browser almost exclusively, so I can't see any old messages.

3. What do you click?

I can't click anything because nothing loads. I'm just trying to go to app.element.io links.

5. More steps...

I don't know, and that's why I came here. I did not install any new programs or change any settings etc. I don't think I can do the "rageshake" command because nothing is loading.

### Browser information

Firefox 115.12.0esr (64-bit)

### URL for webapp

app.element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
Firefox 115 is not a supported environment https://github.com/element-hq/element-web#supported-environments see linked policy

**Comment by isAAAc** [comment]
new esr version today in debian : 
```
# dpkg -l |grep firefox
ii  firefox-esr                              115.13.0esr-1~deb12u1                          amd64        Mozilla Firefox web browser - Extended Support Release (ESR)
ii  firefox-esr-l10n-en-gb                   115.13.0esr-1~deb12u1                          all          English (United Kingdom) language package for Firefox ESR
```

**Comment by t3chguy** [comment]
@isAAAc that isn't the new ESR. https://whattrainisitnow.com/release/?version=esr the current ESR is `128.0`

**Comment by isAAAc** [comment]
esr `128.0` is in mozilla deposit https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions

**Comment by paul-jewell** [comment]
I have come across this issue in gentoo as well, with the esr version. Currently packaged esr version is also 115.13. I recognise that I could install the 128.0 version, currently marked as "unstable" in gentoo, but would prefer not to. Is there really something in app.element.io which needs this latest Firefox version, or are you just pushing the latest version because you can? I would respectfully suggest you could use one of the bigger distributions (eg Ubuntu, Fedora or Debian) as a guide to decide which version of firefox should be targeted as a minimum.

**Comment by t3chguy** [comment]
@paul-jewell we never lock down browsers arbitrarily, ESR115 lacks https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter which was added in Firefox 125. See https://github.com/element-hq/element-web/issues/27684 for discussion about the policy

**Comment by paul-jewell** [comment]
Hi Michael - thanks for explaining this for me - I appreciate your decision. In the end, I updated to -128.
