### ISSUE TITLE
The privacy messenger doesn't respect my privacy

### ISSUE THREAD

**Issue by yakumi9x** [element-hq/element-web#27692]
### Steps to reproduce

Open Element in Tor Browser

### Outcome

Blank page, Uncaught TypeError: Intl.Segmenter is not a constructor

### Operating system

Tails

### Browser information

Tor Browser

### URL for webapp

app.element.io

### Application version

Release v1.11.70

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
See https://github.com/element-hq/element-web#supported-environments - issues related to unsupported environments are closed as per the linked policy

**Comment by t3chguy** [comment]
That is the policy set by management at this time. You can use Tor socks proxy with Element Desktop. Tor being amnesiac is not going to work well until Dehydration support lands anyway if you use end to end encryption.

**Comment by t3chguy** [comment]
Its a chat app sure, but with more complex features in crypto and otherwise than MS Teams and Slack which both explicitly do not support Firefox ESR also.

I suggest following https://github.com/element-hq/element-web/issues/27684 if Tor is close enough to ESR for that to count, or spin up your own Enhancement request for Tor specifically.

**Comment by andreymal** [comment]
> more complex features in crypto

`Intl.Segmenter` is not crypto ¯\\\_(ツ)_/¯

**Comment by rosemash** [comment]
> [MS Teams and Slack] do not support Firefox ESR

MS Teams and Slack aren't open source and don't presume to be privacy/security oriented software

**Comment by guidomz** [comment]
why was this issue closed when apparently the issue hasn't been addressed nor properly discussed?

**Comment by guidomz** [comment]
> That is the policy set by management at this time. You can use Tor socks proxy with Element Desktop. Tor being amnesiac is not going to work well until Dehydration support lands anyway if you use end to end encryption.

Proxy (and therefore Torsocks proxy) is not an option in the Element Desktop configuration or settings.

This just hangs in there and does nothing:
```
torsocks --shell
/opt/Element/element-desktop %U
```

**Comment by guidomz** [comment]
There's a bunch of other [better] clients: https://matrix.org/ecosystem/clients/ . I tried cinny just now and it works in the torbrowser.

**Comment by t3chguy** [comment]
> why was this issue closed when apparently the issue hasn't been addressed nor properly discussed?

The issue was closed because https://github.com/element-hq/element-web/issues/27684 says `Issues only affecting unsupported environments are closed`

The discussion is in https://github.com/element-hq/element-web/issues/27684


> Proxy (and therefore Torsocks proxy) is not an option in the Element Desktop configuration or settings.


```
 ~/W/element-desktop   t3chguy/macos-workaround …  /Applications/Element.app/Contents/MacOS/Element -h
Options:
  --profile-dir {path}: Path to where to store the profile.
  --profile {name}:     Name of alternate profile to use, allows for running multiple accounts.
  --devtools:           Install and use react-devtools and react-perf.
  --no-update:          Disable automatic updating.
  --hidden:             Start the application hidden in the system tray.
  --help:               Displays this help message.
And more such as --proxy, see:https://electronjs.org/docs/api/command-line-switches
```
