### ISSUE TITLE
Element asks to verify its session while it is already verified

### ISSUE THREAD

**Issue by janvlug** [element-hq/element-web#27710]
### Steps to reproduce

1. Open Element Desktop (but I think I've seen this in the browser as well).

#### What did you expect?
A verified session

#### What happened instead?
I get a "popup window" with the text: Verify this session. Other users may not trust it.
Screenshot:
![image](https://github.com/element-hq/element-web/assets/5903208/a10a3165-e030-42cc-b14d-e9871fd3cb06)

When I do the whole verify procedure. This "popup window" does not disappear. Regardless of how often I do the Verify procedure. The "popup window" stays. The only way to get rid of it is clicking the Later button.

Maybe this is the reason that this "popup window" appears again later (usually after a day or so, or maybe after starting Element again).

I see this in the browser console, maybe it is related:
```
WARN matrix_sdk_crypto::store: The user has a pending `/key/query` request which did not finish yet, some devices might be missing.
    user_id="@strypey:feneas.org"
    at /home/runner/.cargo/git/checkouts/matrix-rust-sdk-1f4927f82a3d27bb/a2235d5/crates/matrix-sdk-crypto/src/store/mod.rs:218
    in matrix_sdk_crypto::machine::get_identity with user_id="@strypey:feneas.org" timeout=Some(1s)
```

Note: exactly the same happens on Element Desktop.

### Operating system

Linux Fedora Wayland

### Browser information

Firefox 128

### Will you send logs?

Yes

**Comment by janvlug** [comment]
Debug logs should have been submitted. Should I see them here in this issue?

**Comment by t3chguy** [comment]
No as they are submitted to a private repo

![image](https://github.com/user-attachments/assets/bdc927ba-613d-46cf-a01c-982c0db575a7)

**Comment by janvlug** [comment]
I have the impression that there is some issue with my account recovery or account backup.
I tried to recover in Fractal, and I got this message, maybe it gives some hints on what is wrong:
![image](https://github.com/user-attachments/assets/ebe6f781-80f1-416c-a034-c7b7dd967402)

**Comment by janvlug** [comment]
I tried to dive a bit further into the issue that I have with Element web and Element desktop.
On element desktop, I went into Settings:
![image](https://github.com/user-attachments/assets/1050f383-0514-4af7-912d-5a57cc22d443)
When I click here on "Connect this session to Key Backup" I get a message:
Keys restored
Successfully restored 1592 keys
Next I click "OK"
The Settings windows disappears after clicking "OK". This already seems weird to me, I would expect to go back to the Settings window.
If I open the Settings window again, and go to Encryption | Secure Backup I still get exactly the same as in the screenshot above. Still stating:
not backing up your keys
Secret storage: not ready
Active backup version: None
This backup can be restored on this session

**Comment by janvlug** [comment]
I will probably not be able to reproduce this any more, because I reset Secure Backup and Cross-signing. Both have a ✅ now in settings. Having unverified sessions all the time was getting too annoying for me. I did make some notes about what I roughly did.

**Comment by richvdh** [comment]
Sorry for the delay on getting back to you on this - there have been some vacations in the team in the last couple of weeks :(.

I've investigated what happened here, and it looks like your device had gotten itself into a bit of a mess. I've opened https://github.com/element-hq/element-web/issues/27805 to track the problem. 

Thanks for the report!

**Comment by janvlug** [comment]
Thanks, no problem. I'm glad that you managed to make a new issue out of it which is way clearer than my report here.

**Comment by barathrm** [comment]
I have the same issue, and I'm wondering whether it's the same potential cause (https://github.com/element-hq/element-web/issues/27805). 

Under Security/Cross-signing, it says `Cross-signing is not set up.`, even though I have cross-verified the device from another device. The button under "cross-signing" says `set up secure backup`, but I don't want the secure backup, I've historically just used key sharing across verified devices... 

Am I missing something? I've uploaded logs from an element login where I've cross-verified it and then manually imported e2e room keys from another device.
