### ISSUE TITLE
Security Key Verification Fails on Element Desktop Client (Matrix) for Windows

### ISSUE THREAD

**Issue by FawadAhmed322** [element-hq/element-web#27716]
### Steps to reproduce

Open Element Desktop Client on Windows.
Go to the security settings.
Attempt to verify the session using the valid security key.
Notice that the session remains unverified.

#### What did you expect?
The session should be verified after entering the correct security key.

#### What happened instead?
The session remains unverified even though the correct security key is entered.

### Operating system

Windows 10

### Application version

Element version: 1.11.70 Crypto version: Rust SDK 0.7.1 (80a151e), Vodozemac 0.6.0

### How did you install the app?

Installed from the Element Website

### Homeserver

matrix.fau.de

### Will you send logs?

Yes

**Comment by FawadAhmed322** [comment]
https://github.com/user-attachments/assets/51692159-208a-4b8e-a543-e1557c97f0dc

Attached is the video showing the issue.

**Comment by asimdelvi** [comment]
Assign me this issue

**Comment by t3chguy** [comment]
Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)

**Comment by andybalaam** [comment]
@richvdh will check whether this is the same as some related issues.

**Comment by richvdh** [comment]
@FawadAhmed322: thanks for the report.  I've opened https://github.com/element-hq/element-web/issues/27808 to track this problem.
