### ISSUE TITLE
App displays a background for custom emotes when it should be transparent

### ISSUE THREAD

**Issue by Koakuma-spec** [element-hq/element-web#27745]
### Steps to reproduce

1. Type in custom emotes using /html. Here is one example: `/html <img src="mxc://midov.pl/eef5810eddf6b07d412d44ab9771e46ce774f188" width="32">`
2. Send it
3. Hover over it - whether you're using a light or a dark theme, it is there. It is ESPECIALLY visible when the user is using a custom theme.

Additional note: I think this "[bug fix](https://github.com/matrix-org/matrix-react-sdk/pull/12628)" may have been responsible for it.
Additional note 2: Because to temporarily fix this, I have to go into DevTools and manually uncheck the background color box under .markdown-body img. I also did not see this background in previous versions of element.
![image](https://github.com/user-attachments/assets/8f2d417f-2762-452a-b646-76dff1d353da)

#### What did you expect?
![image](https://github.com/user-attachments/assets/1fb13051-65d2-4a7a-b845-ad8112219bcb)
#### What happened instead?
![image](https://github.com/user-attachments/assets/babb28f6-c47d-41ca-8a9c-2304dec6a6e9)

### Operating system

Windows

### Application version

Element version: 1.11.70 Crypto version: Rust SDK 0.7.1 (80a151e), Vodozemac 0.6.0

### How did you install the app?

https://element.io/get-started

### Will you send logs?

No

**Comment by asimdelvi** [comment]
Can you assign me this issue

**Comment by t3chguy** [comment]
Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)
