### ISSUE TITLE
Mark as read not sending the correct command to mark as read

### ISSUE THREAD

**Issue by niebloomj** [element-hq/element-web#27777]
### Steps to reproduce

1. Where are you starting? What can you see?

I see a chat that is marked as unread (without a number next to it)
![CleanShot 2024-07-18 at 08 52 54@2x](https://github.com/user-attachments/assets/a5598b58-5564-42d8-9b37-de9d82e4a360)

2. What do you click?
I click this button
![CleanShot 2024-07-18 at 08 53 14@2x](https://github.com/user-attachments/assets/6def0c5c-2176-4434-b8ac-a3c06988f953)

3. I see that the chat is NOT marked as read
4. I type `/devtools` to see a developer popup
5. I see that the state is marked as unread here
![CleanShot 2024-07-18 at 08 55 14@2x](https://github.com/user-attachments/assets/853ea94d-d489-4604-9298-122af60f2c4c)
6. I edit the message and update the JSON to be an empty dict.
7. I click send
8. I see that the chat is now marked as read properly. I assume this unread state is being considered for the indicator but not one of the states that are updated by clicking mark as read.

#### What did you expect?
I expected the chat to be marked as read

#### What happened instead?
It remained unread.

### Operating system

macOS

### Application version

Version 2024071801 (2024071801)

### How did you install the app?

Github Download

### Homeserver

Dendrite 0.13.7

### Will you send logs?

Yes

**Comment by dbkr** [comment]
In step 3, did you mean 'read' or 'unread'?

This could be a bug with stable / unstable prefix support for mark as unread though, since the devtools show it's been set with the stable prefix (although we don't know with what client).

**Comment by niebloomj** [comment]
Step 3 wording is correct. After I click the button, the state does not change and the chat is not being marked as read.

**Comment by niebloomj** [comment]
Gotcha thanks! I didn't see that on mobile.

**Comment by niebloomj** [comment]
Issue still persists on latest element nightly and denrite main branch
