### ISSUE TITLE
Button to close side panel is missing

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#27799]
On receiving feedback on the new room header and right panel, it's clear that folks are missing the [x] button.

This issue represents the work needed to add the close button to the right panel. Please see the designs for more details (designs are internal only, screenshots of expected outcome are in the comments below)

Thanks!

<hr />
_Original Issue_

### Steps to reproduce

1. Click on (i) in header to open side panel on the right

#### What did you expect?
A button to close the side panel, typically an X in the top right

#### What happened instead?
No obvious way to close the side panel is visible

![image](https://github.com/user-attachments/assets/269f3a20-4815-4b09-8295-a46352fbdd0f)

Side panel in Edge:

![image](https://github.com/user-attachments/assets/a5d2c44c-dfce-4b8c-813a-25171227cf7e)

Side panel in Slack:

![image](https://github.com/user-attachments/assets/ff316174-112b-46a8-856a-3406ad3f6b41)

Side panel toggle button in MS Teams

![image](https://github.com/user-attachments/assets/892d63e1-2df3-46db-a7cf-71bbb5220c9f)

It seems a X is typical, but even without the X there are alternatives in the top right to close the panel

### Operating system

Windows 11

### Application version

Element version: 1.11.71 Crypto version: Rust SDK 0.7.1 (80a151e), Vodozemac 0.6.0

### How did you install the app?

element.io

### Homeserver

element.io

### Will you send logs?

No

**Comment by kongo09** [comment]
I noticed another weird thing. If I hit the Threads icon because, hey, it has a notification bubble, the right panel closes and does not show Threads, instead of switching over to the Threads section:

![image](https://github.com/user-attachments/assets/24b1107c-85f0-4145-a265-96c06c1fba22)

**Comment by t3chguy** [comment]
That is as design asked for it

**Comment by daniellekirkwood** [comment]
we need to figure out the close button. I also 'miss' it and get confused by how it's there sometimes and now there other times. I've connected this to the Epic to work on after first launch and will discuss it with @americanrefugee when back

**Comment by tibroc** [comment]
To me what @kongo09 mentioned in [his comment](https://github.com/element-hq/element-web/issues/27799#issuecomment-2245829755) seems like a very obvious bug and was immediatley confusing to people I talked to. @t3chguy Should this be treated as a separate issue?

**Comment by t3chguy** [comment]
You can file a separate issue, it won't change how Design/Product investigate/think about it, but might be cleaner.

**Comment by daniellekirkwood** [comment]
Our suggested solution is to drop the tabs and introduce a close button [x] to the far right of the right panel - we're just gathering feedback on the designs before committing to this solution... What would y'all think to that?

What that might look like 👇 
<kbd><img width="459" alt="Screenshot 2024-08-13 at 12 26 20" src="https://github.com/user-attachments/assets/20572853-e855-4c04-9fea-46a8a6fd8974"></kbd>

<kbd><img width="459" alt="Screenshot 2024-08-13 at 12 26 33" src="https://github.com/user-attachments/assets/d18b2e8c-13eb-4f25-8e27-c79eb0991ed9"></kbd>

@tibroc as for the buttons opening the right place in the right panel instead of closing the right panel, we'll address that too. We don't need an issue to track it (unless you already made one?)

**Comment by tibroc** [comment]
@daniellekirkwood The screenshots you provide seem like a good idea to me. It also removes the duplicated functionality between the buttons and the tabs, so it is already less confusing.

I did not yet open a separte issue, so I'm fine with tracking progress here.

**Comment by daniellekirkwood** [comment]
We drew up what keeping the tabs and introducing the [x] would look like and it gets really 'busy' as you'd also need a scroll bar to see all the tabs. 

<kbd><img width="462" alt="Screenshot 2024-08-13 at 13 44 37" src="https://github.com/user-attachments/assets/cd8d88ff-3d62-4ff2-a330-64952a84fa48"></kbd>


To tibroc's point, removing the tabs removes the duplicated functionality

**Comment by Krishcode264** [comment]
![Screenshot 2024-09-18 082355](https://github.com/user-attachments/assets/1d6dfa80-8164-4f42-a16f-8ea661876a1e)
    do we still need to add [X] icon to close the right Side panel ?

**Comment by daniellekirkwood** [comment]
Yes, we will be reintroducing the close button. Thanks for catching that I had not yet updated the content of this issue!

**Comment by daniellekirkwood** [comment]
<img width="307" alt="Screenshot 2024-09-18 at 08 57 33" src="https://github.com/user-attachments/assets/2aaf462a-c5ea-4151-9237-064211f6e916">
