### ISSUE TITLE
:shaka: should autofill correspond to 🤙

### ISSUE THREAD

**Issue by MaxTretikov** [element-hq/element-web#27800]
#### What would you like to do?

I would like typing :shaka: into the message textarea to cause an autofill for \:call_me_hand:

#### Why would you like to do it?

1. Many people only know this gesture by this name, especially many non-white (specifically Hawaiian) folks.
2. Discord and Apple keyboard do it.

#### How would you like to achieve it?

The same way other autofill emotes are achieved.

**Comment by MaxTretikov** [comment]
<img width="276" alt="image" src="https://github.com/user-attachments/assets/5326c6c5-98ef-4951-8661-30b7c95b9496">

**Comment by t3chguy** [comment]
The emoji mappings come from https://github.com/iamcal/emoji-data - we are not wanting to maintain our own mappings. You may open an issue there if you wish
