### ISSUE TITLE
EW using 100% CPU, looping on /keys/query for dead users on every sync request

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27867]
### Steps to reproduce

1. Notice your laptop is draining power faster than usual
2. Spot Element Desktop Nightly chewing constant 100%+ CPU in top
3. Profile it
4. Discover it's WASM crypto using pretty constant 100% CPU
5. Check console logs, and see it constantly hammering /keys/query for the same set of dead users on every /sync response.

#### What did you expect?

Have a sensible retry schedule calling /keys/query on dead users; don't do it on every /sync request.

Don't use 100% CPU in rust-sdk-crypto when the app is basically idle 

### Application version

Element Nightly version: 2024072801 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ara4n** [comment]
have put perf trace on the rageshake.

**Comment by richvdh** [comment]
This seems to be a recent regression. It is most annoying.

**Comment by t3chguy** [comment]
Sounds related to closed https://github.com/element-hq/element-web/issues/27165

**Comment by richvdh** [comment]
yes, but I think a somewhat different cause.

**Comment by richvdh** [comment]
I think this is actually a regression in synapse, likely introduced by https://github.com/element-hq/synapse/pull/17273: Synapse is no longer populating the `failures` property in the response.
