### ISSUE TITLE
"Download video" button will download the content of an HTTP error

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#27861]
Suppose the media repository is having a bad day, and returning 500 errors; or that the video you are looking for has been removed/was never correctly uploaded.

1. Click the download button on a video: 
![image](https://github.com/user-attachments/assets/2e5feb0e-134e-4660-a99e-14bbc27635a5)
2. Save the file to disk
3. Inspect the file

Observe that the content is, in fact, the body of the HTTP error (`{"errcode":"M_NOT_FOUND","error":"Not found"}` or similar).

**Comment by t3chguy** [comment]
Downloads are handled by the browser based on the headers on the resource. Can you confirm what `Content-Disposition` header this 500 M_NOT_FOUND (shouldn't that be a 404?) contained?

**Comment by richvdh** [comment]
> (shouldn't that be a 404?)

The behaviour is the same whether it is a 404 or 500.

> Can you confirm what Content-Disposition header this 500 M_NOT_FOUND (shouldn't that be a 404?) contained?

None, afaict.

**Comment by t3chguy** [comment]
Turns out this download button does not levy the browser's download mechanics and does load the entire blob into memory and spit it out from there
