### ISSUE TITLE
Unsupported browser error on latest Element web

### ISSUE THREAD

**Issue by Chiaki** [element-hq/element-web#27874]
### Steps to reproduce

1. Where are you starting? What can you see?
When I'm trying to open Element web, I got an error: Unsupported browser - Your browser can't run Element.
2. What do you click?
https://app.element.io/

#### What did you expect?
A working Element web client.
#### What happened instead?
A notice about unsupported browser.

### Operating system

Windows

### Browser information

Latest Firefox ESR, latest Firefox

### URL for webapp

app.element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Will you send logs?
No

Without logs there is nothing to investigate here and this issue would need to be closed

**Comment by Chiaki** [comment]
> > Will you send logs?
> > No
> 
> Without logs there is nothing to investigate here and this issue would need to be closed

Ok. But what kind of logs you will need? Browser console logs or what?

**Comment by t3chguy** [comment]
Yes, Element runs entirely in your browser, those are the only logs which relate to the application

**Comment by t3chguy** [comment]
Sounds like your browser is missing the features required to run. Both of those features are available in Firefox ESR 128. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter#browser_compatibility added in 125
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicodeSets#browser_compatibility 116

**Comment by Chiaki** [comment]
> Sounds like your browser is missing the features required to run. Both of those features are available in Firefox ESR 128.
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter#browser_compatibility added in added in 125 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicodeSets#browser_compatibility added in 116

I see. Latest version of ESR is 115.13 at this moment (https://whattrainisitnow.com/release/?version=esr).
So this is probably a bit early update for all users, because Mozilla is not pushed update to the new branch yet global.

**Comment by t3chguy** [comment]
Latest ESR is 128. 115 is the old ESR which Mozilla is still supporting until October, and we have not yet ever shipped a release which claimed ESR compatibility. See https://github.com/element-hq/element-web/tree/master?tab=readme-ov-file#supported-environments for the environments we claim to support for the version which you are using.

The next release will widen compatibility somewhat but ESR 115 (with a featureset 14 months old) will only be partially supported.
