### ISSUE TITLE
Update the Element logo to the correct file

### ISSUE THREAD

**Issue by daniellekirkwood** [element-hq/element-web#27886]
As discussed [here](https://github.com/matrix-org/matrix-authentication-service/issues/3037) we're using the wrong Element logo. 

We should update the file to the correct instance...

**Comment by daniellekirkwood** [comment]
The design team will shortly be adding a file with the correct logo

**Comment by t3chguy** [comment]
@daniellekirkwood please let the designer know these variants are needed for the logo: https://github.com/element-hq/element-web/tree/develop/res/vector-icons

**Comment by daniellekirkwood** [comment]
@element-hq/design @amshakal & @JordanConnor please review the link from @t3chguy

**Comment by JordanConnor** [comment]
Here's a file updating the icons without a background or "roundel" (i've left the solid background ones):
[element-web-icon-update.zip](https://github.com/user-attachments/files/16469228/element-web-icon-update.zip)

**Comment by t3chguy** [comment]
Thanks @JordanConnor though that zip seems to not include a bunch of the necessary icons, `apple-touch-icon-*`, `favicon.ico`, `mstile-*` - should those be left untouched?

**Comment by JordanConnor** [comment]
We could update them all (but the favicon) for consistency: [element-web-icon-update-all.zip](https://github.com/user-attachments/files/16473526/element-web-icon-update-all.zip)
