### ISSUE TITLE
Jump to last RR has vanished

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27883]
### Steps to reproduce

1. open MemberInfo for a user
2. look for the "jump to last read msg" button
3. it no longer exists

#### What did you expect?

It's useful to be able to know when a user was last seen reading msgs in a room

#### What happened instead?

We no longer can.

### Application version

Element Nightly version: 2024073101 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Sounds like the user you're looking at simply has RRs turned off, as the option is still there otherwise. 

![image](https://github.com/user-attachments/assets/a5f911c3-0ba0-471d-9966-a2983b175f7d)

**Comment by ara4n** [comment]
huh, okay, it does seem to be that. perhaps we should grey it out rather than hide it when that happens, in order to avoid this confusion?

**Comment by americanrefugee** [comment]
Sure, we can just show a disabled version of the button (no rollover, icon and text "Disabled" colors)

**Comment by t3chguy** [comment]
@americanrefugee should there be a tooltip? if so what should it say

**Comment by americanrefugee** [comment]
"This feature is disabled"

**Comment by t3chguy** [comment]
@americanrefugee thanks for confirming, though as it happens Compound's tooltips don't seem compatible with disabled MenuItems atm so first cut will skip the tooltip

https://github.com/element-hq/compound/issues/325
