### ISSUE TITLE
outdated reverse-proxy setup wiki instructions

### ISSUE THREAD

**Issue by EntityinArray** [element-hq/element-web#27889]
### Steps to reproduce

element-web checks `https://isekai.su/.well-known/matrix/client` when checking for a valid homeserver during registration.
this URL is not present in the instructions about setting up reverse-proxy
![image](https://github.com/user-attachments/assets/5f35b915-fb0b-4043-8d5b-9329529c29ea)
![image](https://github.com/user-attachments/assets/d871c028-2417-434c-b6c6-eb2da0429f1d)

### Outcome

Element-web checks URL not mentioned in the wiki

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Those instructions don't relate to this repo. That endpoint is part of the Matrix spec so Element is correct in using it: https://spec.matrix.org/v1.11/client-server-api/#well-known-uri
