### ISSUE TITLE
Unable to set up secret storage - e is undefined

### ISSUE THREAD

**Issue by mochman** [element-hq/element-web#27888]
### Steps to reproduce

1.  Open up element web on Firefox 128.0.3 or Chrome 127.0.6533.74
2.  See that a message pops up saying "Encryption Upgrade Available"
3.  Select "Upgrade"
4. Select "Next"

#### What did you expect?
I expected the process to complete.

#### What happened instead?
I received an error message stating:
"Unable to set up secret storage"

### Operating system

Windows 10

### Browser information

Firefox 128.0.3 or Chrome 127.0.6533.74

### URL for webapp

Private Server - Element version: 1.11.72

### Application version

Element version: 1.11.72

### Homeserver

local server, private Synapse v 1.112.0

### Will you send logs?

Yes

**Comment by mochman** [comment]
Logs:
```
2024-08-01T12:39:35.628Z D bootstrapCrossSigning: starting {"olmDeviceHasMaster":true,"olmDeviceHasUserSigning":true,"olmDeviceHasSelfSigning":true,"privateKeysInSecretStorage":false}
2024-08-01T12:39:35.628Z W bootstrapCrossSigning: Olm device has private keys, but secret storage is not yet set up; doing nothing for now.
2024-08-01T12:39:35.628Z D bootstrapCrossSigning: complete
2024-08-01T12:39:35.629Z I bootstrapSecretStorage: creating new secret storage key
2024-08-01T12:39:35.630Z E Error bootstrapping secret storage e is undefined
addSecretStorageKeyToSecretStorage@https://SERVERURL/bundles/5b230e251bb8460e52ca/5484.js:1:51420
bootstrapSecretStorage@https://SERVERURL/bundles/5b230e251bb8460e52ca/5484.js:1:50406
async*./node_modules/matrix-react-sdk/src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx/U/<@https://SERVERURL/bundles/5b230e251bb8460e52ca/1230.js:1:5662
async*Ve@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3767157
Ge@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3767311
./node_modules/react-dom/cjs/react-dom.production.min.js/Ar/<@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3785469
Ar@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3785563
Cr@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3785978
./node_modules/react-dom/cjs/react-dom.production.min.js/Pr/<@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3791606
Me@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3866691
./node_modules/react-dom/cjs/react-dom.production.min.js/Pr/<@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3787435
Pr@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3787465
Zt@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3775535
Qt@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3774761
./node_modules/scheduler/cjs/scheduler.production.min.js/t.unstable_runWithPriority@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3997356
Ko@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3795785
Oe@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3866433
Jt@https://SERVERURL/bundles/5b230e251bb8460e52ca/2586.js:2:3774556

2024-08-01T12:39:53.737Z D FetchHttpApi: <-- GET https://SERVERURL/_matrix/client/v3/sync?filter=xxx&timeout=xxx&set_presence=xxx&since=xxx [30133ms 200]
2024-08-01T12:39:53.769Z D [Perf]: receiveSyncChanges took 31ms
2024-08-01T12:39:53.779Z D FetchHttpApi: --> GET https://SERVERURL/_matrix/client/v3/sync?filter=xxx&timeout=xxx&set_presence=xxx&since=xxx
2024-08-01T12:40:06.993Z I Default catchAccessSecretStorageError() => void
2024-08-01T12:40:06.995Z E Secret storage creation canceled
```

**Comment by spacegaucho** [comment]
having the same issue. using plain `http` conneciton.

![image](https://github.com/user-attachments/assets/afbd9923-e0c7-45ef-bc9a-48b8892ac466)

**Comment by t3chguy** [comment]
> using plain http connection.

Sounds like your browser is going to be blocking crypto: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

**Comment by spacegaucho** [comment]
> > using plain http connection.
> 
> Sounds like your browser is going to be blocking crypto: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

Yeah, thanks for pointing that out found your previous reply: https://github.com/element-hq/element-web/issues/14535#issuecomment-659364011

If OP can confirm this is the same issue this could be closed.

**Comment by mochman** [comment]
No, I use https for my server.  While the UI shows the same error message, the console gives a different one that what you are showing.

![error_https](https://github.com/user-attachments/assets/14991ba4-f1a0-4f8a-aaa8-234e26f327b3)

**Comment by mochman** [comment]
Not sure if it's happening because of `setupNewCrossSigning: undefined` in the init object.
![Untitled](https://github.com/user-attachments/assets/80a8d30e-e11f-41ca-bc3e-0c75ed9c99ae)

**Comment by richvdh** [comment]
The "upgrade encryption" flow is broken and slated for removal: https://github.com/element-hq/element-web/issues/27455
