### ISSUE TITLE
Room Header no longer showing presence indicator

### ISSUE THREAD

**Issue by Twi1ightSparkle** [element-hq/element-web#27895]
### Steps to reproduce

You used to be able to see presence status in the room header for DMs.

#### What did you expect?

To be able to see if the person is online without having to scroll through my "People" list

![screenshot_2024-08-02T15-50-13Z](https://github.com/user-attachments/assets/21a17c4c-d8a9-4df0-b119-6a79473e6a96)

#### What happened instead?

![screenshot_2024-08-02T15-50-22Z](https://github.com/user-attachments/assets/c9d76cc5-9682-4686-adf2-4c30f2989bd8)

### Operating system

Fedora 40

### Browser information

Firefox 128.0.3 (64-bit)

### Application version

Element Web version: 1.11.72 Crypto version: Rust SDK 0.7.1 (431263d), Vodozemac 0.6.0

### Homeserver

Synapse 1.110.0

### Will you send logs?

No

**Comment by daniellekirkwood** [comment]
@americanrefugee should the presence status be visible from the header as well as the right panel?

**Comment by americanrefugee** [comment]
> @americanrefugee should the presence status be visible from the header as well as the right panel?

Yep

**Comment by daniellekirkwood** [comment]
Cool, thx. Do we have figma mock ups for this or should we just copy what we had before?

**Comment by americanrefugee** [comment]
> Cool, thx. Do we have figma mock ups for this or should we just copy what we had before?

The room header component is [here](https://www.figma.com/design/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?node-id=5848-320690&t=OmQ42z0Mf6zPulmR-4).
