### ISSUE TITLE
rich text emotes have incorrect linebreaks after the `* Matthew`

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#27896]
### Steps to reproduce

1. Type `/me *does something*`
2. Note that it renders as:

![Screenshot 2024-08-03 at 21 30 02](https://github.com/user-attachments/assets/ec328a34-a087-42b7-a0b0-2c8277ef4e78)

I've fixed this before, but it's regressed - the markdown renderer is putting a `<p/>` around the rich text causing a linebreak. It needs to be manually stripped off of emotes (or messages in general) when rendering to avoid the spurious linebreak.

#### What did you expect?

No unexpected line breaks in rich text emotes.

#### What happened instead?

An unexpected linebreak after the name of the user.

### Application version

Element Nightly version: 2024080301 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Will you send logs?

negative ghostrider

**Comment by dbkr** [comment]
This might be a regression from the RTL stuff.

**Comment by t3chguy** [comment]
I don't believe it is, I recall this from quite a long while ago
