### ISSUE TITLE
"Chat" button when using widgets is missing

### ISSUE THREAD

**Issue by Twi1ightSparkle** [element-hq/element-web#27894]
### Steps to reproduce

In previous versions of Element there was a button to open and close the right chat when using a widget

![screenshot_2024-08-02T15-43-56Z](https://github.com/user-attachments/assets/5d34acc7-e4b9-439e-835c-0339737ad349)

However in the latest, when you full screen a widget and want to for example look at threads then the only way to bring the right timeline back is to minimize then maximize the widget

#### What did you expect?

The chat button to be there when using widgets

#### What happened instead?

The chat button is missing

### Operating system

Fedora 40

### Browser information

Firefox 128.0.3 (64-bit)

### Application version

Element Web version: 1.11.72 Crypto version: Rust SDK 0.7.1 (431263d), Vodozemac 0.6.0

### Homeserver

Synapse 1.110.0

### Will you send logs?

No

**Comment by daniellekirkwood** [comment]
This should be a part of our room header work. AFAIK @americanrefugee did design this screen - 

@langleyd  @t3chguy tagging for visibility as this is probably quite a big deal and needs to be fixed - adding to epic
