### ISSUE TITLE
Prepend message type in thread panel

### ISSUE THREAD

**Issue by daniellekirkwood** [element-hq/element-web#27890]
#### What would you like to do?

In the Thread list panel there's no details about the type of message that the thread root is. This is quite confusing. 

<kbd><img width="435" alt="Screenshot 2024-08-01 at 16 27 36" src="https://github.com/user-attachments/assets/18d510de-f94a-4b21-9bff-c5461f195018"></kbd>

The first message in this list is a poll and the third is a sticker. 

#### Why would you like to do it?

Make the product better

#### How would you like to achieve it?

Prepend the event with the event type where the rendering has to change

eg: 
<kbd><img width="209" alt="Screenshot 2024-08-01 at 16 29 06" src="https://github.com/user-attachments/assets/99e26148-ed4e-4554-9179-7e19bba2a36f"></kbd>

We do this in the room list for message previews and now with pinned messages

**Comment by t3chguy** [comment]
> We do this in the room list for message previews

I can't reproduce that

![image](https://github.com/user-attachments/assets/6a52fbc7-87e9-4d81-a93d-14ce052970a0)

Do designs for this exist wrt font and all the available copy options for the many types of event?

**Comment by daniellekirkwood** [comment]
<img width="233" alt="Screenshot 2024-08-05 at 12 30 20" src="https://github.com/user-attachments/assets/fca74491-99ea-4c04-98b0-3fdb1d3e56b9">

**Comment by daniellekirkwood** [comment]
@americanrefugee would you be able to mock up a screen or two of what i'm describing here? Do you agree that it's a direction we'd want to go?

**Comment by americanrefugee** [comment]
The [component](https://www.figma.com/design/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?node-id=1112-11564&t=BP85AHRMyh8Kn88r-4) shows a generic prepend message in the Threads panel. That message can say whatever we want.

Don't we actually just need a list of all possible event types and exact wording? Or do we really need visualized examples of every single use case??

**Comment by daniellekirkwood** [comment]
The link to the document we started making notes in is here: https://www.figma.com/design/gpxHFDTNK796n84r1ZxYG2/Room-Header-%26-Details-(2024)?node-id=1320-62268&node-type=canvas&t=p2yAj4jSdyZwFDor-0

**Comment by daniellekirkwood** [comment]
@t3chguy I would like to make it clearer to users the type of message that appears in the right panel (if it's not immediately obvious). This could also apply to the room list too (right now we have an icon for a thread message but nothing else).

In the pinned message banner, we do prepend the message with the type where type != message.

Would you help me by describing what someone might need in order to make this issue ready to be worked on? I can then pull that info together in the description. 

(tagging you because it's currently part of the room header & right panel work) :)

**Comment by t3chguy** [comment]
If it already exists for Pinned messages then we can probably just say to copy that

**Comment by t3chguy** [comment]
@daniellekirkwood do we want the same prefix for thread replies too?

![image](https://github.com/user-attachments/assets/675245d2-c2f4-42be-a9d5-7edcc0024162)
![image](https://github.com/user-attachments/assets/2e9b94de-9f2e-430f-a456-a785240cb049)

e.g. if `Testing` was the name of a file should it be `*File*: Testing`

**Comment by daniellekirkwood** [comment]
I think that might be overkill but yes, let's lean into it and see if there's any responses? I'd rather be clear than confusing... especially given the number of accessibility reports we get about confusing content... 😂
