### ISSUE TITLE
Element always runs into erros with stred credentials after reboot

### ISSUE THREAD

**Issue by solomoncyj** [element-hq/element-web#27911]
### Steps to reproduce

1. log in to element
2. reboot system
3. relaunch element
4. element stuck starting and i need to relaunch and will sign me out after relaunch/ Unable to restore session page

#### What did you expect?
element starting normaly

#### What happened instead?
element stuck starting and i need to relaunch and will sign me out after relaunch/ Unable to restore sessionr page

### Operating system

Fedora 40 KDE

### Application version

1.11.73

### How did you install the app?

flatpak

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The flatpak isn't maintained by us, seek help at https://github.com/flathub/im.riot.Riot/
