### ISSUE TITLE
Read receipt markers are fundamentally broken and need to be fixed

### ISSUE THREAD

**Issue by benjistokman** [element-hq/element-web#27917]
### Steps to reproduce

Do literally anything that isn't reading a message.

#### What did you expect?

Read receipts should not be updated upon any events that don't usually mean the account actually views the content (such as profile picture or display name changes). Nor should they be sent to the bottom upon read receipt of a further up message (such as for a reaction).

#### What happened instead?

Read Receipt status is updated upon any new receipt based entirely on receipt or event timestamp, instead of anything vaguely meaningful.

If it's a message, the receipt marker should be updated to the latest message.

If it's a reaction, the receipt marker should be updated **only to that message**

If it's an event that isn't interactive, such as a profile name update, or moderation update, should not update the receipt marker.

### Operating system

Any. This also applies to mobile.

### Application version

Any of them

### Will you send logs?

Yes

**Comment by benjistokman** [comment]
And if there's only two people in the room it needs to be turned into a checkmark. It's idiotic to have the same system for large public rooms as DMs.

**Comment by dbkr** [comment]
I'm struggling to understand this issue. I think this might need some clarification. Also, we expect a professional standard of interaction here: use of words like 'idiotic' is not acceptable.

**Comment by benjistokman** [comment]
The issue is that the "seen by" feature doesn't actually represent even loosely if the person has seen a message. It updates the tag for things the user doesn't even have to interact with the room directly, such as when they update their display name or profile picture.

And it's idiotic so I'm going to say "idiotic"

**Comment by richvdh** [comment]
For links, I believe this is complaining about https://github.com/element-hq/synapse/issues/9716
