### ISSUE TITLE
Video- and Voicecall Buttons disappear in Groupchat

### ISSUE THREAD

**Issue by plui29989** [element-hq/element-web#27918]
### Steps to reproduce

1. Where are you starting? What can you see?

- create group chat
- invite two (or more) people
- first invitee joins, video-/voicecall buttons are visible
![screen](https://github.com/user-attachments/assets/833c5840-ec54-473b-871e-688e5b85edc9)

- second invitee joins, video-/voicecall buttons disappear
![screen2](https://github.com/user-attachments/assets/180a3e6e-de5b-4c94-bc6a-c3cf14106d08)

#### What did you expect?
video-/voicecall buttons are always visible
#### What happened instead?
It seems like there's not enough space in the top right corner to display all elements. With three+ room members, the member counter expands in size and "cuts off" the video-/voicecall buttons. 

### Application version

Element-Web 1.11.74

### Will you send logs?

No

**Comment by t3chguy** [comment]
Given your screenshot that doesn't look like a space thing but a configuration thing, likely your instance lacks a Jitsi therefore it cannot make conference calls, Matrix as specced are 1:1 only, group calling is still in MSC stage.

**Comment by plui29989** [comment]
Thanks for the hint. I had jitsi enabled but had widgets disabled ("UIFeature.widgets": false)
After enabling widgets again, it works as expected.
