### ISSUE TITLE
Emojis do high distraction effects with no user option

### ISSUE THREAD

**Issue by DarkMio** [element-hq/element-web#27921]
### Steps to reproduce

If someone sends 🎉 in a room, my second screen does funny things and distracts my brain.

Please understand that this is absolutely not acceptable, this threw me off two hours of working.

#### What did you expect?
It should not distract my brain or do funny things, at least not without a user option that is enabled by default.
#### What happened instead?
It distracted me and did funny things.

### Will you send logs?

No

**Comment by t3chguy** [comment]
<img width="672" alt="image" src="https://github.com/user-attachments/assets/256ddc9f-ceea-43ab-9503-96dfd156a2df">

There is a user preference for it, it also honours your navigator preference for prefers-reduced-motion which given your issue description you also may wish to enable.
