### ISSUE TITLE
Reply previews are no longer limited to 2 lines

### ISSUE THREAD

**Issue by robintown** [element-hq/element-web#27928]
### Steps to reproduce

1. Find a message that has more than 2 lines of text
2. Reply to said message

#### What did you expect?

The reply preview should be limited to show only the first 2 lines of text by default. (This is why the "expand quotes" button exists.)

#### What happened instead?

I see the entire message contents in the reply preview:

![Screenshot 2024-08-16 at 11-41-42 Element 3 Test room](https://github.com/user-attachments/assets/736a3b04-d1c3-4184-be44-fe71462fcf64)

### Operating system

NixOS unstable

### Browser information

Firefox 127.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 43fa2e533f79-react-6f3dc3069318-js-d6080398dbf5 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by florianduros** [comment]
Regression due to https://github.com/matrix-org/matrix-react-sdk/pull/12837
