### ISSUE TITLE
Element-Call: Approval for Widget permissions appears every single time

### ISSUE THREAD

**Issue by jacotec** [element-hq/element-web#27935]
### Steps to reproduce

Every single time a call is made using Element-Call, Element Web as well as Element-Desktop are always asking for approval of some Widget permissions, regardless if the switch to store the choice is set or not.

This is extremely annoying.

![image](https://github.com/user-attachments/assets/4346a95e-952a-41b8-8485-4d21eba18130)

#### What did you expect?

I expect that I'm asked only once and that my approval is stored at least if the switch to remember the decision is set to on.

#### What happened instead?

The permissions dialog appears **every single time** a call is started. Even in the same Element-Web or -Desktop session without having it closed.

### Operating system

Independent from OS

### Browser information

Independent from the browser

### URL for webapp

Private server, v1.11.75 - same happening on Element-Desktop

### Application version

1.11.75

### Homeserver

Synapse 1.113.0

### Will you send logs?

No

**Comment by dbkr** [comment]
This should be a temporary thing until the code to auto-approve these permissions lands on stable element web. Why it doesn't remember even when told may be a separate bug.

**Comment by t3chguy** [comment]
> Why it doesn't remember even when told may be a separate bug.

Presumably each new call has a new widget ID so the permissions aren't persisted across them

**Comment by jacotec** [comment]
Latest Element-Web/Desktop 1.11.76 did fix it for me. Thanks!
