### ISSUE TITLE
 GPG error: https://packages.element.io/debian default InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2850B265AC085BD

### ISSUE THREAD

**Issue by vman-dev** [element-hq/element-web#27933]
### Steps to reproduce

1. I just started **sudo apt update** on debian 10 web-server and get an error from https://packages.element.io (have a look on title)
2. I can not get rid of this error and update broke always here. Tried already:  _sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys THE_MISSING_KEY_HERE_ and also _sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys <PUBKEY>_
4. Any advice please? Where to find the latest working PUBKEY (readable)?
Thanks in advance,
vman-dev
![issue-matrix-update](https://github.com/user-attachments/assets/6a41c489-8778-4ac7-b1a5-c0d2a2fd4239)

### Operating system

Debian 10

### How did you install?

Webutorial: https://matrix.org/blog/2020/04/06/running-your-own-secure-communication-service-with-matrix-and-jitsi/

### Homeserver

self-hosted matrix-synapse solution

### Will you send logs?

Yes

**Comment by dbkr** [comment]
I don't think the tutorial you linked to involves using packages.element.io at any point and I don't think either of the commands you said you had tried are given anywhere in our instructions. We can't offer support here I'm afraid: I'd try https://matrix.to/#/#element-web:matrix.org

**Comment by richvdh** [comment]
The instructions for setting up the element repo are at https://element.io/download#linux. They say:

```
sudo apt install -y wget apt-transport-https
‍
sudo wget -O /usr/share/keyrings/element-io-archive-keyring.gpg https://packages.element.io/debian/element-io-archive-keyring.gpg
‍
echo "deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main" | sudo tee /etc/apt/sources.list.d/element-io.list

sudo apt update

sudo apt install element-desktop
```

**Comment by Harry-W-Haines-III** [comment]
Why don't you follow the standard convention and location of PGP keys????

**Comment by axelsimon** [comment]
@Harry-W-Haines-III  `/usr/share/keyrings/` is the standard location of keys used to sign apt packages on Debian (and, by extension, Ubuntu).
For instance, on a Debian server, i see:
```
$ ls -lh /usr/share/keyrings
(…)
-rw-r--r--   1 root root 8.5K Apr 10 00:05 debian-archive-trixie-automatic.pgp
(…)
```
