### ISSUE TITLE
No sign up verification email

### ISSUE THREAD

**Issue by wolgamot** [element-hq/element-web#27940]
### Steps to reproduce

Trying to sign up an account through app.element.io
I go through all the registration steps without issues, valid username password and email (gmail), pass through the captchas and accept the TOS.

### Outcome

No verification email in my inbox, nor in my spam folder. The resend button does nothing. I even tried with a different gmail account and that didn't work either.

### Operating system

NixOS Unstable

### Browser information

Firefox Browser 129.0.1

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by wolgamot** [comment]
Just had the idea to try it in the desktop client. No verification email either.
Doubt it matters here but I didn't feel like adding it to my nixos config just for this so I opened a nix shell with `$ nix-shell -p element-desktop` and tried it there, if anyone has any reason for me to try it in a system install I'll try that lol.

**Comment by GuardianLiarus** [comment]
Getting the same issue here, seems like the matrix.org server doesn't like gmail adresses

**Comment by dbkr** [comment]
This isn't gmail specific: matrix.org is having issues sending mail right now: see https://status.matrix.org/

I'm going to pin this while the matrix.org incident is ongoing as more people are likely to assume this is an Element problem.

**Comment by wolgamot** [comment]
> This isn't gmail specific: matrix.org is having issues sending mail right now: see https://status.matrix.org/

Yeah that makes a lot more sense, thank you!

**Comment by dbkr** [comment]
matrix.org's email sending is now fully restored, sp please open new issues if you see anything not right!
