### ISSUE TITLE
"Element does not support this browser" message in Element Desktop

### ISSUE THREAD

**Issue by babolivier** [element-hq/element-web#27944]
### Steps to reproduce

1. Update Element Desktop to v1.11.75
2. Open Element Desktop

#### What did you expect?

The app opens with no warning

#### What happened instead?

This warning appears at the top left corner of the app

![image](https://github.com/user-attachments/assets/8f59f755-db4b-4800-9a27-78686c7f51f5)

Related: #27934

### Operating system

Arch Linux

### Application version

Element version: 1.11.75 - Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### How did you install the app?

Arch Linux repositories: https://archlinux.org/packages/extra/x86_64/element-desktop/

### Homeserver

abolivier.bzh

### Will you send logs?

Yes

**Comment by dbkr** [comment]
dup of https://github.com/element-hq/element-desktop/issues/1828
