### ISSUE TITLE
Make Settings: Security & Privacy page wrt. Secure Backup less confusing

### ISSUE THREAD

**Issue by barathrm** [element-hq/element-web#27962]
### Your use case

I dont' know whether this is a bug or bad UX or me missing something basic.

#### What would you like to do?

Understand the context of cross-signing vs secure backup and why there are seemingly two buttons for the same thing.

I'm trying to figure out why every time I start element desktop it asks my to verify, even though I've already cross-verified the session and all my sessions have a green shield (https://github.com/element-hq/element-web/issues/27710).

I go to settings/Security & Privacy and see the following 

![image](https://github.com/user-attachments/assets/61f691ef-bb6f-4c83-a450-6a2a392fd508)

Note that under cross-signing it says that it's not set up, but the button under it is for "Set up Secure Backup", which does not sound like the same thing. I've always used cross-signing only. There seems to be a dedicate section for secure backup, with its own dedicated button "Set up". Both seem to start the same UX flow.

I'm now left with some confusing thoughts, chief among them

- Is cross-signing fixed by setting up secure backups?

**Comment by barathrm** [comment]
Addendum; if my cross-signing is broken, is this message from the Sessions part of Settings misleading/false?

![image](https://github.com/user-attachments/assets/467b14be-6509-4f8d-ab82-42b2454e47b8)

**Comment by barathrm** [comment]
Possibly related to https://github.com/element-hq/element-web/issues/26468

**Comment by richvdh** [comment]
seems like an exact duplicate of #26468, to me.

> I'm trying to figure out why every time I start element desktop it asks my to verify, 

Don't know, but I suggest you open a separate issue, include a screenshot, and submit debug logs from within the application.
