### ISSUE TITLE
Display summary for server ACL changes in the timeline

### ISSUE THREAD

**Issue by Johennes** [element-hq/element-web#27988]
#### What would you like to do?

When server ACLs change, Element Web doesn't display any further details.

![Screenshot 2024-09-03 at 08 22 13](https://github.com/user-attachments/assets/f9990bc8-56a8-434a-954b-ab2faa248912)

It would be great if it could show a summary similar to [Element Android](https://github.com/element-hq/element-android/blob/76616b1a285482e7c0d0b427a93e121ba5305a28/vector/src/main/java/im/vector/app/features/home/room/detail/timeline/format/NoticeEventFormatter.kt#L465).

![1e97070c-d790-4d5f-a5e5-1cb027fb4bdf463105238696857018](https://github.com/user-attachments/assets/4e662970-65e6-43be-88b7-545346596922)

#### Why would you like to do it?

To understand what has changed in the room without having to use devtools.

#### How would you like to achieve it?

Expand the textual representation of the event in the timeline like Android does. Alternatively, details could be displayed on demand only after clicking the event.

### Have you considered any alternatives?

None that came to my mind so far.

**Comment by t3chguy** [comment]
Yes I believe it was on an ask from T&S to not spam the timeline with illicit text

**Comment by Johennes** [comment]
Ok, I see. I guess since you cannot interact with ACLs at all in EW, that sort of fits in. Thanks both for the context.
