### ISSUE TITLE
Matrix.org has broken the federation connection 

### ISSUE THREAD

**Issue by artenax** [element-hq/element-web#27982]
### Your use case

The default and largest server on the Matrix network has broken the key exchange between messenger users. Users with accounts on matrix.org do not receive the key from their contacts with accounts on other servers, so they cannot decrypt messages. /discardsession does not help.

Users on matrix.org have in chat instead of message text: “unable to decrypt message” (in Element client) and “message could not be decrypted due to missing key” (in Nheko).
Users of any other servers can read messages from matrix.org users - they get the keys.
Communication between users of any other servers goes without problems.

**Comment by MidhunSureshR** [comment]
Not much can be done here without logs.

**Comment by t3chguy** [comment]
Closing as not an Element Web issue
