### ISSUE TITLE
Visually broken 'remove alias' button

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#27985]
### Steps to reproduce

1. Find a room where you have admin
2. Open settings
3. Add a local alias if it doesn't already have one
4. See: 
<img width="654" alt="Screenshot 2024-09-02 at 10 11 19" src="https://github.com/user-attachments/assets/6f3b4d41-651b-4c87-a403-7256a024f7c4">

#### What did you expect?
Something that looks like a delete button

#### What happened instead?
An 'x' and a separate tiny red blob

### Will you send logs?

No

**Comment by jenish064** [comment]
Hi @dbkr, I would like to work on this issue but new to matrix.org. Can you please elaborate on how do I find room with an admin (mentioned in step 1).

**Comment by dbkr** [comment]
If you create a room, you'll have admin in it.

**Comment by Dev-Gurjar** [comment]
![241019_05h25m47s_screenshot](https://github.com/user-attachments/assets/013919fe-2984-4978-a1b3-8b3eee2f2b87)

I fixed it. What should I do now? Should I send the pull request?

**Comment by Dev-Gurjar** [comment]
the size of the button has to be big otherwise the button for closing room settings will get broken.

trying to attach the changes - d0faf72a09b2d2295466bf93887d2b4edf80ba25

**Comment by florianduros** [comment]
Fixed in https://github.com/element-hq/element-web/issues/27985
