### ISSUE TITLE
When "Publish this room to the public in matrix.org's room directory?" fails it should display why

### ISSUE THREAD

**Issue by ell1e** [element-hq/element-web#27981]
### Steps to reproduce

1. Open up any room you administrate on `matrix.org`
2. Open "Settings" > "General"
3. Make sure your room has an alias with a name set
4. With "Publish this room to the public in matrix.org's room directory?" previously toggled off, toggle it on

#### What did you expect?
It either stays turned on or there's an error message explaining what's going on. I'm not filing this ticket with the intention of claiming that I think enabling this toggle should be allowed in my specific case, but if it's prohibited for a good reason then I'd expect any explanation to be displayed. My apologies if there is one somewhere and I just somehow missed it.

#### What happened instead?
The toggle can't  be toggled on and just silently turns off again. Sorry if I'm missing something obvious here, but it seems like a bug that no info is displayed about this.

### Operating system

Linux

### Browser information

Firefox 129.0.2 (64-bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.76 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by sahil9001** [comment]
Can I take this one up? I'm actually starting out with Open Source, so wanted to try my hands on this.

**Comment by sahil9001** [comment]
I have raised a PR, please check

**Comment by ell1e** [comment]
I'm not a developer on Element, but from briefly scanning the code, does it really show the actual error? It looks a little like it just always claims it's a permission issue. At least in the situation where I tested it, I would be surprised if it was a permission issue although I guess I don't really know.

**Comment by sahil9001** [comment]
@ell1e Well, if you open up the inspect tab, you will notice that the error comes from 403 request. Though I can change this to more generic error like `error.message` if you want to.

**Comment by ell1e** [comment]
So is your change checking that it's actually a 403 response? My apologies if it is, but I think whether I happen to be seeing a 403 is less relevant to addressing this properly, but rather what errors are reasonably possible.

**Comment by alienarena** [comment]
Same is happening for me. It just toggles back to off without any error.
I tried the same in FluffyChat, at least there I get a message "Now allowed to publish room". But no clue why. Any clue why publishing a room isn't allowed?

**Comment by ell1e** [comment]
@alienarena apparently room publishing on the `matrix.org` home server is fully disabled. It's not possible to add a room to the directory, it seems like.
