### ISSUE TITLE
Lost session data

### ISSUE THREAD

**Issue by vranki** [element-hq/element-web#27994]
### Steps to reproduce

1. Where are you starting? What can you see?

Launced element. 

#### What did you expect?
Element to launch
#### What happened instead?
Got the "missing session data" dialog. 
There is 18 gigs of free space on drive.

### Operating system

Ubuntu 24.04

### How did you install the app?

Ubuntu repo

### Homeserver

hacklab.fi

### Will you send logs?

Yes

**Comment by richvdh** [comment]
duplicate of #27995
