### ISSUE TITLE
Element tries to use the deprecated media endpoints on a server enacting the freeze

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-web#28011]
### Steps to reproduce

i tried out setting `enable_authenticated_media: true` in a [localhost](http://localhost/) synapse yesterday and logged in with [app.element.io](http://app.element.io/). element could not receive any media and watching the browser devtools network log i could see the requests using the old endpoints (and 404ing as i'd expect per synapse docs). checking synapse's versions there is v1.11 support and using curl i could also GET the media from the new endpoints. does someone know what's wrong? i have peers telling me it's working for them on their prod deployments that already enacted the "freeze".

#### What did you expect?
authenticated media
#### What happened instead?
unauthenticated media 404ing, no media

### Operating system

arch

### Browser information

Firefox 128

### URL for webapp

app.element.io

### Application version

Element version: 1.11.76 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Homeserver

matrixdotorg/synapse:latest

### Will you send logs?

Yes

**Comment by mkoppmann** [comment]
I have the same issue. It does work with Element Desktop and the mobile apps, but my self-hosted Element Web instance fails due to the usage of the old API:

![Error downloading image](https://github.com/user-attachments/assets/d1b8dc9e-559e-4e04-81b3-3136fa73da93)

It uses: `https://matrix.example.org/_matrix/media/v3/download/example.org/MHM%E2%80%A6XZurja?allow_redirect=true` while Element Desktop is using: `blob:vector://vector/df31…918e4` and `https://matrix.example.org/_matrix/client/v1/media/thumbnail/example.org/ODgJqxkZ…Bgm?width=28&height=28&method=crop&allow_redirect=true` for things like profile images.

**Comment by richvdh** [comment]
> and watching the browser devtools network log i could see the requests using the old endpoint

One thing to note is that the browser devtools cannot be trusted here: there is a serviceworker which is supposed to rewrite the request, but that happens *after* the devtools that record the request.

I'd suggest checking the *server-side* logs to verify which endpoint is actually being used

**Comment by mkoppmann** [comment]
From my Synapse logs:

```
synapse.http.server: [GET-382] <XForwardedForRequest at 0x7f6704810910 method='GET' uri='/_matrix/media/v3/download/example.org/yxwwqx…NkQ?allow_redirect=true' clientproto='HTTP/1.1' site='8008'> SynapseError: 404 - Not found
```

**Comment by dbkr** [comment]
This might be that the service worker hasn't registered, which can happen sometimes especially as we previously did have a service worker that didn't do anything and wasn't really registered properly. A hard reload or three would be worth a try.

**Comment by mkoppmann** [comment]
I tried it in browsers where Element Web was never loaded before and also unregistered the service worker in my regular browser. The problem still occured.

Then I tried https://app.element.io and the pictures loaded on that instance. I compared https://app.element.io/sw.js with the service worker on my instance and the source code on my server was several times larger. I was running v1.11.75 from NixOS 24.05.

Then I realized that v1.11.76 was pushed to stable. I upgraded my instance, now the authenticated images are loading and the `sw.js` file is identical to the one on app.element.io again.

**Comment by HarHarLinks** [comment]
🤷 started working sometime between then and now

**Comment by chmeeedalf** [comment]
I see this problem on Safari, but it works fine from Brave, both on the same macOS device, with the latest element-web (logging into app.element.io).  I checked the sw.js downloaded from both browsers, and `diff` shows them identical.

**Comment by turt2live** [comment]
The downloaded `sw.js` may be different than the one the browser is using. Excessive page reloads generally fixes it.

**Comment by czeidler** [comment]
Not sure if its the same issue but since about two days I can't open new images (old image are loading fine). I am getting "Error downloading image". All involved parties are at `matrix.org`. We are seeing it on Android + desktop. Clients haven't been updated recently.

**Comment by t3chguy** [comment]
> Clients haven't been updated recently.

That'll be why then, authenticated media is relatively new, so you need to be up to date if you are using a server which requires this.

@HarHarLinks has stated it has started working for them so closing this issue. It seems to be one of using outdated clients.

**Comment by jxu** [comment]
I had the same issue. I just reinstalled element-desktop from Ubuntu apt repos and I had to pkill to get it to update.

**Comment by pcworld** [comment]
See also #28370. I think Element is at the very least missing a proper error message in case the service worker is not running.

**Comment by sascha-wi** [comment]
Where is the solution for this issue?? I tried to manually start the service worker, the error is still the same. Again this only happens on the webversion!

**Comment by almatkai** [comment]
I got the same issue, also when I deploy element-web and synapse on server I get reverse of this issue, images and other files being loaded perfectly on Firefox, but not only in others see: https://github.com/element-hq/element-web/issues/29516

**Comment by m13253** [comment]
I reproduced this issue on Firefox 138.0.1 (private browsing), Element web 1.11.100.
The server log confirms that Firefox requested the deprecated media endpoints and got 404.

Specifically, this issue only happens in private browsing. It doesn’t occur in normal mode.
I guess private browsing mode is preventing Element from loading the serviceworker.

P.S.:
As Element doesn’t support multi-account, I use private browsing to log into multiple accounts and manage bot tokens.
Being unable to see profile pictures is pretty inconvenient.

**Comment by t3chguy** [comment]
Private browsing doesn't support service workers so can't access authenticated media endpoints for HTML renderers like img tag

**Comment by grinapo** [comment]
It happens on the brandest newset elementest version as well, currently _version: 1.11.108 Crypto version: Rust SDK 0.12.0 (b30f1f3), Vodozemac 0.9.0_. And before that it's been the one version before, so I do not think very old anything would have been left over. And auth media is not that new anymore, in fact, unauth media is broken beyond usage now.

It occasionally breaks, then it is rather hard to unbreak: plain reload cannot seem to help, tab needs to be closed and reopened. Most users probably don't understand what's happening.

**Comment by mittler-works** [comment]
I can confirm @grinapo description; I just experienced the problem for the first time.

> The downloaded `sw.js` may be different than the one the browser is using. Excessive page reloads generally fixes it.

Excessive page reload still fixes it in 2025, lol 😂

**Comment by grinapo** [comment]
@t3chguy would you want me to open this issue again, with the same description under a new number, or could you please reopen since this seems not to be resolved at all?
