### ISSUE TITLE
Can't join (federated) channels due to missing CORS header on app.element.io (affects Web & Mobile)

### ISSUE THREAD

**Issue by Nexus2k** [element-hq/element-web#28012]
### Steps to reproduce

1. Where are you starting? What can you see?
- I've got an invitation to join a room/DM from a self-hosted matrix instance
3. What do you click?
- I try to click "Start chatting" but receive a 502 error CORS error messages in the Developer Console

On Mobile (Android 14) I do receive an HTTP error 502 during the same action/attempt to join.

#### What did you expect?
Able to join the chat room
#### What happened instead?
I receive an error about a missing CORS header:
```
Access to fetch at 'https://matrix-client.matrix.org/_matrix/client/v3/join/XXXXXXXX' from origin 'https://app.element.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### Operating system

Windows

### Browser information

Chrome 128.0.6613.120 (Offizieller Build) (64-Bit)

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.11.76 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Nexus2k** [comment]
This problem is no longer reproducible. Not sure if something was fixed on element.io side.

**Comment by t3chguy** [comment]
> Not sure if something was fixed on element.io side.

It would have been a matrix.org issue, given it is the server which is responsible for sending the CORS headers as per the Matrix spec: https://spec.matrix.org/v1.11/client-server-api/#web-browser-clients
