### ISSUE TITLE
Chat rightpanel is ugly during EC

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#28013]
### Steps to reproduce

1. Receive an EC-in-ED video call.
2. Tap on the chat icon to view chat while on it. (This causes the rightpanel to first disappear and then reappear with the chat icon, which is clunky)
3. Close the call
4. Chat panel in the rightpanel continues to be visible, alongside the main timeline
5. See double.

![Screenshot 2024-09-04 at 19 23 48](https://github.com/user-attachments/assets/1860db91-e945-4c4c-97f8-e5b1afaa63e1)

#### What did you expect?

 * Chat RightPanel should open immediately when you click on it in the top menu
 * It should close at the end of the call, and never end with both timelines visible simultaneously.

### Application version

Element Nightly version: 2024090301 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
Two timelines being visible is a really old bug surrounding maximized widgets: #23591

**Comment by t3chguy** [comment]
> (This causes the rightpanel to first disappear and then reappear with the chat icon, which is clunky)

Tracked as part of https://github.com/element-hq/element-web/issues/27799

> Chat panel in the rightpanel continues to be visible, alongside the main timeline

Fixed by https://github.com/element-hq/matrix-react-sdk/pull/94
