### ISSUE TITLE
Downloading image via full screen toolbar fails with JSON M_NOTFOUND

### ISSUE THREAD

**Issue by krachynski** [element-hq/element-web#28018]
### Steps to reproduce

1. In any room click on an image
2. See the full page display with the control toolbar
3. Click on download on the toolbar

#### What did you expect?
I expected the image to download.

#### What happened instead?
A new tab was opened up with a JSON response.
`{"errcode":"M_NOT_FOUND","error":"Not found"}`

### Operating system

Windows 11

### Browser information

Firefox 130

### URL for webapp

app.element.io

### Application version

Element version: 1.11.76 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by turt2live** [comment]
triager: this is distinct from https://github.com/element-hq/element-web/issues/28011 because media is loading, but the download button specifically fails.

**Comment by Krishcode264** [comment]
is it browser related issue ? it works well in brave and chrome

**Comment by ledlamp** [comment]
It happens in unencrypted rooms on servers with authenticated media enabled like matrix.org. happens on chrome, 128.0.6613.138, firefox 130.0, element 1.11.77. Two people I asked to test, using app.element.io and matrix.org, also have the issue. It started happening on my own server too when I enabled authenticated media, so I had to turn it back off. It makes it impossible to save images, as even right-clicking and saving the image fails or gives a json file.

Does not affect encrypted rooms where the images are blobs and don't have URLs.

**Comment by kegsay** [comment]
Just hit this in an unencrypted room, when it opens in Firefox. You can get around this on Element Desktop by clicking the download button when you hover over the image confusingly, I guess the code paths are different.

**Comment by freelock** [comment]
Also getting this....

**Comment by ledlamp** [comment]
Oh, that is right.

This button works fine: 
![image](https://github.com/user-attachments/assets/0080896d-f398-49ec-8126-c329923b84c4)

This one does not:
![image](https://github.com/user-attachments/assets/d4ea0691-409f-436b-8cb3-51da5fae5d52)

![image](https://github.com/user-attachments/assets/b2490916-ccab-4331-9f3f-f3f496dca2ec)


Element version 1.11.83 Chrome 130
