### ISSUE TITLE
Latest Brave browser reports as "Not Supported"

### ISSUE THREAD

**Issue by craigs100** [element-hq/element-web#28033]
### Steps to reproduce

1. Where are you starting? What can you see?
(https://app.element.io/#/home)

2. What do you click?
On page load

3. More steps…
None

#### What did you expect?
I expected just to get on and use the system

#### What happened instead?
I received the attached dialogue
![Screenshot from 2024-09-10 16-57-21](https://github.com/user-attachments/assets/111f1b57-412b-4a06-bc41-ed6d8e687d07)

### Operating system

Linux Mint 21.3 Cinnamon, up to date.

### Browser information

Brave : Version 1.69.162 Chromium: 128.0.6613.120 (Official Build) (64-bit)

### URL for webapp

https://app.element.io/#/home

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Brave is indeed not supported: https://github.com/element-hq/element-web#supported-environments

That doesn't mean it won't work, just means it may stop working after an Element or Brave update if features Element requires are missing, and as per the policy it isn't a browser we accept issues for at this time. Sorry

**Comment by craigs100** [comment]
I've been developing web for nearly 30 years. Browser wars are a thing of the past. No one writes web code these days that relies on specific browser functionality. Yes, there may be the odd layout issue with Safari or old browsers, but Brave isn't one of them. It's Chromium and about as up to date as you can get.

Anyway, I'm having to run it in Firefox now specially. Thanks for your time. I'll leave it there. :)

**Comment by t3chguy** [comment]
Indeed, we do not target any specific browser functionality, we rely on web features as defined by the web standards and MDN, but as a business we only go out of our way to support & test a set number of browsers & versions. If Brave is up to date enough for you then dismissing the toast you shared a screenshot of will be remembered within that session's localStorage so you do not need to do so again.
