### ISSUE TITLE
Cannot download shared image in timeline

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#28031]
### Steps to reproduce

1. Receive an image
2. Observe

#### What did you expect?
See the image

#### What happened instead?
![image](https://github.com/user-attachments/assets/998eadbc-a0ec-4622-8ba0-931cf662af5e)

### Operating system

Windows 11

### Application version

Element version: 1.11.76
Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### How did you install the app?

element.io

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by twispers** [comment]
Also getting this error in Firefox on app.element.io but in Chromium the website works fine.

**Comment by pepper-jk** [comment]
> This is due to matrix.org media being slow and therefore timing out. The team is aware, and working on remedies.

Is there any update on this you can link? All I'm finding is related to "authenticated media" and they basically say "update your client or refresh your page multiple times". Does not sound like they are working on any remedies.

> If you're seeing errors for images/files, please update your client. Web users may need to refresh the page multiple times before things start working because of how browsers (don't) work. If you're still seeing issues, it may be a bug in your client: please report it to the developers so they can take a look.
https://matrix.org/blog/2024/09/06/this-week-in-matrix-2024-09-06/

**Comment by pepper-jk** [comment]
So funny thing, our admin figured out what was going wrong.

It appears matrix.org has [\[sunsetted\] unauthenticated media](https://matrix.org/blog/2024/06/26/sunsetting-unauthenticated-media/).
And our server, Synapse, does not activate authenticated media by default.

So our admin set [enable_authenticated_media](https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html#enable_authenticated_media) to `true` in our config.
Now we are able to receive media from matrix.org again.

Hope this helps anybody, hosting their own matrix server, check that your server allows authenticated media.
In case you are using Synapse, just follow the documentation link above.

@kongo09 if you are still having trouble on element.io, I'd inform the server admin team in case they are unaware.

**Comment by dbkr** [comment]
Going to close this now authenticated media has settled down, if that was the problem, or if it wasn't, in the hope that matrix.org's media server has recovered.
