### ISSUE TITLE
New Pin Room Banner: Triggers fullscreen emote animations on first load.

### ISSUE THREAD

**Issue by CrimsonFork** [element-hq/element-web#28042]
### Steps to reproduce

Have a pinned message containing an emote that triggers animations as a pinned message, open the according room after starting the client.

#### What did you expect?
No animations messages that have already been read.
#### What happened instead?
Animations for already read messages that have been pinned.

### Operating system

OpenSUSE Tumbleweed

### Browser information

Firefox 130.0 (Flatpak)

### URL for webapp

app.element.io

### Application version

1.11.77

### Homeserver

  Synapse 1.112.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is already fixed on develop by https://github.com/element-hq/matrix-react-sdk/commit/1ac533e7306a49212cec2d21cb7c82c38e6f202c
