### ISSUE TITLE
Verification popup never disapperars after successful verification

### ISSUE THREAD

**Issue by mlen** [element-hq/element-web#28051]
### Steps to reproduce

- "Verify this session" popup appears
- click "Verify" and go through the process until it displays information that it worked

#### What did you expect?

- the session should be verified
- "Verify this session" popup should disappear

#### What happened instead?

- "Verify this session" popup remains
- session is not verified and "The interactive verification process didn't verify the user identity of the user that participated in the interactive verification" is logged to console

### Operating system

mac OS, Windows, NixOS

### Browser information

Firefox 129.0.2

### Application version

Riot version: 1.11.76 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Homeserver

Synapse 1.101.0

### Will you send logs?

Yes

**Comment by richvdh** [comment]
Duplicate of https://github.com/element-hq/element-web/issues/27808
