### ISSUE TITLE
Sudden connection lost (Russia)

### ISSUE THREAD

**Issue by sicikh** [element-hq/element-web#28050]
### Steps to reproduce

Try to access any Element resource (try to login, view chats, etc.) from Russia (primarily from Moscow). Element and Matrix sites are working properly.

This happens to ~50 people simultaneously.

VPN solves an issue, if we can connect to it (in Russia only a few VPN works). 

#### What did you expect?

Normal functioning Element.

#### What happened instead?

SSL connection timeout (from curl accessing, for example, `/client/versions` endpoint), connection lost (from apps). 

### Operating system

Windows, Manjaro Linux, Android, iOS

### Application version

Element version 1.11.75, Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### How did you install the app?

https://element.io/get-started (Windows), manjaro repository `extra/element-desktop` (Manjaro Linux)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by sicikh** [comment]
Bypassing DPI solves the problem. In total, we can conclude that the official server https://matrix.org is blocked in Russia.

**Comment by t3chguy** [comment]
Closing as not an Element Web issue, but a matrix.org one, various domains are blocked in a plethora of countries, companies, and ISPs, there isn't anything Element can do about that.

**Comment by marknefedov** [comment]
I would add, because of Matrix.org being block, all apps (including mobile), juts crash and won't let to choose a self-hosted server option.
<img width="1486" alt="image" src="https://github.com/user-attachments/assets/228c4228-1387-4679-a105-7295839a95f5">

**Comment by marknefedov** [comment]
on IOS "Loading" spinner just rolls indefinitely.
![695F6325-814C-44CC-A260-D8723E8D785B_4_5005_c](https://github.com/user-attachments/assets/c1935592-ca83-4de1-9e01-de4ee274f2d3)
It probably would be better to add a "Choose server" button somewhere in the starting menu, as of my testing this is the only problem with self hosting.

**Comment by MKC-MKC** [comment]
I have too the same problem. In the Element mobile iOS client there is no way to manually enter the server address as on a PC. The PC version allows you to immediately enter the server, bypassing requests at https://matrix-client.matrix.org, which are censored in some countries, including Russia.

<img width="1680" alt="Снимок экрана 2024-11-01 в 17 59 50" src="https://github.com/user-attachments/assets/2d237f0a-967f-427c-b8da-d7318fc19681">

**Comment by t3chguy** [comment]
@MKC-MKC this repo is not related to the iOS app. Seek the repo relating to the application which you are running to get help.
