### ISSUE TITLE
Element not respecting DND in macOS

### ISSUE THREAD

**Issue by derpwiz** [element-hq/element-web#28088]
### Steps to reproduce

Enable DND on macOS
make sure sounds are enabled
receive messages.  The messages received were only in People chat the other user running their own node/server while I am registered through matrix.org

#### What did you expect?
no noises
#### What happened instead?
lots of noises

### Operating system

macOS 14.6.1 (23G93)

### Application version

Element version: 1.11.77 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### How did you install the app?

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Duplicate of https://github.com/element-hq/element-desktop/issues/788
