### ISSUE TITLE
Pinned event changes not showing up in the room timeline

### ISSUE THREAD

**Issue by anoadragon453** [element-hq/element-web#28091]
### Steps to reproduce

1. Have a room with some pinned messages
2. Unpin the messages
3. Don't see the `m.room.pinned_events` rendered in the timeline in any way (even if "Show hidden timeline events" is enabled)

#### What did you expect?

To see the `m.room.pinned_events` state event rendered in the timeline as "@user:domain unpinned a room message." or similar. This is a supported feature, but there appears to be a bug preventing it from appearing.

#### What happened instead?

No mention of pinned messages in the timeline. However I can see the `m.room.pinned_events` state events in `/devtools`, and there are no pinned messages being shown in the room's UI. So my client definitely received the state events.

I've included some additional details (room ID, state event IDs) in the associated rageshake. 

### Operating system

NixOS Linux

### Application version

Element version: 1.11.77 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### How did you install the app?

From https://github.com/NixOS/nixpkgs/

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by anoadragon453** [comment]
It turns out that if you turn the feature on in Labs, the events get rendered :facepalm: 

Timo appeared had the same bug with the feature on however, so leaving this open for him to confirm.

**Comment by dbkr** [comment]
Pinned messages are out of labs now - are you still getting this? I tried briefly and couldn't repro (although they did collapse slightly weirdly with a pin+unpin just collapsing to "Dave changed the pinned messages for the room." with no option to expand).

**Comment by anoadragon453** [comment]
@toger5 says it was probably a fluke. So, closing.
