### ISSUE TITLE
no screenshots/avatars received from matrix.org

### ISSUE THREAD

**Issue by wzrdtales** [element-hq/element-web#28095]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please open a new issue and fill in the issue template if you want help.

**Comment by wzrdtales** [comment]
this is from a long follow up in a chat with your team, reopen.

**Comment by wzrdtales** [comment]
a little friendlier tone would help a long way. they asked a rageshake which requires an issue, the team probably got what they needed, if not and if i get asked to fill those details already known i will fill them for sure

**Comment by t3chguy** [comment]
Sorry if you find my tone subpar. I am on the team and did not get what I needed to be able to triage the issue. If you'd like this to be looked at I suggest filling in the fields so that it can be reopened
