### ISSUE TITLE
Can't see most images after the authenticated media changes

### ISSUE THREAD

**Issue by jmartinesp** [element-hq/element-web#28099]
### Steps to reproduce

1. Open a room.
2. Receive an image media message, see the thumbnail and the image trying to load
3. Most of the time the image never loads.

#### What did you expect?

The image to be displayed in the timeline.

#### What happened instead?

For some images, closing the room and opening again makes the image load properly. For others, it never loads no matter how many times I retry.

This also happens in my Element Desktop app (nightly version 2024092501 (2024092501)), so it's not exclusive of EW, but I expected the sable EW version to work even if the nightly desktop one might fail.

### Operating system

MacOS

### Browser information

Arc Version 1.61.0 (53949) - Chromium Engine Version 129.0.6668.59

### URL for webapp

app.element.io

### Application version

Element version: 1.11.78 Crypto version: Rust SDK 0.7.2 (7a21514), Vodozemac 0.7.0

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by jmartinesp** [comment]
I mentioned this also happens on the desktop app (in fact, it's where I first experienced it, then I tried in the browser):

> This also happens in my Element Desktop app (nightly version), so it's not exclusive of EW, but I expected the sable EW version to work even if the nightly desktop one might fail.

Also, the logs display an internal server error, so I'm not sure how the browser being used is related, but ok. It seems to be working well again now, maybe the server was having some temporary issues.

**Comment by richvdh** [comment]
Sadly this seems to have been dropped. Unfortunately the logs for the media server have rotated, so I don't think we have a way to figure out what happened here.

**Comment by richvdh** [comment]
See also: https://github.com/element-hq/element-web/issues/28031
