### ISSUE TITLE
Registering & signing out without joining an e2e room means you can't verify on next login

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#28112]
### Steps to reproduce

1. Register a fresh account
2. Click 'skip' on the use case screen
3. Sign out again (not that you don't get a conformation)
4. Sign in again

#### What did you expect?
Probably to just be signed in?

#### What happened instead?
"Unable to verify this device" error and forced to go through the reset flow even though I never set anything up in the first place

### Will you send logs?

No

**Comment by BillCarsonFr** [comment]
I think it's a duplicate of https://github.com/element-hq/element-web/issues/27015

**Comment by dbkr** [comment]
oh, it is yes.
