### ISSUE TITLE
Make system tray icon disableable

### ISSUE THREAD

**Issue by fkm** [element-hq/element-web#28115]
#### What would you like to do?
Please add an option to the settings of the desktop version to disable the system tray icon.

#### Why would you like to do it?
Ever since KDE and Windows introduced icon-only taskbars I don't want applications to show up in the system tray.

#### How would you like to achieve it?
This can be a checkbox in the settings: "Disable system tray icon/integration."

### Have you considered any alternatives?

While I think that this option should be provided by the application, I did try to disable the icon from the system tray settings in KDE. Unfortunately, it is fixed to "Always shown."

![image](https://github.com/user-attachments/assets/fb3c4986-886b-45b1-973a-eb9bab52bfe9)

**Comment by t3chguy** [comment]
Settings > Preferences > Show tray icon and minimise window to it on close
