### ISSUE TITLE
Sending events in encrypted rooms is broken without error

### ISSUE THREAD

**Issue by MTRNord** [element-hq/element-web#28127]
### Steps to reproduce

1. Have an encrypted DM
2. Try to send a message

#### What did you expect?

Able to send messages.

#### What happened instead?

It fails with a failure and retry which also fails. No request is being sent. It works in all other non e2ee rooms.

### Operating system

Fedora Silverblue 40

### Browser information

Firefox 130.0.1 (64-Bit)

### URL for webapp

develop.element.io

### Application version

Version von Element: e428a1eb536b-react-33c900e3070a-js-866fd6f4a3ee Krypto-Version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### Homeserver

matrix.midnightthoughts.space

### Will you send logs?

No

**Comment by MTRNord** [comment]
Note: I assume this is due to the same buggy assumption element X is using of having unsinged devices. Element (as in the product) seems to be forgetting that there exist developers in their customerbase which by nature of matrix will always have unverified devices since not even all clients can do that.

As long as this is not possible to happen network wide, I do consider this behaviour both broken and actively hostile to their userbase. Even worse there exist devices which are unsigned due to element X...

**Comment by MTRNord** [comment]
Ok turns out there is in labs a hidden "disable" button for globally disabling it...

**Comment by t3chguy** [comment]
Fixed by https://github.com/element-hq/matrix-react-sdk/pull/104
