### ISSUE TITLE
Settings: Modal header and "Account" tab are never translated

### ISSUE THREAD

**Issue by jaller94** [element-hq/element-web#28123]
### Steps to reproduce

![2024-09-30_14-09](https://github.com/user-attachments/assets/77775656-2293-4de0-9f0e-1ef131466104)

1. Set Element Web to any language other than English
2. Open "All settings"

#### What did you expect?
The heading and "Account" should be translated.

#### What happened instead?
The heading and "Account" are never translated.

### Operating system

Manjaro Linux (based on Arch Linux btw)

### URL for webapp

staging.element.io

### Application version

Element version: 1.11.78 Crypto version: Rust SDK 0.7.2 (7a21514), Vodozemac 0.7.0

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
They are hooked up to i18n, just missing community-contributed translations for those keys, e.g. `settings|keyboard|dialog_title` & `settings|account|title`

![image](https://github.com/user-attachments/assets/ea014ec0-ba31-4ebb-9cd6-7b999b967d6f)
![image](https://github.com/user-attachments/assets/a028c3e1-7f57-4e44-8944-3cedaf0b4a43)

And as shown above, Polish has them, and works as expected:

![image](https://github.com/user-attachments/assets/3e144d2e-c4db-4a7c-b9a7-cde70a476762)
