### ISSUE TITLE
Receiving "Unable to decrypt message" for several users in specific rooms

### ISSUE THREAD

**Issue by zenimasu** [element-hq/element-web#28132]
### Steps to reproduce

Initially reached out via email communication (NVT#1560598) and was requested to leave a GitHub issue. Several users are seeing "Unable to decrypt message" in encrypted rooms for specific users, but not all users are unable to see the messages. I'll send logs from my account (the one who can't read the message) and the sender's account. The messages are still showing up as "Unable to decrypt message" if that helps.

#### What did you expect?
To be able to see all messages in the room

#### What happened instead?
"Unable to decrypt message" is shown instead of the message

### Will you send logs?

Yes

**Comment by zenimasu** [comment]
logs were sent from both users just now

**Comment by BillCarsonFr** [comment]
> logs were sent from both users just now

Hello, it looks like the logs we have from the sender are from the wrong device. We need the logs from the device that sent the message that cannot be decrypted.

Is it possible to check on your side?

**Comment by BillCarsonFr** [comment]
Looks several messages coming from `justm**son:tradebusters.ems.host` are not decryptable on purpose. The sender has disabled sending keys to unverified devices. You might want to check with him he enabled this option in settings:

<img width="660" alt="image" src="https://github.com/user-attachments/assets/c046174d-f46d-4f42-852b-3e09edd1cfba">

If not please confirm

**Comment by zenimasu** [comment]
@BillCarsonFr could you reattach the image? For some reason I'm unable to see it (it just looks like a broken image).
