### ISSUE TITLE
Chat export doesn't include reactions

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#28134]
### Steps to reproduce

1. Export chat with reactions
2. I think we used to see reactions in the HTML?
3. We don't any more.

#### What did you expect?

Reactions in chat export

#### What happened instead?

No reactions in chat export.

### Application version

nightly

### Will you send logs?

No

**Comment by langleyd** [comment]
Looks like it's never been supported, but from my tests its easy to add. I can open a PR shortly(element-web and react-sdk are currently being merged).
