### ISSUE TITLE
Element can't log in back 

### ISSUE THREAD

**Issue by nikolam** [element-hq/element-web#28142]
### Steps to reproduce

1. Using Xubuntu 22.04 , Element installed form Flatpak, 1.11.79
2. I just open Element from Xfce desktop as usual and it gives a message of can not restore the session/log in
3. Before it used to be able to just log in, after asking me for user password, presumably to access system key store. 
last time I started it, it asked me to authenticate by using Element on another device (?) so I did, on Android and Web browser, too.. The asked to create second password and to store key on disk. 
After that I needed to use 2 passwords to log in and now unlike before it does not let me log in again, prompting me to send a bug report with logs. 

### Operating system

Linux  5.15.0-122-generic #132-Ubuntu SMP, Xubuntu 22.04.5 LTS

### Application version

Element	im.riot.Riot	1.11.79	stable	flathub	system

### How did you install the app?

Flathub

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Issues with the flatpak should be filed at https://github.com/flathub/im.riot.Riot/ as it isn't a package we maintain
