### ISSUE TITLE
Quick settings button image missing

### ISSUE THREAD

**Issue by Justinzobel** [element-hq/element-web#28150]
### Steps to reproduce

Left side-bar with avatar, spaces, threads and settings icon is missing the image for the settings icon

### Outcome

Icon is missing

### Operating system

Solus (Linux)

### Browser information

130.0.1

### URL for webapp

https://chat.opendesktop.org

### Application version

Element version: 1.11.79 Crypto version: Rust SDK 0.7.2 (7a21514), Vodozemac 0.7.0

### Homeserver

chat.opendesktop.org synapse 1.110.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
The chat.opendesktop.org deployment is broken, bunch of icons are missing.

https://chat.opendesktop.org/icons/settings-solid.5cd4545.svg not found - should return https://app.element.io/icons/settings-solid.5cd4545.svg

I suggest seeking out to their admins.

**Comment by Justinzobel** [comment]
> The chat.opendesktop.org deployment is broken, bunch of icons are missing.
> 
> https://chat.opendesktop.org/icons/settings-solid.5cd4545.svg not found - should return https://app.element.io/icons/settings-solid.5cd4545.svg
> 
> I suggest seeking out to their admins.

As the admin, what would you suggest to me in how to fix it? :)

**Comment by t3chguy** [comment]
I suggest using a support room rather than a bug tracker, and telling the helpers there how you deploy it

**Comment by Justinzobel** [comment]
Super helpful, thanks!

**Comment by Justinzobel** [comment]
Solved with https://github.com/element-hq/compound/issues/321
