### ISSUE TITLE
Notification icon has become a square

### ISSUE THREAD

**Issue by robintown** [element-hq/element-web#28169]
### Steps to reproduce

Hover over a room tile

#### What did you expect?

To see a notification 'bell' icon

#### What happened instead?

![Screenshot from 2024-10-09 07-18-58](https://github.com/user-attachments/assets/b829687d-bbfe-4a21-96c0-f6d119e1a537)

### Operating system

NixOS unstable

### Browser information

Firefox 130.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 8d77b2a15ae5-react-df4a223eb621-js-b842192a3415 Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by florianduros** [comment]
@richvdh I'm pretty sure that the issue is fixed, I don't have it on develop since some weeks.

**Comment by t3chguy** [comment]
https://github.com/element-hq/matrix-react-sdk/pull/124 was the cause and was also reverted.
