### ISSUE TITLE
Verification | Unexpected verified badge in DM title bar on the other user avatar

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#28164]
As a fresh user (`eve`) I created a DM with `Alice`.
I then noticed a verified badge on alice

![image](https://github.com/user-attachments/assets/2cb95b39-df6b-42f7-80da-2add045a8a84)

I double check on the console, and Alice is not verified:

`await mxMatrixClientPeg.get().getCrypto().getUserVerificationStatus("@alice:localhost")`
> UserVerificationStatus {needsUserApproval: false, crossSigningVerified: false, crossSigningVerifiedBefore: false, tofu: false}

**If I refresh the browser tab it is then fixed.**
<img width="357" alt="image" src="https://github.com/user-attachments/assets/e02d625c-d525-4117-9f46-0e621ba0246a">

Here is more details on the succession of events:
<img width="599" alt="image" src="https://github.com/user-attachments/assets/ac9849c3-e080-49b1-9009-d62a2ae80d70">

Maybe an outdated room shield? and some confusion between user badges and room shields?

**Comment by BillCarsonFr** [comment]
Found a similar out-of-date UX problem
Starts with Alice and Eve verified.
Let Eve reset it's identity

I then see the warning
![Image](https://github.com/user-attachments/assets/ae7fb969-cc4b-4d60-b862-ea09c8a9ee18)

Then reverify Eve from Alice side.
The Room header is out-of-date and still showing the red warning

switch to one room and come back. it is then up to date
![Image](https://github.com/user-attachments/assets/f9b3c541-2e76-4ec7-bba2-5646abdf4950)

**Comment by andybalaam** [comment]
Crypto team will put this on our backlog and do a timeboxed investigation of whether this is simple to fix.

**Comment by uhoreg** [comment]
Moving back to Qualification, now that we have an estimate.
