### ISSUE TITLE
Change Twitter link on launch screen to Mastodon

### ISSUE THREAD

**Issue by thibaultmol** [element-hq/element-web#28163]
#### What would you like to do?
Currently if you start element without being logged in it shows these links in the footer
![image](https://github.com/user-attachments/assets/244d7e5b-4fe8-4a16-9cd3-c890d1a49bf6)

#### Why would you like to do it?
I think it would make sense to link to open social platform like Mastodon (which you have an account on https://mastodon.matrix.org/@Element than to Twitter :nauseated_face: (which isn't even called twitter anymore anyway)

#### How would you like to achieve it?
Just makes sense for an open ecosystem to promote other open ecosystems than a proprietary one.

**Comment by t3chguy** [comment]
Approved by @ara4n
