### ISSUE TITLE
Why is the avatar still showing as the old one in the Jitsi call after changing accounts?

### ISSUE THREAD

**Issue by doufuhou** [element-hq/element-web#28175]
### Steps to reproduce

1. Log in to account A and it displays normally.  
2. After logging out, when logging into account B, it shows account A's avatar.
![image](https://github.com/user-attachments/assets/d13e04d6-db1b-4fb1-a130-adf350909c36)

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
```
What did you expect?
What happened instead?
Operating system
No response

Browser information
No response

URL for webapp
No response

Application version
No response

Homeserver
No response

Will you send logs?
Yes
```

Please fill in the issue template if you want help.

The Jitsi API sets the avatar only at the time you join the conference, not in the pre-screen, and logging out Element is unable to clear cookies on another domain e.g. Jitsi, hence the old avatar being kept around.

**Comment by doufuhou** [comment]
> ```
> What did you expect?
> What happened instead?
> Operating system
> No response
> 
> Browser information
> No response
> 
> URL for webapp
> No response
> 
> Application version
> No response
> 
> Homeserver
> No response
> 
> Will you send logs?
> Yes
> ```
> 
> 如果您需要帮助，请填写 issue 模板。
> 
> Jitsi API 仅在您加入会议时设置头像，而不是在预屏幕中设置，并且注销 Element 无法清除其他域（例如 Jitsi）上的 cookie，因此保留了旧的头像。
Thank you for your response! After creating an instance of JitsiMeetExternalAPI, passing the avatarUrl can resolve this issue.

**Comment by doufuhou** [comment]
https://github.com/element-hq/element-web/issues/28175#issuecomment-2405573574

**Comment by doufuhou** [comment]
@t3chguy Thank you for your response! After creating an instance of JitsiMeetExternalAPI, passing the avatarUrl can resolve this issue.
