### ISSUE TITLE
Cannot verify my session / device with security key

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-web#28181]
### Steps to reproduce

1. Start fresh Element web from https://app.element.io
2. Login
3. Go to Settings
4. Go to Sessions
5. Identify my Session and click on: Verify Session
6. Click on: Enter Security Key
7. Enter the security key

#### What did you expect?
Session is verified

#### What happened instead?
I end up back at the screen of step 6 without any error message

### Operating system

Windows 11

### Browser information

Edge

### URL for webapp

https://app.element.io

### Application version

Version von Element: 1.11.80 Krypto-Version: Rust SDK 0.7.2 (7a21514), Vodozemac 0.7.0

### Homeserver

https://matrix.opendesk.family

### Will you send logs?

Yes

**Comment by richvdh** [comment]
Somehow, the account has gotten into a state where private cross-signing keys are stored in 4S, but the public keys have not been published.

Seems to be basically a duplicate of https://github.com/element-hq/element-web/issues/27252.
