### ISSUE TITLE
Recent room list missing

### ISSUE THREAD

**Issue by FSG-Cat** [element-hq/element-web#28182]
### Steps to reproduce

Update Element to affected version.
Launch Element.
Done.

#### What did you expect?
Breadcrumbs or Recent rooms or whatever the feature is called is blank. Replicated on both Win 11 and Win 10 machines both running same element version.
#### What happened instead?
Recent rooms works and displays correctly.

#### Other notes.

Homeserver software remains unchanged and the feature worked pre update.

### Operating system

Windows 10 22H2

### Application version

Element Nightly version: 0.0.1-nightly.2024101001 Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### How did you install the app?

https://element.io/download

### Homeserver

feline.support

### Will you send logs?

No

**Comment by FSG-Cat** [comment]
I should add that the list works on the local state once you start clicking on rooms but this list does not sync between clients affected by this bug.

**Comment by t3chguy** [comment]
Fixed by https://github.com/element-hq/matrix-react-sdk/pull/139
