### ISSUE TITLE
Old gitter permalinks no longer works

### ISSUE THREAD

**Issue by agocorona** [element-hq/element-web#28190]
### Steps to reproduce

1. Where are you starting? What can you see?

old permalinks to messages of this kind  https://gitter.im/Transient-Transient-Universe-HPlay/Lobby?at=5c8d8ada52c7a91455a80954  no longer works.

3. What do you click?

For example:
https://gitter.im/Transient-Transient-Universe-HPlay/Lobby?at=5c8d8ada52c7a91455a80954

5. More steps…
I used them heavily in documents to link to gitter conversations, as valuable references and now they don´t work.

#### What did you expect?

To navigate to the exact message referenced by the permalink

#### What happened instead?

It goes to the end of the room

### Operating system

Windows

### Browser information

Edge, chrome

### URL for webapp

https://gitter.im/Transient-Transient-Universe-HPlay/Lobby?at=5c8d8ada52c7a91455a80954

### Application version

Versión de Gitter: 1.11.79 Crypto version: Rust SDK 0.7.2 (7a21514), Vodozemac 0.7.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This project is unrelated to gitter, you'd have to find somewhere else to file issues relating to gitter.im
