### ISSUE TITLE
Missing log-in link

### ISSUE THREAD

**Issue by mbiesiad** [element-hq/element-web#28214]
### Steps to reproduce

1. Visit https://app.element.io/#/register
2. Set Polish language
3. See missing link to log-in action (incorrect)
4. Compare the view with English version or French (correct)

#### What did you expect?
Add missing link  

#### What happened instead?
Shows clear/raw text (no hyperlink)

# Screenshot:

![scr](https://github.com/user-attachments/assets/179659ad-01bf-451c-b71d-4b86dfe90fcc)

### Operating system

NA

### Browser information

NA

### URL for webapp

https://app.element.io/#/register

### Application version

v1.11.81 Latest

### Will you send logs?

No

**Comment by t3chguy** [comment]
The community maintained translation is broken

![image](https://github.com/user-attachments/assets/46d701ed-1b9d-4884-8a5a-338792774c99)

The link is missing from the 2nd item. I suggest seeking help in the translations room

**Comment by mbiesiad** [comment]
It is already FIXED.
