### ISSUE TITLE
Backport the new media endpoints to legacy OS's

### ISSUE THREAD

**Issue by c33s** [element-hq/element-web#28246]
#### What would you like to do?

upload and download files with matrix on legacy systems like win7 and win8. 

#### Why would you like to do it?

because win10 & win11 are spyware and there are simply too many legacy systems out there which do not care about "win7 is EOL". in reality i know customers which use still win xp and also there i also know companies where there app still runs on php 5.6 with smyony 1.x
it is simply reality that there is less and less budget for IT and security. keeping at least some important apps like browser and messenger would be helpful for partly airgapped systems to still be able to get some files (download it on a secure system an send via matrix to the company internal matrix server. so the legacy system would be safe if matrix would still work.)

#### How would you like to achieve it?

backport the media endpoint changes or add a compatibility layer

### Have you considered any alternatives?

if you don't want to the following to happen and need a windows system (for using tools which don't run on wine), you only have the option to keep a win7 or win8 system.

> Windows 10 and Windows 11 have been criticized for privacy concerns due to several factors:
> 
> Telemetry and Data Collection: Both operating systems send a significant amount of data back to Microsoft, including device information, usage patterns, and diagnostic data. Even though users can limit some data sharing, they cannot fully opt out of telemetry.
> 
> Mandatory Microsoft Account: Windows 11 and some versions of Windows 10 push users towards using a Microsoft account to set up the system, making it harder to use a local account. This ties more personal data, like browsing history and settings, to the cloud.
> 
> Cloud Storage Integration: Windows encourages the use of OneDrive for storing files, which means that documents and other data can automatically be uploaded to Microsoft's cloud services, raising concerns about file security and data sovereignty.
> 
> Windows Defender: While Defender is a solid antivirus, it cannot be fully disabled in Windows 10 and 11. In addition, there are concerns that some files and system data are sent to Microsoft for analysis without explicit user consent.
> 
> These features contribute to concerns that Windows compromises user privacy by default.

**Comment by t3chguy** [comment]
There are multiple security fixes which would also need backporting if we were to make a build for a legacy OS, not all of them within our control. Electron has not ported security updates to Electron 22 which is the last version which supports Windows 7. We're up to Electron 33 now. We would not like to release a secure communication product with known security vulnerabilities for a small cohort of users. You are more than welcome to fork it and build such yourself, all of the code & even our workflows to build & package are wholly open source.

**Comment by c33s** [comment]
understood. have assumed that this issue will be closed.

still sad, that you break such an essential api with no fallback for legacy clients. 
you are talking about security vulnerabilities but expose users to the real privacy risks of companies who simply fetch data from us all and don't treat us in an ethical way.

if updating would be only about security, it would never be a problem to update but updates always introduce new "feature" or remove good features. firefox moving from xul to js long time ago, chrome forcing us all to manifest v2 and now manifest v3 which kills ad blocking. what is the sense of a secure communication app if the OS is taking pictures of everything entered on this machine? how can such an OS be more "secure" than an os which doesn't do that?

- Windows Recall is a dependency in explorer in W11 24h2 https://www.youtube.com/watch?v=G9FRadIkkE0 
- 12 months left to keep Copilot off your desktop or learn Linux https://news.ycombinator.com/item?id=41868060
- https://www.pcgamer.com/software/windows/windows-10-only-has-a-year-of-support-12-months-left-to-keep-copilot-off-your-desktop-or-learn-linux/
- General Motors Caught Red-Handed: Texas Sues for Billions Over Decade-Long Data Theft https://www.youtube.com/watch?v=seyvYETWf34
- Mazda requires $100+ subscription for remote start after filing DMCA takedown of open source program https://www.youtube.com/watch?v=1n0AI5aemUY
- Food delivery EULA versus 7th Amendment: EULA wins. Bill of Rights loses https://www.youtube.com/watch?v=f8YBk8Hyr9g
- ASUS charges customers for bootloader unlocking, which was initially advertised as free. https://www.youtube.com/watch?v=yjz6x-YwI00
- Disney thinks streaming service arbitration clause removes liability for Epcot patron's death https://www.youtube.com/watch?v=eUO59pw3r6k

in general i can recommend louis rossmans videos

(i would have used invidious links if youtube wouldn't have made such a great effort of breaking/blocking it.)
