### ISSUE TITLE
Unable to remove reactions from messages after page refresh.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [element-hq/element-web#28249]
### Steps to reproduce

1.	Uploaded an MP4 H265 video file to https://matrix.to/#/!LdFTpgksHpQBBtjOMN:matrix.org/$7z9qoF17VHc08wg2mlG1fRYtfhXbHmhxp-ZNQCXcK-o?via=matrix.org&via=beeper.com.
1.	Reacted with an emoji.

1.	Attempted to remove the reaction.

	### Outcome

	#### What did you expect?
	
	I should have been able to.

	#### What happened instead?

	I was able to.

1.	Refreshed the page.

1.	Attempted to remove the reaction.

	### Outcome
	
	#### What did you expect?
	
	I should have been able to.
	
	#### What happened instead?
	
	I was unable to remove it, yet was able to remove others added subsequently:
	
	> https://github.com/user-attachments/assets/3d9700f7-9942-4ed8-a618-d6bcd175d04b

### Operating system

https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso

### Browser information

https://fedora.pkgs.org/40/fedora-updates-x86_64/firefox-131.0.3-1.fc40.x86_64.rpm.html

### URL for webapp

https://develop.element.io/#/room/!LdFTpgksHpQBBtjOMN:matrix.org

### Application version

> ```YAML
> Element version: 249c0fd1df0a-js-88cf5eb76983
> Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0
> ```

### Homeserver

https://matrix.org/

### Will you send logs?

Yes

**Comment by beedell-roke** [comment]
> ### Will you send logs?
> 
> Yes

Sent:

> `/rageshake` I'm unable to remove the "O" reaction from [`https://matrix.to/#/!LdFTpgksHpQBBtjOMN:matrix.org/$7z9qoF17VHc08wg2mlG1fRYtfhXbHmhxp-ZNQCXcK-o?via=matrix.org&via=beeper.com`](https://matrix.to/#/!LdFTpgksHpQBBtjOMN:matrix.org/$7z9qoF17VHc08wg2mlG1fRYtfhXbHmhxp-ZNQCXcK-o?via=matrix.org&via=beeper.com).

**Comment by MidhunSureshR** [comment]
This is really weird. From the logs, it looks like [eventShouldLiveIn(redaction_event)](https://github.com/matrix-org/matrix-js-sdk/blob/0a29063bc9e61ee70ca43820d4bb91f6a27f1237/src/models/room.ts#L2248) is returning false.

Maybe try `Clear cache and reload` in `Settings` ~> `Help & About`.

**Comment by beedell-roke** [comment]
> Maybe try Clear cache and reload in Settings ~> Help & About.

@MidhunSureshR, unfortunately, I've confirmed that it's either a problem with the server or a module common to all clients, since I have been able to reproduce this on [`f-droid.org/repo/im.vector.app_40106204.apk`](https://f-droid.org/repo/im.vector.app_40106204.apk) (of [`element-hq/element-android`](https://github.com/element-hq/element-android)), too.

However, looking back at [the referenced message](https://matrix.to/#/!LdFTpgksHpQBBtjOMN:matrix.org/$7z9qoF17VHc08wg2mlG1fRYtfhXbHmhxp-ZNQCXcK-o?via=matrix.org&via=beeper.com), the emojis in question appear to have finally been redacted. Perhaps the undermentioned message source data shall tell you something of value (if I've selected the correct message – the highlight isn't very obvious):

<p></p><details><p></p>

<blockquote>

```JSON
{
  "content": {
    "body": "1000009396.mp4",
    "info": {
      "duration": 71077,
      "h": 720,
      "mimetype": "video/mp4",
      "size": 28260134,
      "thumbnail_info": {
        "h": 1080,
        "mimetype": "image/jpeg",
        "size": 280933,
        "w": 1920
      },
      "thumbnail_url": "mxc://matrix.org/UwUKTRfOHkZaYjEbFNdShHKd",
      "w": 1280
    },
    "msgtype": "m.video",
    "url": "mxc://matrix.org/ubcJFQyLqcXmyqqNzlsLiSfX"
  },
  "origin_server_ts": 1729422562766,
  "room_id": "!LdFTpgksHpQBBtjOMN:matrix.org",
  "sender": "@rokejulianlockhart:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "membership": "join",
    "age": 1057522431,
    "m.relations": {
      "m.thread": {
        "latest_event": {
          "content": {
            "body": "Re_ Submission from Service Request Form_ Black display on FW16 after inputting LUKS password. 2024-10-20T12_29_59+01_00.eml",
            "info": {
              "mimetype": "message/rfc822",
              "size": 46349
            },
            "m.mentions": {},
            "m.relates_to": {
              "event_id": "$7z9qoF17VHc08wg2mlG1fRYtfhXbHmhxp-ZNQCXcK-o",
              "is_falling_back": true,
              "m.in_reply_to": {
                "event_id": "$MMpRrrlL2AXm0M0gjb45KTwV8rnnJsW0pQdZZ8qQRdw"
              },
              "rel_type": "m.thread"
            },
            "msgtype": "m.file",
            "url": "mxc://matrix.org/XvClKBoPaUVNvHpCZvSrvHAg"
          },
          "origin_server_ts": 1729424463627,
          "room_id": "!LdFTpgksHpQBBtjOMN:matrix.org",
          "sender": "@rokejulianlockhart:matrix.org",
          "type": "m.room.message",
          "unsigned": {
            "age": 1055621570
          },
          "event_id": "$GNjxcv9C-MuE2UQ5JaQINVLRD4XQEAaoBcNJjX-nqjM",
          "user_id": "@rokejulianlockhart:matrix.org",
          "age": 1055621570
        },
        "count": 4,
        "current_user_participated": true
      }
    }
  },
  "event_id": "$7z9qoF17VHc08wg2mlG1fRYtfhXbHmhxp-ZNQCXcK-o",
  "user_id": "@rokejulianlockhart:matrix.org",
  "age": 1057516185
}
```

</blockquote>

<p></p></details><p></p>

My consequent estimate is that the `matrix.org` server is taking an inordinate amount of time to process these requests. Perhaps, it is a matter of prioritisation, considering that emoji reactions should be fairly inconsequential in comparison to ensuring that messages are sent on-time...?

**Comment by t3chguy** [comment]
> either a client-source or server issue, since I have been able to reproduce this on [f-droid.org/repo/im.vector.app_40106204.apk](https://f-droid.org/repo/im.vector.app_40106204.apk) of [element-hq/element-android](https://github.com/element-hq/element-android) too.

Element Web & Element Desktop share no code other than encryption code which is unrelated to reactions/redactions so this is a server issue

**Comment by RokeJulianLockhart** [comment]
> https://github.com/element-hq/element-web/issues/28249#issuecomment-2452303316

@t3chguy, I'd say that closing this seems short-sighted - surely the client should at least display a reportable error when this fails? I know that Discord does when it's unable to add or remove a reaction.

**Comment by t3chguy** [comment]
@RokeJulianLockhart the server says the redaction is successful with a 200 OK, so it not reflecting that change down `/sync` is not something a client can reliably detect or deal with. The server is not spec compliant in not remote echoing the change.

**Comment by RokeJulianLockhart** [comment]
@t3chguy, I realize that I'm no Matrix developer, but if the client *continues* to display the reaction after I tap or click it to redact it, then surely at some level the client understands that the event was not yet ratified by the server?

I estimate that if whatever informs it that the emoji should remain continues to signal so *despite* the fact that the 200 OK signal has been received by the client, then surely the client should be able to ascertain that the reaction should no longer be displayed?

**Comment by t3chguy** [comment]
@RokeJulianLockhart sure, you could have defensive code like that, and contributions welcome, but having to assume the Server may not be spec compliant will probably double the codebase in size if we have to handle most edge cases which may occur when dealing with non-compliant or buggy servers.

**Comment by beedell-roke** [comment]
> https://github.com/element-hq/element-web/issues/28249#issuecomment-2452332498

@t3chguy, I have reported this to [`matrix-org/matrix.org/issues/2553`](https://github.com/matrix-org/matrix.org/issues/2553#issue-2637886941). Many thanks.

**Comment by beedell-roke** [comment]
@t3chguy, per [`matrix-org/matrix.org/issues/2553#issuecomment-3347665805`][1], can this be re-closed as a *duplicate* of [`matrix-org/matrix.org/issues/2553`][2]? It'll assist someone, who discovers this issue first, to ascertain what path to take to its most recent replacement.

[1]: https://github.com/matrix-org/matrix.org/issues/2553#issuecomment-3347665805

[2]: https://github.com/matrix-org/matrix.org/issues/2553
