### ISSUE TITLE
Make "Match system theme" the default theme

### ISSUE THREAD

**Issue by Justinzobel** [element-hq/element-web#28264]
#### What would you like to do?
Make "Match system theme" the default on all new installs. This is how many other websites are by default. 

#### Why would you like to do it?
This is an accessibility and preferences issue as not everyone can tolerate bright screens or dark.

#### How would you like to achieve it?
Change the default

### Have you considered any alternatives?

None

**Comment by t3chguy** [comment]
It already is the default https://github.com/element-hq/element-web/blob/develop/src/settings/Settings.tsx#L751-L755

**Comment by Justinzobel** [comment]
Ah my apologies, I guess I've been copy/pasting my settings file over for a while.
