### ISSUE TITLE
Click on & view/start a DM with a profile from the list of reactions.

### ISSUE THREAD

**Issue by Fixie00** [element-hq/element-web#28280]
#### What would you like to do?

Click on and view/start a DM with a profile from the list of a message’s reactions. Currently, when pulling up a message’s reactions list, you can’t further click on a profile to engage with them efficiently/privately.

#### Why would you like to do it?

To quickly, efficiently, and privately interact with people in a public room.

Most chat platforms have this, including Element’s less private counterpart, Discord.

#### How would you like to achieve it?

By bringing up the same menu that displays when you search for and click a name from the members list, but when you click on a name from a message’s reactions list.

Attachments:
How this feature looks in Discord - https://github.com/user-attachments/assets/77dcd4a2-ac93-4254-8f95-7e146f67df74

How it looks in Element without the option implemented - https://github.com/user-attachments/assets/c86d8ac1-a50f-4ab5-bead-4d2f8af2f475

Ideally this menu would pop up when clicking a name from the reactions list - 
![IMG_4755](https://github.com/user-attachments/assets/6f7887cc-4d90-40c0-af25-ab9b3bfa02df)

### Have you considered any alternatives?

Currently. You have to go out of reactions, then all the way to the members list, then remember/search up a name that you saw from the reactions list, which is especially inefficient.

**Comment by t3chguy** [comment]
That doesn't look like element-web. You'd need to file an issue on the repository relating to the app which you are using. Element Web doesn't have a list of reactions view, they're shown inline on the timeline only.
