### ISSUE TITLE
Cannot encrypt any message

### ISSUE THREAD

**Issue by austinhuang0131** [element-hq/element-web#28291]
### Steps to reproduce

1. Try to send any message in any encrypted room

(Clear cache & reload has been attempted)

#### What did you expect?

Message sent

#### What happened instead?

Message does not finish encrypting

### Operating system

macOS

### Application version

Nightly 2024102401

Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### How did you install the app?

Direct download

### Homeserver

tchncs.de

### Will you send logs?

If requested

**Comment by t3chguy** [comment]
Without any logs there is nothing to go off here, repro steps don't work without context.

**Comment by austinhuang0131** [comment]
it is submitted

**Comment by austinhuang0131** [comment]
whatever you did, the issue is gone now

**Comment by austinhuang0131** [comment]
reappearing, logs sent again

Element Nightly version: 2024103001
Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

**Comment by richvdh** [comment]
From the logs, there seems to be something wrong with your server: it is not correctly responding to `/keys/upload` requests; they are timing out after 60 seconds:

```
logs-0000.log.gz:2024-10-30T16:08:18.285Z D FetchHttpApi: --> POST https://matrix.tchncs.de/_matrix/client/v3/keys/upload
logs-0000.log.gz:2024-10-30T16:09:18.400Z D FetchHttpApi: <-- POST https://matrix.tchncs.de/_matrix/client/v3/keys/upload [60115ms TypeError: Failed to fetch]
logs-0000.log.gz:2024-10-30T16:09:20.401Z D FetchHttpApi: --> POST https://matrix.tchncs.de/_matrix/client/v3/keys/upload
```

Suggest you take this up with the server admin; it's not really something that can be addressed on the client side.
