### ISSUE TITLE
Room history does not exist

### ISSUE THREAD

**Issue by olezhadem** [element-hq/element-web#28317]
### Steps to reproduce
When i open the room, i dont see history

### Operating system

Windows

### Browser information

Google Chrome 130.0.6723.70

### URL for webapp

https://app.element.io/

### Homeserver

matrix.itcomp.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Your logs contain server errors saying you do not have permission to the history. If you have more details then please provide them but one line of "Steps to reproduce" is not enough.

**Comment by olezhadem** [comment]
> ### Steps to reproduce
> When i open the room, i dont see history
> 
> ### Outcome
> #### What did you expect?
> #### What happened instead?
> ### Operating system
> Windows
> 
> ### Browser information
> Google Chrome 130.0.6723.70
> 
> ### URL for webapp
> https://app.element.io/
> 
> ### Application version
> _No response_
> 
> ### Homeserver
> matrix.itcomp.org
> 
> ### Will you send logs?
> Yes



> Title



> Your logs contain server errors saying you do not have permission to the history. If you have more details then please provide them but one line of "Steps to reproduce" is not enough.
All good? thank you!

**Comment by olezhadem** [comment]
> Ваши журналы содержат ошибки сервера, сообщающие, что у вас нет разрешения на историю. Если у вас есть больше подробностей, пожалуйста, предоставьте их, но одной строки «Шаги для воспроизведения» недостаточно.

All good! Thank you!
