### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by Twig6943** [element-hq/element-web#28334]
### Steps to reproduce

1. Where are you starting? What can you see?
![image](https://github.com/user-attachments/assets/f811c855-5944-4024-8048-0ffb067b69bc)
3. What do you click? 
idk

#### What did you expect?
For the app to open up as intended.
#### What happened instead?
It didn't

### Operating system

EndeavourOS

### Application version

1.11.82

### How did you install the app?

Flatpak (flathub)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Twig6943** [comment]
Logs
[rageshake.zip](https://github.com/user-attachments/files/17559542/rageshake.zip)

**Comment by t3chguy** [comment]
Issues for the flatpak live at https://github.com/flathub/im.riot.Riot/
