### ISSUE TITLE
Privacy invasion and Privacy Breach + no way to disconnect old sessions

### ISSUE THREAD

**Issue by spirillen** [element-hq/element-web#28369]
### Steps to reproduce

try disconnect no longer active sessions

#### What did you expect?

Just disconnect no longer active sessions

![image](https://github.com/user-attachments/assets/a54c9797-d626-4936-94d4-12e255881fd4)

![image](https://github.com/user-attachments/assets/eb6cdd24-c68e-4245-a6c2-9732b6ef3c89)

![image](https://github.com/user-attachments/assets/21a3c953-f36a-4f3f-9acd-65fe2824f90d)

Now all these sessions are opened to be compromised, because I can't disconnect them...

#### What happened instead?

You will force users to connect to github and connect theirs account to another privacy abusive player, not only sticking to Cloudflare, who we all knows are decrypting all connections for PII harvesting and "Caching" of data

![image](https://github.com/user-attachments/assets/a3219213-e584-4193-8a66-4d5c37dd6eac)

### Operating system

No matter

### Application version

No matter

### How did you install the app?

No matter

### Homeserver

crimeflare.github.matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
The authentication necessary is set by your Matrix server. Not Element.
