### ISSUE TITLE
"Your account provider doesn't support signing into a new device with a QR code." on matrix.org

### ISSUE THREAD

**Issue by progval** [element-hq/element-web#28371]
### Steps to reproduce

1. Go to app.element.io
2. Log into a matrix.org account (no third-party login)
3. Click your avatar
4. Click "Link new device"

#### What did you expect?

To see a QR code to log into Element X

#### What happened instead?

!["QR code not supported: Your account provider doesn't support signing into a new device with a QR code."](https://github.com/user-attachments/assets/92f73a2c-a699-46cc-b363-a778f661b943)

### Operating system

Debian 12

### Browser information

Firefox 128.4.0esr

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
matrix.org indeed lacks support. It is missing https://github.com/matrix-org/matrix-authentication-service

**Comment by Bill-Joe-Tech** [comment]
Also seems this issue can be created when making an account on Element, then trying to sign-in on Element X.

**Comment by doznap** [comment]
yeah it's a huge issue, what am i supposed to do?
i created the element account with google, have the desktop app on ubuntu, windowz, and android app, want element x, open all 3 apps and sign in on webapp in browser, NONE of them allow linking via qr code
and the element x app does not say 'oh you can sign in with your google account' like the webapp does. 
fix it. hot damn

**Comment by t3chguy** [comment]
> yeah it's a huge issue, what am i supposed to do?
> i created the element account with google, have the desktop app on ubuntu, windowz, and android app, want element x, open all 3 apps and sign in on webapp in browser, NONE of them allow linking via qr code
> and the element x app does not say 'oh you can sign in with your google account' like the webapp does. 
> fix it. hot damn

That's not an issue in element web which is what this repository is about. Your chosen matrix server lacks support for qr. Your chosen mobile client lacks support for sso without oidc which your matrix server currently requires.

**Comment by alexander-potemkin** [comment]
Have the same issue with my own server with MAS installed.

**Comment by dessalines** [comment]
Due to the authorization grant already used bug, and this one, signing in to element x android is currently impossible.

**Comment by t3chguy** [comment]
@dessalines that doesn't sound like an issue with Element Web. Element web can't force your server to support QR code login

**Comment by dynamodan** [comment]
Can we at least link to the documentation page where the QR code functionality is configured?  It should be somewhere in here: https://element-hq.github.io/matrix-authentication-service/

I'm still looking for it.  Can someone please locate it.

**Comment by alexander-potemkin** [comment]
> Can we at least link to the documentation page where the QR code functionality is configured? It should be somewhere in here: https://element-hq.github.io/matrix-authentication-service/
> 
> I'm still looking for it. Can someone please locate it.

It's in Synapse config actually:

```yaml
experimental_features:
  # QR code generation
  msc4108_enabled: true
```

Hope that helps.

**Comment by dynamodan** [comment]
Oof.  That doesn't work.  I probably don't have the correct version of synapse.  I was actually hoping for a documentation link.  While the config example is nifty, it isn't really a link to documentation.

**Comment by alexander-potemkin** [comment]
> Oof.  That doesn't work.  I probably don't have the correct version of synapse.  I was actually hoping for a documentation link.  While the config example is nifty, it isn't really a link to documentation.

I'm not a part of Element developers team and I was under impression that you need functionality to work.

If that is not the case, I'm sorry that I was not able to help to address your hopes

**Comment by dynamodan** [comment]
It must be very, very bleeding edge.  Here's a link to the pull request that the msc4108 feature is named for:
https://github.com/matrix-org/matrix-spec-proposals/pull/4108

It really has nothing to do with MAS (matrix authentication service) as some previous comments are stating.

I think the feature is only available when compiling from the https://github.com/element-hq/synapse/tree/hughns/msc4108-2025 branch.  I'm running from the latest synapse debian package and it lacks the msc4108 feature.  It crashes on startup with the `msc4108_enabled: true` configuration option.

**Comment by alexander-potemkin** [comment]
Official docker image has it enabled for sure. Guess you can figure out more details from there (the builds are open).

**Comment by dynamodan** [comment]
Ok so I updated to the latest 1.44.0 and the barcode shows, but scanning it results in an error which I will document here, for the benefit of others:
2026-01-10 21:02:46,434 - synapse.http.server - 131 - INFO - GET-578 - <XForwardedForRequest at 0x7fa92412afd0 method='GET' uri='/_synapse/client/rendezvous/01KE**********************Y4' clientproto='HTTP/1.1' site='8008'> SynapseError: 404 - Not found

**Comment by dynamodan** [comment]
I think it's because the version of MAS that I have on the server might not have the QR code support somehow.

**Comment by alexander-potemkin** [comment]
> I think it's because the version of MAS that I have on the server might not have the QR code support somehow.

I don't believe you are on the right way here.

The error is from Synapse server. While the QR code functionality relates to / depends on / implemented on MAS.

QR works just fine when configured correctly. It is not exactly obvious from the docs although - that's for sure.

And the docs doesn't seem to be up to date as well - you might want to check my issues on Synapse repo for more info.

**Comment by dynamodan** [comment]
These are your issues on Synapse when I searched by `author:alexander-potemkin`
https://github.com/element-hq/synapse/issues/19355
https://github.com/element-hq/synapse/issues/19276
https://github.com/element-hq/synapse/issues/19272

None of them relate to the QR code stuff, that I could tell.

Can you post the contents (with tokens and secrets redacted of course) of the `experimental_features.msc3861` and `experimental_features.msc4108` sections of your homeserver.yaml?

My apologies to the element-hq folks for cluttering up this thread, but it's a bit on them for closing the issue as not-planned I guess.

At the bottom of this page:
https://element-hq.github.io/matrix-authentication-service/setup/homeserver.html

It mentions migrating the experimental_features.msc3861 (which is required when msc4108 feature is enabled) so I think that might be part of my problem.  Sorry to bug you so much but I think this dialogue is tremendously helpful to others as well.

Thanks in advance

**Comment by alexander-potemkin** [comment]
It's an open source free project and the authors owes us nothing.

Not to say that I like the level of documentation or support all of the decisions they make, but I don't think that there is anything  on them.

I offered my issues as I've posted lots of configs snippets there and logic I kind of reverse engineered, including reverse proxy configuration which is not up to date in docs and affects lots of API communication.

I don't believe I can offer much at the moment, but I do have plans to publish working configuration / better docs, as from my experience - for a complete stack, including Element Calls, etc.

**Comment by t3chguy** [comment]
This is an issue tracker, not a support forum. Element Web doesn't care whether your server is Synapse or Conduwuit or Dendrite, for this feature to work it needs a server supporting https://github.com/matrix-org/matrix-spec-proposals/pull/4108 and its listed dependencies.

**Comment by dynamodan** [comment]
I'm testing Element Web with these 3 versions of matrix synapse:
1. The package from the Ubuntu 24.04 LTS repository which is version 1.143.0+noble1
2. The package from the Debian GNU/Linux 13 (trixie) repository which is version 1.144.0+trixie1
3. The latest version from PyPI which is 1.44.0

Only matrix synapse 1.44.0 from PyPI will result in a QR code showing in Element Web with the msc4108 experimental feature turned on.  The others fail.

As for (re)defining what exactly the github issue tracker is (or is not) in this context, I'll let the numbers speak:   As of now, there are 3,157 open issues and 21,263 closed.  People are coming here for support, and receiving it.

Element Web / Matrix synapse / MAS being open source software, where else do people go for support?  Send me a link to the "support forum" if there is one.  I would even be happy to pay the right person, or sign up for paid support somewhere.  Where do you go for support?

**Comment by alexander-potemkin** [comment]
@dynamodan , if you click a support request when raising an issue here - you will be redirected to the Matrix server for that: https://matrix.to/#/#element-web:matrix.org
It's not that you will receive your help 100% there, although.
 
For the hosting - you can use someone from the providers list: https://matrix.org/ecosystem/hosting/

I'm not aware if there is any pre-approved service providers list. I believe having one would be beneficial, but it also contradicts the way Element is trying to monetize, I believe - as they are building an open source product and monetizing on cloud offering / self-hosted pre-build product.

If you find any list of such MSP's - please, let me know!

**Comment by t3chguy** [comment]
> As of now, there are 3,157 open issues and 21,263 closed

A good chunk of them duplicates, or enhancement requests.

> People are coming here for support, and receiving it.

Often I will offer a one-liner before closing the issue and pointing people to the support room `#element-web:matrix.org` - though in your case `#synapse:matrix.org` given you're having issues with Synapse.

> where else do people go for support?

Ironically, the Matrix rooms relating to the specific software project you are interested in.
