### ISSUE TITLE
Disable encryption via /.well-known/matrix/client

### ISSUE THREAD

**Issue by frenn** [element-hq/element-web#28397]
### Steps to reproduce

Good afternoon.

1. Launched the synapse server from the Docker-image matrixdotorg/synapse:latest on the domain matrix.example.com.
2. Launched element-web from the Docker-image vector/element-web on the domain element.example.com.
3. Everything is fine. The messaging is ok. The calls are working.

Encryption must be disabled. My teammates will lose the keys in a week. :D

1. Read this:
https://github.com/element-hq/element-web/blob/develop/docs/e2ee.md#disabling-encryption
2. Set it up in nginx on the domain matrix.example.com :
```
location /.well-known/matrix/client {
  return 200 '{"io.element.e2ee": {"force_disable": "true"}}';
  add_header Content-Type application/json;
  add_header "Access-Control-Allow-Origin" *;
}
```
3. Checking the setting:
**curl -s https://matrix.example.com/.well-known/matrix/client | jq**

I get:
```
{
    "io.element.e2ee": {
        "force_disable": true
    }
}
```

### Outcome

When creating private chats, encryption is still enabled by default. You can't turn it off.

What did I do wrong?

### Will you send logs?

No

**Comment by t3chguy** [comment]
Are your usernames `@foo:matrix.example.com` or `@foo:example.com`?

**Comment by frenn** [comment]
> Are your usernames `@foo:matrix.example.com` or `@foo:example.com`?

@foo:matrix.example.com

**Comment by t3chguy** [comment]
Logs would be required to dig into this further

**Comment by t3chguy** [comment]
![image](https://github.com/user-attachments/assets/24a8b45f-8504-44b8-8b9b-b40df5d74be4)

There's a bit of a disconnect here, are you returning `true` or `"true"`?

**Comment by frenn** [comment]
> There's a bit of a disconnect here, are you returning true or "true"?
Sorry, **"true"**.

> Logs would be required to dig into this further
[synapse.log](https://github.com/user-attachments/files/17648229/synapse.log)
[element.log](https://github.com/user-attachments/files/17648232/element.log)

**Comment by t3chguy** [comment]
> Sorry, "true".

That is incorrect then, look at the docs again: https://github.com/element-hq/element-web/blob/develop/docs/e2ee.md#disabling-encryption
boolean != string

> [element.log](https://github.com/user-attachments/files/17648232/element.log)

This log is not helpful, Element runs entirely in the browser, the nginx log doesn't show anything from the app. See the issue template on how to submit logs:

![image](https://github.com/user-attachments/assets/4e007258-e1fd-4ff1-a76f-2eaa290a4f80)

**Comment by frenn** [comment]
@t3chguy 

> boolean != string

It's working. Thank you very much. The moment with nginx configuration must be specified in this instruction - https://github.com/element-hq/element-web/blob/develop/docs/e2ee.md#disabling-encryption. I think.

Thanks again.
