### ISSUE TITLE
rooms with pinned messages scroll down and back up when you click into the room

### ISSUE THREAD

**Issue by Aranjedeath** [element-hq/element-web#28390]
### Steps to reproduce

1: Be joined to a room like conduwuit Offtopic https://matrix.to/#/#conduwuit-offtopic:puppygock.gay which has 100 or more pinned messages
2: look at some other room in your element client
3: later, think to check offtopic and click over (left side panel w/e)
4: watch as the room loads in, the Pinned Messages takes visible time to load in and pushes the "room" messages down when it does so; later (seconds) element will reflow the messages back upward (maintaining the position of the read marker). 

#### What did you expect?
idk, maybe the pinned messages bar pops down when ready?

#### What happened instead?
It shifts the content (room messages) twice to load in the pinned messages bar

### Operating system

KDE NEON (Linux / Ubuntu 2404) KDE Plasma 6.2.2 w/Qt 6.8.0

### Application version

Element version: 1.11.84 Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### How did you install the app?

apt

### Homeserver

explodie.org running conduwuit

### Will you send logs?

Yes

**Comment by dbkr** [comment]
I can reproduce this fairly reliably if it helps (I get it constantly and it's a massive paper cut).

**Comment by florianduros** [comment]
@dbkr Can you share a record/video of the behaviour?

**Comment by dbkr** [comment]
I mad a new room for it but it didn't happen, but I reliably get it in one of our internal rooms. Looks like it's maybe doing an http request that takes longer in a larger(?) room and then scrolling after that. Recording: (nothing sensitive in the room at the time!)

![Nov-21-2024 09-42-43](https://github.com/user-attachments/assets/fc36c1d3-204c-45fa-a072-b6dfcc53fa89)
