### ISSUE TITLE
Change _Submit Debug Logs_ dialog not to require GitHub issue

### ISSUE THREAD

**Issue by grinapo** [element-hq/element-web#28394]
### Description
Right now Submit Debug Logs contain only this:

> Before submitting logs, you must [create a GitHub issue](https://github.com/vector-im/element-web/issues/new/choose) to describe your problem.

According to @richvdh the text should read something like that:

> If you want us to be able to respond or ask for more details you should [create a GitHub issue](https://github.com/vector-im/element-web/issues/new/choose) to describe your problem before submitting logs. Otherwise you can just send the logs without filling the "Issue" field, but try to provide as much details in the "Notes" as possible.

### Outcome

Inexperienced users cannot simply report UTD problems, for example, while they are really suggested to do so.

**Comment by t3chguy** [comment]
We don't look through rageshakes unless they are linked to a github issue we are triaging, so you can send them, but unless one of the devs asked you to, they won't be looked at so might as well be going into the abyss. Not changing this as it is as designed.

**Comment by grinapo** [comment]
It's been fun to be a messenger between you, guys. Keep on the good work!

**Comment by richvdh** [comment]
> According to @richvdh the text should read something like that:
> 
> > If you want us to be able to respond or ask for more details you should [create a GitHub issue](https://github.com/vector-im/element-web/issues/new/choose) to describe your problem before submitting logs. Otherwise you can just send the logs without filling the "Issue" field, but try to provide as much details in the "Notes" as possible.

This is not a direct quote, to be clear.

**Comment by richvdh** [comment]
> We don't look through rageshakes unless they are linked to a github issue we are triaging,

I don't agree. Plenty of rageshakes *do* get looked at; in particular they are an extremely valuable resource for investigating and triaging sources of UTD errors.

My experience is that people are deterred from submitting debug reports due to this text. I agree that it's time for this text to be reconsidered.

**Comment by richvdh** [comment]
no disagreement with that. Just hoping we can reword the dialog to be slightly less off-putting. Let's discuss in tomorrow's call.

**Comment by t3chguy** [comment]
The dialog as it stands was implemented to match designs, this isn't something we should be going behind their back on

**Comment by richvdh** [comment]
In consultation with @americanrefugee, we came up with:

> We recommend _creating a GitHub issue_ to ensure that your report is reviewed.

**Comment by richvdh** [comment]
> In consultation with @americanrefugee, we came up with:
> 
> > We recommend creating a GitHub issue to ensure that your report is reviewed.

I have made this change in Localazy. The change should land in the next release of Element-Web.
