### ISSUE TITLE
Error Processing Audio Message / DownloadError: Failed to fetch

### ISSUE THREAD

**Issue by altarofwisdom** [element-hq/element-web#28410]
### Steps to reproduce

1. Where are you starting? What can you see? Uploaded FLAC files to the app

<img width="703" alt="image" src="https://github.com/user-attachments/assets/f3934379-e058-4b35-aba1-61af08543580">

3. What do you click? Nothing
4. More steps…

#### What did you expect?
Uploaded files should be available
#### What happened instead?
App indicates most messages are not available and can't be downloaded. Some do appear randomly, but 99% of them are in error. They were properly uploaded and were availabkle until I quit the app.

### Operating system

macOS Sonoma

### Application version

1.11.81

### How did you install the app?

official webpage

### Homeserver

cutefunny.art

### Will you send logs?

Yes

**Comment by altarofwisdom** [comment]
Just updated to 1.11.84, same behavior

**Comment by t3chguy** [comment]
```
2024-11-08T08:44:50.187Z W Unable to decrypt audio message Failed to fetch
TypeError: Failed to fetch
```

This looks like an issue with your server's media repository

**Comment by altarofwisdom** [comment]
seem to happen as well on matrix.org server

**Comment by t3chguy** [comment]
I suggest reporting it to them at support@matrix.org then

**Comment by altarofwisdom** [comment]
If it's happening on several servers, I'm not sure who would be in charge of dealing with the issue ? matrix.org as they actually develop the server "template", right ? Sorry I'm a bit lost about who does what ;-)
