### ISSUE TITLE
Messages containing only >3 tildes are formatted as code blocks

### ISSUE THREAD

**Issue by lunasophia** [element-hq/element-web#28474]
### Steps to reproduce

When typing three or more `~` in a message on their own, Element Web (and other clients) formats the message as an empty, one-line code block. This also happens in Android Element X version 0.7.3 but does *not* occur in Element 1.6.22.

#### What did you expect?
I expect the message to be delivered as is 
#### What happened instead?
A single line, empty code block is sent

Raw message:
```
{
  "content": {
    "body": "~~~",
    "format": "org.matrix.custom.html",
    "formatted_body": "<pre><code></code></pre>\n",
    "m.mentions": {},
    "msgtype": "m.text"
  },
  "event_id": "-",
  "origin_server_ts": 1731677365055,
  "room_id": "-",
  "sender": "-",
  "type": "m.room.message",
  "unsigned": {}
}
``````
### Operating system

Fedora Linux

### Browser information

Firefox 132

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

No (not comfortable sending usernames)

**Comment by t3chguy** [comment]
This is the doing of commonmark, the chosen Markdown dialect

![image](https://github.com/user-attachments/assets/c0314748-6b8d-4240-82b3-f1635d5817a4)

Looks to be a documented alternative to backticks for code blocks.

https://spec.commonmark.org/0.31.2/#fenced-code-blocks

Closing as expected

Looks like Github's Markdown does the same thing FTR.

> Element 1.6.22.

Not sure what Element that is, Element Web/Desktop never had such a version string, but Element Web/Desktop is using the correct Commonmark spec and legacy Element clients may be using alternatives at their own peril.

**Comment by t3chguy** [comment]
Related https://github.com/element-hq/element-meta/issues/330 https://github.com/element-hq/element-meta/issues/81 https://github.com/element-hq/element-meta/issues/1630
