### ISSUE TITLE
element 1.11.86 update breaks older mac os x (pre- 11)

### ISSUE THREAD

**Issue by phliKtid** [element-hq/element-web#28492]
### Steps to reproduce

i am running element as a desktop version on mac os x (specifically, 10.15/catalina, the last 10.x version).  it has run element fine.  today i got an upgrade notice in element, which i've gotten and done before.  this time, after it installed the update, the new version wouldn't start and threw an error saying it required mac os x 11.x or higher.  i know 10.15 is eol (nov 2022, i think?), but it's the latest officially supported on the hardware i'm running this on.  it would be nice if it did checks and stopped before continuing to do the 1.11.86 update, as all previous element versions had worked.  i went back and re-installed 1.11.85 and it's working.  but it's trying to trick me into updating again by sending pop-up notices about an available update. : )  or you can just tell me my os is eol and i can get with the times or pound sand. : )

#### What did you expect?
element to either not offer the update, or when beginning the update do a check and stop

#### What happened instead?
it offered the update, it installed the update, then when starting, 1.11.86 it said it required mac os x 11.x or higher

### Operating system

mac os x

### Application version

element 1.11.86

### How did you install the app?

upgrade offered in desktop element 

### Will you send logs?

No

**Comment by t3chguy** [comment]
> it would be nice if it did checks and stopped before continuing to do the 1.11.86 update, as all previous element versions had worked.

That'd be a request for [electron-builder](https://www.electron.build/) (the packaging tool we use which handles the update mechanism)/[Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac) (the update mechanism itself). We just update the Electron version periodically to ensure latest accessibility and security changes and they (typically Chromium) drop support for older systems. 

Nothing in the Electron changelogs visible in https://github.com/element-hq/element-desktop/pull/1968 warned about any such breaking change but indeed their announcement does state this https://www.electronjs.org/blog/electron-33-0#breaking-changes

You can disable the auto-updater by creating a config.json file and setting the `update_base_url` to an empty string if you wish to keep running an old version, though keep in mind zero support or backported security updates will be available there.

As per https://github.com/element-hq/element-web#supported-environments the OS is unsupported and as such any issues specific to those environments are closed.

**Comment by phliKtid** [comment]
thanks for the info, t3chguy.  i appreciate it!
