### ISSUE TITLE
Typing two keys quickly in spotlight dialog closes the dialog

### ISSUE THREAD

**Issue by david-crespo** [element-hq/element-web#28493]
### Steps to reproduce

After upgrading to 1.11.86:

1. Press `cmd-k` to open room quick search
2. Type any two keys quickly

I was able to confirm that downgrading to 1.11.85 fixes the issue.

#### What did you expect?

I expect the search dialog to stay open and the input field shows the two keys I pressed.

#### What happened instead?

The dialog closes, and the message input is focused instead. This means that if I type, for example, three keys and press enter, the first two go into the room quick search and the third + enter go into the message box. I have been sending a lot of one-letter messages today.

https://github.com/user-attachments/assets/7234a53c-ef72-4737-89f8-f223599ebdad

### Operating system

macOS

### Application version

1.11.86

### How did you install the app?

https://element.io/app-for-productivity, but that was a long time ago. This was just an in-app upgrade.

### Homeserver

https://matrix.oxide.computer

### Will you send logs?

Yes

**Comment by david-crespo** [comment]
I'm only a simple country web developer, but this commit from last week changes the node that gets focused on various events in the spotlight dialog.

https://github.com/element-hq/element-web/commit/86c6ba9dd7d541a389df503ddf91377dbeb54df2#diff-4f723693a224616ad86bb469ab940e993ed1fc02a91fe002e95b2aad28bd0f6f

**Comment by t3chguy** [comment]
> I'm only a simple country web developer, but https://github.com/element-hq/element-web/pull/28452 from last week changes the node that gets focused on various events in the spotlight dialog.

This PR is not included in 1.11.86 as it was merged after the RC.

@MidhunSureshR you were handling fixing this and believed it to be due to React 18 double-rendering which only affects development builds, this issue claims otherwise, can you confirm?

**Comment by MidhunSureshR** [comment]
I can repro on 1.11.86 but not on 1.11.85.

**Comment by MidhunSureshR** [comment]
From a git bisect, this is from https://github.com/element-hq/element-web/pull/28336

**Comment by Ajmalajjuca** [comment]
move to 1.11.85.

**Comment by t3chguy** [comment]
This is already fixed on develop and will be in the next release

**Comment by andrew-demb** [comment]
@t3chguy can you please tell us, approximately when the next release will be published?

**Comment by dreirund** [comment]
I see the same.
