### ISSUE TITLE
Session logged out when not requested

### ISSUE THREAD

**Issue by andriusign** [element-hq/element-web#28490]
### Steps to reproduce

1. Where are you starting? What can you see? Open Element Desktop. 
2. What do you click? Click Element shortcut icon as usual or run from command line.
3. More steps…

#### What did you expect?
Previous logged in session to be restored
#### What happened instead?
No old session, currently logged out

![image](https://github.com/user-attachments/assets/b22bcc4d-b598-4c70-8505-2c4a40bd4c52)

### Operating system

Linux Mint 21.3 Cinnamon 6.0.4, kernel 6.8.0-45-generic

### Application version

Element 1.11.85

### How did you install the app?

Via Software Center (flatpak version)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by andriusign** [comment]
@t3chguy is anyone at least reading the issues that have been posted? There has been no reaction to the recent issue https://github.com/flathub/im.riot.Riot/issues/490
Are you the same owners of that repo?

**Comment by t3chguy** [comment]
We don't own that repo, like we don't own the package. It is maintained by the community.
