### ISSUE TITLE
Georgian Language - State Fire Service of Poland

### ISSUE THREAD

**Issue by zarooba01** [element-hq/element-web#28518]
We are from the National Headquarters of the State Fire Service of Poland and we're developing a communication system based on the Element platform in Georgia. This will be an important system in the field of the country's fire safety.
We are missing Georgian translations for web and Android versions. We have already translated all expressions in https://translate.element.io/projects/element-android/element-app/.
Is this sufficient for the translation to work, or is there anything else we need to do?

**Comment by t3chguy** [comment]
This repo is unrelated to Element Android, you should open an issue in https://github.com/element-hq/element-android
