### ISSUE TITLE
Incorrect state shown after rejoining room

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#28536]
### Steps to reproduce

1. User 1 creates new chat, invites User 2
2. User 2 accepts invite
3. User 1 promotes User 2 to moderator
4. User 1 leaves chat
5. User 2 re-invites User 1
6. User 1 rejoins

![image](https://github.com/user-attachments/assets/25f7d897-f4f0-4666-8306-25a86a849ed4)

#### What did you expect?

User 1 sees User 2 as moderator

#### What happened instead?

User 1 sees User 2 as ordinary user

![image](https://github.com/user-attachments/assets/647a9430-628f-4bf4-b79c-2705e51518c0)

(Reloading the page fixes the issue)

### Application version

Element version: 1.11.86-dev Crypto version: Rust SDK 0.7.2 (fceea46f), Vodozemac 0.8.1

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Sounds like a duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/4528?

**Comment by t3chguy** [comment]
We don't tend to double-track issues. We tend to close in favour of upstream bugs

**Comment by richvdh** [comment]
AFAICT element-web still doesn't support stable MSC4222, and hence this still isn't fixed

**Comment by richvdh** [comment]
(it doesn't set the stable `use_state_after` query param which is necessary to opt into state_after.

cc @dbkr as the person that did the implementation)
