### ISSUE TITLE
room search popup (Ctrl+K) closes if I type too fast

### ISSUE THREAD

**Issue by kylrth** [element-hq/element-web#28657]
### Steps to reproduce

1. press Ctrl+K to show the room search popup
2. type very fast

#### What did you expect?

The characters appear at the top of the search bar and filter the displayed rooms

#### What happened instead?

The popup closes and some of the characters I typed appear instead in the compose box in the current room.

### Operating system

Manjaro

### Application version

Element version: 1.11.86 Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### How did you install the app?

Arch repo

### Homeserver

Synapse v1.119.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Its fixed in 1.11.87
