### ISSUE TITLE
Update of Element Makes Session Incompatible

### ISSUE THREAD

**Issue by TheFibonacciEffect** [element-hq/element-web#28682]
### Steps to reproduce

1. Install the newest Element release through pacman
2. Open Element
3. Be greeted by a message that the session was unable to be restored

#### What did you expect?
That Element just opens and I can write a message to my collegues
#### What happened instead?
the session was unable to be restored

### Operating system

Arch Linux

### Application version

 1.11.87-1

### How did you install the app?

pacman

### Homeserver

ethz.ch

### Will you send logs?

Yes

**Comment by TheFibonacciEffect** [comment]
It seems to be easy to just log in again and all the messages are there again. So its fine, I guess.

**Comment by TheFibonacciEffect** [comment]
Manually exporting the key file from my phone and importing into Element works like a charm :+1:

**Comment by TheFibonacciEffect** [comment]
I guess the only thing is that I now have 38 unread messages in the top left, that are not actually unread. I couldnt find a way to mark all as read, but that will be solvable eventually I guess.
![image](https://github.com/user-attachments/assets/891a7028-3ca2-4dcc-90b7-1b56cfe44e04)

**Comment by pm4rcin** [comment]
@TheFibonacciEffect do you use `gnome-keyring` or similar software with Element?

**Comment by TheFibonacciEffect** [comment]
@pm4rcin Yes, Im using kwallet from KDE

**Comment by pm4rcin** [comment]
Then it looks like you have the same problem as me. Would you close the issue and write your findings in my issue https://github.com/element-hq/element-web/issues/28684?

**Comment by TheFibonacciEffect** [comment]
The issue is part of issue https://github.com/element-hq/element-web/issues/28684
