### ISSUE TITLE
Sign in option is missing from Japanese translation of the register page

### ISSUE THREAD

**Issue by TellowKrinkle** [element-hq/element-web#28695]
### Steps to reproduce

1. Go to https://app.element.io/#/register
2. Set the language to Japanese
3. Attempt to switch from registering an account to signing in
4. Set the language to English
5. Repeat (3)

#### What did you expect?
Both Japanese and English have a link(-ish button) to switch from registration to sign in

#### What happened instead?
In Japanese, there's the text サインイン (Sign In) near the bottom, but it is not a link and clicking it does nothing.
<img width="1536" alt="image" src="https://github.com/user-attachments/assets/c3ce15b5-a79c-40fe-ad86-f8f9e73b366e">
In English, there's the text "Already have an account? <ins>Sign in here</ins>".  It's still not a link (the browser shows nothing when you hover over it and you can't e.g. right click and copy address), but clicking the underlined portion goes to https://app.element.io/#/login.
<img width="1536" alt="image" src="https://github.com/user-attachments/assets/c05fa3a4-3b60-4252-b6d8-f456eca76130">

### Operating system

macOS 14

### Browser information

Safari 18.1.1

### URL for webapp

app.element.io

### Application version

Element version: 1.11.87, Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### Homeserver

N/A

### Will you send logs?

No

**Comment by t3chguy** [comment]
The translations are community contributed. See https://github.com/element-hq/element-web/blob/develop/docs%2Ftranslating.md for where to get help

**Comment by TellowKrinkle** [comment]
It looks like a large number of languages are missing the link tags.  Do you know what might have caused this? 
<img width="1536" alt="image" src="https://github.com/user-attachments/assets/f05f9eea-49ff-49b4-a6a0-7b78832c05b1">

**Comment by t3chguy** [comment]
You'd have to ask the translations room.
