### ISSUE TITLE
Why QR Code not show?

### ISSUE THREAD

**Issue by GoddPerGugtern** [element-hq/element-web#28746]
### Steps to reproduce

When I click the profile picture,and click link new device

#### What did you expect?
I got one QR Code 
#### What happened instead?
![image](https://github.com/user-attachments/assets/03b27544-f0ac-4813-914a-3a94d505bf24)
What's the account provider mean?

### URL for webapp

develop.element.io

### Homeserver

Synapse 1.21.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Are you running https://github.com/element-hq/matrix-authentication-service? Synapse doesn't natively support Device Linking and needs MAS for it.

**Comment by spaetz** [comment]
Your homeserver needs 1) matrix-authentication-service running and your homeserver needs
```
experimental_features:
  #QR code login
  msc4108_enabled: true
```

**Comment by t3chguy** [comment]
Closing due to no response

**Comment by SPiRiT369** [comment]
(Just thinking out loud...) What's the point of adding "Link new device" option to the menu if the server does not support that feature? 🤕
