### ISSUE TITLE
Visual glitches in room list

### ISSUE THREAD

**Issue by babolivier** [element-hq/element-web#28744]
### Steps to reproduce

1. Open Element Desktop

#### What did you expect?

The left side panel shows a clean list of rooms, optionally with a preview of the latest message.

#### What happened instead?

Some entries in the room appear glitched, with the preview for one room appearing on top of the other:

![image](https://github.com/user-attachments/assets/bbb23439-5784-4ea1-955c-427ed1a3254b)

This happens both with message preview on and off, and although it doesn't happen on every room simultaneously, it seems to happen to any room at random.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2024121601, Crypto version: Rust SDK 0.7.2 (96c405f), Vodozemac 0.8.1

### How did you install the app?

Archlinux User Repository (AUR): https://aur.archlinux.org/packages/element-desktop-nightly-bin

### Homeserver

abolivier.bzh

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
@babolivier unless you can repro this on one of the packages we ship you'd need to seek support from the maintainer of the community maintained package. Sorry
