### ISSUE TITLE
Element Desktop is stuck with loading spinner after upgrade

### ISSUE THREAD

**Issue by cdauth** [element-hq/element-web#28798]
### Steps to reproduce

I have recently upgraded to Element Desktop 1.11.89. Before I was running a version that was a few months old, but I don’t know which one exactly.

Since the upgrade, when I start Element, I am stuck with a loading spinner and a “Logout” link underneath. Trying to exit Element by pressing Ctrl+Q shows a confirmation dialog, but when I click “Close Element”, nothing happens. Right-clicking the icon the task bar and pressing “Quit” there does close the app.

I cannot provide any logs, since it seems like Element Desktop is hiding the logs from the user. When I run the app from a terminal, it forks and then quits without any useful output. I was not able to find any documentation how to access the log.

I can access my Matrix account through Element Web, so I assume that the problem is not on the server side.

### Outcome

Element Desktop is stuck with the loading spinner.

### Operating system

Arch Linux

### Application version

1.11.89

### How did you install the app?

Pacman

### Homeserver

rankenste.in (running the latest matrixdotorg/synapse docker image)

### Will you send logs?

No

**Comment by t3chguy** [comment]
The arch package isn't maintained by us. You'd need to seek help from it's maintainer. Our Linux packages don't fork or hide logs

**Comment by cdauth** [comment]
Ah, looks like I made a mistake. Probably I already had element-desktop running when I started it. When I run the command and the app is not running yet, it does not fork.

This is the log output, although I doubt this is helpful:
```
/home/cdauth/.config/Element exists: yes
/home/cdauth/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
```

**Comment by eMPee584** [comment]
ah wow, thanks to this I tried downgrading to element-desktop 1.11.66 from 1.11.89 and it fixed the spinner issue for me on debian unstable 😎
