### ISSUE TITLE
Replies in 1.11.88 and 1.11.89 are "invisible" in Android client

### ISSUE THREAD

**Issue by baqui63** [element-hq/element-web#28830]
### Steps to reproduce

After updating Windows Desktop client to 1.11.88, and then to 1.11.89, people using Android client (1.6.24 and possibly others) cannot see the text of the reply; they do see the quoted message. The reply text does show in the notification for the message and long touching it shows the reply text. This does not happen with posts, only replies. There are at least three people, including myself, having the problem on our Android clients.

This also happens with replies made with the current web client.

Using 1.11.87 to edit an "invisible" reply fixes it, allowing the Android client to display the text,

To reproduce this, use Desktop client 1.11.88 or 1.11.89 or the web client to reply to a message. Then view the reply in the Android client. Only the quoted message is displayed; the text of the reply is invisible.

I can send logs if desired.

### Outcome

Expected: Text of replies to messages to be visible on all clients.

Instead, Android clients do not display the text of the reply.

### Operating system

Windows 11 Pro 24H2, Android 15 (possibly others)

### Application version

Element 1.11.88 & 1.11.89, Android 1.6.24 (possibly others)

### How did you install the app?

Installed updates using Element itself

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is a bug in the android client not adhering to the matrix spec, i suggest opening an issue there as I am unable to transfer

**Comment by baqui63** [comment]
Thanks, will do.

--
yan juras
(646)642-4813
