### ISSUE TITLE
modernizr fails on MobileSafari in Private Mode

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#2904]
We should add 'Don't use me on iOS in private mode' in the modernizr warning text to avoid confusing users

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/14962

**Comment by Johennes** [comment]
Copy in question: https://github.com/vector-im/element-web/blob/develop/src/async-components/structures/CompatibilityView.tsx#L122

**Comment by t3chguy** [comment]
This got redesigned to point at the mobile apps
