### ISSUE TITLE
scrolling up when mouse is near bottom of timeline suddenly stops due to notification area unhiding

### ISSUE THREAD

**Issue by uhoreg** [element-hq/element-web#3135]
What happens is:

1. mouse is near the bottom of timeline
2. I use the scrollwheel to scroll the timeline up
3. notification area pops up with down-arrow to jump to end of messages
4. mouse is now on top of the notification area
5. scrollwheel no longer scrolls the timeline up

**Comment by ara4n** [comment]
The only way I can think of solving this is if we make RoomStatusBar `position: absolute` and `pointer-events: none` and have the scroll-wheeling 'shine through' to the main scroller behind.  This is a pretty major tweak, but probably a desirable one.

**Comment by t3chguy** [comment]
Closing due to no further reports in many years
