### ISSUE TITLE
Riot shows 1:1 conversations I left in the right profile menu

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#3192]
[![bounty](https://api.bountysource.com/badge/issue?issue_id=41852234)](https://www.bountysource.com/issues/41852234-riot-shows-1-1-conversations-i-left-in-the-right-profile-menu)

### Description

When I click on someone's avatar to bring up their profile, I can see the 1:1 conversations I've opened with them. However, if I leave that 1:1 conversation, I wouldn't expect it to show up - but it does.

### Steps to reproduce

- Have a friend/second account to test with
- Open a 1:1 conversation with that friend
- (unsure if required) Have the friend accept the invite
- Leave the room
- Open your friends profile, note that the 1:1 is still shown

I would have expected the 1:1 to disappear from the list. Particularly if both parties have left because the room is completely inaccessible (which is the case in the screenshot below, despite one end thinking there's someone in it).

![image](https://cloud.githubusercontent.com/assets/1190097/22791690/7cba077a-eea7-11e6-86cf-3065d7dbfd1d.png)

Log: not sent (sourced from a Riot install without bug reporting)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 55
- **OS**: Windows
- **URL**: Riot 0.9.7 install (web). CAn be reproduced on riot.im/develop

**Comment by turt2live** [comment]
A more interesting case of the original issue: 
![image](https://cloud.githubusercontent.com/assets/1190097/23238015/34789276-f91d-11e6-8257-10fee654674d.png)

What happened long ago was I migrated from my matrix.org account (`@turt2live:matrix.org`, pictured above) to my own homeserver. In the process of doing that, I invited my new account to all the rooms I was in and had my matrix.org account leave. The "Direct Chat" above was manually re-labelled as 1:1 by me so Riot would ignore the fact that Giphy is in the room (and that someone joined/left). 

Apparently Riot still considers the 1:1 chat with someone else as a 1:1 chat with my alternate account, despite that alternate account having left.

**Comment by dbkr** [comment]
Not sure what is actually best to do here but I seem to recall this was intentional as it makes about as much sense to invite the person back into a room they previously left as to invite them to a new one (or rejoin the room yourself).

**Comment by turt2live** [comment]
@dbkr That feels too awkward in my opinion. If a user cared enough to re-add a user to the room then they'd likely already know which room they wanted to add them back to and can find it easily. As for leaving a room, if I left I don't want to see it again (unless I actively go hunting for the room, but at that point I'm not expecting to find it in MemberInfo).

**Comment by t3chguy** [comment]
it might make sense for keeping track of room history, if you want to re-read things
how about putting them the bottom of the list and marking them visually somehow

**Comment by turt2live** [comment]
I'd argue that if I left a room then I still don't care about history either, otherwise I would have left it. Putting the rooms behind a "Show more" button would probably be a happy medium.

**Comment by turt2live** [comment]
Updated the OP to advertise the bounty :)

**Comment by dbkr** [comment]
Sorry, I completely misread last time I looked at this and read it as *them* leaving. This is surely correct since we can't assume that you'd be able to just re-join a 1:1 room you left - in general, you won't be able to. So yes, you're completely right.

**Comment by t3chguy** [comment]
@dbkr so should I change my PR to only omit the ones we are no longer in, rather than ones which *either party* has left?

**Comment by dbkr** [comment]
I was actually just going to comment and say, actually, it does seem better to open a new chat with someone if they left, so let's just merge your PR as-is. Do you fancy fixing the conflict and I'll hit the button?

**Comment by t3chguy** [comment]
Sure

**Comment by t3chguy** [comment]
Though from this comes a new issue, Reuse Existing Room modal should use the same algo, right @dbkr

**Comment by t3chguy** [comment]
further question, if we don't care about 1:1s that we no longer can use to communicate with a given person, should we clean them out of `account_data`?
