### ISSUE TITLE
joining a new IRC portal room from RoomDirectory has no name/avatar/etc

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#3352]
it's a very ugly experience - you type #foo and select a network, hit join, and the next thing you see is the ugly preview screen for 'You are trying to join a room' but it doesn't even tell you the alias of the room you are trying to join...

**Comment by ara4n** [comment]
This is very obvious on indieweb as described at https://github.com/vector-im/riot-web/issues/3335

**Comment by t3chguy** [comment]
Closing due to no further reports in many years
