### ISSUE TITLE
if /register returns 400 riot silently fails

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#4823]

**Comment by lampholder** [comment]
I've P1'ed this, but I don't know how commonly it occurs. We could bump it down if it only occurs in very rare/specific circumstances.

**Comment by lampholder** [comment]
@ara4n - did you discover this when running against Dendrite? If so I'd be tempted to drop this to P2.

**Comment by lukebarnard1** [comment]
@lampholder I remember @ara4n mentioning in the Monday sync that it was whilst running against Dendrite so it's probably not p1.

I hope Dendrite will closely mirror the error statuses and codes given by Synapse 😇 If not, supporting two sets of outcomes is going to make error handling in Riot a bit of a nightmare.

**Comment by t3chguy** [comment]
![image](https://github.com/user-attachments/assets/ceed077f-0824-425d-8094-11f506ba057b)

This got fixed at some point
