### ISSUE TITLE
Make keyshare requests not a modal dialog and actually visualise what keys are being requested

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#5533]
Split out & extended from #4522:

 * Rather than a modal dialog, which is super-intrusive, display some kind of non-modal alert of the request for keys.
   * This could be something in the Invites section of the RoomList, saying "A new device is requesting your keys".
   * This could show you a summary of the sessions being requested - i.e. how many sessions, for which rooms; we could even have a server API to summarise (e.g. "1256 messages sent by Bob between 12:00 and 13:00")
   * It guides the user into verifying the requester, and then shares the keys (and does so transparently from then on).

See bottom https://docs.google.com/document/d/12r21OrXYEvzKclKCUWX2a-2ckU6Se0IJHoZaLicVxFc/edit#heading=h.1t5ui387zzvs for some UX experiments.

See https://docs.google.com/document/d/1m4gQkcnJkxNuBmb5NoFCIadIY-DyqqNAS3lloE73BlQ/edit# for Rich's draft of keyshare messages themselves.

**Comment by t3chguy** [comment]
keyshare requests are gone
