### ISSUE TITLE
Marking room meta notifications as read does not work

### ISSUE THREAD

**Issue by vsund** [element-hq/element-web#5756]
### Description

I'm in a bridged IRC channel with low traffic but much user fluctuation (many joins/leaves without real messages in between). When I try to mark these "meta messages" (joins/leaves) as read, the notification at the top ("unread messages, mark as read?") appears again immediately.

### Steps to reproduce

* Join a room with many meta messages (typically a bridged IRC channel with many joins/leaves)
* Wait some time until the screen gets filled up with these messages (they collapse if there are enough)
* Click "mark as read"

The click on "mark as read" should now mark all these meta messages as read but it appears again immediately. I'm not sure whether this is related to the collapsed view of these messages, notifications for these meta messages or to something entirely different.

To get it marked as read, I need to expand them all and then mark them as read.

I'm also not sure whether it's necessary to see these joins/leaves as important to notify the user. Furthermore the room is displayed bold (as if there were unread messages) again and again.

Also not sure whether https://github.com/vector-im/riot-web/issues/2629 is related.

### Version information

I'm using the desktop client in version 0.13.2 on Arch Linux.

**Comment by turt2live** [comment]
"mark as read" was a button from several versions ago. Are you sure you're on 0.13.2?

**Comment by vsund** [comment]
@turt2live Yup, sorry for the confusion, wrote this up from mind. It's a "Jump to first unread message." label with an X on the right side (which should have the same effect I guess).

**Comment by turt2live** [comment]
Ah, alright then. It sounds like a side effect of https://github.com/vector-im/riot-web/issues/2629
