### ISSUE TITLE
Widgets should have equal width, even if the widget title is long.

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#5812]
### Description

![image](https://user-images.githubusercontent.com/1190097/33849275-63561fd8-de6d-11e7-821d-61fdea081be4.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by uhoreg** [comment]
From the screenshot, it looks like they need to have equal height (including the title bar) too

**Comment by t3chguy** [comment]
This is no longer the case, widgets now have individual resize which can be saved locally or into room state.


https://github.com/user-attachments/assets/07dda189-d37d-45a8-bcf9-f6f6d91b7050
