### ISSUE TITLE
Chinese Language lacks 2 types which causes confusion

### ISSUE THREAD

**Issue by MTRNord** [element-hq/element-web#5913]
Reported in: https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$151499105552FQZfM:anmige.com
The Chinese language seems to have 4 language Codes. We support 2 of them currently but lack the other 2 which causes some confusion.

Language Codes are:
- zh (unsupported)
- zh-CN (unsupported)
- zh_Hans (supported)
- zh_Hant (supported)

According to [this](https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$151499158255ISeWs:anmige.com) we might be able to copy `zh_Hans` to `zh-CN`

I also asked about this in the Translation Room: https://matrix.to/#/!OYyXUbcTKVsDBUniNn:matrix.eclabs.de/$15149918452254guDWz:matrix.ffslfl.net   

Any Ideas how to do it are apreciated. Copying is one way but we would have to do it all the time or special case it.

**Comment by t3chguy** [comment]
I wouldn't be surprised if this applies to more "alias" codes, so maybe a map of aliases would be most maintainable

**Comment by MTRNord** [comment]
Also worth noting zh-CN isn't listed by Weblate.

**Comment by qzicxjmozbxameuhnk** [comment]
I realized that the final solution should be to modify the language selection related code in the matrix-react-sdk project.

As a simple solution to the problem in the element-web project deployment process, just add a line of code. Although this will cause a seemingly duplicate option in the language list, of course you can also solve it by replacing zh-hans, but here I am Choose not to interfere with the original code.

After
`https://github.com/vector-im/element-web/blob/77476451bd5558129579bfcdc39cd09f7c5d515c/scripts/copy-res.js#L200`
You just add a line:
`languages['zh-cn'] = {'fileName': langFileMap['zh_Hans'], 'label': "简体中文/zh-CN"};`
This should solve the problem.

**Comment by qzicxjmozbxameuhnk** [comment]
For users who download the built version directly from [releases](https://github.com/vector-im/element-web/releases/tag/v1.7.33), you only need to modify the ‘element/i18n/languages.7aef263.json’ file and add a mapping in it, like this:
`    "zh-cn": {
        "fileName": "zh_Hans.8dbef42.json",
        "label": "简体中文/zn-CN"
    },`

**Reminder:** Modifying the ‘languages.json’ file is invalid, you must need to modify the file like ‘languages.7aef263.json’. After the modification, you need to [disable cache] and [clear local storage] in the browser, and you can see the effect after refreshing.

**Comment by t3chguy** [comment]
Fixed by move to Localazy

![image](https://github.com/user-attachments/assets/cc001729-6221-4b07-8816-d4ed6370454e)
