### ISSUE TITLE
Date separators don't update unless the timeline changes

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#6049]
### Description

In a room with just myself I had posted something yesterday and today the label was still stuck at "Today". When I sent another message the separator happily changed to "Yesterday".

It's a bit confusing at first when the date separator doesn't change with the clock.

### Steps to reproduce

- In a room by yourself, send a message at 23:59 such that the "Today" header is visible
- Wait until the clock strikes 00:00 (or later)
- Note that the header is still "Today" (send another message to see it change)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Believed to be fixed, no reproduction in years
