### ISSUE TITLE
Videos greater than 25MB uploaded as m.file rather than m.video (clone of 1752 from riot-ios)

### ISSUE THREAD

**Issue by repli-a** [element-hq/element-web#6426]
Copy of [1752](https://github.com/vector-im/riot-ios/issues/1752) from riot-ios.

On all versions of the Riot app (web, Android, iOS), any video file over 25MB is uploaded as an m.file rather than m.video, and is not presented in an embedded HTML5 player as a result. Would be great to be able to specify where this cutoff is in case we want to use this for sending larger screeners.

It looks like @manuroe already has this in the pipeline on the iOS side, per @turt2live posting here to make sure there's visibility on the desktop app side as well.

Thanks!

**Comment by bisongde** [comment]
Any updates on this bug?

**Comment by t3chguy** [comment]
Did some investigation
cannot repro on Firefox.
Can easily repro on Chrome/Electron

![image](https://user-images.githubusercontent.com/2403652/40867603-84c93bb0-65fd-11e8-84f4-b01bf76a4827.png)

**Comment by bisongde** [comment]
Thanks Michael. Will try to get this across to the Chrome devs and see if there's anything they can do to rectify.

**Comment by t3chguy** [comment]
code section where error is visible; https://github.com/matrix-org/matrix-react-sdk/blob/a1581ad2dc4cbb196867a1fd2c66f60e04d2bef6/src/ContentMessages.js#L165-L167

**Comment by bisongde** [comment]
Tested this in Firefox on client hosted at riot.im today and was able to reproduce the issue. Does not seem to be limited to Chrome. Don't see the same ffmpeg error in the console though.

**Comment by bisongde** [comment]
I also confirmed that even on Firefox 60.0.1 (64-bit), in a non-E2E room, this problem occurs.

**Comment by t3chguy** [comment]
The code path doesn't log to console, you need to breakpoint on it

**Comment by bisongde** [comment]
I have a breakpoint on lines 165 through 167 in ContentMessages.js as you indicated above, but I don't receive an error in the console on upload completion even when the upload is incorrectly categorized as m.file.

**Comment by Half-Shot** [comment]
Starting to wonder if this might be related to https://github.com/vector-im/riot-web/issues/4264, except it doesn't quite go as far as crashing the app. Chrome/Electron doesn't seem to like large files sent as file objects.

**Comment by turt2live** [comment]
I think this one is much more closely related to #7069 given I had a 4.77kb image end up being an m.file.

**Comment by t3chguy** [comment]
This got fixed
