### ISSUE TITLE
Clicking 'jump to first unread' froze Riot and caused it to consume 100% cpu

### ISSUE THREAD

**Issue by lampholder** [element-hq/element-web#6548]
From a rageshake.

**Comment by lampholder** [comment]
P2 just 'cause we haven't seen lots of reports of this.

**Comment by ara4n** [comment]
@uhoreg did you ever see this one again? i'm wondering if it was on an underpowered device that spent ages going through processing all the members from the /context request.

**Comment by uhoreg** [comment]
It was a somewhat-underpowered device, but not overly underpowered (~6 year old laptop)

**Comment by t3chguy** [comment]
Closing this as presumed fixed in the many years due to lack of further reported cases
