### ISSUE TITLE
Typing notification for ignored users

### ISSUE THREAD

**Issue by aidalgol** [element-hq/element-web#6552]
### Description

Typing notifications for a ignored users still show up in rooms.

### Steps to reproduce

I have had trouble reproducing this consistently, but here are the steps to _try_ reproducing.

Users Alice and Bob will need a communication channel outside of Matrix to reproduce this.

1. Alice and Bob join a room
1. Alice sets Riot to ignore Bob
1. Bob starts typing in the room text input
1. Alice observes the typing notification in that room "Bob is typing..."

Log: sent

(Could not get screenshot.)

### Version information

- **Platform**: desktop

- **OS**: Windows, Debian
- **Version**: 0.14.1

**Comment by t3chguy** [comment]
These should be filtered out by the server as per the spec: https://spec.matrix.org/v1.12/client-server-api/#server-behaviour-16
