### ISSUE TITLE
riot spins forever when joining a room if /directory fails

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#6554]
when you join a room by alias, riot first does a /directory request. if that fails with a 50x, you don't get an error message - instead you just see a spinner of doom.

This contributes to a general 'joining rooms is flaky' vibe

**Comment by richvdh** [comment]
(and for some reason it took 22 seconds between my server sending the request:

```
2018-04-18 13:17:03,801 - synapse.http.outbound - 165 - INFO - GET-9- {GET-O-2} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/query/directory?room_alias=%23matrix%3Amatrix.org
```

and matrix.org *beginning* to process it:
```
2018-04-18 12:17:26,111 - synapse.access.http.8080 - 59 - INFO - GET-4090864 - 2a01:7e00:e001:900::1 - 8080 - Received request: GET /_matrix/federation/v1/query/directory?room_alias=%23matrix%3Amatrix.org
```

given that the federation request gets timed out after 10 seconds, it's not that surprising that the join failed)

**Comment by bwindels** [comment]
Don't think so, the one I fixed was the room re-rendering after join before it could get the self-user from the room.

**Comment by turt2live** [comment]
@richvdh are you still seeing this? I cheated and made the GET in `synapse/rest/client/v1/directory.py` return a 500 all the time and was met with "#myroom:example.org is not accessible at this time". This was the case for typing `/join #myroom:example.org` and clicking a link to #myroom:example.org

**Comment by richvdh** [comment]
well, it's not something I encounter regularly. I'm entirely prepared to believe it's gone away, if you can't reproduce it.
