### ISSUE TITLE
Textfield don't gain focus on each click

### ISSUE THREAD

**Issue by Noisefever** [element-hq/element-web#6576]
### Description

Mouseclick doesn't make the textfield active when I click in the second line.

### Steps to reproduce

just click on the second line of the textfield and type ;)
nothing happens. I have a second line because I don't use a fullscreen window. But even in the fullscreen window the textfield click area is too small for what I would expect!

![2018-04-23 08_00_29-riot](https://user-images.githubusercontent.com/30522533/39109823-e211abe8-46ce-11e8-9c05-1c4f2d208ee2.png)

The screenshot shows that I can even mark the text and can't type!

### Version information

- **Platform**: web desktop?
- **OS**: Windows 10
- **Version**: 0.14.1

**Comment by lukebarnard1** [comment]
Related:
 - Clickable area for the composer: https://github.com/vector-im/riot-web/issues/4906
 - General problems with window dimensions: https://github.com/vector-im/riot-web/issues/6488
