### ISSUE TITLE
Please implement preview of image urls in the client

### ISSUE THREAD

**Issue by lastmetroid** [element-hq/element-web#6664]
Posting image urls wont create a preview in the chat, like Skype does. Please implement.

**Comment by t3chguy** [comment]
Yes it does, if you have url previews enabled.

**Comment by makedir** [comment]
No it does not. I have url preview enabled (enable inline URL previews by default), it does do nothing. I tried with small sized image urls too. The url is just rendered, not the image. Posting urls does nothing, no preview render at all.

**Comment by makedir** [comment]
https://i.imgur.com/FjQwiZu.png

it just shows the url, not any preview of the image.

**Comment by turt2live** [comment]
That looks like URL previews are not enabled on the server.

**Comment by makedir** [comment]
Erm. So I have to enable it on the server? I have actually trued it but the server crashes now when I want to start it. I changed this:

url_preview_enabled: True
url_preview_ip_range_blacklist:
- '127.0.0.0/8'
- '10.0.0.0/8'
- '172.16.0.0/12'
- '192.168.0.0/16'

**Comment by turt2live** [comment]
The 'crash' is likely it telling you you need to install another package so that the URL previews work.

**Comment by t3chguy** [comment]
> So I have to enable it on the server?

Yup, riot doesn't fetch previews itself as that would be a security nightmare as it'd expose your ip address to anyone in the room

**Comment by makedir** [comment]
So what options do I have to make it quick and fast work? Is there a simple apt-get package for that? Is there an anonymizer for it maybe too or proxy to use for the fetch?
