### ISSUE TITLE
Clicking urls is rather hard (on mobile clients)

### ISSUE THREAD

**Issue by lastmetroid** [element-hq/element-web#6665]
If you post a single line url, it is rather hard to click on it. The click listener seems to be just on the pixels of the url text. Please change it so the entire row is clickable and opens the url.

**Comment by turt2live** [comment]
This kind of issue is best opened on https://github.com/vector-im/riot-android or https://github.com/vector-im/riot-ios (or both), I believe. If it's still hard to click on the web/desktop client, then this is the right place.

**Comment by t3chguy** [comment]
Also how would you handle multiple urls in the same line in your scenario?

**Comment by t3chguy** [comment]
Riot already has optional previews which make things easier to click, in labs on android at least iirc
