### ISSUE TITLE
Logout due to invalid access token on startup causes "failed to start" dialog to appear

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#6753]
I think, anyway. Noting before I forget about it.

to repro: sign in, close tab, sign in from another browser, delete device of first signin, go back to first one, you should just get the, "you've signed out" dialog, not the "failed to restore session" one.

**Comment by richvdh** [comment]
Given this hasn't been updated in 6 years, let's assume it was either never a thing, or has changed.
