### ISSUE TITLE
missing avatar on user after joining HQ

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#6943]

**Comment by ara4n** [comment]
<img width="422" alt="screen shot 2018-06-26 at 10 46 48" src="https://user-images.githubusercontent.com/1294269/41903636-56a98642-792e-11e8-9716-9cdfec68c69b.png">

Fixed after switching room & back again.

**Comment by lampholder** [comment]
This feels like it has a lot in common with https://github.com/vector-im/riot-web/issues/6944

**Comment by ara4n** [comment]
@bwindels in your LL journeys did you see anything which might explain this?

**Comment by bwindels** [comment]
Given that is was filed before we started on LL, seems unlikely though ...
Looking at #6944 as well, which mentions federation triggering the issue, could this be related to #7332 ?

**Comment by t3chguy** [comment]
Closing this as presumed fixed in the many years due to lack of further reported cases
