### ISSUE TITLE
Desktop notifications not appearing even when enabled in riot and chrome (Ubuntu)

### ISSUE THREAD

**Issue by lampholder** [element-hq/element-web#7317]
On Tom's computer.

**Comment by lampholder** [comment]
- Tested desktop notifications using https://www.bennish.net/web-notifications.html - they work fine
- My notif settings look like:
  ![image](https://user-images.githubusercontent.com/1922197/45762489-5e334e80-bc26-11e8-907f-9ad67b20a33e.png)
- And my chrome is definitely configured to allow desktop notifs for Riot:
  ![image](https://user-images.githubusercontent.com/1922197/45762604-a488ad80-bc26-11e8-916b-ba0057a73a9d.png)
  ![image](https://user-images.githubusercontent.com/1922197/45762581-99358200-bc26-11e8-90e3-0b7bfdd87ecf.png)

**Comment by lampholder** [comment]
P2 until we know whether this has happened to anybody else

**Comment by t3chguy** [comment]
Closing this as presumed fixed in the many years due to lack of further reported cases
