### ISSUE TITLE
Clearly differentiate in the UX between trivially reversible, reversible-with-somebody-elses-help, and irreversible actions.

### ISSUE THREAD

**Issue by lampholder** [element-hq/element-web#7539]
I'd like to see a consistent design language for operations which are:
- reversible - you can reverse your action all by yourself (e.g. leaving a publicly-joinable room)
- potentially reversible - you can reverse your action by asking to be reinvited (e.g. leaving an invite-only room)
- irreversible - nobody can ever undo this (e.g. deleting your account)

Inspired by https://github.com/vector-im/riot-web/issues/5724

**Comment by lampholder** [comment]
As per https://github.com/vector-im/riot-web/issues/5800, perhaps the distinction is not 'trivially reversible, reversible-with-faff and irreversible'; maybe a better distinction would be drawn along the lines of 'how hard we think you should think' about an action before doing it.

**Comment by lampholder** [comment]
https://github.com/vector-im/riot-web/issues/7536

**Comment by DC7IA** [comment]
Also with visibility of a room's history. 
It is not clear that setting it from "Anyone" to anything else makes it impossible to change it later.

There should be a warning.

**Comment by gaelledel** [comment]
<img width="1241" alt="Screenshot 2024-02-16 at 10 56 08" src="https://github.com/element-hq/element-web/assets/76945183/362e4868-2807-4df2-81ac-b3bbf91fc552">
We have a red CTA and message prompt for irreversible outcome in newest edition
