### ISSUE TITLE
Historical rooms is always empty

### ISSUE THREAD

**Issue by bwindels** [element-hq/element-web#7850]
On riot-web, "Historical rooms" section in the left panel always says "You have no historical rooms" (often after showing a spinner for a while). @bmarty says there is also no lazy loading for this request, another filter is used in a parallel /sync. There is no lazy_load_members argument in this filter

**Comment by bmarty** [comment]
FTR https://github.com/matrix-org/matrix-android-sdk/pull/409

**Comment by lampholder** [comment]
@bwindels does this mean the historical rooms feature has been broken since lazy loading? (And nobody's noticed?)

**Comment by bwindels** [comment]
@lampholder I'm unsure whether the breakage is related to lazy loading or not. As part of finding it broken Benoit mentioned it should lazy load members as well.

**Comment by turt2live** [comment]
As a data point: in my history of using riot, it has never worked.

**Comment by thomas-profitt** [comment]
I'm having this problem too.

1. I leave some rooms in Riot, and the rooms immediately appear in Historical.
2. I refresh the page
3. I click Historical
4. The spinner spins.
5. The "You have no historical rooms" message is shown.

Monitoring HTTP requests in the browser debugging tools, I can see Riot updating Filter 1 with `"include_leave": true`, but sync requests are passing `filter=7`, and sending a GET request for Filter 7 shows that it doesn't have `"include_leave": true`

**Comment by dr1** [comment]
I have been having this bug for awhile now. It stopped working about the time my IRC appservice didnt want to let me leave a room, and I had to manually edit myself out. Didnt touch the matrix DB, so don't know if related, but it wasnt long after that I noticed historical rooms were gone. Now they do exactly what thomas mentions above.

**Comment by Wodann** [comment]
This is still a problem for left rooms

**Comment by t3chguy** [comment]
Historical rooms is gone
