### ISSUE TITLE
Replying to a message containing a ping causes the intended recipient(s) of the ping to be pinged again

### ISSUE THREAD

**Issue by n-o-o-b** [element-hq/element-web#7874]
This happens for both room pings and user pings. Examples:

![image](https://user-images.githubusercontent.com/19697175/50057582-861e4980-0164-11e9-9ef7-1da890391113.png)
(As seen by users other than Ruff_Wizard. User Ruff_Wizard does not get themself pinged by their reply, but the rest of the room does.)

![image](https://user-images.githubusercontent.com/19697175/50057589-933b3880-0164-11e9-9e8c-ae66a0797b7d.png)
(As seen by user Ruff_Wizard. User Ruff_Wizard gets pinged by a message replying to one containing their name.)

It shouldn't work like this; this system assumes that someone necessarily wants/needs to get pinged just because another person is replying to a message which contains their name/a room ping. If someone wants to ping the person or the room again, they can simply insert another ping in the text of their reply. The system shouldn't ping every time the intial ping is replied to.

**Comment by lieuwex** [comment]
Is there any reason why homeservers don't first [strip the fallback](https://matrix.org/docs/spec/client_server/latest#stripping-the-fallback) before checking for push rules?

**Comment by t3chguy** [comment]
That's up to the homeserver, not Element, would recommend you take your question to whatever homeserver you are wishing did that
