### ISSUE TITLE
Putting your machine to sleep can cause an "incompatible cache" warning when resuming

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#7905]
It's possible I put my laptop to sleep before the incremental sync finished after having refreshed the page (I clicked 'update' on develop then shut the lid on the laptop). 

![image](https://user-images.githubusercontent.com/1190097/50169880-bf150600-02ab-11e9-918c-32f71767309c.png)

**Comment by lampholder** [comment]
UGH.

That's super alarming, and reasonably likely to occur in the wild, but sounds like the sort of thing that could take quite a while to debug :/

**Comment by jryans** [comment]
I wonder if we can construct a way to trigger it more reliably...

**Comment by turt2live** [comment]
Apparently I'm an expert at doing so. Managed to hit it every day this week :p

Ftr, it's fine if you ignore the dialog and refresh. Might just need a check in the dialog to see if the app is actually corrupted?

**Comment by turt2live** [comment]
Easy reproduction steps:
* Cache enough of Riot that it can load (Firefox seems best to do this)
* Disconnect your internet / stop webpack dev server
* Refresh the page

Failing that:
* Cache Riot in firefox
* Close firefox and ensure the tab will open on startup
* Stop webpack dev server
* Start firefox again

**Comment by t3chguy** [comment]
Closing this as presumed fixed in the many years due to lack of further reported cases
