### ISSUE TITLE
Unclear how my backup was "verified" by my other device

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#7928]
![image](https://user-images.githubusercontent.com/1190097/50296974-e64d0e00-0438-11e9-989b-b42dfe4c978f.png)

I can take a guess at how the signature was verified, however I don't have my laptop's device verified - how does Riot determine that the device is verified here?

**Comment by jryans** [comment]
@turt2live That screen should be reflecting simple device verification we already know today, so it would seem to be saying the current device _has_ verified "Chrome - Laptop".

What does it look like in the device list when you click on yourself in some room?

**Comment by turt2live** [comment]
It says it is verified, but I do not remember doing that. I only set up this current device within the last day, and haven't verified anything :(

**Comment by jryans** [comment]
Hmm, well, that part is a mystery then... 😖
