### ISSUE TITLE
"Room Upgraded" banner seems like it has the wrong alignment

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#7999]
![image](https://user-images.githubusercontent.com/1190097/50647824-d48a6100-0f36-11e9-91b6-56ab436a6739.png)

It feels wrong in that there's left aligned text that's in the middle of the composer.

**Comment by lampholder** [comment]
I "designed" this to mirror the positioning of _You do not have permission to post in this room_:

![Screenshot 2019-03-19 at 19 15 36](https://user-images.githubusercontent.com/1922197/54635162-7c65f400-4a7b-11e9-8309-37256bfc226a.png)

But you're right, it does look a little bit odd. I think p3 cosmetic minor bug is right and we can probably remove the fire from this one :)
