### ISSUE TITLE
Right panel in new design is too wide

### ISSUE THREAD

**Issue by kepi** [element-hq/element-web#8667]
On rotated monitor right panel in new design is too wide even when resized to minimal allowed size. Looks like top icons are causing the problem, they should responsively split to two rows. 

![riot-right-panel](https://user-images.githubusercontent.com/105303/52821520-5087d500-30af-11e9-94e6-c4dae8bd973d.png)

**Comment by turt2live** [comment]
Worth noting that you're able to resize it, although I do think you're limited to a minimum size :(

**Comment by tulir** [comment]
You can also hide the right pane by clicking the selected icon at the top right

**Comment by kepi** [comment]
> Worth noting that you're able to resize it, although I do think you're limited to a minimum size :(

screenshot is with panel resized to minimum size :) That was first we tried.

> You can also hide the right pane by clicking the selected icon at the top right

Thanks, I forget about this option. Anyway in many cases it is beneficial to have it displayed so it would be great to improve it.

**Comment by ara4n** [comment]
relaxing the min width sounds like a good idea. I don't think it's being pushed out by the icons (i hope)

**Comment by t3chguy** [comment]
It is not being pushed out by the icons, but lowering the min will create poor readability in the new right panel designs where they are horizontally denser

A little bit of a reduction might be doable.

![image](https://user-images.githubusercontent.com/2403652/94919021-99bab180-04ab-11eb-9053-130892c95ad6.png)

**Comment by daniellekirkwood** [comment]
Build a PH chart to see screen width usage: https://posthog.hss.element.io/insights/8oug6Lje

**Comment by t3chguy** [comment]
@americanrefugee has said no lower than 280px
