### ISSUE TITLE
Lazy-loaded rooms to historical cannot be forgotten

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#9168]

**Comment by aaronraimist** [comment]
Keywords: forget room option missing from historical section of room list

**Comment by anoadragon453** [comment]
I'm confused. So a too. that has lazy-loading enabled doesn't disappear when you click Forget on it?

**Comment by aaronraimist** [comment]
No. It doesn’t have a forget button at all. https://matrix.to/#/!QtykxKocfZaZOUrTwp%3Amatrix.org/%2415525377971071233GYPFN%3Amatrix.org

**Comment by turt2live** [comment]
It's not related to the lazy loading you're thinking of. When you open the section it lazily loads rooms to shove in there, which can take a while. Once it succeeds, the rooms can't be forgotten.

**Comment by lampholder** [comment]
I'm still too confused to triage this I'm afraid. Can we have some repro steps and screenshots?

**Comment by turt2live** [comment]
1. Leave a room so the historical section shows up
2. Click on said historical section to expand it
3. Wait infinite amounts of time for the hidden spinner to stop spinning (for the request to complete)
4. Rooms that pop in are not forgettable

nb: step 3 is a different bug, which is somewhere in the pile of "historical section sucks" bugs

**Comment by SilverWolf32** [comment]
I'm having this issue as well (on the desktop client if it matters, which it probably doesn't). In my case it was a room I clicked on and loaded, but never actually joined.

**Comment by earfolds** [comment]
I get this on my matrix.org account. If I leave a room, the historical section pops up, and lists several rooms that are not forgettable. Clearing cache and reload hides the historical section.

**Comment by robmv** [comment]
Same problem here, I join or create a new room and then leave, this new room appear on the Historical section, with another private chat I leaved a week ago that has no option to leave today. @earfolds recommendation of Clearing cache worked, and from now if I repeat the process, the old room doesn't reappear.

Looks like a client caching issue

**Comment by t3chguy** [comment]
Historical is gone
