### ISSUE TITLE
restoring a key backup doesn't seem to finish?

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#9425]
tried on my account and it just sits there with a loading spinner

**Comment by jryans** [comment]
@dbkr Can you repro this one reliably?

**Comment by dbkr** [comment]
Yep, although trying it again I did get my keys back (or at least some of them) so it may just be that the dialog keeps spinning even though it does actually finish.

**Comment by dbkr** [comment]
...having tried again immediately afterwards, it did then complete after a few minutes (with two log lines for each session it had already done...). I have about 27000 megolm sessions.

**Comment by rioux602** [comment]
Having same issue, though I wasn't able to have this completed yet. I created a ticket but closed it as a duplicate #13664

**Comment by rioux602** [comment]
> Having same issue, though I wasn't able to have this completed yet. I created a ticket but closed it as a duplicate #13664

Nevermind, it seems to be working this morning. Possible it took several hours?

**Comment by bwindels** [comment]
Saw this today on the nightly as well. I have around 15000 sessions.

**Comment by richvdh** [comment]
Assuming this is no longer a thing. If it is, please repopen and rageshake.
