### ISSUE TITLE
Suggestion - Change to CONTRIBUTORS.rst

### ISSUE THREAD

**Issue by JQuilty** [element-hq/element-web#9796]
Hi,

I was reading the contributors.rst guide, and in it it notes that it follows the other project. However, to read this, you have to go to the other project's page. 

I would suggest that a copy based on that be put in the rst page. As it is now, it can be confusing to be on a page for another project after clicking a link from this project. It also says there is "no formal documentation" on code style, but links to a style guide, which is still documentation. So I would suggest something like "It isn't a completely definitive list, but we have a style guide that should be followed."

**Comment by aaronraimist** [comment]
Related: #7430

**Comment by t3chguy** [comment]
This got fixed
